### ISSUE TITLE
Correction to Anthology ID D19-1101

### ISSUE THREAD

**Issue by edwinrobots** [acl-org/acl-anthology#1001]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

This paper has "Edwin D. Simpson" as author, which is correct. However, I had previously used only "Edwin Simpson". Please can the two authors be merged under "Edwin Simpson" so that D19-1101 is also listed under "Edwin Simpson"? Thank you!

**Comment by mjpost** [comment]
Since the PDF has "Edwin Simpson", the easiest fix is to edit `data/xml/D19.xml` and correct it. If you do that yourself and create a PR, it will speed things up.
