### ISSUE TITLE
less results when sorting with year of publication

### ISSUE THREAD

**Issue by shuoyangd** [acl-org/acl-anthology#1007]
Hi,

I realized that when searching on ACL anthology, sorting results with relevance (default) always gives a lot more results than sorting with the year of publication. For example, when [searching "machine translation"](https://www.aclweb.org/anthology/search/?q=machine+translation), sorting by relevance gives 54,300 results while sorting by the year of publication gives only 7,400. Looking at the difference in results, I think lots of workshop papers, if not all of them, have been filtered by ranking by the year of publication.

Is there some information missing with these papers or is this some bug with the search?

Thanks,
Shuoyang

**Comment by nschneid** [comment]
Sorry nobody got around to this earlier, but it's now being addressed in #2605.
