### ISSUE TITLE
redirect from acl.ldc.upenn.edu

### ISSUE THREAD

**Issue by danielgildea** [acl-org/acl-anthology#1015]
has anyone contacted ldc about redirecting old urls such as

http://acl.ldc.upenn.edu/J/J93/J93-2003.pdf

?

**Comment by mjpost** [comment]
No, but I can do this. Where did you see this linked from? Do you know if the LDC used to host portions of the Anthology?

**Comment by danielgildea** [comment]
That was the main anthology web site until sometime around 2008.
There are links in some papers in the anthology, e.g.

https://www.aclweb.org/anthology/W06-1630.pdf

**Comment by mjpost** [comment]
It's a great idea, but it seems the LDC doesn't want to do it.

It's a good lesson about owning one's own property. Hopefully our permanent location will be enough for search engines to redirect future searches.

(A bigger idea is to consider batch-rewriting these URLs in the PDFs...)
