### ISSUE TITLE
Correction to Anthology ID J88-1001

### ISSUE THREAD

**Issue by ewan-klein** [acl-org/acl-anthology#1017]
## Metadata correction: please describe the issue here

Current author list:
Gerald Gazdar, Geoffrey K. Pullum, Robert Carpenter, Thomas E. Hukari, Robert D. Levine

Corrected author list:
Gerald Gazdar, Geoffrey K. Pullum, Robert Carpenter, **Ewan Klein**, Thomas E. Hukari, Robert D. Levine

**Comment by mjpost** [comment]
Thanks! I think it makes sense to bypass [our policy on name corrections](https://www.aclweb.org/anthology/info/corrections/) in this situation. We'll process this soon.

**Comment by ewan-klein** [comment]
Thanks! ACLWeb anthology is a fantastic resource.

**Comment by mjpost** [comment]
Glad we could help! Thanks for bringing the error to our attention.
