### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#102]
We should build continuous integration tests that verify the format of the authoritative files in `import/`. This will ensure that nothing can be committed to the master branch unless it is valid XML.

**Comment by mbollmann** [comment]
Any concrete plans yet for how to approach this? I do have some experience with setting up Travis CI, though I'm not sure when I could get around to this.

**Comment by mjpost** [comment]
We should run the XML validator for start. I know that someone has done this (was it you?) because the schema has been updated.

I was also thinking maybe we should require all commits to master to require at least two people (one the committer) to approve, just to have more eyes on things. But that may be overkill.

We should also have Python unit tests on many of the scripts.

**Comment by mjpost** [comment]
Are the memory requirements that high?

I am going to write some unit tests for the Python scripts which I can add to this.

**Comment by mbollmann** [comment]
The in-built profiling from Hugo reports up to 18 GB memory usage, but to be honest I'm not sure what that actually means. It builds fine on my laptop with 8 GB RAM, though I suspect some swapping to disk is happening. (I've read on some FAQ page that Travis CI limits its sandboxes to ~3 GB RAM.)

**Comment by mjpost** [comment]
Thanks for doing this! I consider it closed.
