### ISSUE TITLE
Correction to Anthology ID N19-1128

### ISSUE THREAD

**Issue by teias-courses** [acl-org/acl-anthology#1033]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections
[NAACL2019_WiC.pdf](https://github.com/acl-org/acl-anthology/files/5401444/NAACL2019_WiC.pdf)
/) to read about the three types of corrections.

## Revision or erratum: please add the following information**

This revision corrects some numbers in Table 3 for the "Threshold"-based baseline. The results were incorrectly reported for the dev set (rather than the test set).

- [X] I have attached the revised PDF or erratum to this issue
- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**

**Comment by mjpost** [comment]
I am having a hard time reading this data. Please clean up the commit message and provide a summary of the changes.

**Comment by mjpost** [comment]
Closing this since there has been no response. Feel free to reopen and address my question.
