### ISSUE TITLE
Metadata title of W18-5516

### ISSUE THREAD

**Issue by leondz** [acl-org/acl-anthology#104]
The title of this paper in the workshop proceedings and individual PDF is "UKP-Athene: Multi-Sentence Textual Entailment for Claim Verification", which is not reflected in the metadata, that omits the group & system prefix

**Comment by mjpost** [comment]
Thanks. The text you need to modify can be found in [import/W18.xml] ([link](https://github.com/acl-org/acl-anthology/blob/master/import/W18.xml)). Please make the change and then issue a pull request referencing this issue.
