### ISSUE TITLE
404 https://www.aclweb.org/anthology/papers/P18-1244/p18-1244

### ISSUE THREAD

**Issue by tyoc213** [acl-org/acl-anthology#1043]
https://www.aclweb.org/anthology/papers/P18-1244/p18-1244

**Comment by akoehn** [comment]
https://www.aclweb.org/anthology/P18-1244/
Works. Why do you think your URL is supposed to work?

**Comment by tyoc213** [comment]
I see, because is the one linked here https://openreview.net/search?term=A+Purely+End-to-End+System+for+Multi-speaker+Speech+Recognition&group=all&content=all&source=all&sort=cdate%3Adesc

**Comment by akoehn** [comment]
Please report the incorrect link there, nothing we can do about that.
