### ISSUE TITLE
Correction in booktitle W18-66

### ISSUE THREAD

**Issue by MarietTheune** [acl-org/acl-anthology#105]
This is about W18-66. If we go to this page

https://aclanthology.info/volumes/introduction-to-the-proceedings-of-the-3rd-workshop-on-computational-creativity-in-natural-language-generation-cc-nlg-2018

then we see the title of the Proceedings as  "Introduction to the Proceedings of the 3rd Workshop on Computational Creativity in Natural Language Generation (CC-NLG 2018)". But it should be "Proceedings of the 3rd Workshop on Computational Creativity in Natural Language Generation (CC-NLG 2018)". The same holds for the naming of the URL.

It looks like the problem is caused by an error in the bibtex:

https://aclanthology.info/volumes/introduction-to-the-proceedings-of-the-3rd-workshop-on-computational-creativity-in-natural-language-generation-cc-nlg-2018.bib

booktitle =  "Introduction to the Proceedings of the 3rd Workshop on Computational Creativity in Natural Language Generation (CC- NLG 2018)"

should be (everywhere)

booktitle =  "Proceedings of the 3rd Workshop on Computational Creativity in Natural Language Generation (CC-NLG 2018)"

The same holds for all the bibtex files of the individual papers of this workshop.

**Comment by mjpost** [comment]
Thanks. The text you need to modify can be found in [import/W18.xml] ([link](https://github.com/acl-org/acl-anthology/blob/master/import/W18.xm)). Please make the change and then issue a pull request referencing this issue.
