### ISSUE TITLE
Ingest LREC 2016

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#106]
There are open issues for LREC 2014 (#31) and LREC 2018 (#99), but we are also missing LREC 2016. Does anyone know anything about that?

**Comment by knmnyn** [comment]
I have the XML from ELRA for that, and I think @villalbamartin has it as well.  I can take care of uploading the .PDFs to the aclweb.org server.

**Comment by mjpost** [comment]
I also got the full ZIP file from them, containing PDFs and BibTeX (albeit embedding in HTML pages). That can be found here:

- https://www.dropbox.com/sh/pp3vwzcm1mjrs2q/AAAybZecl5wGO9LQ9oP-IKRwa?dl=0

Min, can you attach the XML? I could put it together with that file and maybe find someone who would be willing to do this.

**Comment by mjpost** [comment]
Hi @villalbamartin, do you have the XML that Min mentioned? It would be nice to close this out.

**Comment by knmnyn** [comment]
My apologies for the delay.  I recalled incorrectly.  I only had the LREC *18* XML not the LREC 16 XML.  However, Ulrich Schafer did try to process and provide a bib file for LREC 16, which Christoph and Martín had tried to process earlier.  I will forward this to you in a separate email shortly.

**Comment by mjpost** [comment]
@kilian-gebhardt Any interest in applying your IWPT ingestion skills to this task? It's mostly a matter of munging the existing format to extract the (exiting) BibTeX and pull in the abstracts...

**Comment by kilian-gebhardt** [comment]
@mjpost I can have a look but it might take a few days until I have time. 
- Can you update the link to the materials? The dropbox link is dead.
- Does the bibfile that @knmnyn mentioned exist? 
- For IWPT 2003 you said that you ran some script for the bibtex -> xml conversion. Can you provide this to me?

**Comment by mjpost** [comment]
It's generous of you to contribute your time, and a bit of a delay on three year-old proceedings will not matter.

[Here](https://www.dropbox.com/sh/p2fdpvhcoq2mptn/AAA_wnESBRdu1z1swVnkVddda?dl=0) is the updated link (updated above, too).

I could not locate the bib file. However, they should be easy to extract from the individual files in the `summaries/` directory in the zip file. It would also be nice to pull out the abstracts, which are also in those files.

If you can generate the format described in [step 3(b) of the ACLPUB README](https://github.com/acl-org/ACLPUB/blob/master/anthologize/README.md), you can then run [anthologize_xml.py](https://github.com/acl-org/ACLPUB/blob/master/anthologize/anthology_xml.py) to generate the XML file that I import. But you could also just pass it to me and I'd take care of that step. I'm [in the process](https://github.com/acl-org/acl-anthology/tree/docs) of overhauling these documents so should have something much more readable on this for future volunteers.

**Comment by akoehn** [comment]
There is a bibtex.html in the dropbox folder, which seems to contain the official bibtex file.
That file is also here: http://www.lrec-conf.org/proceedings/lrec2016/bibtex.html
A simple copy&paste should suffice to obtain the bibtex file without html.

**Comment by mjpost** [comment]
Ah, this is great. It just needs the "abstract" field added.

**Comment by kilian-gebhardt** [comment]
Thanks for the information. I assume that the prefix shall be `L16-1XXX` in analogy to LREC 2018 and 2014. 

What about the co-located workshops? There seems to be no meta-data (it would need to be crawled from the workshop's homepages) but only complete proceedings pdfs. But, in princinple, shall they be ingested as well (using free `W16-YYXX` prefixes)?

**Comment by mjpost** [comment]
Yes, L16-1XXX. 

Have LREC workshops been imported in the past that you know? I don’t think so and therefore wouldn’t bother with these ones especially since the metadata is not split out. If you really want to do them, assemble a list of workshop names and I’ll assign W IDs.

**Comment by knmnyn** [comment]
Hi Matt:

In the past this was not consistently done; we ingested whatever LREC
workshop organizers asked us to index.  In the past, LREC workshop and PC
chairs did not systematically recommend LREC workshops to be archived.
Some workshop organizers did and some didn't.  In some cases, the
particular workshop series was commonly held at *ACL venues, so the
particular workshop organizers expected the workshop instance to be indexed
(which we complied with).

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by kilian-gebhardt** [comment]
I made some progress writing a [conversion script](https://gist.github.com/kilian-gebhardt/d7e70e329cd696ee8b367af009e96fb7) but a bit of fine-tuning is still required due to shortcomings with the data provided by LREC.

- The anthology compilation process complains 
```WARNING   Paper L16-1701 has <editor> but is not a proceedings volume;```
but according to the bibtex documentation, inproceedings can have an optional editor-field. Shall I drop the editor field or is this rather an issue of the anthology?
- The bibtex entries state that `location = {Portorož, Slovenia},` and `address = {Paris, France},`. As the conference took place in Portorož and `location` is an undefined key, I would change this to `address =  {Portorož, Slovenia}`.
- I could join all the pdfs to a single proceedings file, but this would be 598MB in size, so I suggest not to do this.
- There some additional pdfs for the invited talks, keynotes, and two introductory texts that don't have page numbers and bibtex information. Shall we include this into the anthology?

**Comment by mbollmann** [comment]
> * The anthology compilation process complains
>   `WARNING   Paper L16-1701 has <editor> but is not a proceedings volume;`
>   but according to the bibtex documentation, inproceedings can have an optional editor-field. Shall I drop the editor field or is this rather an issue of the anthology?

If we want to produce the editor field in the BibTeX, we should pull it from the front matter; their values would be identical, no? The individual papers shouldn't have it since it's redundant. (And the warning appears because the website currently doesn't do anything with it.)

**Comment by mjpost** [comment]
Agreed about `<editor>`.

Using `address` over `location` reflects what we did in #277, so please go ahead.

I think, no need to have a consolidated PDF.

We don't currently have a way to encode invited talks, keynotes, and other things, but are working on it (#298). Maybe if you can send me those four separately, we can queue it up till that's done.
