### ISSUE TITLE
Correction to Anthology ID 2020.emnlp-main.488 Pages: 6045–6057

### ISSUE THREAD

**Issue by Bosheng2020** [acl-org/acl-anthology#1065]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
Dear Sir/Madam,

There is a typo in the title of our paper on EMNLP2020 website. 

The title of our paper should be "DAGA: Data Augmentation with a Generation Approach for Low-resource Tagging Tasks". However, on EMNLP2020 website, there is a missing space and the title became "DAGA: Data Augmentation with a Generation Approach forLow-resource Tagging Tasks". (There should be a space behind between the word "for" and the term "Low-resource").  I found the same typo on the schedule page and anthology pages as below.

I have emailed some organizers and they suggested us to update it over here. Since this typo affects the following pages, could you kindly help us update it? Thank you so much!

https://www.aclweb.org/anthology/events/emnlp-2020/#2020-emnlp-main
https://www.aclweb.org/anthology/2020.emnlp-main.488/
https://www.aclweb.org/anthology/2020.emnlp-main.488.bib
https://2020.emnlp.org/schedule

## Revision or erratum: please add the following information**

- [ ] I have attached the revised PDF or erratum to this issue
- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**

**Comment by mjpost** [comment]
This is just one simple change in data/xml/2020.emnlp.xml. Please make that change and submit a PR (referencing this issue) and we will approve it.

**Comment by Bosheng2020** [comment]
Thanks a lot. 

Kindly approve this Pull Request: https://github.com/acl-org/acl-anthology/pull/1066
