### ISSUE TITLE
Link to proceedings does not work

### ISSUE THREAD

**Issue by piekvossen** [acl-org/acl-anthology#1068]
Link to proceedings does not work for SpLU-2020 workshop

**Comment by mjpost** [comment]
What link?

**Comment by nschneid** [comment]
Shouldn't it have WS as a venue?

**Comment by piekvossen** [comment]
If you go to:

https://spatial-language.github.io

You find a link to the Proceedings for accepted papers. This link points to the anthology but it is a dead link

Best wishes

Piek

On 14 Nov 2020, at 20:27, Matt Post <notifications@github.com<mailto:notifications@github.com>> wrote:



What link?

**Comment by akoehn** [comment]
1. That link works for me2. We are not responsible for external links.
