### ISSUE TITLE
Correction to Anthology ID 2020.wnut-1.18

### ISSUE THREAD

**Issue by xashru** [acl-org/acl-anthology#1071]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
The name of the paper was changed in the camera-ready version, but the anthology doesn't reflect the change. The name of this paper should be "Punctuation Restoration using Transformer Models for High-and Low-Resource Languages". Could you please update the anthology?

**Comment by mjpost** [comment]
EMNLP workshops were submitted with the review title instead of the final title. If you submit a PR (edit `data/xml/2020.wnut.xml`), it will expedite a fix.

**Comment by xashru** [comment]
Done https://github.com/acl-org/acl-anthology/pull/1076
