### ISSUE TITLE
Correction to Anthology ID 2020.wnut-1.72

### ISSUE THREAD

**Issue by soroushv-dartmouth** [acl-org/acl-anthology#1072]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

The title shown on the website (https://www.aclweb.org/anthology/2020.wnut-1.72/) and the metadata does not match the title of the paper in the pdf. The correct title is the one in the pdf, which is "Dartmouth CS at WNUT-2020 Task 2: Informative COVID-19 Tweet Classification Using BERT". Can you please update the metadata to reflect this?

Thank you for your time!

**Comment by mjpost** [comment]
Unfortunately, EMNLP workshops were submitted with the review title, instead of the final title. You can expedite a fix by editing `data/xml/2020.wnut.xml` and submitting a PR.

**Comment by soroushv-dartmouth** [comment]
Thanks for the quick response Matt. I am not quite sure how to do that. Is there someone that can help me with that so I don't mess it up? I understand if that's too much to ask, in which case I can look up how to do this.

Best,
Soroush

________________________________

**Comment by mjpost** [comment]
If you don't want to do it, we'll get to it eventually. There are instructions here: https://www.aclweb.org/anthology/info/corrections/#correcting-metadata.

**Comment by soroushv-dartmouth** [comment]
Thank you!

Best,
Soroush


---

Soroush Vosoughi, PhD

Assistant Professor of Computer Science

Dartmouth College

Hanover, NH 03755

soroush.vosoughi@dartmouth.edu

________________________________
