### ISSUE TITLE
Correction to Anthology ID 2020.acl-main.218

### ISSUE THREAD

**Issue by wise-east** [acl-org/acl-anthology#1073]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

I am the author of this paper and I am wondering what needs to be done to make this version of the paper published to ACL appear on Google Scholar. So far, Google Scholar only shows the arxiv version. I saw that the more recent EMNLP2020 papers and papers from the same ACL2020 conference had the ACL versions appear in Google Scholar. Does something about the metadata need to be changed/matched?

**Comment by mjpost** [comment]
Unfortunately (because this is a common problem: #126), we have no control over Google Scholar and its indexing.
