### ISSUE TITLE
Correction to Anthology ID 2020.sustainlp-1.0

### ISSUE THREAD

**Issue by vered1986** [acl-org/acl-anthology#1075]
## Metadata correction: 

Hi, my last name was misspelled in the workshop description paper. I would like to change "Schwartz" to "Shwartz" in the meta-data (it is spelled correctly in the PDF). Thank you!

**Comment by mjpost** [comment]
Submitting a PR yourself (edit the file `data/xml/2020.sustainlp-1`) will expedite the fix.

**Comment by vered1986** [comment]
Thanks! Here it is: https://github.com/acl-org/acl-anthology/pull/1080
