### ISSUE TITLE
Correction to Anthology ID 2020.emnlp-main.4

### ISSUE THREAD

**Issue by JoLuGl** [acl-org/acl-anthology#1079]
**2020.emnlp-main.4**

## Metadata correction: Capitalization of the title
Our paper's title should be capitalized like this: Unsupervised Stance Detection for Arguments from Consequences

As demanded, when submitting our paper I entered the title with the curly braces, but for some reason it didn't work. Here is the title with curly braces around the capitalized letters: {U}nsupervised {S}tance {D}etection for {A}rguments from {C}onsequences

Thanks for your help!
Jonathan Kobbe

**Comment by mbollmann** [comment]
Curly braces are not supposed to be used to protect common nouns, only proper nouns or acronyms. It is up to the bibliography style to determine how to render a paper's title with regards to case; if all nouns are protected with curly braces, this doesn't work anymore.

**Comment by JoLuGl** [comment]
Hello,

thanks for the fast answer. Apparently, EMNLP's instructions on how to 
enter the metadata are wrong then.
However, it would be nice if you could ensure that the correct 
capitalization is shown in the antology and in the bibtex-file.

Thanks!
Jonathan Kobbe


Am 17.11.2020 um 13:12 schrieb Marcel Bollmann:

**Comment by mbollmann** [comment]
Oh, you're right that the casing shouldn't have changed in our own metadata, only the curly braces. At least I believe so. @mjpost?

**Comment by mjpost** [comment]
We didn't lowercase anything. If you look in the XML, for example, paper ID 4 is lowercased, but paper ID 2 is title cased.

**Comment by JoLuGl** [comment]
That's true and this is basically what I wonder about. In the softconf platform which was used for submission, the title is displayed like this: {U}nsupervised {S}tance {D}etection for {A}rguments from {C}onsequences

However, I did not expect this to be such a big deal. So if you want, feel free to close the issue again. I can certainly live with a lowercase title :)

**Comment by mjpost** [comment]
Hi Jonathan—we'll happily approve and merge if you want to submit a PR (https://www.aclweb.org/anthology/info/corrections/#correcting-metadata) to correct the display casing (though not the case protection).

**Comment by mjpost** [comment]
Closing for now, please feel free to reopen with a PR.
