### ISSUE TITLE
author name variants: Ramón Fernandez Astudillo

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#1082]
1. In paper metadata, "F." is missing for `W18-6451`, `P15-1104`, `S15-2109`, `S15-2102`, `S16-1036`, `W17-5048`
2. Add author name variants to unify under canonical name of "Ramón Fernandez Astudillo":
   - https://www.aclweb.org/anthology/people/r/ramon-astudillo/
   - https://www.aclweb.org/anthology/people/r/ramon-astudillo1/
   - https://www.aclweb.org/anthology/people/r/ramon-fernandez-astudillo/

CC: @ramon-astudillo

**Comment by ramon-astudillo** [comment]
Thanks @nschneid, I have a history o being terrible at writing my own name. Let me know if there is anything I can do to help.

**Comment by davidweichiang** [comment]
Should F(ernandez) be part of the last name?

**Comment by ramon-astudillo** [comment]
Yes "Fernandez Astudillo" is last name, thanks

**Comment by davidweichiang** [comment]
Thanks for the quick answer! What about in "Ramon F. Astudillo"?

**Comment by ramon-astudillo** [comment]
I would change all instances to
```
<author><first>Ramon</first> <last>Fernandez Astudillo</last></author> 
```

**Comment by nschneid** [comment]
@ramon-astudillo No accent?

**Comment by ramon-astudillo** [comment]
thanks sorry, "Ramón"

**Comment by davidweichiang** [comment]
@mjpost please correct me if I'm misremembering, but @ramon-astudillo, we try to make the metadata in the XML file match what's printed on the paper if possible. It's easy to unify the different spellings so they all appear on a single author page.

**Comment by ramon-astudillo** [comment]
Sadly the spelling will probably be different from paper to paper. At have used "Ramón F. Astudillo" which wrongly implies "Fernandez" is a second name and sometimes "Ramón Astudillo" which leaves out one of the two words in my last name.

Now I try to use always "Ramón Fernandez Astudillo" which is correct. My last name has two words "Fernandez Astudillo".

**Comment by davidweichiang** [comment]
@ramon-astudillo is it okay with you if we make the metadata in the XML match what's printed on the paper, and unify your author pages into a single page? If so, when your name is printed as Ramón F. Astudillo, do you want it to be `<first>Ramón F.</first> <last>Astudillo</last>` or `<first>Ramón</first> <last>F. Astudillo</last>`?

**Comment by ramon-astudillo** [comment]
I favor the second case, many thanks
```
<first>Ramón</first> <last>F. Astudillo</last>
```
