### ISSUE TITLE
Make volumes adhere to the flat directory structure

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#1087]
All our files are relatively flat, but we still have nested structures for volumes (in the build dir under `anthology/papers/`).

This looks like an oversight from a previous change and noone has complained yet.

**Comment by mbollmann** [comment]
Here's the precise reason why that still happens:

https://github.com/acl-org/acl-anthology/blob/6df3f486e8f3cdeffd47593e15f1d65ccc683fb1/bin/create_hugo_pages.py#L116-L118

Maybe that alias can be removed, and a flat permalink for volumes be added in `hugo/config.toml`. I can test that when I have some time.
