### ISSUE TITLE
Correction to Anthology ID 2020.emnlp-main.237

### ISSUE THREAD

**Issue by koukoulala** [acl-org/acl-anthology#1091]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Revision or erratum: please add the following information**

- [ ] I have attached the revised PDF or erratum to this issue
- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects the results related to knowledge graph embedding  (The original results are affected by a programming error) in Table 1, Figure 4 in the main text, and Table 3 in the appendix. The revised results still hold all the conclusions in the original paper.

**Description of changes**
[DiCGRL_revised.pdf](https://github.com/acl-org/acl-anthology/files/5581421/DiCGRL_revised.pdf)

**Comment by mjpost** [comment]
This is not the Anthology ID. Please include the Anthology ID per the instructions.

**Comment by koukoulala** [comment]
> This is not the Anthology ID. Please include the Anthology ID per the instructions.

Thanks. I have corrected the Anthology ID.
