### ISSUE TITLE
Correction: Revision to paper PDF to correct author contribution

### ISSUE THREAD

**Issue by kracwarlock** [acl-org/acl-anthology#110]
The first 4 authors of the paper contributed equally. This is mentioned in the [arXiv](https://arxiv.org/pdf/1704.00057.pdf) version with a footnote. The footnote is missing from the ACL version and we wish to correct this mistake now.

ACL Anthology ID: [W17-5526](http://www.aclweb.org/anthology/W17-5526)

We wish to submit a new PDF with the only change being a footnote that says that the first 4 authors contributed equally.

> Use this template to request a correction to the ACL Anthology.
> 
> Please ensure that you:
> 
> - [x] ...have read and understood the [criteria for corrections](http://aclanthology.info/corrections).
> - [x] ...have included (if relevant) the ACL Anthology ID (e.g., J93-2003).
> 
> If approved, we will follow up with information about how to submit the correction.

**Comment by mjpost** [comment]
Hi, thanks. We can post a revised version to the Anthology, though note that the original will still be available.

Please add the new PDF to this issue, or post a link.

**Comment by kracwarlock** [comment]
[sigdial2017.pdf](https://github.com/acl-org/acl-anthology/files/2760591/sigdial2017.pdf)

**Comment by mjpost** [comment]
Thanks. I need to get confirmation from all four authors affected by the change. If they all have GitHub accounts, please have them confirm here. Alternately, you can also email me, CC'ing the authors, and everyone can confirm in thread.

**Comment by Layla-ElAsri** [comment]
Hi, I confirm the changes.

**Comment by jzumer** [comment]
I confirm the changes.

**Comment by mjpost** [comment]
All right, just waiting for @temporaer.

**Comment by temporaer** [comment]
Confirming as well.

**Comment by mjpost** [comment]
Okay. Four people with reasonable resemblance to the first four authors of this paper have requested a small change. I'm convinced. The paper is [in place](http://aclweb.org/anthology/W17-5526v2) and [will be linked](https://aclanthology.info/papers/W17-5526/w17-5526) the next time @villalbamartin generates the site.

**Comment by kracwarlock** [comment]
Thank you very much for the quick resolution!
