### ISSUE TITLE
aclanthology.coli.uni-saarland.de

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#111]
What are the impediments to getting `aclanthology.coli.uni-saarland.de` to report itself as `aclanthology.info`?

**Comment by villalbamartin** [comment]
`aclanthology.coli.uni-saarland.de` is the server's internal name at the University, and we used it for a long time to make sure switching the DNS would work just fine.

Now, here is some interesting behavior: If you access the anthology via `aclanthology.info`, the first time it will redirect you to `aclanthology.coli.uni-saarland.de`. But if you do it a second time in the same session it remains `aclanthology.info`. I have often wondered about this, but I never seriously stopped to think about why this happen. 

I will look into why this happens. If I can get the server to stay in the domain in which it was called, then we can implement a [301 Redirect](https://en.wikipedia.org/wiki/HTTP_301) for well-behaved services, and support the old domain in the background for the other ones.

**Comment by mjpost** [comment]
Awesome work, Martín! This is really great news.

I’d be happy to have it hard-coded, but I’ll leave it up to you.

I didn’t see the Saarland → Anthology redirect happening in one of my browsers. Maybe the cache just needed clearing. I expect this will be the case for many folks.

**Comment by villalbamartin** [comment]
It was not my original intention to redirect in that case - I was assuming that someone accessing `aclanthology.coli.uni-saarland.de` with https had a good reason for doing it.

But anyway, this is no longer an issue. As of now (and after a very brief minute of instability, sorry!) all requests should redirect to `https://aclanthology.info`. For the record, this is what our configuration file looks like now (with extra comments):

```
server {
    # If someone uses regular http for either domain,
    # they get redirected to https://aclanthology.info
    listen  80;
    server_name  aclanthology.info aclanthology.coli.uni-saarland.de;
    # Redirect to HTTPS
    return         301 https://aclanthology.info$request_uri;
}
server {
    listen       443 ssl;
    # We still listen to aclanthology.coli.uni-saarland.de,
    # but we redirect to aclanthology.info
    server_name  aclanthology.coli.uni-saarland.de;
    ssl_certificate /etc/letsencrypt/live/aclanthology.info/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aclanthology.info/privkey.pem;
    return         301 https://aclanthology.info$request_uri;
}
server {
    listen       443 ssl default_server;
    server_name  aclanthology.info;
    ... # All configuration options are here
}
```

Our SSL certificates are still valid for both domains and they may remain so until the end of time (or until no one accesses the old server at all), but this should be invisible for us.

I will tentatively close this ticket, as things seem to be working fine. If I broke something, feel free to reopen it.

**Comment by mjpost** [comment]
This works for me in the https case now, too. Thanks a ton, @villalbamartin.
