### ISSUE TITLE
COLING venue page headings

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#1112]
https://www.aclweb.org/anthology/events/coling-2020/ and previous COLINGs list "ICCL" as the abbreviation at the top of the page, which is incorrect (it stands for the International *Committee* on Computational Linguistics, the body that organizes the conference).

**Comment by aryamccarthy** [comment]
I just noticed the same and was going to file an issue—but you’re already on it.

To be clear about the proposed remedy: `s/ICCL/COLING/`, right? The venue is still the International _Conference_ etc etc.

**Comment by nschneid** [comment]
Yep
