### ISSUE TITLE
INLG proceedings not part of SIGGEN

### ISSUE THREAD

**Issue by evanmiltenburg** [acl-org/acl-anthology#1114]
The [INLG2020 proceedings](https://www.aclweb.org/anthology/volumes/2020.inlg-1/) should be part of SIGGEN, just like previous editions (e.g. [2019](https://www.aclweb.org/anthology/volumes/W18-65/)). This is currently not the case.

**Comment by mjpost** [comment]
Closed in 5e6ab9774cf8749d645334405797505c225c94b2.
