### ISSUE TITLE
Correction to Anthology ID W16-4009

### ISSUE THREAD

**Issue by AleksandrsBerdicevskis** [acl-org/acl-anthology#1123]
[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
Please merge the ACL anthology page for the second author (https://www.aclweb.org/anthology/people/a/aleksandrs-berdicevskis1/) with this one: https://www.aclweb.org/anthology/people/a/aleksandrs-berdicevskis/. Berdicevskis and Berdičevskis are the same person (me), but due to a different spelling two different pages have been created. If merging the pages requires correcting the spelling in W16-4009 (Berdičevskis > Berdicevskis), that's fine with me. Thanks very much.

**Comment by danielgildea** [comment]
done
