### ISSUE TITLE
LREC2020 listed as part of COLING2020

### ISSUE THREAD

**Issue by marcschulder** [acl-org/acl-anthology#1128]
LREC 2020 appears to be listed as part of COLING 2020, causing its papers to be listed there also: https://www.aclweb.org/anthology/events/coling-2020/#2020-lrec-1
The individual papers aren't duplicated, but list both venues in their description.
I assume this is a bug?

**Comment by nschneid** [comment]
Yep, #1126

**Comment by mjpost** [comment]
Closed with #1118.
