### ISSUE TITLE
Correction to Anthology ID XXX

### ISSUE THREAD

**Issue by wasiahmad** [acl-org/acl-anthology#1130]
Hi, I have two author profiles in the ACL anthology.

1. https://www.aclweb.org/anthology/people/w/wasi-ahmad/
2. https://www.aclweb.org/anthology/people/w/wasi-uddin-ahmad/

My name is Wasi Uddin Ahmad, but my first name is Wasi and last name is Ahmad. So, I want to retain my first profile which is under `wasi-ahmad`. Is it possible to change my name from `Wasi Uddin Ahmad` to `Wasi Ahmad` for the following paper such that both my profiles get merged?

- https://www.aclweb.org/anthology/K19-1035/

Thanks!

**Comment by davidweichiang** [comment]
We can merge your two profiles without having to make a change to the papers.

**Comment by wasiahmad** [comment]
Thanks! But it seems like the profiles are not merged yet.

**Comment by davidweichiang** [comment]
Sorry, it was bundled with another correction which was left hanging. I'll try to merge it soon.
