### ISSUE TITLE
Correction to Anthology ID 2020.fever-1.5

### ISSUE THREAD

**Issue by belindal** [acl-org/acl-anthology#1132]
## Metadata correction

It would great if my middle initial could be added to my name for this paper, i.e. "Belinda Li" -> "Belinda Z. Li".
I have two different profiles right now because of this paper, and I would like to merge them:
- https://www.aclweb.org/anthology/people/b/belinda-li/
- https://www.aclweb.org/anthology/people/b/belinda-z-li/

**Comment by mjpost** [comment]
Done. Please be sure to correct this in your Softconf profile. I have also added the first version as a variant for you, in case this occurs again.
