### ISSUE TITLE
Correction to Anthology ID 2018.jeptalnrecital-long.13

### ISSUE THREAD

**Issue by sebastiendelecraz** [acl-org/acl-anthology#1138]
## Metadata correction: please describe the issue here**

My name in meta-data is write in french with an accent on the e. This spawned a second anthology page in my name with only this article.

Can you please change my name in metadata as : Sebastien Delecraz

And, if possible, I would like to merge the two profiles
https://www.aclweb.org/anthology/people/s/sebastien-delecraz1/
https://www.aclweb.org/anthology/people/s/sebastien-delecraz/
in one:
https://www.aclweb.org/anthology/people/s/sebastien-delecraz/

**Comment by mjpost** [comment]
Fixed in abb4a094cf9e41eab9c44b823cb4b4bbdcaf7c7b.
