### ISSUE TITLE
Correction to Anthology ID: 2020.wat-1.2

### ISSUE THREAD

**Issue by benyamin2011** [acl-org/acl-anthology#1139]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
This paper has been written by me (Benyamin Ahmadnia) as the first and corresponding author, and Raul Aranovich as the second author (as it is correctly published in the PDF file of the paper), while in the ACL Anthology and all the paper corresponding, the authors appear as Benyamin Ahmadnia and Bonnie Dorr and this is a mistake.
In order to avoid any authorships and/or ethics issues or conflicts, please change the second author’s name (from Bonnie Dorr to Raul Aranovich) in all corresponding, and update me accordingly.
I need to confirm and emphasize that there is no need to make any changes to the published PDF file.

## Revision or erratum: please add the following information**

- [ ] I have attached the revised PDF or erratum to this issue
- [*] I have written a brief description of the changes below
[Description.pdf](https://github.com/acl-org/acl-anthology/files/5656036/Description.pdf)

The brief description of the changes will be displayed on your paper page and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**
This paper has been written by me (Benyamin Ahmadnia) as the first and corresponding author, and Raul Aranovich as the second author (as it is correctly published in the PDF file of the paper), while in the ACL Anthology and all the paper corresponding, the authors appear as Benyamin Ahmadnia and Bonnie Dorr and this is a mistake.
In order to avoid any authorships and/or ethics issues or conflicts, please change the second author’s name (from Bonnie Dorr to Raul Aranovich) in all corresponding, and update me accordingly.
I need to confirm and emphasize that there is no need to make any changes to the published PDF file.

**Comment by benyamin2011** [comment]
The authors' list and order in the PDF are correct, we only need to make a change in the metadata.

**Comment by mjpost** [comment]
Thanks. This is a bit of an unusual error. Can you explain how this happened? 

Changes to the author list require approval from the workshop chairs. It would also be ideal to hear from Bonnie (either here or over email) so that she could confirm this.

**Comment by benyamin2011** [comment]
This changes had to be applied in the camera-ready. I tried multiple times but I was not able to make any changes in the authors’ list.
It wouldn’t be ideal to include Bonnie in this issue because she doesn’t have any contributions in this work and she is not aware of this publication.
In case you need to contact her, you can do yourself (bdorr@ihmc.us). This is out of my patience to re-explain everythings from the beginning.
The problem comes from the WAT workshop organizers, I made my request at the time of notifications but no one responded to my request.

Best,
Benyamin

Benyamin Ahmadnia, Ph.D.
————————————–—
Postdoctoral Scholar
Department of Linguistics
University of California, Davis
https://www.dr-ahmadnia.com

________________________________

**Comment by benyamin2011** [comment]
Also, I need to mention that the Workshop Chairs are already aware of this issue. They advised me to contact you for making the mentioned changes. You can contact them as well to get approval.

**Comment by benyamin2011** [comment]
Please update me on your decision. This is a neither difficult nor strange mistake to be corrected. In case you decide to no further action on this issue, that would be okay. However, there still be authorship right for the correct second author (as shown in the paper).

**Comment by akoehn** [comment]
Hi @benyamin2011, as Matt pointed out, it is our policy that we do not decide on whether to change authorship metadata.  We always require approval from the chairs, as [stated in our policy](https://www.aclweb.org/anthology/info/corrections/#note-on-author-changes).  They are the ones that can actually make an informed decision, not us and that is why we require a notification from them for these kinds of changes.

**Comment by bonniejdorr** [comment]
Benyamin and I are co-authors on a multitude of papers, but the one mentioned here appears to have been a mistake. I thought this was rectified when WAT 2020 organizers contacted me on 12/8/2020 (the first I heard about this paper's existence). My understanding from Benyamin is that my name was accidentally included in the submission. Benyamin, unfortunately you'll need to see this through. Here is what I wrote to WAT 2020 organizers when questioned about the request to replace my name with Dr. Raul Aranovich on 12/8/2020 (an error fix that I supported, of course):

_Hello Dr. Gao,

Thanks for writing to me regarding the issue below. I have Cc'ed Benyamin to ensure all are in the loop.

I do not have any record of co-authorship on a 2020 paper with that particular title. Benyamin and I have lots of co-authored papers over the last two years, so it is understandable that an error like this could have easily happened, as authorship list are sometimes copy-pasted to future related publications.

So yes, please do replace my name with the correct second author. Thank you for addressing this quickly, and it is no problem at all for me. 

I assume you will contact Dr. Aranovich, as well, to let him know the correction has been made. [Feel free to forward this correspondence to him, if needed, so everyone knows we've gone full circle on this communication.]

Bonnie Dorr_

**Comment by mjpost** [comment]
Okay, thanks @bonniejdorr. So it seems what happened is your name was entered inadvertently at submission time and then this couldn't be corrected prior to publication. I am comfortable moving forward if we can get confirmation from Raul Aranovich. 

@benyamin2011, can you arrange for him to email me or comment on this thread? We can then quickly make the change and include it with the next batch of corrections.

**Comment by benyamin2011** [comment]
Dear Dr. Aranovich,

I apologize for any inconvenience.

Regarding our publication (WAT 2020) that was affected by the wrong authors’ name, would you please check the communication email here and just confirm that you’re the second author of the paper?
I’d appreciate your time and patience.

Yours Truly,
Benyamin

P.n
Thanks to Dr. Dorr for all her cooperation.


Benyamin Ahmadnia, Ph.D.
————————————–—
Postdoctoral Scholar
Department of Linguistics
University of California, Davis
https://www.dr-ahmadnia.com

________________________________

**Comment by benyamin2011** [comment]
Hello everybody. Yes, I agree to be listed as a co-author in this publication. Please let me know if this acknowledgment is sufficient. All the best,

RAUL ARANOVICH

On Jan 3, 2021, at 2:49 PM, Ahmadnia, Benyamin <ahmadnia@tulane.edu<mailto:ahmadnia@tulane.edu>> wrote:

Dear Dr. Aranovich,

I apologize for any inconvenience.

Regarding our publication (WAT 2020) that was affected by the wrong authors’ name, would you please check the communication email here and just confirm that you’re the second author of the paper?
I’d appreciate your time and patience.

Yours Truly,
Benyamin

P.n
Thanks to Dr. Dorr for all her cooperation.


Benyamin Ahmadnia, Ph.D.
————————————–—
Postdoctoral Scholar
Department of Linguistics
University of California, Davis
https://www.dr-ahmadnia.com<https://www.dr-ahmadnia.com/>

________________________________

**Comment by mjpost** [comment]
Thanks, everyone. I have independently received a note from the workshop chairs, so this is all settled now.
