### ISSUE TITLE
EI Indexing

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#114]
[Elsevier Ei indexing](https://suggestor.ei.engineeringvillage.com) is important to many academics in China. We need a process for doing this as automatically as possible for *ACL and EMNLP proceedings.

**Comment by villalbamartin** [comment]
I should probably be the one to contact them, so I'm assigning this ticket to myself. I'll send them an email and see what they need from us to be indexed.

**Comment by mjpost** [comment]
Chenliang Li of Wuhan University had volunteered to do this—I'll ping him to see the status.

**Comment by mjpost** [comment]
This is being tracked here: 
https://github.com/acl-org/acl-anthology/projects/9

**Comment by lichenliang-whu** [comment]
We just finished suggesting EMNLP'18 and NAACL'19 (including long and short papers) to  EI.

**Comment by mjpost** [comment]
Great! I marked it on this page: https://github.com/acl-org/acl-anthology/projects/9
