### ISSUE TITLE
Correction to Anthology ID W19-2507

### ISSUE THREAD

**Issue by qcrit** [acl-org/acl-anthology#1147]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

The metadata for paper W19-2507 should be amended so that the last author is listed as Joseph P. Dexter, not Joseph Dexter. The last author is correctly listed as Joseph P. Dexter in the pdf.

**Comment by mjpost** [comment]
Done. Please ensure your name is entered correctly in your Softconf profile.
