### ISSUE TITLE
Correction: metadata J17-4007

### ISSUE THREAD

**Issue by robvanderg** [acl-org/acl-anthology#115]
In the bib file of J17-4007 (https://aclanthology.info/papers/J17-4007/j17-4007.bib) a part of my last name is listed as first name, resulting in me being two persons in the anthology. This should be corrected to:

and van der Goot, Rob

Kind regards, 
Rob van der Goot

**Comment by mjpost** [comment]
Thanks for reporting this. Do you mind creating a pull request with the fix? You can navigate [to the file](https://github.com/acl-org/acl-anthology/blob/master/import/J17.xml), make the fix directly in the browser, and issue it as a pull request. I can then check it over and approve it.

**Comment by danielgildea** [comment]
This seems to be a systematic problem with the CL journal articles.
Min-Yen, would it be possible to fix the name parsing in your import script?
(I think this script is not in the repository.)
