### ISSUE TITLE
Correction to Anthology ID 2020.udw-1.22 p. 195–204

### ISSUE THREAD

**Issue by elejalea** [acl-org/acl-anthology#1152]
[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here
[Tyers, Mishchenkova.pdf](https://github.com/acl-org/acl-anthology/files/5666819/Tyers.Mishchenkova.pdf)
Dear colleagues. My coauthor and I worked on the article ‘Dependency annotation of noun incorporation in polysynthetic languages’ [p. 195–204]. I am very sorry to report that by mistake there is indicated my affiliation to only one institution (School of Linguistics, HSE University, Moscow ). This causes a terrible problem in my home institution that is the Russian Academy of Sciences (Institute of Linguistics, RAS, Moscow; Institute for System Programming, RAS, Moscow), so that I cannot pass the attestation this year. I would kindly ask to permit the addition of my affiliation in the forementioned article. In total, three institutions should appear in my data. I have made this change in the attached pdf version. 
Hope for understanding.
Karina Mishchenkova

**Description of changes**
This revision corrects the affiliation information of Karina Mishchenkova. Two institutions are added: Institute of Linguistics, RAS, Moscow; Institute for System Programming, RAS, Moscow.

**Comment by elejalea** [comment]
Dear colleagues. Thank you for regarding the request. But the link for the uploaded second version is incapacitated. It pops 404 Not Found error. The error is encountered while trying to use an ErrorDocument to handle the request. https://www.aclweb.org/anthology/2020.udw-1.22v2.pdf

**Comment by mjpost** [comment]
Sorry @elejalea, I forgot to upload the files. Everything is now in place.
