### ISSUE TITLE
Correction to Anthology ID 2020.nlptea-1.3

### ISSUE THREAD

**Issue by brucewlee** [acl-org/acl-anthology#1155]
**Please be sure to add the Anthology ID in the title**

## Metadata correction: please describe the issue here**
Dear colleagues. My coauthor and I worked on the article ‘LXPER Index 2.0: Improving Text Readability Assessment Model for L2 English Students in Korea'. The metadata was put as "Bruce Lee," but I unify all my academic publishing under the name "Bruce W. Lee". And that's what I wrote in the PDF, too. Can I have my metadata name changed to "Bruce W. Lee"? This is causing some administrative issues here in my institution.

**Comment by akoehn** [comment]
Yes, you can.  The easiest edit the metadata in https://github.com/acl-org/acl-anthology/blob/master/data/xml/2020.nlptea.xml and create a pull request.

Also make sure to have your name correct in softconf and other submission sites so this does not come up again.

**Comment by mjpost** [comment]
Closed in #1157.
