### ISSUE TITLE
Correction to Anthology W18-5813

### ISSUE THREAD

**Issue by kr0niker** [acl-org/acl-anthology#1159]
## Metadata correction: the paper is written by me, Ivan P. Yamshchikov as stated in the PDF. Please, change the author from "Ivan Yamshchikov" to "Ivan P. Yamshchikov"

**Comment by akoehn** [comment]
If you can, please file a PR by adjusting your name in the relevant files in https://github.com/acl-org/acl-anthology/tree/master/data/xml; this will make everything faster (cc #1158)
