### ISSUE TITLE
Correction to Anthology ID 2020.findings-emnlp.203

### ISSUE THREAD

**Issue by zsquaredz** [acl-org/acl-anthology#1173]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Revision or erratum: please add the following information**

- [ ] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**
Please update the metadata of the paper: the title of the paper need to be updated to "Reducing Quantity Hallucinations in Abstractive Summarization" instead of "Reducing the Frequency of Hallucinated Quantities in Abstractive Summaries"

**Comment by mjpost** [comment]
Thank you! If you create a PR referencing this issue, it will get resolved faster.

**Comment by zsquaredz** [comment]
Hi Matt, I have figured the title in the xml seems to be the correct one: https://github.com/acl-org/acl-anthology/blob/dedf122473acf933295a69165ed38ebcc25402df/data/xml/2020.findings.xml#L2439 

Not sure why Google Scholar had it wrong: https://scholar.google.com/citations?user=UO0MJeQAAAAJ&hl=en

**Comment by mjpost** [comment]
Google likely crawled it just after we ingested it, and before the PCs noticed the error and corrected it.
