### ISSUE TITLE
Correction to Anthology 2020.emnlp-main.385

### ISSUE THREAD

**Issue by dspoka** [acl-org/acl-anthology#1177]
Paper Name: An Empirical Investigation of Contextualized Number Prediction

The author order list is flipped. Prof. Taylor Berg-Kirkpatrick should be last and I should be first.

**Comment by akoehn** [comment]
Per our guidelines, we require an ACK for author list changes from the relevant chairs.  Please contact them so that they either comment here or send an email to the anthology.

**Comment by mjpost** [comment]
Also, if permission from the PCs is obtained, this would require a new PDF, which has Taylor first.

**Comment by mjpost** [comment]
Permission was obtained from a program chair via personal email.

**Comment by dspoka** [comment]
[numerical_emnlp (5).pdf](https://github.com/acl-org/acl-anthology/files/5773062/numerical_emnlp.5.pdf)
Paper is attached!

**Comment by dspoka** [comment]
Hey just wanted to check see if there is anything else I need to do. 
Thanks, 
Daniel

**Comment by mjpost** [comment]
No, you're all set. This is just waiting until the next time we process corrections, on early February.

**Comment by dspoka** [comment]
Hey I'm sorry but the Anthology still is not changed. Is anything wrong?

**Comment by mjpost** [comment]
Hi @dspoka: I am the bottleneck here. We are working on changing that, and that process has consumed most of my time. In the meantime, I hadn't realized how much time had passed on your request here. I'll process this shortly.

**Comment by dspoka** [comment]
Thank @mjpost! I just saw some people starting citing our work and it would be really hard to change things after that point. Thanks again!

**Comment by mjpost** [comment]
I understand—sorry for the delay. We intend to do this on a monthly basis.

**Comment by avi-jit** [comment]
@mjpost, while the change gets reflected on the anthology, can other authors (like me) manually change the bib when citing this paper? I have a camera-ready deadline for NAACL today.

**Comment by mjpost** [comment]
Yes, you can, but the paper has been updated. If you download the updated bib file it should be correct.
