### ISSUE TITLE
Correction to Anthology ID: 2020.acl-main.189

### ISSUE THREAD

**Issue by xkianteb** [acl-org/acl-anthology#1182]
**Please be sure to add the Anthology ID in the title**

Anthology ID: 2020.acl-main.189
Title: Active Imitation Learning with Noisy Guidance

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
In the Anthology the 2nd and 3rd author names are switched. Here is the link to the paper (https://www.aclweb.org/anthology/2020.acl-main.189/). If you look at the paper the actual author order is Kianté Brantley, Amr Sharaf, Hal Daumé III but the Anthology has it Kianté Brantley, Hal Daumé III, Amr Sharaf including in the official BibTeX as well.

## Revision or erratum: please add the following information**

- [ ] I have attached the revised PDF or erratum to this issue
- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**

**Comment by akoehn** [comment]
We need an ACK from the relevant PC. See https://www.aclweb.org/anthology/info/corrections/#note-on-author-changes

**Comment by nschneid** [comment]
@akoehn Is this really necessary for author *order* changes to match the existing PDF?

**Comment by xkianteb** [comment]
"Permission is not required for the correction of obvious spelling errors or other typos or for changes to an author’s name." - This seems like permission should not be required given that the order to is wrong with respect to the original pdf that was submitted. If I need permission, who should I contact about this?

**Comment by mjpost** [comment]
According to [recent ACL CsfP](https://2021.aclweb.org/calls/papers/#authorship), yes.

**Comment by mjpost** [comment]
@xkianteb You should email the ACL 2020 program chairs. This is quite a stringent policy and I personally think it’s causing a lot of work, but the policy was adopted after some considerable thought. There may be cause to loose the policy in the future but at the moment we’re bound by it.

**Comment by akoehn** [comment]
> @akoehn Is this really necessary for author order changes to match the existing PDF?

Yes, and it is indeed the main reason for the policy.  Most of the conferences disallow author ordering changes after submission but at the same time a lot of them do not check the camera-ready PDF.  Therefore, authors could circumvent this by submitting a PDF with different ordering and then request the change to the metadata later.  As we don't know anything about each case, we removed ourselves from the decision and not defer to the PC.

**Comment by mjpost** [comment]
I have received permission from the 2020 ACL PC chairs via email.

**Comment by xkianteb** [comment]
@mjpost Thank you so much :)
