### ISSUE TITLE
Change issue template for author changes

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#1184]
We should create a specific template for author ordering changes where the process is detailed.  It gets tedious to have to remind people to read the guidelines (even though they are linked in the general template).

Don't have time for that now, just wanted to open this issue.

**Comment by mjpost** [comment]
We should use an [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) for this.

**Comment by akoehn** [comment]
Oh, two years already :-)

I agree that it seems like a very good idea to rely more on issue forms. Even with templates people fill them out so differently.

**Comment by mjpost** [comment]
In addition to this, it would be nice to have a link on every paper page that reads something like

> See an error in the metadata for this page? Click here to file an issue.

This link would open an issue with the provided metadata-correction issue form. That form would also link people to the documentation showing them how to create their own PR.

**Comment by mjpost** [comment]
This was fixed in #1826.
