### ISSUE TITLE
Correction to Anthology ID W18-6604 and 2020.lrec-1.669

### ISSUE THREAD

**Issue by hgoliv** [acl-org/acl-anthology#1186]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

In both of the papers with the ID in the title (W18-6604 and 2020.lrec-1.669) the author "Ricard Rodrigues" is linked to the profile "Ricardo Rodrigues Ciferri", but they are not the same person.

Best,
Hugo

**Comment by mjpost** [comment]
Thank you! I think this was created automatically and it's good to have the mistake corrected.
