### ISSUE TITLE
The full proceedings for EMNLP2020 are missing 😢

### ISSUE THREAD

**Issue by bshmueli** [acl-org/acl-anthology#1197]

**Comment by nschneid** [comment]
Are you looking for https://www.aclweb.org/anthology/2020.emnlp-main.0/?

**Comment by bshmueli** [comment]
Thanks but the linked PDF is not the full proceedings.

**Comment by nschneid** [comment]
Oh it's just the front matter. @mjpost any idea?

**Comment by mjpost** [comment]
The front matter PDF is there, but not the full proceedings (10k-page PDF). I'm not sure why, I'll have to look into it.
