### ISSUE TITLE
Correction to Anthology ID C92-XXXX

### ISSUE THREAD

**Issue by Nyavlys** [acl-org/acl-anthology#1204]
## Metadata correction
Booktile for [International Conference on Computational Linguistics (COLING) (1992)](https://www.aclweb.org/anthology/events/coling-1992/) refers to the "15th International Conference", as [COLING 1994](https://www.aclweb.org/anthology/events/coling-1994/) does (whereas [COLING 1990](https://www.aclweb.org/anthology/events/coling-1990/) refers to the "13th" International conference").

According to the [ACM digital library](https://dl.acm.org/conference/coling/proceedings), COLING 1992 is the 14th conference.

Note however that the pdf files for the [front matter](https://www.aclweb.org/anthology/C92-1000.pdf) are indeed entitled "15th International Confernce".

**Comment by mjpost** [comment]
Yikes. I'm going to correct the title so it will at least be fixed in BibTeX and other metadata. Thanks for reporting!
