### ISSUE TITLE
Broken link in MustC paper

### ISSUE THREAD

**Issue by skyprince999** [acl-org/acl-anthology#1207]
There is a broken link on Page 2 of the paper 
[MustC: A multilingual Speech translation dataset](https://www.aclweb.org/anthology/N19-1202.pdf) 

Note 5 gives a broken link. It should point to the following: https://github.com/lowerquality/gentle

**Comment by akoehn** [comment]
We collect and publish papers but don't edit them on our own.  If you find something that needs changing, you can contact the authors.

That being said, the text in the paper is correct and only the underlying hyperlink is broken. Imo that does not warrant a new revision.
