### ISSUE TITLE
Correction to Anthology ID 2020.webnlg-1.1

### ISSUE THREAD

**Issue by mille-s** [acl-org/acl-anthology#1215]
## Metadata correction: please describe the issue here**
The order of the authors was changed in the camera-ready version, but we did not update the metadata.

Current order: Simon Mille, Petros Alvanitopoulos, Roberto Carlini Salguero, Jens Grivolla, Montserrat Marimon Felipe, Georgios Meditskos, Maria Rousi, Klearchos Stavrothanasopoulos, Spyridon Symeonidis, Stefanos Vrochidis, Leo Wanner

Desired order: Simon Mille, Spyridon Symeonidis, Maria Rousi, Montserrat Marimon Felipe, Klearchos Stavrothanasopoulos, Petros Alvanitopoulos, Roberto Carlini Salguero, Jens Grivolla, Georgios Meditskos, Stefanos Vrochidis, Leo Wanner

Thanks!

**Description of changes**
The order of the authors was updated.

**Comment by akoehn** [comment]
Please obtain an ACK from the relevant chairs, as described here: https://www.aclweb.org/anthology/info/corrections/#note-on-author-changes

**Comment by DaBr01** [comment]
As Workshop Chair of INLG 2020 I'm okay with the change.

**Comment by mille-s** [comment]
Hi can you please confirm that everything is in order for the change to be implemented? Thanks!

**Comment by mjpost** [comment]
This looks good. We will get to this in the next round of corrections we process.
