### ISSUE TITLE
Bug report - ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND

### ISSUE THREAD

**Issue by shizhediao** [acl-org/acl-anthology#1219]
*Use this issue template to help file your issue. Please delete portions that are not relevant, and feel free to change it or add sections.*

#### Issue description
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/norman-k-sondheimer.md" from page "papers/P79/P79-1006.md": page not found

#### Steps to reproduce the issue

1. simply clone and run `make`
alternatively, I tried the instructions in detailed README.
I am able to run steps 1 to 3 but failed at Step 4: Run Hugo when I type in `hugo --minify `

#### What's the expected result?

> Optionally, the --minify flag can be used to create minified HTML output

#### What's the actual result?

> INFO     Running Hugo... this may take a while.
Start building sites … 
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/norman-k-sondheimer.md" from page "papers/P79/P79-1006.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/norman-k-sondheimer.md" from page "papers/P81/P81-1006.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/n-j-belkin.md" from page "papers/P80/P80-1039.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/nikolaos-aletras.md" from page "papers/2020.aacl/2020.aacl-main.80.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/naoaki-okazaki.md" from page "papers/2020.aacl/2020.aacl-main.89.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/norman-k-sondheimer.md" from page "papers/P82/P82-1016.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/norman-k-sondheimer.md" from page "papers/P82/P82-1026.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/nikhil-prabhu.md" from page "papers/2020.aacl/2020.aacl-srw.13.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/nishant-kambhatla.md" from page "papers/2020.aacl/2020.aacl-srw.14.md": page not found
ERROR 2021/02/22 11:36:43 [en] REF_NOT_FOUND: Ref "/people/n/ngo-thanh-nhan.md" from page "papers/P84/P84-1023.md": page not found
...

#### Additional details / screenshot

- ![Screenshot]()
-

**Comment by akoehn** [comment]
shizhediao writes:

> #### Steps to reproduce the issue
>
> 1. simply clone and run `make`

That is strange because every commit to the master branch is built using
the CI pipeline.

Can you report
 - the git commit ID you are on
 - the hugo version you are using (`hugo version`)
?

**Comment by shizhediao** [comment]
Hi,
git commit id = 0f15da09e1aad521cbb28265e4069ced6c019c2b
hugo version is: Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
Thanks!

**Comment by mbollmann** [comment]
We haven't tested with Hugo versions newer than v0.58 so far, I think it's very likely that they introduced some breaking changes that will require adapting our templates.

**Comment by mbollmann** [comment]
Oh, I just saw #1221, maybe that's the same problem you're experiencing?

**Comment by mjpost** [comment]
I'm going to close this on the assumption that this is the same as #1221. Please feel free to reopen if that is not that case!
