### ISSUE TITLE
If we're going to generate the dynamically, I think we should make both available. If statically as part of Hugo, then we should just do RIS.

### ISSUE THREAD

**Issue by dhiyaa** [acl-org/acl-anthology#1223]
If we're going to generate the dynamically, I think we should make both available. If statically as part of Hugo, then we should just do RIS.

_Originally posted by @mjpost in https://github.com/acl-org/acl-anthology/issues/235#issuecomment-480246650_

**Comment by mjpost** [comment]
Hi @dhiyaa—why did you turn this into a new issue?

**Comment by mjpost** [comment]
This seems like an accident, so closing. Feel free to reopen with an explanation.
