### ISSUE TITLE
Correction to Anthology ID 2020.inlg-1.0 - FrontMatter INLG 2020

### ISSUE THREAD

**Issue by bridav** [acl-org/acl-anthology#1225]
Correction to https://www.aclweb.org/anthology/2020.inlg-1.0/

## Revision or erratum: please add the following information**

- [x] I have attached the revised PDF or erratum to this issue

- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:
> Correct to programme and area chair list as well as list of sponsors
    Uploaded new book.pdf of front matter generated from softcon.

**Description of changes**

- Corrected Missing Acknowledgement of sponsor - Bloomberg L.P. 
- Added 1 missing PC member
- Move 1 incorrect Area chair to PC [list.]
See front matter attached (url
[book.pdf](https://github.com/acl-org/acl-anthology/files/6028378/book.pdf)
)

**Comment by mjpost** [comment]
Unfortunately, we're currently unable to add revisions to front matter. This will be addressed soon.
