### ISSUE TITLE
Fail to build: 'Illegal number: hugo'

### ISSUE THREAD

**Issue by MikeWangWZHL** [acl-org/acl-anthology#1226]
*Use this issue template to help file your issue. Please delete portions that are not relevant, and feel free to change it or add sections.*

#### Issue description
I encountered this issue when running `make`:
`/bin/sh: 1: [: Illegal number: hugo`
`...`
`Makefile:149: recipe for target 'build/.mods' failed
make: *** [build/.mods] Error 123`

I downloaded `hugo_extended_0.81.0_Linux-64bit.tar.gz`, extracted the binary file and put it in one of my `PATH` : `.../miniconda/bin`, note that since I am on lab server I don't have permission to root and the global `/usr/local/bin`  

when I run `hugo help` in command line it works fine.

Any hint on what's going on?

Thanks in advance

**Comment by mbollmann** [comment]
That's a weird error message for sure, but based on the line where it appears: do you have "bibutils" installed, as mentioned in the README under "Prerequisites"? You can test that by running `which bib2xml` for example.

**Comment by akoehn** [comment]
If that turns out to be the source of the root message, we should definitely add a check in the makefile for missing binaries.

**Comment by MikeWangWZHL** [comment]
Thanks for your replies! It turns out that I don't have 'bibutils' (I accidentally checked 'binutils' LOL), I will try to contact admin to install it and try again, Thanks!
BTW, it turns out that I can use the API to get access to data without build the web, thanks for the great work!

**Comment by mbollmann** [comment]
@akoehn Absolutely. On a related note, how difficult would it be to add a flag to the Makefile that skips building the various bibliography files? I often hot-patch something like that for development as it means some 100k fewer files hogging my harddrive, and the website will build fine without them.

@MikeWangWZHL You're welcome! If you can't/don't want to install bibutils, try commenting out the two instances of `@find build/data-export ... >/dev/null` in the Makefile. You won't get the EndNote and MODS XML bibliography files, but the rest of the build process should run fine.

**Comment by akoehn** [comment]
Marcel Bollmann writes:

> @akoehn Absolutely. On a related note, how difficult would it be to
> add a flag to the Makefile that skips building the various
> bibliography files? I often hot-patch something like that for
> development as it means some 100k fewer files hogging my harddrive,
> and the website will build fine without them.

30 seconds of work? I’ll do a PR with both changes.

**Comment by akoehn** [comment]
I think this issue can be seen as resolved.  Feel free to reopen if there is a reason.
