### ISSUE TITLE
Correct XML files for title casing

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#123]
There are many data integrity issues related to title casing. See [Issue #90](https://github.com/acl-org/acl-anthology/issues/90). What we need to do is:

- Go back through old titles and correct the casing. This means (a) removing {} when they were incorrectly placed around the entire title and (b) correctly uppercase acronyms and proper nouns and protect them with {}s.
- Come up with a method for checking newly ingested data to be sure that this has been done. It would be easy to build a list of things that should be protected (acronyms like MT and NLP, words like "English") and flag them if not.

**Comment by davidweichiang** [comment]
My understanding from the discussion at #90 is that authors/pub chairs did do this in bibtex and the information was discarded on conversion to xml. Are the original bibtex files kept anywhere?

Also, if only there were scientists who could build us an AI to automatically detect capitalized words...

**Comment by mjpost** [comment]
It's possible that this was lost on import, but I think there is a deeper problem, which is general lack of knowledge on the right way to do this. Authors, for example, are given no guidance when filling out their paper metadata when uploading camera readies. I've been a pub chair and tried to be very thorough and yet don't remember checking for this. I also remember one conference from a while back (I think on the old Anthology, before the XML conversion) where every paper title was surrounded in `{{ ... }}`. So there hasn't been consistency, which is to be expected when you have a different set of volunteers conscripted into the relevant jobs every year. To get this correct, I think we need a combination of info-boxes at upload time, prompting authors to enter this information, along with checks at ingest time to ensure it's been done.

**Comment by davidweichiang** [comment]
I agree, but I'm just thinking about the easiest way to fix past conferences. Given that it often wasn't done correctly even in the originals, maybe a rule-based processor would be good enough. I can try to write some rules. What would the input format and output format be? Do the xml files in import/ have a way to mark capitalized words?

**Comment by mjpost** [comment]
Yes, building a handful of rules would probably go a long way, e.g., `Penn` → `{Penn}`. That would be great if you took a stab at it!

The XML files currently don't mark capitalization. I suggest we alter the `<title>` tag directly and then modify downstream non-BibTeX scripts to strip it out.

**Comment by davidweichiang** [comment]
So this should take the form of a script that reads XML files like the ones in `import/`, writes out the same format, and protects capitalized words in the `<title>` field -- with curly braces, or a new tag like `<name>`?

**Comment by mjpost** [comment]
That sounds good to me. (I was going to suggest we could even skip XML parsing, but it looks like 3486 of 48259 `<title>` instances are not closed on the same line).

What do you mean by `<name>`? Are you suggesting preserving `<title>` and just adding a new field? That could also make sense and would preserve backward compatibility. I'd suggest something more specific than `<name>`, though, like `<casedtitle>` (or whatever). Or maybe you're suggesting embedding `<name>` inside `<title>`? That seems like a purer, more XML-authentic approach, and I think there is an easy way to get the frontier of any XML node, so it would be easy to process. Again I'd suggest a more specific tag name...

It would be good to factor out the set of rules somehow, say into another data structure, so that they could be read by another script. That could be useful for example in [an import validation script](https://github.com/acl-org/acl-anthology/issues/130).

**Comment by davidweichiang** [comment]
I meant something like `<title><name>BLEU</name>: a Method for Automatic Evaluation of Machine Translation</title>`. (Actually, I chose a particularly troublesome example. Not only is that word supposed to be in small caps, it's supposed to be blue!)

I'd be fine with `<cased>` as well. It seems more Latin-specific and less semantic, but that's fine, we're dealing with a completely Latin-specific problem.

**Comment by mjpost** [comment]
Whichever name you like is fine. 

I also like the idea of adding (BLEU-specific) attributes for small caps and color.

**Comment by davidweichiang** [comment]
[This branch](https://github.com/davidweichiang/acl-anthology/tree/fixedcase/tools/fixedcase) has a preliminary script for marking fixed-case words in the titles. I eyeballed some of the changes it makes and didn't see any false positives...false negatives are of course much harder to find.

**Comment by mjpost** [comment]
PR #161 addressed many of these. I just noticed a new one, though: IBM, as in [A Simple, Fast, and Effective Reparameterization of IBM Model 2](https://aclanthology.info/papers/N13-1073/n13-1073).

**Comment by davidweichiang** [comment]
Oh, there are so many...so far I’ve experimented with the following heuristics. 

- If a word appears in past abstracts more often with uppercase than lowercase, make it fixed case. (This list has to be filtered by hand.)

- If a word has any uppercase letters in non-initial position, make it fixed case. (This would fail for a camelCase word that appears as CamelCase at the beginning of a title.)

- If a single word is at the beginning of a title and is set off by a colon, make it fixed case. (This would fail for a title like “Cdec: A System Normally Spelled in Lowercase Except Here”.)

Those heuristics have really high precision; no idea about recall.

Complications: There are a lot of fixed-case phrases like “Modern Standard Arabic” that can’t be tagged on a word by word basis.

**Comment by davidweichiang** [comment]
The new version of anthologize.pl projects curly braces to `<fixed-case>` in the `title` and `booktitle` fields, so going forward this should be taken care of.

For some reason there are still a couple of old conferences where the curly braces were not succesfully projected to the XML; I'll take a look at that next.

And of course the majority of conferences never had curly braces to begin with.

**Comment by nschneid** [comment]
>  Complications: There are a lot of fixed-case phrases like “Modern Standard Arabic” that can’t be tagged on a word by word basis.

What about a heuristic that considers all n-grams in titles, checking to see whether they are present and consistently capitalized in the corresponding abstract, in order to bootstrap a list of capitalized n-grams?

(Or there may be a better algorithm from the terminology extraction literature.)

**Comment by davidweichiang** [comment]
I think that could work. One difficulty is that these phrases are not consistently capitalized. Some people might write it as "Modern Standard Arabic" and some poeple might write it as "modern standard Arabic." (When I write a BibTeX entry by hand and encounter cases like this, I try to check the paper itself to see how the authors wrote it.)

**Comment by mjpost** [comment]
@nschneid, we have a PR open at #231, with David's first-pass scripts and my hopeless regex effort. Do you have any bandwidth+interest to give this a shot?

**Comment by nschneid** [comment]
Not in the next, like, 3 months. Sorry. :(

**Comment by danielgildea** [comment]
I think David's scripts are ready for prime time now [967ffc51b5e85cc2ef90c5b9313e862e23059351].  Let's just run them 
and not worry about Modern Standard Arabic.

**Comment by mjpost** [comment]
I'm going to close this because I think we've substantially addressed everything here. If phrasal caps bother someone enough to fix it, we can reopen it.
