### ISSUE TITLE
Convert HTML escape codes to UTF-8

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#124]
The XML files are full of HTML escape codes (e.g., `&amp;`, `&#252;`, and many more). These are ugly and unnecessary and often require special conversions. We should have establish the XML as officially UTF-8, and convert all of these instances directly to their UTF-8 representations.

**Comment by danielgildea** [comment]
& must be encoded as &amp; for a document to be valid xml.

&#252; could be replaced with with a UTF-8 character, but it is valid
XML as is and is understood by the XML parsing libraries in both ruby and
python without any extra conversion/coding on our part.
