### ISSUE TITLE
techtalks.tv links are down

### ISSUE THREAD

**Issue by working12** [acl-org/acl-anthology#1241]
*Use this issue template to help file your issue. Please delete portions that are not relevant, and feel free to change it or add sections.*

#### Issue description
techtalks.tv links in the ACL page is not working

#### Steps to reproduce the issue

1. Go to any research paper with techtalks.tv video link and try to access it.

**Comment by mbollmann** [comment]
Thanks! I can confirm that the whole techtalks.tv site isn't loading for me either. However, that's a problem on the side of techtalks.tv, not ours – there's nothing we can do here except remove the links if the problem persists. We should probably wait a while longer to see if they come back online first.

(Also, we're all unpaid volunteers here, so please don't fret if it takes a week or two to get a response – it's expected!)

**Comment by mbollmann** [comment]
Looks like this problem has persisted for quite some time, and that we do have backups, but they don't seem to be publicly available anywhere yet, as discussed in https://github.com/acl-org/acl-anthology/issues/167#issuecomment-654315111 and below.

Maybe @mjpost can weigh in if there's been any progress on this. For now I'm going to close this as a duplicate of #167.

**Comment by akoehn** [comment]
There are backups but only on disk.P.S. This whole video situation is a bit of a mess and that is not anybody's fault, just an effect of lots of things.

**Comment by mjpost** [comment]
The situation has worsened—techtalks.tv has been reclaimed as a pornographic site, which we are now linking to.
