### ISSUE TITLE
Correction to Anthology ID 2020.vlsp-1

### ISSUE THREAD

**Issue by sonvx** [acl-org/acl-anthology#1249]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
- The list of editors is different from the current version. Please update the correct list in the attached meta file.

## Revision or erratum: please add the following information**

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:
> This revision corrects the proceedings file by replacing the actual proceedings file. The current version is empty.

**Description of changes**
- Update the meta file (list of editors)
- Update the proceedings file with the correct proceedings.

[meta.txt](https://github.com/acl-org/acl-anthology/files/6253028/meta.txt)
[VLSP-2020_bib.txt](https://github.com/acl-org/acl-anthology/files/6253029/VLSP-2020_bib.txt)
[VLSP-2020.pdf](https://github.com/acl-org/acl-anthology/files/6253030/VLSP-2020.pdf)

**Comment by mjpost** [comment]
I have put the PDF in place. @xinru1414, we could use a PR here that:

* Corrects the `<editor>` lines to match the provided meta
* Adds the updated crc32 hash to the `<url>` line in the `<meta>` block

**Comment by sonvx** [comment]
Hi @mjpost ,
I created a PR to correct the meta file, please let me know if I should update anything else: https://github.com/acl-org/acl-anthology/pull/1252.
