### ISSUE TITLE
Correction to Anthology ID 2020.emnlp-main.236

### ISSUE THREAD

**Issue by eumesy** [acl-org/acl-anthology#1251]
Attached is a revised version of the manuscript. Could you please upload it to the ACL anthology?
[2020.emnlp-main.236v2.pdf](https://github.com/acl-org/acl-anthology/files/6257515/2020.emnlp-main.236v2.pdf)

## URL

https://www.aclweb.org/anthology/2020.emnlp-main.236/

## Types of corrections: Revision

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below
- [x] I have added the header and footer stamps, as well as the original page numbering.

## Description of changes

1. Described the experimental setup in more detail.

- Described the stopword list we used, in Appendix A.4.
- Described how to limit the vocabularies when using vector converter algorithm, in Appendix D.
- Described the pseudocode and hyperparameters of **U**nsupervised SIF weighting and **P**iecewise CCR (Ethayarajh, 2018), in Appendix D.

2. Conducted comprehensive experiments in a consistent setting.

We re-ran all preliminary experiments (Sec. 7.1, 7.2, 7.3) with the same settings as the benchmark test (Sec. 7.4) and updated the values in the relevant tables.
Also, we conducted the experiments in a more comprehensive setting. For example, we added the experimental results of fastText to the table where only the results of GloVe and word2vec were listed.
Note that the results of the additional experiments do not affect the claims of the paper in any way.

3. Made other minor fixes.

- Added one grant to Acknowledgments.
- Identified the language we worked on (Bender rule), in Section 2.
- Added citations, e.g., the library we used (Flamary and Courty, 2017).
- Corrected an error in which the experimental results were written interchangeably (the WMD score of Twitter and that of SICK-R), in Table 9.
- Moved the results of GenSen (Subramanian et al., 2018) from the supervised methods section to the semi-supervised methods section, in Table 10.
- Fixed typos.

**Comment by eumesy** [comment]
To whom it may concern (@xinru1414 ?);
when do you expect this revision to be reflected in the ACL anthology?
It's been four weeks, so let me confirm to be sure.
https://www.aclweb.org/anthology/info/corrections/

**Comment by akoehn** [comment]
It was added to a pull request to be merged soon; changes are usually bundled because it is too much work to do them one by one.

**Comment by eumesy** [comment]
@akoehn @xinru1414 Thank you for your quick response! I understand. I appreciate your hard work for us. 
I am waiting for the merge to complete.
