### ISSUE TITLE
PDF missing

### ISSUE THREAD

**Issue by hunterhector** [acl-org/acl-anthology#1254]
It seems like PDF links from the anthology are all broken.

I first observe that the PDF file for https://www.aclweb.org/anthology/N13-1073/ is missing, the link https://www.aclweb.org/anthology/N13-1073.pdf returns 404. But I soon realize many papers are missing, such as:

https://www.aclweb.org/anthology/N13-1073.pdf
https://www.aclweb.org/anthology/2020.acl-main.1.pdf

**Comment by mjpost** [comment]
This was a temporary problem that's now fixed.

**Comment by jonmay** [comment]
doesn't seem fixed...

**Comment by mjpost** [comment]
Fixed again.
