### ISSUE TITLE
Link to pdf broken

### ISSUE THREAD

**Issue by adityak6798** [acl-org/acl-anthology#1255]
The link to the pdf of [https://www.aclweb.org/anthology/2020.louhi-1.9/](https://www.aclweb.org/anthology/2020.louhi-1.9/) is broken. I can see the metadata but not the pdf. Pdf link [https://www.aclweb.org/anthology/2020.louhi-1.9.pdf](https://www.aclweb.org/anthology/2020.louhi-1.9.pdf)

**Comment by mjpost** [comment]
This was a temporary problem that's now fixed.
