### ISSUE TITLE
dataset for ACL 2020 paper giving 404 error

### ISSUE THREAD

**Issue by eagirre** [acl-org/acl-anthology#1257]
The dataset for this paper is giving a 404 error:

https://www.aclweb.org/anthology/2020.acl-main.84/

**Comment by mjpost** [comment]
Hmm, it seems that every attachment just links to `https://www.aclweb.org/anthology/attachments`. I suspect that this has to do with #1124, which reworked the prefixes a little bit. I'll fix this a bit later tonight. Thank you for reporting, and apologies for the trouble.

**Comment by davidweichiang** [comment]
@mjpost It's not just attachments, it's all the PDFs, too.
