### ISSUE TITLE
error: open pdf file in acl-anthology

### ISSUE THREAD

**Issue by MonsKim999** [acl-org/acl-anthology#1258]
Hi, I am an author of the COLING conference in ACL-anthology.
I tried to open my paper in this link: https://www.aclweb.org/anthology/2020.coling-main.177/
​
but I got the error saying "The page you were looking for doesn't exist"
​
Please, could you rebuild this page to be able to open a pdf file?

**Comment by mjpost** [comment]
Thanks for reporting, fixed!
