### ISSUE TITLE
Some 2020 workshop PDFs missing?

### ISSUE THREAD

**Issue by katrinerk** [acl-org/acl-anthology#1259]
I'm getting a 404 not found on the PDF link of this workshop paper: https://www.aclweb.org/anthology/2020.blackboxnlp-1.15/
and also on this: https://www.aclweb.org/anthology/2020.scil-1.35/

Feel free to ignore if you just haven't gotten around to adding the PDFs, but I was surprised  that the pages are there but the PDFs are not.

Thanks,
Katrin

**Comment by ryskina** [comment]
I am getting the same issue for every PDF so far in ACL 2020. I also tried some papers from older conferences that were definitely there before and they all give a 404.

**Comment by mjpost** [comment]
Thanks for reporting, fixed!
