### ISSUE TITLE
Correction to Anthology ID 2021.eacl-main.156

### ISSUE THREAD

**Issue by eberts-google** [acl-org/acl-anthology#1267]
[We_Need_to_Talk_About_Random_Splits__EACL_2021_Camera_Ready_.pdf](https://github.com/acl-org/acl-anthology/files/6311714/We_Need_to_Talk_About_Random_Splits__EACL_2021_Camera_Ready_.pdf)

## Revision or erratum: please add the following information**

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

**Description of changes**
This revision fixes the URL to the source code (page 2), which accompanies the paper. The correct URL is https://github.com/google-research/google-research/tree/master/talk_about_random_splits.

**Comment by mjpost** [comment]
Can you please add the [Anthology ID](https://www.aclweb.org/anthology/info/ids/)?

**Comment by akoehn** [comment]
There is none yet because eacl 2021 is not yet ingested.

**Comment by mjpost** [comment]
Ah, right. It's under review but not merged (#1264).
