### ISSUE TITLE
Erroneous duplicate elements in the authoritative XML

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#127]
While parsing the XML files under `import/`, I discovered two instances with minor errors:

+ Paper W17-7001 has two `<title>` elements, the latter of which has the same content as its `<booktitle>` and is probably there in error. The title output on the current website is correct, but a different parser could possibly interpret this the wrong way.
+ Paper Y04-1021 has three `<booktitle>` elements, all of which are identical.

I can fix this and do a PR, but also wanted to draw attention to the fact that the current XML schema doesn't account for these things (and therefore can't detect them), as it allows for an arbitrary number of any element in a `<paper>`, includes titles.

**Comment by mjpost** [comment]
Yes, please fix in a PR.

Can we tighten the schema? We could address at least `<booktitle>` and `<title>`. This would fit naturally in the data integrity project.
