### ISSUE TITLE
2021 not showing up on the main page

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1274]
EACL 2021 is live but not showing up on the main page. @mbollmann, do you have time to take a look?

https://www.aclweb.org/anthology/events/eacl-2021/

**Comment by mbollmann** [comment]
Is this the first ingestion of 2021? The current main page still has to be updated manually for new years... I can do that later today.

(Reminds me that with the new automatic build previews, I should build some demo branches for an updated main page!)

**Comment by mjpost** [comment]
I created a PR (#1276) that partially fixed it, but didn't get the headers right. Just pushed up what I think is a fix. If not, I'll take you up on your offer to fix later!

https://aclanthology.org/previews/front-page-2021/
