### ISSUE TITLE
Switch to aclanthology.org

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1278]
Sometime this year, I am hoping we can switch to aclanthology.org as our primary hosting site. There are technical reasons—ACL IT has been pushing for this, since we often come close to our hosting and bandwidth limits, and the Anthology is a key piece of that. But I also like it better aesthetically; aclanthology.org (versus aclweb.org/anthology) is more parsimonious (16 versus 20 characters); and using a top-level domain reflects its status.

The main question is whether we change the canonical URL as well. My thinking is that yes, we do, with permanent 301 redirects for papers existing at the time of the switch.

I welcome discussion.

**Comment by knmnyn** [comment]
I strongly endorse this.  I think the team has made a few change to canonical URLs without much (any?) negative repercussions, so this makes sense.  I'll be very happy if the team can make this as the canonical version because this was the original intent of registering this domain under ACL auspices over a decade ago.

**Comment by mjpost** [comment]
Here are some TODOs:

1. [ ] Update the canonical URL in `bin/anthology/data.py`
1. [ ] Update the Google Search console to crawl aclanthology.org instead of aclweb.org
1. [ ] Update the `<link rel=canonical>` header for all pages (this might follow from 1)

**Comment by Genius1237** [comment]
Wasn't sure whether to bring this up here or open a separate issue about this. Google has started showing results from aclanthology.org in it's search results. For papers on aclweb.org, it shows the last modified/updated date correctly. For papers from the new site, it shows something like 4 days ago (when it last crawled it I guess). I've attached screenshots below.

Old
![image](https://user-images.githubusercontent.com/15867363/126162132-8845e582-8047-4643-a322-d162eff4bf0f.png)

New
![image](https://user-images.githubusercontent.com/15867363/126162174-a7877efb-c052-4c46-937c-63f26d8224ea.png)


Being able to look at the year is useful in getting to know when a paper is from. Anything that can be done to address this in the future?

**Comment by akoehn** [comment]
We deliver all metadata we can (though there is some more to come in #1407, which might fix the extracted text) . Maybe google stores the date it first found the site?

**Comment by mjpost** [comment]
Yes, I'm guessing this is what is happening. Though it might be that for new files, Google uses metadata from the file's timestamp itself. In that case we could manually set those dates to, say, the ingestion date. However, I'm not sure we'll have bandwidth to look into this.
