### ISSUE TITLE
Papers out of sync

### ISSUE THREAD

**Issue by ojahnn** [acl-org/acl-anthology#128]
I was looking up a paper and found that the pdf link pointed to the wrong file:

The pdf at [http://aclweb.org/anthology/W04-1907](http://aclweb.org/anthology/W04-1907) should be [**Corpus-based Induction of an LFG Syntax-Semantics Interface for Frame Semantic Processing**](https://aclanthology.info/papers/W04-1907/w04-1907), but instead it's [**The HOLJ Corpus: supporting summarisation of legal texts**](https://aclanthology.info/papers/W04-1908/w04-1908). On the page for this title, the pdf link incorrectly points to [**Automated Induction of Sense in Context**](https://aclanthology.info/papers/W04-1909/w04-1909) - they're all from the same venue, with different IDs. I'm not sure how far down this goes.

I'm wondering if it would be possible to detect, correct, and avoid errors like this automatically?

Might be technically related to #44. If the system can look into the pdf, it can also check the pdf's title against the metadata and see if there are any conflicts.

**Comment by mjpost** [comment]
Thanks for reporting this! It seems there is an off-by-one error for the whole volume, and that [the "Editorial"](https://github.com/acl-org/acl-anthology/blob/e4d2c6d87a1ee6e2671bbb652dfeaf5c354d1fa2/import/W04.xml#L2126) is missing as a separate PDF.

This is definitely the kind of thing we should check for at ingestion time. I [created an issue](https://github.com/acl-org/acl-anthology/issues/130) within the [Data Integrity Project](https://github.com/acl-org/acl-anthology/projects/5) (which is looking for a lead!) to track this more general issue.

**Comment by mjpost** [comment]
#141 reported a few more ingestions issues:

- W04-13
- W04-19
- W04-30 (with last two papers)
