### ISSUE TITLE
Ingestion: FNP 2021

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1297]
Publication date: 2021-09-10
1 volume

**Comment by xinru1414** [comment]
@drelhaj Yes. Please @ me here once ISBN and copyright forms are taken care of.

**Comment by drelhaj** [comment]
@xinru1414 we received all the signed copyright forms. Do you want them included in the zip file in the link above (as that's what I understood from Matt's comment up there) or can I use a separate link as in [this link](https://www.lancaster.ac.uk/staff/elhaj/fnp_proceedings/fnp_2021_copyrights.tgz)? as for the ISBN, we haven't received a reply from ACL (acl@aclweb.org), I'm a bit worried we contacted the wrong person. Cheers

**Comment by xinru1414** [comment]
closed in #1623
