### ISSUE TITLE
Try to get ACL, etc. indexed again

### ISSUE THREAD

**Issue by cfedermann** [acl-org/acl-anthology#13]
**S/N:** 15
**Priority:** high
**Title:** Try to get ACL, etc. indexed again

**Comment by knmnyn** [comment]
This has to deal with the long-term difficulty of having ACL Anthology venues (those that the ACL has direct control over; not third-party proceedings) indexed by scientific citation indexers (e.g., Web of Science).  We probably need to invoke a committee to help with this.

**Comment by villalbamartin** [comment]
As far as I understand, this issue has been solved with the latest server migration.
