### ISSUE TITLE
Correction to Anthology ID 2020.nlpcovid19-2.24

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1301]
An explanation is forthcoming.

[Tracking_And_Understanding_Public_Reaction_During_Covid_19_Saudi_Arabia_As_A_Use_Case.pdf](https://github.com/acl-org/acl-anthology/files/6421063/Tracking_And_Understanding_Public_Reaction_During_Covid_19_Saudi_Arabia_As_A_Use_Case.pdf)

**Comment by xinru1414** [comment]
Closing this because of repetition. See #1303
