### ISSUE TITLE
Correction to Anthology ID 2020.paclic-1.3

### ISSUE THREAD

**Issue by huyen144** [acl-org/acl-anthology#1313]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
Please help to correct the title of this paper 
"A new look a99t Pattani Malay Initial Geminates: a statistical and machine learning approach".
(https://aclanthology.org/2020.paclic-1.3/)
The correct title is: 
"A new look at Pattani Malay Initial Geminates: a statistical and machine learning approach".
(replacing "a99t" with "at").

Thank you.

## Revision or erratum: please add the following information**

- [ ] I have attached the revised PDF or erratum to this issue
- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**

**Comment by mjpost** [comment]
Thanks. If you want to edit `data/xml/2020.paclic.xml` and create a PR, it will expedite this.

**Comment by huyen144** [comment]
> Thanks. If you want to edit `data/xml/2020.paclic.xml` and create a PR, it will expedite this.
Sure, thank you very much.
