### ISSUE TITLE
Duplicate acronyms on venue pages

### ISSUE THREAD

**Issue by marcschulder** [acl-org/acl-anthology#1317]
#### Issue description
In venues.yaml a few venues list their acronym in brackets as part of the name field, e.g. _"International Conference on Computational Linguistics (COLING)"_. However, this information is already specified in the acronym field. On the [venue's page](https://www.aclweb.org/anthology/venues/coling/) this results in an acronym duplication: "International Conference on Computational Linguistics (COLING) (COLING)"

#### Solution
I have removed the acronyms from name fields to fix this, see #1316

#### Additional details
The one case I did not touch yet (although I think it should also be changed) is _DeeLIO_, because the acronym is mentioned in the middle of the name: "Deep Learning Inside Out (DeeLIO): The Workshop on Knowledge Extraction and Integration for Deep Learning Architectures".

**Comment by mjpost** [comment]
Closed via #1316.
