### ISSUE TITLE
Bug report: preview overwrites root

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1319]
Every once in a while, the root of aclanthology.org gets overwritten by the syncing preview. For example, right now, aclanthology.org redirects to http://localhost:8000/previews/ingest-amta-2006, and the browser displays a failure.

This must have to do with the [preview workflow target](https://github.com/acl-org/acl-anthology/blob/master/.github/workflows/preview.yml), but I can't figure out how, since it only happens sometimes.

**Comment by mjpost** [comment]
It looks like this occasionally happens when a branch preview is updated: somehow, the branch subdirectory is undefined. [Here's an example](https://github.com/acl-org/acl-anthology/runs/2603846037?check_suite_focus=true):

<img width="801" alt="image" src="https://user-images.githubusercontent.com/455256/118648811-ce684880-b7b0-11eb-99e6-11771d8c335e.png">

This could, however just be the fault of bash in echoing the value. I can't see why it works sometimes and not others.

**Comment by akoehn** [comment]
one safe-guard would be to abort if the branch name is empty.
