### ISSUE TITLE
Correction to Anthology ID 2021.eacl-main.310

### ISSUE THREAD

**Issue by marcospln** [acl-org/acl-anthology#1321]
Corrected version of the dataset for the paper 2021.eacl-main.310 (_Probing for idiomaticity in vector space models_)

The file can be downloaded from [this repository](https://github.com/marcospln/noun_compound_senses/archive/refs/heads/main.zip)

**Description of changes:**
Sentences with copyright were removed from the dataset, and  a script to automatically get them from the original resources was added.

**Comment by xinru1414** [comment]
@marcospln please link the new version of the .pdf file directly.

**Comment by marcospln** [comment]
https://www.aclweb.org/anthology/2021.eacl-main.310.pdf

**Comment by marcospln** [comment]
The issue was to include the new version of the dataset (https://github.com/marcospln/noun_compound_senses/archive/refs/heads/main.zip), no of the the pdf file: both pdfs in the anthology are the same file (and it's ok).

**Comment by mjpost** [comment]
@xinru1414 the revision has the same checksum; we should remove the extra files and the revision line from the XML file with June's revisions.

@marcospln In general we don't update attachments, though there isn't a specific policy against it. It's just a lot of work handling corrections as it it. We don't have a formal policy for this, though, so I suppose we can do it this time. @xinru1414, this would go under `attachments/eacl/2021.eacl-main.310.Software.zip`.

**Comment by marcospln** [comment]
> @marcospln In general we don't update attachments, though there isn't a specific policy against it. It's just a lot of work handling corrections as it it. We don't have a formal policy for this, though, so I suppose we can do it this time. @xinru1414, this would go under `attachments/eacl/2021.eacl-main.310.Software.zip`.

  The attachment is the dataset, not the software. In any case, if the policy is not to upload attachment is not problem, as the paper includes the url to the dataset itself.

**Comment by mjpost** [comment]
The [paper page](https://aclanthology.org/2021.eacl-main.310/) currently links to Software. Is this request here replacing that, or to add an additional resource?

**Comment by marcospln** [comment]
This is an additional resource. The page had this resource, but it has been removed due to copyright issues, now solved in the new version. But again, feel free to don't upload it.

**Comment by xinru1414** [comment]
@mjpost Shall we update it or not?

**Comment by mjpost** [comment]
Yes.
