### ISSUE TITLE
Correction to Anthology 2020.paclic-1.3

### ISSUE THREAD

**Issue by francescob13** [acl-org/acl-anthology#1335]
[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

There is a spurious 99 in the title:

A new look a99t Pattani Malay Initial Geminates: a statistical and machine learning approach

Should really be:

A new look at Pattani Malay Initial Geminates: a statistical and machine learning approach

The title is correct in the pdf.

Could this please be fixed?

**Comment by mjpost** [comment]
A PR has been submitted for this already in #1322.
