### ISSUE TITLE
Previews should not be indexed

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1343]
We should add a `robots.txt` file to the repo and prevent indexing of everything under `previews`. We might also want to prevent indexing of PDFs and secondary files on mirror sites, at least for file types with a `<link ref=canonical>` tag at the top.

**Comment by akoehn** [comment]
Agree re previews, but as already discussed somewhere else, as far as I understand canonical links do not work across domains and therefore cannot be used for mirrors.

**Comment by mjpost** [comment]
I had forgotten that discussion. But digging around a bit, it seems that it might not be true that cross-domain links don't work:

* [rel=canonical: the ultimate guide](https://yoast.com/rel-canonical/)
* [Using Rel=Canonical Tag For SEO-Friendly Cross-Domain Duplicate Content](https://powerdigitalmarketing.com/blog/using-relcanonical-tag/#gref)

Good news for us if true. Something tells me to trust the SEO folks :)

**Comment by mjpost** [comment]
Google [backs this up](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls):

> Canonical URL: A canonical URL is the URL of the page that Google thinks is most representative from a set of duplicate pages on your site. For example, if you have URLs for the same page (example.com?dress=1234 and example.com/dresses/1234), Google chooses one as canonical. The pages don't need to be absolutely identical; minor changes in sorting or filtering of list pages don't make the page unique (for example, sorting by price or filtering by item color).
> The canonical URL can be in a different domain than a duplicate URL.

**Comment by akoehn** [comment]
yay! I probably confused it with the discussion about trying to mark our content (especially PDFs) as canonical in *our* metadata -- that does not work.

**Comment by mjpost** [comment]
With the new top level previews, it was easy to create a robots.txt. The canonical links are handled automatically when we switch.
