### ISSUE TITLE
404 error accessing PDF for "11.textgraphs-1.10"

### ISSUE THREAD

**Issue by dmhowcroft** [acl-org/acl-anthology#1346]
Actions:
0. navigate to https://www.aclweb.org/anthology/11.textgraphs-1.10/
1. click the PDF link to open https://www.aclweb.org/anthology/11.textgraphs-1.10.pdf

Expected Behavior:
access the PDF for paper `11.textgraphs-1.10`

Observed Behavior:
404 page not found error

**Comment by mnschmit** [comment]
The pdfs seem to be missing for all of this year's TextGraphs papers.

**Comment by mjpost** [comment]
Somehow, these got imported under the wrong Anthology ID. The IDs should be of the form `2021.textgraphs-1.X.pdf`. If you manually change the PDF url, you can retrieve the file. We will have this fixed today.
