### ISSUE TITLE
Correction to Anthology ID L18-1258

### ISSUE THREAD

**Issue by Tariq60** [acl-org/acl-anthology#1357]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
adding me as an additional author

I am already listed as an author in the current pdf in the anthology.
https://www.aclweb.org/anthology/L18-1258.pdf

**Description of changes**
adding me as an additional author: Tariq Alhindi

**Comment by mjpost** [comment]
Policy has been changed, this can be processed. Ping: @xinru1414

**Comment by Tariq60** [comment]
hello, will this request be processed now?

**Comment by mjpost** [comment]
@xinru1414 can you handle this with December's corrections?
