### ISSUE TITLE
404 WikiGraphs: A Wikipedia - Knowledge Graph Paired Dataset

### ISSUE THREAD

**Issue by ModestGoblin** [acl-org/acl-anthology#1358]
**404**
https://www.aclweb.org/anthology/11.textgraphs-1.7/
[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.
<blockquote class="twitter-tweet"><p lang="und" dir="ltr">❤️‍🔥 <a href="https://t.co/mWE5J5Bawz">pic.twitter.com/mWE5J5Bawz</a></p>&mdash; Thomas Sikma (@modestgoblin) <a href="https://twitter.com/modestgoblin/status/1401289703450714113?ref_src=twsrc%5Etfw">June 5, 2021</a></blockquote>

**Comment by mjpost** [comment]
These were incorrectly imported and have been moved. Please see https://aclanthology.org/2021.textgraphs-1.7/.

**Comment by ModestGoblin** [comment]
thank(s), :feelsgood:
