### ISSUE TITLE
Correction to Anthology ID W19-46 (Proceedings of the Fourth Arabic Natural Language Processing Workshop)

### ISSUE THREAD

**Issue by ortogono** [acl-org/acl-anthology#1364]
## Metadata correction: please describe the issue here**

Would it be possible to add Wajdi Zaghouani to the end of the list of editors of the workshop:
https://www.aclweb.org/anthology/W19-4600/

Thanks.

**Comment by xinru1414** [comment]
@ortogono Please obtain a permission from the chair, see [here](https://www.aclweb.org/anthology/info/corrections/#note-on-author-changes) .

**Comment by ortogono** [comment]
I was the publication chair for the workshop
https://sites.google.com/view/wanlp2021/home

**Comment by xinru1414** [comment]
repeat #1597 closing this one
