### ISSUE TITLE
Correction to Anthology ID 2021.cmcl-1.25

### ISSUE THREAD

**Issue by barry** [acl-org/acl-anthology#1367]
## Metadata correction: please describe the issue here**

The author order is wrong on the Anthology landing page and does not match the author order in the PDF:
https://www.aclweb.org/anthology/2021.cmcl-1.25/

**Comment by akoehn** [comment]
Hi @barry, please obtain an ack from the relevant chairs -- unless it's you :-) -- according to the notes on author changes: https://www.aclweb.org/anthology/info/corrections/

**Comment by akoehn** [comment]
ACK received via email.
