### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by emjotde** [acl-org/acl-anthology#137]
Hi,
I would like to submit a corrected version of the following paper:
http://aclweb.org/anthology/W18-6478

The changes are two minor corrections to math (missing parenthesis, replace max with min) and a typo. The math typos seem to have caused distress to PhD students trying to re-implement things.

[Dual_Conditional_Cross_Entropy_Filtering_of_Noisy_Parallel_Corpora (1).pdf](https://github.com/acl-org/acl-anthology/files/2854274/Dual_Conditional_Cross_Entropy_Filtering_of_Noisy_Parallel_Corpora.1.pdf)

Thanks a lot!
Marcin

**Comment by mjpost** [comment]
Thanks, we'll process this soon.
