### ISSUE TITLE
Correction to Anthology ID 2020.emnlp-main.517

### ISSUE THREAD

**Issue by xainlp** [acl-org/acl-anthology#1374]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

There is a typo in the title. Concretely, the two words `Active Learning` were attached together as one word `ActiveLearning`. Same error happens in the corresponding bibtex file, that is, in the title attribute `{A}ctive{L}earning` should be separated as two words: `Active` `Learning`

[edit by @akoehn: removed the empty part of the template]

**Comment by xinru1414** [comment]
@xainlp Did you link the new pdf? If not, please do so.

**Comment by xainlp** [comment]
@xinru1414 I haven't and I don't think it's necessary, the title is correct in the pdf version. The error appears only on the website and corresponding bibtex.  Any comments?

**Comment by mjpost** [comment]
Correct, this is metadata only. Thanks, @xainlp, we'll process this with June's corrections.
