### ISSUE TITLE
Adding Anthology ID 2021.naacl-srw.21

### ISSUE THREAD

**Issue by nelson-liu** [acl-org/acl-anthology#1389]
## Revision or erratum: please add the following information**

- [x] I have attached the revised PDF or erratum to this issue

Hi! I (one of the NAACL SRW chairs) mistakenly omitted this paper when compiling the proceedings. Would it be possible to add it as a new entry `2021.naacl-srw.21` ?

The paper is attached to this issue.
The title is: `Towards Multi-Modal Text-Image Retrieval to improve Human Reading`
The authors are: `Florian Schneider, Özge Alacam, Xintong Wang, Chris Biemann`
[37_Final_Paper_PDF.pdf](https://github.com/acl-org/acl-anthology/files/6704101/37_Final_Paper_PDF.pdf)

Thank you so much!

**Comment by nelson-liu** [comment]
Hi @mjpost , gentle ping / is there anything more I can do to help out with this issue?

**Comment by mjpost** [comment]
Yes, sorry this got missed. @xinru1414, can you add this paper? Probably easiest to just do it manually.

**Comment by nelson-liu** [comment]
thanks for bumping this @mjpost . @xinru1414 , let me know if there's anything I can do to help---thanks so much for helping out with this!

**Comment by mjpost** [comment]
I just added it. It will be merged with July's corrections.

**Comment by nelson-liu** [comment]
Thanks so much, Matt! I really appreciate your help on this, and sorry for the inconvenience :pray: . I'll close this issue once the changes are live.
