### ISSUE TITLE
Ingest IWCS 2021

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#1391]
The event has already happened with proceedings at https://iwcs2021.github.io/proceedings/, but I would like to be able to import papers with all the metadata.

**Comment by akoehn** [comment]
the new URL is: https://iwcs2021.github.io/proceedings.html and I assume the organizers are in the process of ingestion, as they state:
> The proceedings are made available for convenience before they appear on the aclanthology.

So I think there is no (unusual) work needed from our side.

**Comment by nschneid** [comment]
Ah OK— @kovvalsky is this in the works?

**Comment by kovvalsky** [comment]
@nschneid Yes, I have been in contact with @mjpost and he is planning to inject the IWCS and its satellite workshops' proceedings into the anthology.

**Comment by mjpost** [comment]
The ingestion tarball can be found here: https://iwcs2021.github.io/proceedings/iwcs/

We should mark the best papers as listed here: https://iwcs2021.github.io/proceedings.html

**Comment by nschneid** [comment]
Any progress here?
