### ISSUE TITLE
Move anthology PDFs over to aclanthology.info to get coverage by Scholar

### ISSUE THREAD

**Issue by cfedermann** [acl-org/acl-anthology#14]
**S/N:** 12
**Priority:** high
**Title:** Move anthology PDFs over to aclanthology.info to get coverage by Scholar
**Proposer:** Darcy Dapra

**Comment by knmnyn** [comment]
Changed to migrate service back to aclweb.org hosting.

**Comment by villalbamartin** [comment]
The solution we agreed on the end is: PDFs can be host anywhere (right now we are using aclweb.org), but we need a specific header for every paper in the Anthology. This has been now implemented, and so I'm closing this ticket.
