### ISSUE TITLE
I appear under two names

### ISSUE THREAD

**Issue by antmarakis** [acl-org/acl-anthology#1420]
Hi!

I am not sure where to post this, so I will write it down here. Apologies if this is the wrong place!

Recently I changed my name on the User Profile page (without changing any other information). I now see that my page has been split into two, under the two different names.

[Page 1](https://aclanthology.org/people/a/antonios-maronikolakis/)

[Page 2](https://aclanthology.org/people/a/antonis-maronikolakis/)

Is there a way to get it fixed? I didn't know changing a single field would have this effect.

**Comment by mjpost** [comment]
We can fix this easily. Which is the correct spelling?

**Comment by antmarakis** [comment]
Thank you! Just to confirm, the correct name should be "Antonis".
