### ISSUE TITLE
Q16 has been overwritten with contents of Q15

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#143]
This was introduced by commit 867a48df6a877b3567b3048e3f6c505a22915a0b.  The file `Q16.xml` seems to have the old contents of `Q15.xml` (without the abstracts), while the information about Q16 appears to have been lost in the process.

**Comment by mjpost** [comment]
Hmm, yes, you can see this in the diff ([direct link](https://github.com/acl-org/acl-anthology/pull/140/commits/867a48df6a877b3567b3048e3f6c505a22915a0b#diff-0aea4263629a67ce0e27f870a3110393)). 

I don't think the site has been regenerated so this didn't affect production, but I just restored the original Q16 until @davidweichiang can look at this.

**Comment by davidweichiang** [comment]
Sorry about that!! It's fixed by https://github.com/acl-org/acl-anthology/commit/9dacf44584749bd83f57897d61bb847771a31f6a.
