### ISSUE TITLE
Encoding errors

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#146]
There are [encoding issues in L12](https://github.com/acl-org/acl-anthology/blob/7a24dfe734b21e0b7952b26f67b328685a7d3b73/import/L12.xml#L8483). I don't know how widespread this is, but it would probably be sufficient to search the entire Anthology for non-token-initial instances of "Â".

**Comment by davidweichiang** [comment]
It looks like I fixed this in https://github.com/acl-org/acl-anthology/commit/c690ebc6e00090545c69b212618c3d5dc9e92847.
