### ISSUE TITLE
Paper labeling in C69.xml

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#147]
> The **C69** issue is a consequence of faulty XML, in my opinion. In the database import script, IDs of the form "x000" get interpreted as proceedings volumes, except for workshops, where it is IDs of the form "xx00". In `C69.xml`, volumes follow the workshop format, which leads to the first nine papers being ignored until a "proper" volume ID (1000) is found.

> However, IMHO, the actual issue is that each paper has its own proceedings entry, which doesn't seem correct or useful to me. I believe the file should have a single proceedings entry with ID 1000, and the individual papers should be renumbered 0101 -> 1001, 0201 -> 1002, 0301 -> 1003, and so on.

_Originally posted by @mbollmann in https://github.com/acl-org/acl-anthology/issues/107#issuecomment-465190070_

**Comment by davidweichiang** [comment]
The index page for C69 (https://www.aclweb.org/anthology/events/coling-1969/) is display weirdly, with many papers repeated and many papers omitted. I know that the numbering is wrong, but even so, should they be displaying like this?

**Comment by mjpost** [comment]
C69 just needs to be reorganized. Each paper has two entries: one for the preprint (an abstract), and the other for the paper (e.g., https://aclweb.org/anthology/C69-0100.pdf and https://aclweb.org/anthology/C69-0101.pdf).

I suggest that we

- renumber papers from numbers 1001..1071, deleting the preprints from direct access
- concatenate all papers into a volume, which will contain preprints and other items

So for example:

```xml
<volume id="C69">
 <paper id="0100">
 <title>INTERNATIONAL CONFERENCE ON COMPUTATIONAL LINGUISTICS COLING 1969: Preprint No. 1</title>
 </paper>

 <paper id="0101">
 <title>TREE GRAMMARS (= Δ-GRAMMARS)</title>
 <author><last>Mel’čuk</last><first>I. A.</first></author>
 <author><last>Gladky</last><first>A. V.</first></author>
</paper>
```

would become

```
<volume id="C69">
 <paper id="1001">
 <title>TREE GRAMMARS (= Δ-GRAMMARS)</title>
 <author><last>Mel’čuk</last><first>I. A.</first></author>
 <author><last>Gladky</last><first>A. V.</first></author>
</paper>
```

Thoughts? CC: @villalbamartin @danielgildea @mbollmann @davidweichiang

**Comment by mjpost** [comment]
Update: there are also a number of "post-prints", which appear to be commentary *after* the conference, a fascinating idea we should revive. Also [this document ("Die Mälarinseln und ihre Sehenswürdigkeiten Allgemeines über die Gegend)](https://aclweb.org/anthology/C69-7201.pdf) for @mbollmann. I would retain entries for them and also fold them into the full proceedings.
