### ISSUE TITLE
Missing PDF for 2021.privatenlp-1.3

### ISSUE THREAD

**Issue by habernal** [acl-org/acl-anthology#1489]
PDF is missing for https://aclanthology.org/2021.privatenlp-1.3/

Also, strangely, this paper is not listed in its parent WS proceedings here:

https://aclanthology.org/volumes/2021.privatenlp-1/

**Comment by mbollmann** [comment]
This is [apparently](https://github.com/acl-org/acl-anthology/commit/ca36605b81b508ee3d70480a41e92f4e11c29032) a non-archival paper that was mistakenly added to the Anthology. The real bug then is that the page https://aclanthology.org/2021.privatenlp-1.3/ still exists -- @mjpost, are we not running rsync with `--delete`?

**Comment by akoehn** [comment]
No, but we should (see https://github.com/acl-org/acl-anthology/blob/5c951490ca14a3fa5caffd3a1a288800bf79a6f7/Makefile#L318).

We used to have non-generated files in the target directory but I'm fairly certain that the mirroring work fixed that and we can now `--delete`.

**Comment by mjpost** [comment]
#1490
