### ISSUE TITLE
possible issue with anthology search

### ISSUE THREAD

**Issue by esalesky** [acl-org/acl-anthology#1492]
For some ACL 2021 papers (found specifically for some IWSLT 2021 papers) searching the exact paper title in the anthology returns nothing. However, they are in the anthology, and searching these papers on google turns up the paper in the anthology, suggesting it has been indexed. 

Examples: 
- Searching "ZJU’s IWSLT 2021 Speech Translation System" gives ["No Results"](https://aclanthology.org/search/?q=ZJU%E2%80%99s+IWSLT+2021+Speech+Translation+System), but the paper is [here](https://aclanthology.org/2021.iwslt-1.16/) in the Anthology, and searching the title on google rather than the anthology [returns the paper](https://www.google.com/search?client=ms-google-coop&q=ZJU%E2%80%99s+IWSLT+2021+Speech+Translation+System&cx=000299513257099441687:fkkgoogvtaw) -- in the Anthology
- This is less immediately obvious for some papers, where search returns related papers/people, but not the paper in question (see paper metadata on [this search](https://aclanthology.org/search/?q=Edinburgh%E2%80%99s+End-to-End+Multilingual+Speech+Translation+System+for+IWSLT+2021)), but again, the anthology link is returned by google

Screenshots:
- ![anthology screenshot](https://files.slack.com/files-pri/T409KA55G-F02BLMR7BME/image.png)
- ![google screenshot](https://files.slack.com/files-pri/T409KA55G-F02B3968ZQU/image.png)

**Comment by mjpost** [comment]
I think the screenshots are no longer available? We did just switch to Semantic Scholar for the search button, which in my limited testing produces much better results. For example, [2020.wmt-1.1](https://aclanthology.org/2020.wmt-1.1/) used to return non-matches from prior years, but [SS finds it nicely](https://www.semanticscholar.org/search?q=Findings%20of%20the%202020%20Conference%20on%20Machine%20Translation%20%28WMT20%29&sort=relevance).

**Comment by mbollmann** [comment]
I believe this has been fixed.
