### ISSUE TITLE
Correction to Anthology ID 2021.acl-long.110

### ISSUE THREAD

**Issue by abushoeb** [acl-org/acl-anthology#1493]
**Please be sure to add the Anthology ID in the title**
## Revision: please add the following information**

- [X] I have attached the revised PDF to this issue
- [X] I have written a brief description of the changes below

**A brief description**
This revision includes the missing subsection (extended 6.1 and 6.2) of section 6 (Dependency Parsing).

**Description of changes**
Subsection 6.1 was truncated due to having a special character in the text. Similarly, 6.2 was missing in the original submission. This revision includes those missing portions. 

[Download Revised paper](https://www.shoeb.info/wp-content/uploads/shoeb-acl-2021-emoji.pdf)

**Comment by mjpost** [comment]
Attaching file locally.
[shoeb-acl-2021-emoji.pdf](https://github.com/acl-org/acl-anthology/files/6978689/shoeb-acl-2021-emoji.pdf)
