### ISSUE TITLE
Ingest CCL 2021

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1532]
https://www.dropbox.com/s/qji3pa7mt3p1vv3/ccl2021_data.tgz?dl=0

**Comment by heshizhu** [comment]
Thank you. I am one of the two publishing chairs of CCL 2021. Our preferred ingestion date is August 31th (about two weeks). Please feel free to help me with any content issues.

**Comment by heshizhu** [comment]
Thank you. I am one of the two publishing chairs of CCL 2021. Our preferred ingestion date is August 31th (about two weeks). Please feel free to @ me with any content issues.
