### ISSUE TITLE
Remove affiliations from editor lines

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#157]
Based on a manual check, we should add input checks to editor lines for:

- Google
- University, Universitat
- Institute
- USA
- more than two tokens
- a comma
- III
- Chair
- Council
- (editor)

You can quickly find these with something like `grep "<editor.*," *.xml` from the command line. I started with some of these on [this branch](https://github.com/acl-org/acl-anthology/tree/editor_corrections) if someone wants to complete it.

_Originally posted by @mjpost in https://github.com/acl-org/acl-anthology/issues/151#issuecomment-468316304_

**Comment by davidweichiang** [comment]
I did a quick second check. But then I tried a more complex grep, `grep -A1 '<editor> *$' *.xml`, and for whatever reason, editor names formatted this way are _much_ more likely to have affiliations in them. So another round of corrections is needed before we can close this.

**Comment by mjpost** [comment]
Ah, yes, I didn't check multi-line editor lines. Really we should just parse this and check the parsed frontier of editor nodes...I may get to this tomorrow if you don't beat me to it. I updated the list of words to check above.
