### ISSUE TITLE
Handling DOIs

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#158]
We need to update [the DOI process](https://github.com/acl-org/acl-anthology/wiki/DOI) away from the Rails setup. This requires writing

- a script to submit volumes and papers for DOI assignation
- a scrip to take assigned DOIs and add them to the XML

**Comment by knmnyn** [comment]
@mjpost, how do you want the Anthology XML to be modified?  I can probably write a script to read in the XML using python3 and write it back out again with the DOI related children in the the appropriate place.

Can you point me to the proper outputting/formatting code for the XML output?  I'm hoping whatever I write will retain the exact formatting of the current Anthology XML so as to not totally change lines by vacuous reformatting.

**Comment by mjpost** [comment]
Hi @knmnyn—we just use your `<doi>` tag, with the DOI tag, e.g.,

    <doi>10.18653/v1/P17-2091</doi>

An example script for reading and writing the XML is [add_attachment.py](https://github.com/acl-org/acl-anthology/blob/master/bin/add_attachment.py). It takes an XML file to read, and another XML file to write (they can be the same path). You can see how it iterates through the papers in the file. If you call `indent()` on the root node at the end, it will be sure to create the correct indention (alternately, just make sure you set `node.tail` when you create the XML node—it should be `\n    ` (newline and four spaces).

**Comment by mjpost** [comment]
This is done and documented here: https://github.com/acl-org/acl-anthology/wiki/Adding-DOIs
