### ISSUE TITLE
Correction to Anthology ID W19-46

### ISSUE THREAD

**Issue by wajdiz** [acl-org/acl-anthology#1597]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Changes to the author list
Please add my name to the workshop proceedings as I was a co-organizer and my name is the only one missing.
I obtained permission from Barbara Plank the ACL 2019 workshop chair as per the attached email.
My name is to be added last in the author's list (just following Mahmoud) as per the order in proceedings.
My full name: Wajdi Zaghouani

[ACL 2019 Workshops - Correction-Barbara.pdf](https://github.com/acl-org/acl-anthology/files/7261281/ACL.2019.Workshops.-.Correction-Barbara.pdf)

You need permission from the relevant conference program chairs if you
want to change the author list in the metadata, see
[the notes on author changes](https://www.aclweb.org/anthology/info/corrections/#note-on-author-changes)

 - [ X] I have read the note on author changes and will contact the program chairs
       for permission to be posted here or via email.

## Revision or erratum: please add the following information**

- [ ] I have attached the revised PDF or erratum to this issue
- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**
Adding missing workshop organizers name.

**Comment by xinru1414** [comment]
@wajdiz Just double checking that this is a meta data change and the added organizer name is `Wajdi Zaghouani`
