### ISSUE TITLE
Correction to Anthology ID 2021.emnlp-main.557

### ISSUE THREAD

**Issue by avi-jit** [acl-org/acl-anthology#1634]
## Revision or erratum: please add the following information**

- [X] I have attached the revised PDF or erratum to this issue
- [X] I have written a brief description of the changes below

[paper.pdf](https://github.com/acl-org/acl-anthology/files/7480066/paper.pdf)

**Description of changes**
An acknowledgements section was added.

**Comment by avi-jit** [comment]
@xinru1414 @mjpost let me know if something needs to be done from my end?

**Comment by xinru1414** [comment]
@avi-jit Nothing you need to do. The November correction PR will be approved and merged at the end the month
