### ISSUE TITLE
EMNLP 2021 workshops missing from joint.yaml

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#1636]
In the joint.yaml, one workshop is missing and one is incorrect:

 - codi: the joint lists `2021.codi-1` but the volume in the XML is `main`
 - `wnut.2021-1` is missing

I'm not creating a PR for this as I am not sure whether the codi volume should be changed to `1` or the joint should be changed to `main` and I have to grab lunch soon :-)

**Comment by akoehn** [comment]
And NILLI is missing as well, according to twitter: https://twitter.com/ale_suglia/status/1456510355035893761

**Comment by mbollmann** [comment]
I can't take care of this right now, but want to bring attention to #1164 again...

**Comment by mjpost** [comment]
What is NILLI? I don't see anything like that [on the workshop page](https://2021.emnlp.org/workshops).

**Comment by akoehn** [comment]
> What is NILLI? I don't see anything like that [on the workshop page](https://2021.emnlp.org/workshops).

No clue; I was just quoting the twitter thread on my mobile, do I couldn't check whether it's actually an error. Seems like it's not.

**Comment by mjpost** [comment]
Adding this to the ingest script would help, but partially it's a process problem of messy handoffs.
