### ISSUE TITLE
Missing PDFs

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1650]
The following PDFs are missing from the server. @davidstap, the majority of them are MT Archive PDFs, can you fix this?

## Files that could not be downloaded
- [x] https://aclanthology.org/2021.bionlp-1.pdf
- [x] https://aclanthology.org/2021.maiworkshop-1.pdf

**Comment by davidstap** [comment]
Hi @mjpost, I can re-ingest these to recreate the PDFs and upload them again.

Do you have any clue why these went missing? They must have been there since the PRs were reviewed and approved.

**Comment by mjpost** [comment]
I wonder if we just forgot to check when merging.

Let me run this once more, because I found that some of them were uploaded to the wrong place (e.g., `~/anthology-files/amta` instead of `~/anthology-files/pdf/amta`)

**Comment by mjpost** [comment]
Hi @xinru1414, it seems that the P19-2050 updates are missing, can you check if you forgot to upload them? If not can you do so?

**Comment by davidstap** [comment]
I'm curious whether the wrong place issue solves a large portion of these...

**Comment by mjpost** [comment]
No it didn't resolve any. In fact I copied them over blindly and am now worried that might have been a mistake, so I'm going to double check the checksums.

**Comment by xinru1414** [comment]
@mjpost `P19-2050` is done

**Comment by davidstap** [comment]
@mjpost All missing MT Archive PDFs are on the server. Note that all the AMTA 2016 PDFs listed here were already uploaded (and available through the website), so I have not re-ingested them. Is there another problem with these PDFs? I spotted checked a few and they match the title so all seems good.

**Comment by mjpost** [comment]
I spot-checked ten or so, looks good. Thank you!

I’m going to keep this open for the remaining handful of papers, though.

**Comment by mjpost** [comment]
@xinru1414 can you look into the remaining two papers? Can we retrieve them from the ingestion directory for example?

**Comment by xinru1414** [comment]
@mjpost for some reasons those weren't uploaded copied during ingestion, it should be good now

**Comment by mjpost** [comment]
Thank you!
