### ISSUE TITLE
Google scholar link leads to a 404 error

### ISSUE THREAD

**Issue by rama-a** [acl-org/acl-anthology#1661]
When clicking on the Google Scholar paper link for A Comparison of Different NMT Approaches to Low-Resource Dutch-Albanian Machine Translation it leads to a 404 error, while through regular google search you reach the right page: 
Error link:
_https://aclanthology.org/2021.mtsummit-LoResMT.7/_
Working link:
_https://aclanthology.org/2021.mtsummit-loresmt.7/_

**Comment by akoehn** [comment]
We have zero influence on (and no affiliation with) google scholar, you will have to raise that issue with google if it persists. Sorry.
