### ISSUE TITLE
Correction to Anthology IDs 2021.mrl-1.21 & 2021.mrl-1.22

### ISSUE THREAD

**Issue by d-ataman** [acl-org/acl-anthology#1664]
- [x] I have read the note on author changes and will contact the program chairs
       for permission to be posted here or via email.

**## **Revision or erratum****

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

The papers should be removed from the anthology.
[2021.mrl-1.21.pdf](https://github.com/acl-org/acl-anthology/files/7539825/2021.mrl-1.21.pdf)
[2021.mrl-1.22.pdf](https://github.com/acl-org/acl-anthology/files/7539826/2021.mrl-1.22.pdf)

**Comment by mjpost** [comment]
Hi, can you provide an explanation? What [kind of retraction](https://aclanthology.org/info/corrections/) is this?

**Comment by d-ataman** [comment]
Hi,

The paper should be removed entirely from the listing on the author page.
