### ISSUE TITLE
Correction to Anthology ID 2021.emnlp-main.318

### ISSUE THREAD

**Issue by Betahj** [acl-org/acl-anthology#1670]
**Please be sure to add the Anthology ID in the title**

Please review [our correction policy](https://aclanthology.org/info/corrections/).

## Revision or erratum: please add the following information**

- [√] I have attached the revised PDF or erratum to this issue
- [√] I have written a brief description of the changes below

This revision adds a mistakenly deleted subsection "6.3 Dual-encoder Structure" in the Related Work section, written in our initial version but deleted in the camera-ready version PDF by mistake.
This revision also adds an acknowledgment subsection to appreciate the help and support from the authors from EMNLP2020 "Two are Better than One: Joint Entity and Relation Extraction with Table-Sequence Encoders (https://aclanthology.org/2020.emnlp-main.133/)"
[EMNLP21_2085_ABSA_revised.pdf](https://github.com/acl-org/acl-anthology/files/7560089/EMNLP21_2085_ABSA_revised.pdf)

**Comment by xinru1414** [comment]
@Betahj The anthology ID for this paper is `2020.emnlp-main.133`

**Comment by Pzoom522** [comment]
This correction is **WEIRD**. The updated pdf is for `2021.emnlp-main.318` rather than `2020.emnlp-main.133`. Also, https://github.com/acl-org/acl-anthology/issues/1672 is possibly relevant to what happens here!

**Comment by Betahj** [comment]
@xinru1414 Hello, the paper (https://aclanthology.org/2020.emnlp-main.133/) you mentioned is the paper we cited and thanked and is not the paper we submitted for revision. We noticed that the replacement also worked on that paper by mistake. Would you please fix this problem?

**Comment by Betahj** [comment]
Thanks a lot for your reply!
Could you please reverse the paper 2020.emnlp-main.133 to the previous version?
It brought me some trouble.


Best,
Hongjiang Jing

---Original---
From: ***@***.***&gt;
Date: Fri, Nov 19, 2021 18:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [acl-org/acl-anthology] Correction to Anthology ID 2085 (Issue #1670)




 
This correction is WEIRD. The updated pdf is for 2021.emnlp-main.318 rather than 2020.emnlp-main.133. Also, #1672 is possibly relevant to what happens here!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xinru1414** [comment]
@Betahj Thanks for the clarification. If I understand correctly, both #1670 and #1672 are corrections for `2021.emnlp-main.318`? If that's the case, can you combine them?

**Comment by xinru1414** [comment]
@Pzoom522 thank you for catching the error I appreciate it!

**Comment by xinru1414** [comment]
closing because of duplication #1672

**Comment by Betahj** [comment]
@xinru1414 Thank you for your kind help!

**Comment by LorrinWWW** [comment]
@xinru1414 Can you recover the pdf of `2020.emnlp-main.133`? The current [link](https://aclanthology.org/2020.emnlp-main.133.pdf) still incorrectly leads to the pdf of `2021.emnlp-main.318`. Thanks!

**Comment by Betahj** [comment]
@xinru1414 Hello, the paper [2020.emnlp-main.133](https://aclanthology.org/2020.emnlp-main.133.pdf) links to our paper [2021.emnlp-main.318](https://aclanthology.org/2021.emnlp-main.318.pdf) incorrectly again. Could you please fix this problem?

**Comment by xinru1414** [comment]
@LorrinWWW @Betahj I believe the current link is correct. See screenshot below.
![Screen Shot 2021-11-22 at 3 10 54 PM](https://user-images.githubusercontent.com/27436920/142948725-54eab7ab-e27b-45ac-bba1-066d89df474f.png)


The incorrect changes were never merged and published.

Let me know if you have further questions.

**Comment by mjpost** [comment]
Hi, FYI it was incorrect, but I fixed it earlier today from backup.

**Comment by xinru1414** [comment]
@mjpost thanks!
