### ISSUE TITLE
custom search not returning EMNLP 2021 papers

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1675]
As reported by @annargrs, using the Google Custom Search Engine box from the Anthology site does not turn up papers from EMNLP 2021. e.g.,

[BERT Has Uncommon Sense: Similarity Ranking for Word Sense BERTology](https://aclanthology.org/search/?q=%22BERT+Has+Uncommon+Sense%3A+Similarity+Ranking+for+Word+Sense+BERTology%22) turns up no results:

![image](https://user-images.githubusercontent.com/455256/142665215-8c7b8879-8251-4ae3-8f71-d854211c054b.png)

Though [it exists](https://aclanthology.org/2021.blackboxnlp-1.43/).

**Comment by mbollmann** [comment]
The Anthology version is not in main Google either for me: https://www.google.com/search?q=BERT+Has+Uncommon+Sense%3A+Similarity+Ranking+for+Word+Sense+BERTology

It is correctly being shown in our sitemap, though:

```bash
$ curl -s https://aclanthology.org/sitemap_1.xml.gz | gunzip - | grep "2021.blackboxnlp-1.43"                                                                                                      
    <loc>https://aclanthology.org/2021.blackboxnlp-1.43/</loc>
```

I can only conclude that Google simply hasn't re-indexed us since this was added.

**Comment by mjpost** [comment]
The google search console lists it as “submitted, not in sitemap”, with a last sitemap crawl date of November 11. That’s for the sitemap index. I added all the individual sitemaps to see if that helps. I think it reread the index but not the individual pieces (before #1658, there were only 3 pieces, now there are 5).

**Comment by mjpost** [comment]
I think we need an SEO volunteer…

**Comment by mbollmann** [comment]
Well, it's in the very first piece, and it also seems to be in https://aclanthology.org/sitemap.xml, so I don't know what would be going on here.

But yeah, just one of several reasons I'd like to get rid of GCSE for our internal search engine ASAP. Being correctly (and timely) indexed in Google proper will still remain important, of course ...

**Comment by mjpost** [comment]
Note that it [is in Google](https://www.google.com/search?q=BERT+Has+Uncommon+Sense%3A+Similarity+Ranking+for+Word+Sense+BERTology+site%3Aaclanthology.org), just not really being surfaced.

![image](https://user-images.githubusercontent.com/455256/142693038-f0ae82d2-a22d-4150-b903-047937b05203.png)

But I agree with the goal.
