### ISSUE TITLE
Correction to Anthology ID 2020.emnlp-main.133 [URGENT]

### ISSUE THREAD

**Issue by LorrinWWW** [acl-org/acl-anthology#1679]
## Other metadata correction: 

The pdf file of 2020.emnlp-main.133 was incorrectly replaced with 2021.emnlp-main.318 (at #1670). The pdf file should be [this one](https://github.com/acl-org/acl-anthology/files/7581471/2020.emnlp-main.133.pdf). Can you recover that?

Thank you very much!

**Comment by mjpost** [comment]
I replaced the old file from backup.

**Comment by LorrinWWW** [comment]
> I replaced the old file from backup.

Thank you very much!
