### ISSUE TITLE
Correction to Anthology ID 2021.findings-acl.457

### ISSUE THREAD

**Issue by sjgiorgi** [acl-org/acl-anthology#1682]
## Other metadata correction: please describe the issue here**

- No abstract is listed for this (or any Findings at ACL 2021) on the Anthology page. 
- The pre-recorded video is not linked.  

Both apply to all Findings at ACL 2021 papers (but not previous Findings), so please close if this was intentional across the venue.

**Comment by akoehn** [comment]
Thx for opening an issue!

Missing Findings abstracts is tracked in #1439, the abstracts where originally not provided and have to be manually added.

We will add video links once someone provides them to us, which has not happened yet.
