### ISSUE TITLE
Correction to Anthology ID 2021.emnlp-main.644

### ISSUE THREAD

**Issue by MaximilianAhrens** [acl-org/acl-anthology#1683]
**Please be sure to add the Anthology ID in the title**

Please review [our correction policy](https://aclanthology.org/info/corrections/).

## Other metadata correction: please describe the issue here**

The un-numbered equation before equation (1) (page 2, right column, top third), contains a minor typo. It is not carried through in the paper. Therefore it has no effect on any other formulae or results. However, for the sake of correctness, we would like to rectify this typo:

It currently reads as:
    \delta = \mathbb{E}[\mathbb{E}[y| \bs{Z},\bs{C},t = 1] - \mathbb{E}[y|\bs{Z},\bs{C},t=1] | t=1 ]

However, it should read as:
    \delta = \mathbb{E}[\mathbb{E}[y| \bs{Z},\bs{C},t = 1] - \mathbb{E}[y|\bs{Z},\bs{C},t=0] | t=1 ]

The change is in the second last "t=". This needs to be "t=0", not "t=1". In all other occurrences in the paper, this is already stated correctly otherwise.

Furthermore, in the text-line immediately before this equation, it reads "the casual effect", however, this clearly needs to read as "the causal effect".  We believe that no specific description of these minor typo adjustments need to be documented in the paper.

Both minor typos have been corrected in the attached version. We deeply apologise for having to correct our paper.

## Revision or erratum: please add the following information**

- [ x] I have attached the revised PDF or erratum to this issue
- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

**Description of changes**

[2021_Bayesian_Topic_Regression_corrected.pdf](https://github.com/acl-org/acl-anthology/files/7597138/2021_Bayesian_Topic_Regression_corrected.pdf)

**Comment by mjpost** [comment]
@xinru1414 We can summarize this as "Corrects a small typo in the text and in an unnumbered equation."

**Comment by xinru1414** [comment]
@mjpost Thanks got it
