### ISSUE TITLE
Correction to Anthology ID 2021.findings-emnlp.176

### ISSUE THREAD

**Issue by EricLee8** [acl-org/acl-anthology#1691]
## Revision or erratum: please add the following information**

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

[new_submission_EMNLP21.pdf](https://github.com/acl-org/acl-anthology/files/7616158/new_submission_EMNLP21.pdf)

**Description of changes**
This revision adds a previously omitted acknowledgment.

**Comment by EricLee8** [comment]
We thank you very much for this correction.

**Comment by xinru1414** [comment]
@EricLee8 you are very welcome.
