### ISSUE TITLE
Show DOIs in single BibTex file

### ISSUE THREAD

**Issue by cfedermann** [acl-org/acl-anthology#17]
**S/N:** 18
**Priority:** Medium
**Title:** Show DOIs in single BibTex file

**Comment by villalbamartin** [comment]
If I understand it correctly, this issue wants the .bib files to show the DOI. It's that correct? If so, the issue seems to be corrected now.

**Comment by knmnyn** [comment]
I think it was the single file anthology.bib or exports should also involve outputting the DOI when available.  If this is working, we can close this!

**Comment by mjpost** [comment]
DOIs are included (https://aclweb.org/anthology/anthology.bib.gz), so I'll close this issue.

**Comment by mjpost** [comment]
DOIs are output (see https://aclweb.org/anthology/anthology.bib.gz), so I'm closing this.
