### ISSUE TITLE
DOI for 2021.sigmorphon-1.25 is broken?

### ISSUE THREAD

**Issue by jonorthwash** [acl-org/acl-anthology#1705]
#### Issue description
DOI for [2021.sigmorphon-1.25](https://aclanthology.org/2021.sigmorphon-1.25/) appears to not work.

#### Steps to reproduce the issue

1. Go to [https://aclanthology.org/2021.sigmorphon-1.25/](https://aclanthology.org/2021.sigmorphon-1.25/).
2. Click the [DOI link](10.18653/v1/2021.sigmorphon-1.25).

#### What's the expected result?

Land on the same page.

#### What's the actual result?

Land on "Error: DOI Not Found" page.

**Comment by mjpost** [comment]
@xinru1414 it seems that DOIs were never assigned for this. This shouldn't be possible, because the script ensures the DOI exists before adding. Is this the one where you added them manually? If so, can you make sure that the DOIs were created?

**Comment by xinru1414** [comment]
@mjpost Yes you are right. I double checked on the doi crossref site. Originally the sigmorphon paper DOIs were created and ingested along with acl in July. The five added papers were later on ingested in Sep, and their DOIs weren't created correctly.

**Comment by xinru1414** [comment]
This should be fixed now
