### ISSUE TITLE
Merge static-rewrite

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#171]
The preview of the static site is live: https://aclweb.org/anthology. We'll be announcing this soon and collecting feedback over the coming days.

Since we have a functioning site, I think we are ready to merge `static-rewrite` into master. Are there any objections to this?

One thing we might do beforehand (or immediately afterward) is cleanup of the current repo. There are a number of things that could be removed or changed:

- [x] What do folks think about renaming `import/` to `db/` or something? I think I'd prefer to have a noun instead of something that reads predominantly as a verb
- [x] We can remove all the Rails stuff
- [x] `export/` is not used and is mostly empty files

**Comment by mbollmann** [comment]
Yes, I would definitely want to clean out the Rails stuff (and unused things) before merging. I'd suggest creating a tag for the latest Rails website before the merge so we can always find it again easily, should the need ever arise.

**Comment by mjpost** [comment]
I have tagged it as [v2.0](https://github.com/acl-org/acl-anthology/releases). We can call the static release version 3 (and [v1 here](https://www.aclweb.org/old_anthology/)).

I just cleaned up all the rails stuff and [pushed it to a new "cleanup" branch](https://github.com/acl-org/acl-anthology/tree/cleanup), branching off `static-rewrite`. If it looks good to you, you can merge it.

**Comment by mjpost** [comment]
Any objections to merging now?

**Comment by mbollmann** [comment]
Not really, except for tidying up `import/` a bit. I'm indifferent to the naming (though I would prefer `data/` over `db/`), but I also wondered if we should put XML and YAML files in different subfolders, for example.

Oh, and if we do merge this to master, should we get rid of the "draft" popup already that I put on the site?

**Comment by mjpost** [comment]
`data/` is find to me, and if you want to do a little more sub-organization, that also sounds fine.

I like the feedback box, though we could remove the word "draft" and just call it the latest version. We could keep it up for the next few weeks, maybe through the end of the month.

**Comment by mjpost** [comment]
Just so we have clear ownership of this, I'm assigning it to you, @mbollmann. Please create a PR against master when you're ready.
