### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DetmarM** [acl-org/acl-anthology#1711]
The aclweb.org/anthology links have stopped working! 

URLs such as 
https://www.aclweb.org/anthology/W19-4440/
https://www.aclweb.org/anthology/2020.coling-main.509 
http://www.aclweb.org/anthology/N18-1011.pdf
now result in a page not found error.

URLs without the www, e.g.
https://aclweb.org/anthology/W19-4440/
https://aclweb.org/anthology/2020.coling-main.509 
http://aclweb.org/anthology/N18-1011.pdf
that also used to work fine and are common short forms used in many bibliographies also stopped
working but instead of a file not found an Error 22 is returned.

Note that this problem also applies for doi entries resolving to the acl anthology. For example 
http://dx.doi.org/10.18653/v1/2020.coling-main.509
for a paper at COLING 2020 that resolves to 
https://www.aclweb.org/anthology/2020.coling-main.509
is now resulting in page not found.

If one replaces http://www.aclwerb.org/anthology/ with https://aclanthology.org/ that works - but it would be important for the aclweb.org/anthology links, which were/are commonly used in many publications and on web pages, to also remain functional!

**Comment by nschneid** [comment]
Status update: https://twitter.com/aclanthology/status/1468299749077966850
