### ISSUE TITLE
Correction to Anthology ID 2021.emnlp-main.214

### ISSUE THREAD

**Issue by jianliu-ml** [acl-org/acl-anthology#1716]
## Revision or erratum: please add the following information**

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

**Description of changes**

This revision corrects the sponsor number in the Acknowledgments section, where the number No.6210021758 (which is in fact an 
application number) has been revised to the correct approval number No.62106016.

[docEE.pdf](https://github.com/acl-org/acl-anthology/files/7684502/docEE.pdf)

**Comment by jianliu-ml** [comment]
@xinru1414 Hello, and many thanks for the correction! The updated version, however, appears to be missing the proceeding information, such as "Proceedings of the 2021 Conference on Empirical Methods in Natural Language Processing," as well as the page number at the foot of each page. Is it possible that they will be included in the future? Thanks!

**Comment by mjpost** [comment]
Hi @jianliu-ml—the updated version is not part of the officially-issued proceedings, so we do not stamp it with the proceedings footer.

**Comment by jianliu-ml** [comment]
> Hi @jianliu-ml—the updated version is not part of the officially-issued proceedings, so we do not stamp it with the proceedings footer.

Okay, I get it. And best wishes to you!
