### ISSUE TITLE
Can't acces Machine Translation in the Covid domain: an English-Irish case study for LoResMT 2021 from Google Scholar

### ISSUE THREAD

**Issue by seamusl** [acl-org/acl-anthology#1719]

**Comment by mbollmann** [comment]
The paper is here & the PDF link also works for me:
https://aclanthology.org/2021.mtsummit-loresmt.15/

We have no control over what Google Scholar shows, unfortunately.

**Comment by seamusl** [comment]
Thanks for coming back to me quickly.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
