### ISSUE TITLE
Ingest the MT Archive

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#172]
The [MT Archive](http://www.mt-archive.info) has a lot of old MT-related proceedings that are not in the Anthology, and it seems that it is not actively maintained any more. It would be great to ingest all of this information. [The license is CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/deed.en_US) seems to provide permission for this, though it would be good to contact someone and get formal assent.

**Comment by mjpost** [comment]
The data for the MT archive has all been digitized here: https://github.com/mardub1635/mt-archive/

Over the next few weeks, @mardub1635 and I will be ingesting them. I think that we'll do them one conference at a time, in order to make reviewing easier.

**Comment by ozancaglayan** [comment]
What's the procedure here and would you need help?

**Comment by mjpost** [comment]
Hi @ozancaglayan—I've written [a checklist](https://github.com/acl-org/acl-anthology/wiki/MT-Archive-Ingestion-Checklist) which you can go through.

**Comment by ozancaglayan** [comment]
Hi thanks. I don't understand the first and second arguments to ingest script in the checklist:
```
acl-anthology/bin/ingest_tsv.py mt-archive/data/amta/1994.amta.tsv mt-archive/data/amta/1996.amta.tsv mt-archive/conference-list.tsv
```

Is the second meant to be the `meta_file`?

**Comment by mjpost** [comment]
That was a typo. It should be:

```bash
acl-anthology/bin/ingest_tsv.py mt-archive/data/amta/1994.amta.tsv mt-archive/conference-list.tsv
```

i.e., two arguments, the conference TSV and the meta file TSV.

**Comment by mjpost** [comment]
This issue has been converted to [a project](https://github.com/acl-org/acl-anthology/projects/12).
