### ISSUE TITLE
aclweb.org is down

### ISSUE THREAD

**Issue by danielgildea** [acl-org/acl-anthology#1726]
The acl anthology search box isn't working, because the results from google
point to aclweb.org, which is not working.

Some DOIs resolve to aclweb.org:
https://doi.org/10.18653/v1/2020.acl-main.119
These should point directly to aclanthology.org.

Does anyone know what is happening with aclweb.org?

**Comment by danielgildea** [comment]
same as #1711

**Comment by HelloRusk** [comment]
Here is a temporary solution for Google Chrome users:

1. install "Redirector" extension https://chrome.google.com/webstore/detail/redirector/pajiegeliagebegjdhebejdlknciafen/
2. set up redirect rules like below

<img width="881" alt="スクリーンショット 2021-12-16 12 21 26" src="https://user-images.githubusercontent.com/36184621/146302437-07b4fd5f-a579-4c92-8100-a1f4d68cd58e.png">

**Comment by nschneid** [comment]
On Twitter there seems to be a fair amount of frustration about this. Is there any way to push a hotfix for the search result URLs?

**Comment by nschneid** [comment]
@desilinguist any insights regarding aclweb.org?

**Comment by mbollmann** [comment]
> On Twitter there seems to be a fair amount of frustration about this. Is there any way to push a hotfix for the search result URLs?

So, checking our custom search configuration, I found that we never changed the URLs we point to there...

![grafik](https://user-images.githubusercontent.com/11348502/146472545-3ec06f01-075c-4111-a93e-30b455cfeca3.png)

I changed all of these now, and at least the search embedded in our site seems to be mostly fixed.

**Comment by danielgildea** [comment]
aclweb.org is working again now.  We should still make DOIs point to aclanthology.org.  This is tracked by #1278.
