### ISSUE TITLE
https certificate expired

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#1749]
The aclancology.org certificate is expired (at least it is not valid atm)

**Comment by mjpost** [comment]
Thanks, just pinged Nitin.

**Comment by mjpost** [comment]
I'm not sure what's happening. Chrome reports a valid cert:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/455256/147875447-aa9af1ee-1536-4c72-baa7-16a65ccf04fc.png">

But I saw the cert failure warning in Safari, and I get this error when trying to add DOIs from the command line:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='aclanthology.org', port=443): Max retries exceeded with url: /2021.sustainlp-1.1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))
```

**Comment by mjpost** [comment]
@akoehn can you check that this is resolved for you? From @desilinguist, it seems that letsencrypt deprecated a root CA, and we needed to reboot.
