### ISSUE TITLE
Many older conferences lacking fields

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#175]
`<address>, <bibkey>, <bibtype>, <booktitle>, <month>, <pages>, <publisher>, <url>, <year>`

This information is all in the BibTeX but didn't make it into the XML. It should be straightforward to re-import it programmatically -- I just want to check to make sure that all those fields are really wanted.

**Comment by davidweichiang** [comment]
An entire workshop (W15-57, Workshop on Deep Machine Translation) seems to be missing.

**Comment by davidweichiang** [comment]
Oops, duplicate of #173.

**Comment by danielgildea** [comment]
Also, many CL journal articles have the wrong author order:
http://www.aclweb.org/anthology/J01-2003
(seems to be an issue of reading down vs. across the author list on the title page)
