### ISSUE TITLE
BibTeX now has "location" instead of "address"

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#177]
Maybe due to https://github.com/acl-org/acl-anthology/commit/726e6ac0983a759d41a27eb325f22ce90dee9359#diff-b1807deb96836fdba824f319f0e2210eR115

The "location" field isn't recognized by the Zotero ACL Anthology importer.

**Comment by mbollmann** [comment]
Plain BibTeX really should use the `address` field IMO, compatibility issues being one of them.

FWIW, I've changed it back to `address` with the refactoring of the BibTeX generation in 7cd20c3, but maybe @mjpost or @danielgildea want to weigh in if this is indeed what we want?

**Comment by danielgildea** [comment]
1. I used "location" following what is on the anthology currently.
2. Technically, "address" is supposed to be the location of the publisher, not the location of the conference.
3. However, "location" is a non-standard field that is not used by any .bst file that I have ever seen.  If we use "location", the locations will not be included in the citations produced by our own ACL style files.  Maybe that is fine.
4. The CL journal copy editors are fanatical about including the location of the conference for all conference papers cited.  This is one argument for including the conference location as the "address" in our bibtex - it will provide the conference location as required when using the current CL style files.

**Comment by nschneid** [comment]
I am a fan of papers that include conference locations in the bibliography because it helps me figure out whether I attended the conference and saw the work there. :)

**Comment by mjpost** [comment]
Thanks for this really helpful info, Dan. I pushed up these changes before seeing this discussion but it sounds like we should be using `address`. Note that the pre-ingested bibtex had `address`, too:

- P18-1002: [pre-ingest bib](http://www.aclweb.org/anthology/P/P18/P18-1002.bib) | [post-ingest bib](http://www.aclweb.org/anthology/papers/P/P18/P18-1002.bib)
