### ISSUE TITLE
Correction to Anthology ID 2021.acl-long.550

### ISSUE THREAD

**Issue by seantrott** [acl-org/acl-anthology#1777]
The Data link previously linked to the Word in Context dataset, and was updated to refer instead to the correct RAW-C dataset at the following link: https://github.com/seantrott/raw-c

**Comment by xinru1414** [comment]
@seantrott Just making sure that the correct dataset link is  `https://github.com/seantrott/raw-c`?

**Comment by seantrott** [comment]
Yes, exactly––thanks!

**Comment by xinru1414** [comment]
@mjpost Should I change the wrong paperwithcode link `https://paperswithcode.com/dataset/wic` to the aforementioned correct link as an attachment, OptionalSupplementaryMaterial?

**Comment by mbollmann** [comment]
@xinru1414 @seantrott We don't support external links for code or attachments. The data link (to Word in Context) is provided by [Papers with Code](https://paperswithcode.com/), and needs to be updated on their side. Changes on Papers with Code will automatically be updated on the Anthology once a week.

**Comment by xinru1414** [comment]
@mbollmann thanks for the clarification!

**Comment by seantrott** [comment]
Hello,

Thanks for the clarification! Sorry, just another question: I'm trying to
edit the dataset <https://paperswithcode.com/dataset/raw-c> on
PapersWithCode, and I'm not sure where to find the place to update the
link? I see WiC is listed under "Similar Datasets", but not the dataset
itself. I did try adding the GitHub link as a "Homepage" URL––is that what
I'm meant to do?

Thank you for your help!
Sean

**Comment by mbollmann** [comment]
@seantrott I think you need to edit the page for your **paper**: https://paperswithcode.com/paper/raw-c-relatedness-of-ambiguous-words-in-1

**Comment by seantrott** [comment]
Ah, got it, apologies! Thank you, I've updated the paper page to point to
RAW-C instead of WiC. Thanks again.
