### ISSUE TITLE
Correction to Anthology ID N19-1063

### ISSUE THREAD

**Issue by ccmaymay** [acl-org/acl-anthology#1781]
## Other metadata correction: missing data set

ACL Anthology ID N19-1063 was submitted with a data set zip file, but I can't find that data set on the ACL Anthology or paperswithcode.  I've attached a screenshot of the final submission page on softconf:

---

<img width="626" alt="Screen Shot 2022-01-18 at 3 18 08 PM" src="https://user-images.githubusercontent.com/457238/150012500-f6242468-83e1-40fe-a2c4-cada25f656e4.png">

---

as well as the data set zip file downloaded from that page: [2098_Dataset.zip](https://github.com/acl-org/acl-anthology/files/7892143/2098_Dataset.zip).  Please let me know what (if anything) I need to do to fix this.  Thank you!

**Comment by mjpost** [comment]
Hmm, it isn't in the ingestion data we received:

![image](https://user-images.githubusercontent.com/455256/150022720-d9454c70-8597-46b3-9d53-49b85c63b77f.png)

However, we can add this with this month's revisions. Thank you!

**Comment by ccmaymay** [comment]
Thank you!!
