### ISSUE TITLE
Correction to Anthology ID 2020.acl-srw.27

### ISSUE THREAD

**Issue by YumaTsuta** [acl-org/acl-anthology#1784]
## Metadata correction: please describe the issue here**
The first author's name is reversed in some citation texts  such as BibTex and Endnote on [the page](https://www.aclweb.org/anthology/2020.acl-srw.27/).
On this page,  the first author is "Tsuta Yuma", but the correct order is "Yuma Tsuta", as shown in the PDF.

[I've issued this before](https://github.com/acl-org/acl-anthology/issues/1336#issue-900443807), but the citation was left unchanged.

**Comment by xinru1414** [comment]
I see that the acl landing page for this paper: https://aclanthology.org/2020.acl-srw.27/ has the correct information (corected in #1336). I'm not sure if we can change citation texts ? @mjpost

**Comment by mbollmann** [comment]
The citations and the landing page are built from exactly the same data source. If one changes, the others change. For me all the citation formats on the website look identical, giving "Yuma" as the first name and "Tsuta" as the family/last name. Is that how it should be, @YumaTsuta ?

**Comment by YumaTsuta** [comment]
Sorry, I checked again and it was in the correct order.
I think I probably misunderstood.
I'm very sorry.

**Comment by xinru1414** [comment]
@mbollmann thx!
