### ISSUE TITLE
Add .pdf to links?

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#179]
According to the search console, some of the Google crawl has completed, but the results are not any better in Scholar (#126, or see the "specific issues" on [this wiki page](https://github.com/acl-org/acl-anthology/wiki/Google-Scholar-Indexing), which are not improved).

I found [this page](https://scholar.google.com/intl/en/scholar/inclusion.html), which specifies that for individual authors, the PDF links should end in PDF. I wonder if that contributes to our problem, since our "canonical links" are of the form [http://www.aclweb.org/anthology/D18-1029](http://www.aclweb.org/anthology/D18-1029). Perhaps we should add ".pdf" to these? I could update the Apache rewrite rules tonight to support this.

**Comment by knmnyn** [comment]
Hi all:

I think we have had good contacts with Google Scholar that we can ask this
question. I strongly would opt against having a format specific extension
attached to a canonical URL as this potentially violates the point of
having a canonical redirect. @mjpost I will forward you the contact at
Scholar who has been working with us prior to your term.

- M
-- 

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by mjpost** [comment]
Thanks, Min. I just responded to you there.
