### ISSUE TITLE
Correction to Anthology ID 2021.findings-emnlp.321

### ISSUE THREAD

**Issue by Daphiy** [acl-org/acl-anthology#1796]
> This revision corrects a typo in Equation 3

This is the original paper: https://aclanthology.org/2021.findings-emnlp.321/

uploaded corrected pdf here: 
[emnlp2021_kge_autodetec_correction.pdf](https://github.com/acl-org/acl-anthology/files/7986533/emnlp2021_kge_autodetec_correction.pdf)
.

**Comment by xinru1414** [comment]
@Daphiy Is this a typo correction in Equation 3? If not could you briefly describe the update?

**Comment by Daphiy** [comment]
Hi, yes we mixed up y and yhat in the equation. The equation was written
as:

[image: image.png]

and it was now corrected to be:

[image: image.png]

Our code and results are in line with the corrected equation - the mix up
was only in the paper.

Will the new pdf I uploaded replace the current one, or how does
the correction work exactly?

Thanks,
Daphna

**Comment by xinru1414** [comment]
@Daphiy Yes the new pdf will replace the old one!
