### ISSUE TITLE
P03 companion volume paper ids out of sync

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#180]
The [P03 companion volume (P03-2)](http://aclweb.org/anthology/P/P03/#2000) had both the SRW and posters/demos. There's no front matter (2000) as far as I can tell; the SRW front matter is 2001 and the posters/demos front matter is 2014. But in the .bib files, the front matter did not have their own ids, with the result that the URLs are out of sync by 1 for the student papers and by 2 for the posters/demos. It would be easy enough to correct the URL fields in the .bib (and therefore the .xml). But this volume would be unusual for not having a paper 2000. In other years, these two are listed as separate volumes (and I can't remember in what years they were physically bound together as one book).

**Comment by mbollmann** [comment]
This doesn't seem to be an issue [on the new website](http://aclweb.org/anthology/events/acl-2003/#p03-2)?

(Though the link you posted reveals another issue, which is that traces of the legacy Anthology are still accessible on the server...)

**Comment by davidweichiang** [comment]
But if you click on P03-2000, it's a 404. The BibTeX is fine since Dan's code is rewriting the URLs (right?).

**Comment by mbollmann** [comment]
That would make the actual issue that P03-2000 is more of a "symbolic" entry that doesn't have an associated PDF, and therefore shouldn't show a PDF link. But I don't see anything being out-of-sync on the new website.
