### ISSUE TITLE
Front matter for journals

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#181]
The website (both old and new) has a rule that says journals (J and Q series) don't have front matter, and therefore don't generate paper entries for x000 IDs (e.g., there's no J14-1000, J14-2000 etc. in http://aclweb.org/anthology/events/cl-2014/).

However, I discovered by accident that some journal issues actually *do* have front matter stored as PDFs on the server, e.g.:
http://www.aclweb.org/anthology/J98-1000

These are currently inaccessible from the website.

**Comment by mjpost** [comment]
It looks like this includes some but not all of the CL print issues. I think CL stopped printing around 2008, but these front matter scans seem only to go to 2001.

Can we add an annotation in the XML that indicates when front matter exists and thus generate links for them?

**Comment by mbollmann** [comment]
I think this heavily relates to #156. If all papers reliably had `<url>` tags (or similar) specifying a URL or internal filename for the PDF, the journals without front matter could simply not have those.

**Comment by mbollmann** [comment]
Can we maybe get a full PDF file list from the server (okay, *000 IDs would be sufficient for this case)? Then we could maybe add this information to the XML programmatically.

**Comment by mjpost** [comment]
Sent it to you.
