### ISSUE TITLE
1977 workshop not listed on main page

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#182]
On the main page:

    http://www.aclweb.org/anthology/

There is no entry for "77" in the "WS" row, even though this workshop and page exists:

    http://www.aclweb.org/anthology/events/ws-1977/

**Comment by mbollmann** [comment]
Year ranges [are hardcoded in the front page template](https://github.com/acl-org/acl-anthology/blob/static-rewrite/hugo/layouts/index.html#L46), and the current range was taken from the Rails template, which also lacks this entry.

**Comment by mjpost** [comment]
Awesome, thanks.
