### ISSUE TITLE
Correction to Anthology ID 2021.paclic-1.26

### ISSUE THREAD

**Issue by icadelacruz** [acl-org/acl-anthology#1820]
## Other metadata correction: please describe the issue here**
The title of our paper included author names in the metadata. The correct title should be **Science Mapping of Publications in Natural Language Processing in the Philippines: 2006 to 2020**

**Comment by mjpost** [comment]
Thanks. This will be processed with February's corrections. If you want to expedite it, you can create a pull request with the fix. The file you want to edit is data/xml/2021.paclic.xml.
