### ISSUE TITLE
No DOIs for COLING 2020 workshops

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#1841]
E.g. https://aclanthology.org/2020.udw-1.1/

**Comment by akoehn** [comment]
I was under the impression that we only generate DOIs for ACL proceedings, ICCL would need to take care of COLING ones.  Or am I wrong?  Are there DOIs generated and we just have not ingested them?

**Comment by mjpost** [comment]
@akoehn is correct. If COLING wants to submit DOIs, we can ingest them.
