### ISSUE TITLE
Correction to Anthology ID 2020.conll-1.14

### ISSUE THREAD

**Issue by mdingemanse** [acl-org/acl-anthology#1857]
**Please be sure to add the Anthology ID in the title**

Please review [our correction policy](https://aclanthology.org/info/corrections/).

## Other metadata correction: please describe the issue here**

Generated DOI link on front page of PDF is incorrect. The actual DOI is https://doi.org/10.18653/v1/2020.conll-1.14 (which leads to the paper in the anthology); but the front page of the PDF has it incorrectly as "https://doi.org/10.18653/v1/P17" (which is a nonexistent DOI)

**Comment by xinru1414** [comment]
@mdingemanse could you point me to the problematic link? I see the correct DOI link here: 
<img width="1271" alt="Screen Shot 2022-03-28 at 9 11 19 AM" src="https://user-images.githubusercontent.com/27436920/160441517-9e9bb35d-a365-455e-8507-959eae128e33.png">

**Comment by mdingemanse** [comment]
Weirdly, the metadata is all good, but it's the link on the first page of the PDF itself that is wrong: https://aclanthology.org/2020.conll-1.14.pdf 
![image](https://user-images.githubusercontent.com/9883915/160691068-0aed8803-7f79-4338-b65d-2123c34fdc23.png)

**Comment by xinru1414** [comment]
@mjpost I'm not sure if we can fix the DOI link on the paper pdf ? Any pointers?

**Comment by mjpost** [comment]
When the proceedings chairs watermarked the PDFs, they added an incorrect footer. There's nothing we can do about it.

**Comment by mdingemanse** [comment]
Sorry to have missed this latter exchange and the closing of the issue. I can easily supply a PDF in which this is corrected (see attached) — would that help? My concern is that the incorrect link otherwise will keep tripping up readers. 

If this is not the place to request this change, where else do we go? I would hope errors introduced by chairs would also be correctable.

[van Arkel et al_2020_A simple repair mechanism can alleviate computational demands of pragmatic.pdf](https://github.com/acl-org/acl-anthology/files/8417682/van.Arkel.et.al_2020_A.simple.repair.mechanism.can.alleviate.computational.demands.of.pragmatic.pdf)
