### ISSUE TITLE
No `build/anthology` folder after running `make`

### ISSUE THREAD

**Issue by BKHMSI** [acl-org/acl-anthology#1890]
Hi, I am trying to build the website locally. I followed the steps provided in the ReadMe, and at the end I get this output after running `hugo --minify`

```
                   |   EN    
-------------------+---------
  Pages            | 138163  
  Paginator pages  |      0  
  Non-page files   |      1  
  Static files     |  77059  
  Processed images |      0  
  Aliases          |      0  
  Sitemaps         |      1  
  Cleaned          |      0 
```

which I assume means that the build was successful. However, I can't find the `anthology` folder in the `build` directory to actually render the pages on my browser.

Any pointers would be really appreciated!

**Comment by akoehn** [comment]
The files should be in `build/website/anthology/`

You can run `make serve` to start a web server with the correct paths.

This send like there is still outdated documentation somewhere, can you point me to it? (Otherwise I can have a look once I'm out of bed 😬)

**Comment by BKHMSI** [comment]
It's in the ReadMe after the "Generating" heading

> The fully generated website will be in `build/anthology` afterwards.

I was able to successfully serve it with `make serve` 

Thanks for the help!
