### ISSUE TITLE
Ingestion request (2022-05-31)

### ISSUE THREAD

**Issue by ud-portugues** [acl-org/acl-anthology#1894]
Dear editors of ACL Anthology, as I requested before (to Matt Post), I would like to upload the papers of the conference UDFEST-BR 2022. Here goes the required information:
- venue identifier: udfestbr (already arranged with Matt)
- volume title: Proceedings of the Universal Dependencies Brazilian Festival
- website: https://sites.google.com/icmc.usp.br/udfest-br/
- publication date: if possible, until the end of this month (May)

Best regards,
Thiago A. S. Pardo
taspardo@icmc.usp.br

**Comment by mjpost** [comment]
Hi @ud-portugues, sounds good. Can you provide the proceedings tarball?

**Comment by ud-portugues** [comment]
Hi, Matt. I had sent it in another e-mail. Here goes the link to it:

https://www.dropbox.com/s/kpee0ehkh7juldk/udfestbr_data.tgz?dl=0

Best regards,
Thiago A. S. Pardo

**Comment by mjpost** [comment]
This was closed in #1966.
