### ISSUE TITLE
Ingestion request: INLG 2022 (2022-07-01)

### ISSUE THREAD

**Issue by MirunaClinciu** [acl-org/acl-anthology#1897]
Ingestion request for INLG 2022, Potential volumes of interest: [2022.inlg], [2022.inlg-long], [2022.inlg-short], [2022.inlg-tutorials], [2022.inlg-demos], [2022.inlg-genchal], [2022.nlg4health].

inlg:
  acronym: INLG
  is_acl: true
  name: International Natural Language Generation Conference
URL: https://inlgmeeting.github.io/

nlg4health:
   acronym: NLG4Health
   name: Workshop on Natural Language Generation in Healthcare
URL: https://nlg4health.uvt.nl/
    is_acl: true

genchal:
	acronym: GenChal
name: Generation Challenges #Proceedings of the 15th Conference on Natural Language Generation: Generation Challenges

**Comment by mjpost** [comment]
What is your hoped-for ingestion date?

**Comment by mjpost** [comment]
HI @MirunaClinciu, in order to publish this on July 1, we will need the proceedings soon.

**Comment by MirunaClinciu** [comment]
Due to corrections we had a big delay on uploading INLG proceedings.
Link to proceedings, as I cannot upload it here:
https://github.com/MirunaClinciu/proceedings

**Comment by mjpost** [comment]
Great, thank you, @xinru1414 will take a look soon!

**Comment by MirunaClinciu** [comment]
Hi there, are any updates regarding INLG proceedings?

**Comment by xinru1414** [comment]
@MirunaClinciu sorry about the late response. I looked at the git repo containing the proceedings. I can't ingest the proceedings because the format isn't correct. I noticed that you are following aclpub2. Please follow instructions [here](https://github.com/rycolab/aclpub2) to generate the `expected output` and share the data.tgz here. I'll proceed to ingest once I receive the correct ingestion material. Thanks!

**Comment by ThiagoCF05** [comment]
Hello everyone,

Sorry the delay. Here there are the proceedings:

Main Conference: https://drive.google.com/file/d/1rZjRqM5hXFiqikxO7v2Oc7K1CGtD-VNn/view?usp=sharing
Demo: https://drive.google.com/file/d/1hfVZjDgam6PcI4Yi7iehao4dDSSJEkTE/view?usp=sharing
Workshop: https://drive.google.com/file/d/1JKD1WSLXAYs5fZkb55Ku9NEQsb125CKX/view?usp=sharing

Please let me know whether there is something else we should do.
Thanks for all your help,
Take care.

**Comment by ThiagoCF05** [comment]
Dear @xinru1414 and @mjpost ,

Please let us know whether the files are correct.

Best wishes,

**Comment by xinru1414** [comment]
@ThiagoCF05 Unfortunately the ingestion materials are still incomplete. I'm linking [this page](https://github.com/rycolab/aclpub2) again. Please pay extra attention to the `Proceedings input format and structure` and the `Expected output` sections. I'm not seeing the `inputs` folder, which should include all the `yaml` files, in the ingestion material you submitted. It's also missing the `attachments` folder, so please double check if any papers have attachments.

**Comment by ThiagoCF05** [comment]
@xinru1414 I am sorry about that. Here it is the input files missing:

Main: https://drive.google.com/drive/folders/1FdxCTTIBiso2Nb28GO7t3ZsJEky-l1OZ?usp=sharing
Demo: https://drive.google.com/drive/folders/1u71d9vCwQ169f7DWrXzBIPXQ_wV13PB3?usp=sharing
Workshop: https://drive.google.com/drive/folders/1mjQ7sZgi2qVbqrZBLkkkVKFV0sTyRXns?usp=sharing

Please let me know whether I should merge the folders for each venue.

Thanks in advance,

**Comment by xinru1414** [comment]
Hi @ThiagoCF05 The above links still don't contain complete information.  It should contain an `output` folder, and the `output` folder should contain an`inputs` folder (which contains the yaml files we need for ingestion), an `attachments` folder (which contains attachments for the papers), a `proceedings.pdf` file (this is the entire proceedings pdf that we need for ingestion) and `watermarked_pdf` folder (this contains water marked paper pdfs that we need for ingestion)

Below is an example: 
<img width="601" alt="Screenshot 2022-11-05 at 10 10 34 PM" src="https://user-images.githubusercontent.com/27436920/200155267-5036b103-233d-4fbf-b80d-d8c9cd88de13.png">

**Comment by ThiagoCF05** [comment]
Dear @xinru1414 , thanks for your guiding. I organized the files in the correct format now. They are available in the following links:

Main Conference: https://drive.google.com/file/d/1BEoFktySqmPom7phXgc-3exxu_2Nc6-q/view?usp=sharing
Demo: https://drive.google.com/file/d/114cHaJ8_zWph7_oorvVnz_o_pWcr8zp0/view?usp=sharing
Workshop: https://drive.google.com/file/d/1mD6sqSsDZ7Xg6JygDe6ygoi8eifjVkQa/view?usp=sharing

Please let me know whether it works now.
Best,

**Comment by xinru1414** [comment]
@ThiagoCF05 The ingestion material is still incomplete. I'm referring to [this page](https://github.com/rycolab/aclpub2) again -- the `watermarked_pdf` dir must contain a special file named `0.pdf`. However it's missing in the current submission. 

Please double check the instructions on the `aclpub2` page.

**Comment by ThiagoCF05** [comment]
Dear @xinru1414 , thanks. Just added the `0.pdf` in the proceedings. here it is the following .zip files:

1. Main Conference: https://drive.google.com/file/d/16VRZmuZpGAvsJMo0O2q2Zp6_N5vpJwli/view?usp=sharing
2. Demo: https://drive.google.com/file/d/1JjoEFe3Ke5Rpo60d3mYhUMzQgo1CpbsO/view?usp=sharing
3. Workshop: https://drive.google.com/file/d/17IK4vmoyLBWQuBS2FHeH-u81-d0yjy13/view?usp=sharing

Thanks for your help.
Best wishes,

**Comment by xinru1414** [comment]
@ThiagoCF05 We are getting really close here, hopefully this is the last fix. In all three `papers.yaml` files, there are some `first_name` and `last_name` fields are filled with author's email addresses instead of their first name and last name.

**Comment by ThiagoCF05** [comment]
Dear @xinru1414 ,

I would really like to thank you for all your help.

I manually fixed these first name cases. The problem is that some authors did not register on Open Review. So the python script was copying their email as first and last names. Here there are the correct files:

Main Conference: https://drive.google.com/file/d/1iJ6wQE7O7kIRjK9p2IReQrqB-v8GbMl5/view?usp=sharing
Demo: https://drive.google.com/file/d/1ixaHbG98otpWvyRPGAv2hbzRDmmzoDkp/view?usp=sharing
Workshop: https://drive.google.com/file/d/1bIXQQ7mB3KokFZV6wCMoVl41Z_wsvF61/view?usp=sharing

Best wishes,
Thiago.

**Comment by mjpost** [comment]
@xinru1414 is this ready for review and merging?

**Comment by ThiagoCF05** [comment]
https://github.com/acl-org/acl-anthology/issues/2324
