### ISSUE TITLE
License for the site generator

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#190]
As far as I can tell, the code to generate (or for the old one: to serve) the anthology website is not licensed under a specific software license.  The readme only refers to "materials", which are licensed under CC-licenses.

As the static rewrite is currently quite new and every contributor can still be grasped, this would be a good time to have a proper license for the code. It could be GPL or Apache, everything is better than no license.  One could argue that the code is also CC-licensed but that is really not a good fit.

**Comment by mjpost** [comment]
Thanks for bringing this up—this is a good idea. I propose we use the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0). The following people have contributed code to `static-rewrite`: @mbollmann @davidweichiang @danielgildea. What do you think of this?

**Comment by akoehn** [comment]
If you decide on Apache 2.0 (which I think is a fitting license), these steps should be done:

 - the license header needs to be added to the scripts (it is at the bottom of the page Matt linked)
 - the apache license should be added as a LICENSE file

If you all agree to this, I can create a pull request with these changes if wanted.

**Comment by mbollmann** [comment]
+1 for Apache License

**Comment by mjpost** [comment]
Assuming everyone agrees, yes, it would be great if you could do a PR (though I suggest waiting for responses before doing that work).

**Comment by danielgildea** [comment]
I hereby license my contributions under Apache 2.0 (and any other open source license).

**Comment by mjpost** [comment]
@davidweichiang Any issues with this suggestion?

**Comment by davidweichiang** [comment]
No, I also hereby say what Dan said.

**Comment by mjpost** [comment]
Great. @akoehn, I think we're all set if you want to make a PR.

**Comment by akoehn** [comment]
Ok, I will create a PR soon.

**Comment by akoehn** [comment]
@knmnyn there are several perl scripts you wrote.  Could you agree to also put them under Apache 2.0?  If you do, I will push my pull request.

**Comment by knmnyn** [comment]
Hi Arne:

Yes, I agree to that.  Please go ahead and file them under Apache 2.0.  - M
