### ISSUE TITLE
Ingestion request: KONVENS 2022 (2022-09-05)

### ISSUE THREAD

**Issue by RobinSchaefer** [acl-org/acl-anthology#1902]
Hello,

We would like to register this year's KONVENS (https://konvens2022.uni-potsdam.de/). 

The venue identifier: konvens
The volume title: Proceedings of the 18th Conference on Natural Language Processing (KONVENS 2022)

Our submission deadline is June 3rd. 

Once our meeting is registered, is there anything else that needs to be done on our side before the final submission of proceedings?

Best regards,
Robin Schaefer

**Comment by mjpost** [comment]
What is your publication date? Also are there any workshops?

**Comment by RobinSchaefer** [comment]
We would like to publish the proceedings on September, 5th 2022. There are no workshops.

**Comment by mjpost** [comment]
Sounds good, thanks for the info!

**Comment by RobinSchaefer** [comment]
Hello,

I have a couple of questions regarding the preparation of our proceedings.

1. Do we need an ISBN number?
2. Do we need to add page numbers, footers and license information to the papers?
3. Is it correct that we don't need to hand in the latex source files? Only the pdf plus the requested meta information? 

Thank you!

Regards,
Robin

**Comment by mjpost** [comment]
You only need an ISBN number if you plan to publish the proceedings.

You don't have to add page numbers, etc, but it is common to do so, as part of a finished product. However, we don't require it.

Yes, we just need the PDFs and the metadata.

**Comment by RobinSchaefer** [comment]
Okay, thank you.

Just to be clear, with respect to the ISBN "publishing" means outside of the ACL Anthology? We only want the proceedings to appear in the Anthology.

**Comment by akoehn** [comment]
Correct, isbn is for selling it as a book etc.

If the papers are eg licensed under cc-by, it would be helpful to have this info in a footer or in a footnote of each paper. If you have a say in this, please lobby for the papers to put under cc-by, which is the same license that all our conferences use. Not required but advisable for open science reasons.

**Comment by RobinSchaefer** [comment]
Okay, thanks for clarifying.

**Comment by RobinSchaefer** [comment]
Hello,

I submitted our proceedings this week but so far did not receive a confirmation. Did you receive my email? I just want to be sure that everything is alright. Thank you!

Regards,
Robin

**Comment by mjpost** [comment]
We have received it and it is under ingestion!

Can you please confirm that none of the papers is non-archival?
