### ISSUE TITLE
Correction to Anthology ID 2021.nllp-1.20

### ISSUE THREAD

**Issue by dcx** [acl-org/acl-anthology#1907]
## Option 1: Metadata correction

Hello, there seems to be a small typo in the HTML abstract of this paper, which does not exist in the PDF. In the second sentence, "On this co pus" was originally "On this corpus". Thanks for providing this streamlined process!

**Comment by mjpost** [comment]
Hi, thanks for reporting. If you want to submit a PR (edit `data/xml/2021.nllp.xml`), it will expedite the fix.

**Comment by dcx** [comment]
PR submitted!
