### ISSUE TITLE
Correction to Anthology ID 2022.lchange-1.16 -- 2022.lchange-1.22

### ISSUE THREAD

**Issue by smontariol** [acl-org/acl-anthology#1912]
# Metadata correction

Several papers have a wrong prefix for their title, due to an error in the papers.yml file of the workshop proceedings.
The prefix that should be removed is "black[LSCDiscovery shared task] ".
Papers ids: 2022.lchange-1.16 to 2022.lchange-1.22 (7 papers)
Thanks a lot in advance.

**Comment by mjpost** [comment]
Thanks. Will merge tonight.
