### ISSUE TITLE
Correction paper PDFs in Anthology ID 2022.acl-srw

### ISSUE THREAD

**Issue by andreamad8** [acl-org/acl-anthology#1922]
# Revision or erratum

*Please add the following information*

- [x] I have attached the revised PDF or erratum to this issue

- https://aclanthology.org/2022.acl-srw.15.pdf ==> [168.pdf](https://github.com/acl-org/acl-anthology/files/8718215/168.pdf)
- https://aclanthology.org/2022.acl-srw.4.pdf ==> [141.pdf](https://github.com/acl-org/acl-anthology/files/8718216/141.pdf)
- https://aclanthology.org/2022.acl-srw.27.pdf ==> [200.pdf](https://github.com/acl-org/acl-anthology/files/8718217/200.pdf)
- https://aclanthology.org/2022.acl-srw.26.pdf ==> [199.pdf](https://github.com/acl-org/acl-anthology/files/8718218/199.pdf)

Updating the PDFs  141, 168, 199, and 200 due to a Softconf uploading error.

**Comment by andreamad8** [comment]
We would like also to update the proceeding with the correct files, but the file is too big. How could we upload it?

**Comment by xinru1414** [comment]
@mjpost Do we support proceeding update/correction? 
@andreamad8 Can you please indicate the original paper (anthology id) and its corresponding updated paper pdf for each {og_paper, updated_paper} pair?

**Comment by mjpost** [comment]
Hi @andreamad8: yes, please find the Anthology IDs for each of these papers, and we will update them.

If you can post a Dropbox link to the new proceedings, we can update that as well.

**Comment by andreamad8** [comment]
Thanks


> @mjpost Do we support proceeding update/correction? @andreamad8 Can you please indicate the original paper (anthology id) and its corresponding updated paper pdf for each {og_paper, updated_paper} pair?

- 2022.acl-srw.15 ==> [168.pdf](https://github.com/acl-org/acl-anthology/files/8718215/168.pdf)
- 2022.acl-srw.4 ==> [141.pdf](https://github.com/acl-org/acl-anthology/files/8718216/141.pdf)
- 2022.acl-srw.27 ==> [200.pdf](https://github.com/acl-org/acl-anthology/files/8718217/200.pdf)
- 2022.acl-srw.26 ==> [199.pdf](https://github.com/acl-org/acl-anthology/files/8718218/199.pdf)
I update the first comment as well :)

@mjpost

This is the drive link: https://drive.google.com/file/d/193UAkSu-F3QNVpKp-6PfHzWntf-NKu74/view?usp=sharing

**Comment by xinru1414** [comment]
@andreamad8 Did you just want the [proceedings.pdf](https://aclanthology.org/2022.acl-srw.0.pdf) to be updated? @mjpost In that case shall we process it as a revision, or simply update the server pdf and the hash?

**Comment by mjpost** [comment]
If they provide the proceedings PDF we can just update it and its hash.

**Comment by andreamad8** [comment]
Hi, 

we would like both the proceeding.pdf and the paper mentioned in this pull request to be updated. 

-- Andrea
