### ISSUE TITLE
Correction to Anthology ID 2022.findings-acl.320

### ISSUE THREAD

**Issue by nilinykh** [acl-org/acl-anthology#1930]
## Option 1: Metadata correction

The dataset that is used in the paper is *not* Visual Genome (as it says now), it's Image Description Sequences (https://github.com/clp-research/image-description-sequences).

**Comment by mbollmann** [comment]
This needs to be corrected on Papers with Code: https://paperswithcode.com/paper/attention-as-grounding-exploring-textual-and-1
