### ISSUE TITLE
Correction to Anthology ID "2022.acl-tutorials.3"

### ISSUE THREAD

**Issue by yuchenlin** [acl-org/acl-anthology#1931]
# Instuctions

## Option 1: Metadata correction

Link: https://aclanthology.org/2022.acl-tutorials.3/ 
The author "Bill Lin" should be "Bill Yuchen Lin" and linked to https://aclanthology.org/people/b/bill-yuchen-lin/ .

**Comment by mjpost** [comment]
If you can submit a PR against `data/xml/2022.acl.xml` with the correction, it will expedite the fix.

**Comment by yuchenlin** [comment]
Hi @mjpost, thank you very much. I have created a PR here https://github.com/acl-org/acl-anthology/pull/1962
