### ISSUE TITLE
Correction to Anthology ID 2022.csrr-1.0

### ISSUE THREAD

**Issue by ykl7** [acl-org/acl-anthology#1932]
# Instuctions

## Option 1: Metadata correction

Link: https://aclanthology.org/2022.csrr-1.0/

The list of authors should be: Antoine Bosselut, Xiang Li, Bill Yuchen Lin, Vered Shwartz, Bodhisattwa Prasad Majumder, Yash Kumar Lal, Rachel Rudinger, Xiang Ren, Niket Tandon and Vilém Zouhar.

**Comment by mjpost** [comment]
If you submit a PR with corrections in the file `data/xml/2022.csrr.xml`, it will expedite the process.

**Comment by ykl7** [comment]
Thanks Matt! I have added a PR with the same.
