### ISSUE TITLE
links to papers in anthology ending in .pdf no longer work

### ISSUE THREAD

**Issue by DetmarM** [acl-org/acl-anthology#194]
This new version of the anthology is great - thank you for making this most important resource of our field new and shiny again!

A crucial aspect is backward compatibility for the many published links out there, though. The most compact way to refer to the anthology so far was of the form
http://aclweb.org/anthology/W18-0513.pdf
Until recently this worked with the .pdf or without the pdf suffix to retrieve the paper (and when adding a .bib suffix, one gets the bibtex entry, which is marvelous). I do remember the discussion some twenty years ago that we do want to support other file formats, at the time .ps was the most common form and we also submitted the .tex sources to cmp-lg etc. - so I agree that we should also support the URL not ending in the .pdf suffix. But it would be a major blow if we break all the links in publications and on web pages that do include the .pdf suffix. 
It would be important to continue to support the links ending in .pdf  that used to work until recently and that are widely mentioned in published work.

**Comment by mjpost** [comment]
Fixed.

Note you can also append a `/` (e.g., [http://aclweb.org/anthology/W18-0513/](http://aclweb.org/anthology/W18-0513/)) to get the paper page.

**Comment by DetmarM** [comment]
Thanks a lot for the quick fix - also for the pointer to the / leading to the index card for the paper - neat!
