### ISSUE TITLE
Ingestion request ALTA 2022 (2022-12-13)

### ISSUE THREAD

**Issue by prasys** [acl-org/acl-anthology#1943]
G'day,

We are preparing the proceedings for the ALTA2022 conference. 

We have a repo (based on the previous year's repo) which is being tracked here.

The repository that we are tracking the proceedings in [this repo](https://github.com/prasys/ALTA2022proceedings/) (WIP). 

The metadata about our conference can be obtained here 
[Meta data](https://github.com/prasys/ALTA2022proceedings/blob/main/meta) 

There is only one volume (main conference), and the title is  Proceedings of the The 20th Annual Workshop of the Australasian Language Technology Association

The conference starts on December 14th 2022. We would like to negotiate December 13th 2022 as the publication date 

Is this information sufficient - Do you need anything else from us?

Thank You,
Pradeesh

**Comment by mjpost** [comment]
Thanks. This looks good, except the `abbrev` field for ALTA isn't `ALTW` but `ALTA`, as [you can see here on the Anthology ALTA page](https://aclanthology.org/venues/alta/). Can you fix that in your metadata file?

**Comment by prasys** [comment]
Hi @mjpost 

Thanks for pointing that out. I've just fixed the meta

Thanks,
Pradeesh

**Comment by prasys** [comment]
Kia ora @xinru1414 

Sorry for the late response. We would like this to be done as soon as possible. If not, probably after the Christmas/New Year break

https://otagouni-my.sharepoint.com/:u:/g/personal/prapr694_student_otago_ac_nz/ETSjELpXioxHrIrtOaROmFABZ5FE9kaAe-ao3nCOltYTXw?e=hCrpRk 

Let me know if you can't access this sharepoint link 

Thank  you,
Pradeesh

**Comment by prasys** [comment]
@xinru1414 
https://otagouni-my.sharepoint.com/:u:/g/personal/prapr694_student_otago_ac_nz/ETSjELpXioxHrIrtOaROmFABZ5FE9kaAe-ao3nCOltYTXw?e=okOYvn

My university only allows up to a week. Let me know should you need more time and I'll upload it
