### ISSUE TITLE
SIGEDU missing on anthology main page

### ISSUE THREAD

**Issue by DetmarM** [acl-org/acl-anthology#195]
On the page https://www.aclweb.org/anthology/ there is a list of events held by SIGs. Currently, the SIGEDU https://sig-edu.org/ is missing there, and therefore there also is no way to look at  the longstanding Building Educational Applications Workshop series procedings
https://sig-edu.org/bea/past
for which the proceedings are all included in the anthology, in the way that it is, e.g. for 
SIGANN at https://www.aclweb.org/anthology/sigs/sigann/
Could SIGEDU be added with such a page to the anthology page?

**Comment by mjpost** [comment]
You can see BEA workshops [here](http://aclweb.org/anthology/venues/bea/), but yes, the SIG should be added.

I will add this to the docket. If you are up to it, this can be fixed faster if you submit a pull request (against the `static-rewrite` branch) with the fix. You need to create a "sigedu.yaml" file and put it in the `import/` directory. You can use one of the other files as a template, e.g., [sigmorphon.yaml](https://github.com/acl-org/acl-anthology/blob/static-rewrite/import/sigmorphon.yaml).

I think we may also have to manually add it to the front page index; perhaps @mbollmann can comment on that.

**Comment by mbollmann** [comment]
> I think we may also have to manually add it to the front page index; perhaps @mbollmann can comment on that.

I kinda already did, in [the detailed README](https://github.com/acl-org/acl-anthology/blob/static-rewrite/README_detailed.md) :)

> + YAML files for SIGs (`sig*.yaml` and `semitic.yaml`); these contain names, URLs, and associated venues for all special interest groups.  (**Note:** To add a new SIG, it also needs to be included in [`bin/anthology/data.py`](bin/anthology/data.py)!)

Although once I restructure the folder so that SIGs live in their own subfolder, we can even get rid of that.

**Comment by mjpost** [comment]
Ah, okay, thanks for documenting that!

**Comment by mjpost** [comment]
Hi @DetmarM—the static rewrite has now been merged into master, and @mbollmann has implemented the change he mentioned above. All we need to do is create a file `data/yaml/sigs/sigedu.yaml` and SIGEDU will be live. If you can provide the list of events (e.g., W18-05) that are SIGEDU events, it will help us get this done.

**Comment by DetmarM** [comment]
Thanx @mjpost, here is the list of events related to SIGEDU (namely the BEA and NLP4CALL workshop series) - can you integrate them and then make the SIGEDU appear on the main page?
W18-05                                                                               
W18-71                                                                               
W17-50                                                                               
W17-03                                                                               
W16-05                                                                               
W16-65                                                                               
W15-06                                                                               
W15-19                                                                               
W14-18                                                                               
W14-35                                                                               
W13-17                                                                               
W12-20                                                                               
W11-14                                                                               
W10-10                                                                               
W09-21                                                                               
W08-09                                                                               
W05-02                                                                               
W03-02

**Comment by DetmarM** [comment]
Thanks - but this does not seem to have had the effect of making EDU appear in the list of SIGs on the anthology site - what's missing?

**Comment by aryamccarthy** [comment]
After Matt's pull request, the information is there. It will appear once the site is rebuilt. :-)
