### ISSUE TITLE
Correction to Anthology ID 2022.eamt-1.20

### ISSUE THREAD

**Issue by BramVanroy** [acl-org/acl-anthology#1979]
## Revision

Asking for a revision since one author submitted a final, camera-ready version with a missing page for 2022.eamt-1.20. (I mentioned the whole 2022.eamt identifier because I am not sure whether all items need to change because all papers following this one now have different page numbers). The documentation states that I should only send in an updated PDF for the paper that changed. However, because this change adds a whole page, that would also shift the page numbers of following papers. So, do all papers need to be updated to reflect the different page numbers? In any case, I have added all files (PDF of the paper, PDF of the proceedings, and full archive) below. (Note that if you downloaded any of those files before you may need to clear cache to get the most recent ones. The updated paper should contain ten pages.)

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

Files:

- [PDF of updated paper](https://lt3.ugent.be/media/uploads/eamt2022/eamt_2022_paper_103.pdf)
- [PDF of final proceedings](https://lt3.ugent.be/media/uploads/eamt2022/proceedings-eamt2022.pdf) 
- [full updated data archive](https://lt3.ugent.be/media/uploads/eamt2022/eamt-2022_data.tgz)

Description:

This revision replaces paper "A Taxonomy and Study of Critical Errors in Machine Translation" by Khetam Al Sharou and Lucia Specia with an updated, correct version. In the first version of the proceedings, the authors had mistakenly submitted a camera-ready version with a missing page. In this revision, that page has been added. Because of this change, the page numbers of some publications have changed.

**Comment by mjpost** [comment]
Do you want to try re-ingesting the whole volume? The diff should only change the paper numbers, plus the hashes on 2022.eamt-1.20 and the proceedings volume.

**Comment by BramVanroy** [comment]
@mjpost Wouldn't the PDFs/hashes of all papers that follow 1.20 also have to change, since they have been modified with their new page number? Paper 1.20 has one page extra so following papers now start at a later page number, which is "printed" at the bottom of their pages.

**Comment by xinru1414** [comment]
@mjpost yes, will do.
