### ISSUE TITLE
The colon mark ( : ) is mistakenly quoted in the paper titles of Repl4NLP 2022

### ISSUE THREAD

**Issue by kaisugi** [acl-org/acl-anthology#1985]
#### Issue description

The titles listed below are incorrect.

```
Clozer”:" Adaptable Data Augmentation for Cloze-style Reading Comprehension
ANNA”:" Enhanced Language Representation for Question Answering
A Study on Entity Linking Across Domains”:" Which Data is Best for Fine-Tuning?
TRAttack”:" Text Rewriting Attack Against Text Retrieval
WeaNF”:" Weak Supervision with Normalizing Flows
```

#### Additional details / screenshot

<img width="1061" alt="スクリーンショット 2022-06-15 13 43 05" src="https://user-images.githubusercontent.com/36184621/173738317-df879909-5391-463c-b6ab-61347834ba47.png">

**Comment by mjpost** [comment]
Hi, we can fix this, but things will go more quickly if you create a PR yourself. The file to edit is `data/xml/2022.repl4nlp.xml`. It should be clear what to do.
