### ISSUE TITLE
Correction to Anthology ID 2021.mrl-1.5

### ISSUE THREAD

**Issue by ethch18** [acl-org/acl-anthology#1990]
# Instructions

**Please be sure to add the Anthology ID in the Issue title**

Please review [our correction policy](https://aclanthology.org/info/corrections/),
then fill out the information below.

## Option 1: Metadata correction

*Please replace this text with a description of the issue*

## Option 2: Revision or erratum

*Please add the following information*

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

Our experiments use the original codebase of Chau et al. (2020), which was recently revised to clarify that the original implementation of their TVA method (used in this paper) was equivalent to that of their VA method.  We have updated our paper to replace relevant mentions of TVA with VA and slightly rephrased one additional sentence to improve fluency.  Our findings, conclusions, and recommendations are unaffected.

[2021.mrl-1.5.erratum.pdf](https://github.com/acl-org/acl-anthology/files/8932896/2021.mrl-1.5.erratum.pdf)

**Comment by mjpost** [comment]
It looks like this commit got dropped, but I believe this has been processed since the revision [is present on the Anthology](https://aclanthology.org/2021.mrl-1.5/).
