### ISSUE TITLE
Ingestion request: LDL-2014, 2016, 2018

### ISSUE THREAD

**Issue by chiarcos** [acl-org/acl-anthology#1993]
The workshop series on Linked Data in Linguistics is in the ACL Anthology with venue identifier `ldl`(https://aclanthology.org/venues/ldl/). However, it seems that prior to 2020, all editions conducted as LREC workshops are missing from the ACL Anthology. 

Can we ingest them? 
That would be http://www.lrec-conf.org/proceedings/lrec2014/workshops/LREC2014Workshop-LDL2014%20Proceedings.pdf, http://www.lrec-conf.org/proceedings/lrec2016/workshops/LREC2016Workshop-LDL2016_Proceedings.pdf, http://lrec-conf.org/workshops/lrec2018/W23/W23_2018-Proceedings.zip

 [NB: We cannot ingest the very first edition, as this has been commercially published, but everything else is under standard ELRA copyright clauses.]

I was always under the impression that would have been done automatically via the LREC publication workflow (https://aclanthology.org/venues/ldl/), apologies for seeing this only years after.

**Comment by xinru1414** [comment]
Hi @chiarcos, Could you upload the full proceeding zip file for 2014, 2016 and 2018? In order to ingest them we need the zip files which include all bib files, pdf files and meta file -- the above 2018 link doesn't seem to work.

**Comment by chiarcos** [comment]
Thank you, will do. [Probably mid-July.]

Am Do., 23. Juni 2022 um 00:59 Uhr schrieb xinru1414 <
***@***.***>:

**Comment by xinru1414** [comment]
@chiarcos any update on this?

**Comment by chiarcos** [comment]
Apologies for the delay. I changed jobs since then. It will take me some
more time to see to that, please keep the issue open until end of spring
semester (August 2023).

Am Sa., 25. Feb. 2023 um 03:58 Uhr schrieb xinru1414 <
***@***.***>:

**Comment by anthology-assist** [comment]
Closing due to lack of submitter response.
