### ISSUE TITLE
Correction to Anthology ID 2022.acl-long.52

### ISSUE THREAD

**Issue by hongking9** [acl-org/acl-anthology#2002]
# Instructions

**Please be sure to add the Anthology ID in the Issue title**

Please review [our correction policy](https://aclanthology.org/info/corrections/),
then fill out the information below.

> Anthology ID is "2022.acl-long.52".

## Option 1: Metadata correction

> We would like to replace the already uploaded software with a new version, which is more readable and easier to use. We attach "2022.acl-long.52.software.rev1.zip". Please replace the old version with this new version.

## Option 2: Revision or erratum

*Please add the following information*

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

> In addition, we found a minor error in our paper but it can be misleading. In Algorithm 2 in page 4, just one line should be added. It seems the line was deleted accidentally while writing. New line "and $Queue[1\cdots n_{que}] = 0$" should be added between line "$n_{pat} = 0$" and line "$B_{conf} = S_{conf}$". The revised version (2022.acl-long.52.rev1.pdf) is attached. Please replace it with this revised version.

> The brief description: This revision corrects an error, which is a type of typo. One line in Algorithm 2 is corrected. 

[2022.acl-long.52.rev1.pdf](https://github.com/acl-org/acl-anthology/files/9029730/2022.acl-long.52.rev1.pdf)
[2022.acl-long.52.software.rev1.zip](https://github.com/acl-org/acl-anthology/files/9108303/2022.acl-long.52.software.rev1.zip)

**Comment by xinru1414** [comment]
@mjpost do we have a software correction policy?

**Comment by mjpost** [comment]
Just replace the old software; no revisions.

**Comment by hongking9** [comment]
@mjpost @xinru1414 The software hasn't been replaced yet. Could you please check and replace it? (I don't know how I can replace it..)

**Comment by mjpost** [comment]
Updated. The software was quite different, can you confirm this was intended?

**Comment by hongking9** [comment]
> Updated. The software was quite different, can you confirm this was intended?

Yes, it is intended. Because the old version was less readable, we re-implemented it so as to be more user-friendly and we confirmed that the same results are reproduced. Thank you for the update!
