### ISSUE TITLE
Ingestion request: CLIB 2020

### ISSUE THREAD

**Issue by DCL-IBL** [acl-org/acl-anthology#2005]
Dear ACL Anthology editors,

We would be grateful if the following Proceedings could be considered for inclusion into the ACL Anthology.

Venue identifier: CLIB
Venue name: Computational Linguistics in Bulgaria
Website: https://dcl.bas.bg/clib/
Volume title: Proceedings of the Fourth International Conference Computational Linguistics in Bulgaria (CLIB 2020)

Desired publication date: 30 July 2022

License: Proceedings are licenced under a Creative Commons Attribution 4.0. International License (CC BY 4.0) and upon submission authors have confirmed their agreement with the license's terms.
ISSN 2367-5578 (print)
ISSN 2367-5675 (online)

Contact email: clib2022@dcl.bas.bg

Many thanks,
Ivelina Stoyanova, Svetlozara Leseva
CLIB Organising Committee

**Comment by mjpost** [comment]
Yes, we can ingest this. However, we will need the materials very soon in order to meet your desired date.

**Comment by DCL-IBL** [comment]
Thank you, we are preparing and sending them in a couple of days.

**Comment by DCL-IBL** [comment]
The data are uploaded [here](https://drive.google.com/drive/folders/1A89OSQYyN2ufxNUje78CzC-aHnmchFqb). 
Many thanks!
Ivelina

**Comment by DCL-IBL** [comment]
Hello,

Would it be possible to also request ingestion of our CLIB 2022 proceedings? Camera ready papers are due by 7 Sept, we would be ready to submit the data by 15 Sept with a publication date 30 Sept? 

Do I need to submit a separate issue for that?

Please let me know if there are any issues with the 2020 data so that we can make adjustments.

Many thanks!
Ivelina

**Comment by mjpost** [comment]
I think we missed that you had uploaded data. @xinru1414 can you please look at this?

Yes, please create a separate issue for 2022 proceedings.
