### ISSUE TITLE
Ingestion request: GermEval (2022-09-05)

### ISSUE THREAD

**Issue by RobinSchaefer** [acl-org/acl-anthology#2012]
Hello,

We would like to register this year's GermEval Shared Task (https://qulab.github.io/text_complexity_challlenge/).

The venue identifier: germeval
The volume title: Proceedings of the GermEval 2022 Shared Task Text Complexity DE Challenge

Our submission deadline is July 22nd.

GermEval is a co-event of Konvens 2022, which already has been registered. We would like to publish the proceedings on September, 5th 2022.

Best regards,
Robin Schaefer

**Comment by mjpost** [comment]
Looks good, thank you!
