### ISSUE TITLE
Correction to Anthology (merging names)

### ISSUE THREAD

**Issue by evanmiltenburg** [acl-org/acl-anthology#2015]
These three profiles should probably be merged (with the top one being the main profile):

- https://aclanthology.org/people/k/kathleen-f-mccoy/
- https://aclanthology.org/people/k/kathleen-mccoy/
- https://aclanthology.org/people/k/kathy-mccoy/

**Comment by mjpost** [comment]
Thanks! One of these was a typo in the metadata.
