### ISSUE TITLE
Correction to Anthology ID 2022.naacl-main.24

### ISSUE THREAD

**Issue by romanklinger** [acl-org/acl-anthology#2017]
# Instructions

## Option 1: Metadata correction

The paper https://aclanthology.org/2022.naacl-main.24.pdf is the same pdf file as https://aclanthology.org/2022.naacl-main.23.pdf. It seems that the PDF for 2022.naacl-main.24 is not available.

**Comment by xinru1414** [comment]
This issue is fixed now.
