### ISSUE TITLE
Correction to Anthology ID 2022.trustnlp-1

### ISSUE THREAD

**Issue by dapurv5** [acl-org/acl-anthology#2031]
# Instructions

## Option 1: Metadata correction / Non-archival paper removal

Hi there,
I am an organizer for the TrustNLP workshop 2022. https://github.com/naacl-2022/TrustNLP2022
Paper ID 14 published on the ACL anthology, is meant to be non-archival and we wish to remove it from the proceedings.

I have made the changes in the proceedings repo and generated the final pdf here (without this paper) https://github.com/naacl-2022/TrustNLP2022/blob/main/build/proceedings.pdf 

Can you please update this on the ACL anthology website.

Thanks in advance.

**Comment by xinru1414** [comment]
@mjpost Are we processing this as a removal or retraction? 
@dapurv5 The pdf link you provided doesn't work.

**Comment by dapurv5** [comment]
Sorry, the repo above has limited access.

Attached file here. 

[proceedings.pdf](https://github.com/acl-org/acl-anthology/files/9106759/proceedings.pdf)

**Comment by mjpost** [comment]
@xinru1414 remove the XML entry for the paper entirely, and replace the full proceedings, please.

**Comment by xinru1414** [comment]
@mjpost Should I also remove 2022.trustnlp-1.9.pdf on our end?
