### ISSUE TITLE
Correction to Anthology ID 2022.naacl-main.38

### ISSUE THREAD

**Issue by mcnuttandrew** [acl-org/acl-anthology#2046]
# Instructions

**Please be sure to add the Anthology ID in the Issue title**

Please review [our correction policy](https://aclanthology.org/info/corrections/),
then fill out the information below.

## Option 1: Metadata correction

There a number of typos in the author list.
It currently reads: "Cynthia Sullivan, William Brackenbury, Andrew McNut, Kevin Bryson, Kbyllofficial@gmail.com Kbyllofficial@gmail.com, Yuxin Chen, Michael Littman, Chenhao Tan, Blase Ur"
It should read "Jamar L. Sullivan Jr., Will Brackenbury, Andrew McNutt, Kevin Bryson, Kwam Byll, Yuxin Chen, Michael L. Littman, Chenhao Tan, Blase Ur"

**Comment by xinru1414** [comment]
@mcnuttandrew For `Jamar L. Sullivan Jr.`, what's their first name and last name?

**Comment by mcnuttandrew** [comment]
@xinru1414 First name "Jamar" Last name: "Sullivan"

**Comment by akoehn** [comment]
@mcnuttandrew the name needs to be completely divided into first and last name. Should the name for `Jamar L. Sullivan Jr.` be changed to `Jamar Sullivan`?

See also the source  linked below (and if you have multiple changes, it might be fastest if you give us the corrected XML snippet): https://github.com/acl-org/acl-anthology/blob/22d944638b01bb884cd11a4663e26ca5e99768a1/data/xml/2022.naacl.xml#L512

**Comment by mcnuttandrew** [comment]
Thanks all for the responsiveness! I should have just filed a PR to begin with, which is what i've done now. Let me know if theres any other files that should be updated or anything like that

**Comment by akoehn** [comment]
Thanks! I started the CI pipeline for the PR to make it mergeable.
