### ISSUE TITLE
Bug report: 2022.naacl-main.13 leads to incorrect PDF

### ISSUE THREAD

**Issue by lucy3** [acl-org/acl-anthology#2050]
#### Steps to reproduce the issue

1. https://aclanthology.org/2022.naacl-main.13/ leads to paper titled "Two Contrasting Data Annotation Paradigms for Subjective NLP Tasks"
2. Click on "PDF" on the abstract / title landing page. 
3. https://aclanthology.org/2022.naacl-main.13.pdf loads "MULTIVERS: Improving scientific claim verification with weak supervision and full-document context"

#### What's the expected result?

The PDF should match the paper. 

#### What's the actual result?

The PDF leads to a different paper.

**Comment by mjpost** [comment]
Thanks for reporting. We've had a few papers like this, and will work with the NAACL pub chairs to sort it out.

**Comment by mjpost** [comment]
Please accept our apologies that this is taking so long. We are still working with the NAACL chairs to have them send us the corrected data.

**Comment by xinru1414** [comment]
Resolved: https://aclanthology.org/2022.naacl-main.13.pdf
