### ISSUE TITLE
Correction to Anthology ID 2022.wnu-1.5

### ISSUE THREAD

**Issue by phosseini** [acl-org/acl-anthology#2052]
# Instructions

**Please be sure to add the Anthology ID in the Issue title**

Please review [our correction policy](https://aclanthology.org/info/corrections/),
then fill out the information below.

## Option 1: Metadata correction

- There is an author, Patrícia Schmidtová (currently the second author), who is mistakenly added to the list of authors of our paper. The correct list of authors is as follows:
   - ```Pedram Hosseini, Christopher Wolfe, Mona Diab, David Broniatowski```
- The footer in the PDF file is not an accurate description of the venue:
   - The current version says: "Proceedings of the 3rd Wordplay: When Language Meets Games Workshop (Wordplay 2022), pages 38 - 46 July 15, 2022 ©2022 Association for Computational Linguistics" while the correct version should be: "**Proceedings of the 4th Workshop of Narrative Understanding (WNU2022), pages 38 - 46 July 15, 2022 ©2022 Association for Computational Linguistics**"

**Comment by xinru1414** [comment]
@phosseini Thank you for bring it up to our attention about the footer in the PDF. It seems like all PDFs of this workshop has the wrong footer.  I'll get in touch with the workshop organizers.

**Comment by phosseini** [comment]
The list of authors is now correct and updated, but the PDF footer does not seem to be correct. Is the footer going to be updated as well?

**Comment by mjpost** [comment]
These issues are out of our control. We only host material, and cannot update footers or be responsible for data correctness. Please contact the chairs of the workshop, who alone can correct the proceedings that they submitted to us.
