### ISSUE TITLE
Correction to Anthology ID 2022.acl-long.298

### ISSUE THREAD

**Issue by Valahaar** [acl-org/acl-anthology#2056]
Hi, our v2 of the paper 298 doesn't appear to have the official ACL footer.

V1: https://aclanthology.org/2022.acl-long.298v1.pdf
V2: https://aclanthology.org/2022.acl-long.298v2.pdf

Could you please update the PDF? 
Thanks!

**Comment by xinru1414** [comment]
@Valahaar We do not add footers to revisions.
