### ISSUE TITLE
Request to merge author profiles and disambiguate the author name

### ISSUE THREAD

**Issue by janetlauyeung** [acl-org/acl-anthology#2063]
Dear the staff of the ACL Anthology: 

I'm opening this issue to ask if the following pages could be merged under one single Author page, preferably **Yang Janet Liu**, where the first name is **_Yang Janet_**, and the last name **_Liu_**. I have been using **Yang Janet Liu** to publish since 2021 for disambiguation purposes. Currently there are two author pages for me (the first two links below), and two of my papers are not listed under any specific author page (the last two links below). 

- https://aclanthology.org/people/y/yang-janet-liu/
- https://aclanthology.org/people/y/yang-liu-georgetown/
- https://aclanthology.org/2020.lrec-1.648/
- https://aclanthology.org/2020.lrec-1.733/

Thank you so much in advance!

**Comment by nschneid** [comment]
In addition to paper-level changes this involves updating

https://github.com/acl-org/acl-anthology/blob/7e309c89b81af82cc47194a48b63d31487c69766/data/yaml/name_variants.yaml#L5463-L5465

to a canonical name of `{first: Yang Janet, last: Liu}` change the id to `yang-janet-liu`

**Comment by xinru1414** [comment]
@nschneid yes thanks for the pointer

**Comment by janetlauyeung** [comment]
Thanks for making the changes, but it looks like I still have **two** author pages: I think the change was made so that my 2020 LREC papers (the last two links in my initial post) were moved under the [Yang Janet Liu page](https://aclanthology.org/people/y/yang-janet-liu/) while I still have [this author page](https://aclanthology.org/people/y/yang-liu-georgetown/) where my 2019 papers were listed. Would it be possible to merge these two pages as well so that I only have one author page, ideally [the Yang Janet Liu one](https://aclanthology.org/people/y/yang-janet-liu/)? Thank you so much! I appreciate your help!

**Comment by mjpost** [comment]
Sorry we missed these. Can I ask you to update them and create a PR? That will expedite the process, since then I can just approve it and merge. To do this, edit `data/xml/W19.xml`, and change all instances of `yang-liu-georgetown` to `yang-janet-liu`.

If this presents trouble we can do it but it may take a bit longer.

**Comment by janetlauyeung** [comment]
No worries! I have updated the relevant information in `data/xml/W19.xml`, as mentioned in your comment, and a PR has been created pending a maintainer's review and approval. Thank you so much for your help, and please let me know if additional actions are needed from my end!
