### ISSUE TITLE
Correction to Anthology ID 2022.naacl-main.435 (etc.)

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#2067]
Papers by https://aclanthology.org/people/n/noah-a-smith/ @nasmith in 2022, as well as a few from previous years, are showing up with "Noah Smith" in the metadata despite "Noah A. Smith" in the PDF.

**Comment by mjpost** [comment]
Maybe tell him to fix his open review profile?

**Comment by nschneid** [comment]
He fixed it
