### ISSUE TITLE
Correction to Anthology ID 2022.acl-long.396

### ISSUE THREAD

**Issue by lambdaDove** [acl-org/acl-anthology#2072]
## Option 2: Revision or erratum
- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

Description of the changes:
The experimental results are updated by fixing the data leakage issue in the code. The studied problem, proposed technique, and conclusion remain unchanged. The updated results still demonstrate the advantage of the proposed method over baselines though the margins are not as large as the original version.
[Subgraph Retrieval Enhanced Model for Multi-hop Knowledge Base Question Answering 2480.pdf](https://github.com/acl-org/acl-anthology/files/9199066/Subgraph.Retrieval.Enhanced.Model.for.Multi-hop.Knowledge.Base.Question.Answering.2480.pdf)

**Comment by xinru1414** [comment]
@lambdaDove FYI the Anthology ID for the paper is `2022.acl-long.396` which you can find on the paper landing page https://aclanthology.org/2022.acl-long.396/
