### ISSUE TITLE
Correction to Anthology ID 2022.deeplo-1.5

### ISSUE THREAD

**Issue by bchivers-stanford** [acl-org/acl-anthology#2076]
Hi,

I noticed some metadata issues with [Anthology ID 2022.deeplo-1.5](https://aclanthology.org/2022.deeplo-1.5/).

- The abstract is just "t".  It would be great if you could copy the abstract from the paper into there.  I'll paste the abstract text from the paper at the bottom of this issue.
- The final two authors got concatenated - it's Natalya I. Rapstine.  And another author - Alex Storer.  Right now, there exists [this page](https://aclanthology.org/people/n/natalya-i-rapstine-and-alex-storer/) of the two authors concatenated.  They are also concatenated in the Bibtex - this will also need to be updated.  The citation also has a double "and" because of this - Brian Chivers, Mason P. Jiang, Wonhee Lee, Amy Ng, **and** Natalya I. Rapstine **and** Alex Storer. 2022.   It would be great if you could sweep everywhere the authors are mentioned and correct this.

Thanks!

Abstract:
Text segmentation and extraction from unstructured documents can provide business researchers with a wealth of new information on firms and their behaviors. However, the most valuable text is often difficult to extract consistently due to substantial variations in how content can appear from document to document. Thus, the most successful way to extract this content has been through costly crowdsourcing and training of manual workers. We propose the Assisted Neural Text Segmentation (ANTS) framework to identify pertinent text in unstructured documents from a small set of labeled examples. ANTS leverages deep learning and transfer learning architectures to empower researchers to identify relevant text with minimal manual coding. Using a real world sample of accounting documents, we identify targeted sections 96% of the time using only 5 training examples.

**Comment by xinru1414** [comment]
All deeplo papers are missing abstract, we are waiting for the workshop organizers to update them all at once. 

Combined names is fixed.
