### ISSUE TITLE
Correction to Anthology ID 2022.semeval-1.233

### ISSUE THREAD

**Issue by robvanderg** [acl-org/acl-anthology#2077]
## Option 1: Metadata correction

The last name the author is incorrect, it should be "van der Goot" (in both the anthology and the .bib file). If "van der" was removed automatically (which I assume it was?), this should probably be reconsidered, it is very common in the Netherlands, and is a part of the last name (it is not a middle name).

**Comment by mjpost** [comment]
We didn't delete this. Can you double-check that your name is entered correctly into OpenReview?
