### ISSUE TITLE
Anthology search always shows a maximum of 100 papers (10 pages with 10 papers)

### ISSUE THREAD

**Issue by dieuwkehupkes** [acl-org/acl-anthology#2087]
#### Issue description
Anthology search always shows maximally 100 papers, even if the amount found that is indicated is much higher.

#### Steps to reproduce the issue

1. Go to the search engine, type in a search word with a lot of hits, for instance, "multi-lingual"
2. Click on "year of publication" to restrict to papers

#### What's the expected result?
When I search for "multi-lingual", the search engine reports that there are about 4100 results found in (0.26 seconds). What I would expect, is that I can actually see all those 4100 papers. 

#### What's the actual result?
Instead, I can see only 100 papers, and this number does not change if I use different search terms.

**Comment by dieuwkehupkes** [comment]
Uffa that's unfortunate! Thanks for getting back to me so quickly.

**Comment by GMK2000GMK** [comment]
Has this issue been resolved? I still get 100 results even though it says 1500 results for my searches
