### ISSUE TITLE
Ingestion request: ROCLING 2022 (2022-11-21)

### ISSUE THREAD

**Issue by yfliu-fcu** [acl-org/acl-anthology#2095]
Dear Anthology Director,

I'm Yi-Fen Liu who the publication chair of the 34rd annual Conference on Computational Linguistics and Speech Processing (ROCLING 2022). Conference website: https://rocling2022.github.io/

We want to register the ROCLING  2022 to ACL Anthology. Please see following two items:
(a) the complete list of volumes: please see the attached file,
and (b) the desired publication date: November 21, 2022 (the first day of the conference)

If there is any question, please let me know.

Best regards,
Dr. Yi-Fen Liu

--
Assistant Professor
Dept. Information Engineering and Computer Science
Feng Chia University, Taiwan
Email: yfliu@fcu.edu.tw
[Anthology Volume_ROCLING 2022.xlsx](https://github.com/acl-org/acl-anthology/files/9281950/Anthology.Volume_ROCLING.2022.xlsx)

**Comment by xinru1414** [comment]
@yfliu-fcu thank you for the ingestion request. We can proceed once we have the ingestion material.

**Comment by yfliu-fcu** [comment]
Thank you for your notification. We are now preparing the materials for the
forthcoming ROCLING 2022 proceedings, including the copyright transfers.

**Comment by xinru1414** [comment]
@yfliu-fcu Thank you for letting us know. If you could submit 2 weeks prior to the desired publication date that'd be the best.

**Comment by yfliu-fcu** [comment]
We finished the ROCLING 2022 proceedings with ACLPUB format for
publication.  All data, including the copyright transfers, has uploaded to
Google Drive and the link has been sent to the Anthology Director via
emails: ***@***.***; ***@***.*** Let me know if there are any
issues on our end. Thank you.

**Comment by xinru1414** [comment]
@yfliu-fcu please preview [here](https://preview.aclanthology.org/rocling-22-ingestion/volumes/2022.rocling-1/) and let me know if there are any issues.

**Comment by yfliu-fcu** [comment]
@xinru1414 we have updated the .bib for some font issues in the abstracts. please reload them from the shared google drive folder.

**Comment by yfliu-fcu** [comment]
@xinru1414 can we preview the updated files? and we would like to know if the proceedings of Rocling 2022 is going to be published at November 19? Rocling 2022 will start at November 21.
