### ISSUE TITLE
Ingestion request

### ISSUE THREAD

**Issue by sdobnik** [acl-org/acl-anthology#2096]
Dear Matt,

I would like to request a publication of another volume for our conference this year which is endorsed by SIGSEM.

Venue identifier: CLASP (? see below)
Venue name: (Dis)embodiment 2022
Volume title: Proceedings of the 2022 CLASP Conference on (Dis)embodiment
Website: https://sites.google.com/view/disembodiment/home
Conference dates: 14 - 16 September 2022, Gothenburg, Sweden
Desired publication date: Wednesday 13 September 2022 (end of day, GMT+2)

We are using Softconf for the proceedings.

Reading your current instructions, it might make sense to request a standard venue identifier such as CLASP (Centre for Linguistic Theory and Studies in Probability) to be used also for the future events (and if possible also to collect the existing volumes, at least the one published in the ACL anthology: https://aclanthology.org/volumes/2021.reinact-1/).

Currently the series is as follows:

2021: https://gu-clasp.github.io/events/conferences/ReInAct2021/ with ACL anthology
2018: https://gu-clasp.github.io/events/conferences/dialogue-and-percetion-workshop/ with University of Gothenburg 
2017: https://gu-clasp.github.io/events/conferences/LaML/ with University of Gothenburg

Best regards,

Simon Dobnik
simon.dobnik@gu.se

---
From: Katrin Erk <katrin.erk@mail.utexas.edu>
Sent: Friday, February 18, 2022 11:36:11 PM
To: Shalom Lappin <shalom.lappin@gu.se>
Cc: Sharid Loáiciga <sharid.loaiciga@gu.se>; Asad Basheer Sayeed <asad.sayeed@gu.se>
Subject: Re: Draft CFP and website
 
Hi Shalom,

Good news: Your conference is endorsed by SIGSEM.

Cheers,
Katrin

On Mon, Feb 14, 2022 at 5:04 PM Katrin Erk <katrin.erk@mail.utexas.edu> wrote:
Many thanks, Shalom! I'll pass this on to the board.

Cheers,
Katrin

On Sat, Feb 12, 2022 at 2:11 AM Shalom Lappin <shalom.lappin@gu.se> wrote:
Hi Katrin,

    You can see our draft CFP at https://sites.google.com/view/disembodiment/call-for-papers. This website is still under development, and we will be revising it within the next few weeks. The conference is scheduled for the week of Sept 13, 2022, and we will fix the precise days soon.

We are hoping that the draft CFP provides sufficient information for the SIGSEM executive to make a decision on our request for sponsorship. Let us know. Many thanks for your help with this.

Best,
Shalom
>> This message is from an external sender. Learn more about why this <<
>> matters at https://links.utexas.edu/rtyclf.                        <<
-- 
Katrin Erk, Department of Linguistics
The University of Texas at Austin
http://www.katrinerk.com/

**Comment by xinru1414** [comment]
Ingested: https://aclanthology.org/volumes/2022.clasp-1/
