### ISSUE TITLE
Correction to Anthology ID 2020.emnlp-main.423

### ISSUE THREAD

**Issue by darthskyy** [acl-org/acl-anthology#2097]
The revision corrects a typo on the footnote on page 5239 say "Te dataset..." instead of "The dataset..."

- [x ] I have attached the revised PDF or erratum to this issue
- [x ] I have written a brief description of the changes below

[Tackling the Low-resource Challenge for Canonical Segmentation (Corrected).pdf](https://github.com/acl-org/acl-anthology/files/9291045/Correction.pdf): Correction highlighted.
[Tackling the Low-resource Challenge for Canonical Segmentation.pdf](https://github.com/acl-org/acl-anthology/files/9291047/Tackling.the.Low-resource.Challenge.for.Canonical.Segmentation.pdf)

**Comment by xinru1414** [comment]
@darthskyy which link is the revised paper pdf?

**Comment by xinru1414** [comment]
@darthskyy Both pdfs you linked have `Te dataset` instead of `The dataset`. You don't need to highlight the pdf. Please update the corrected pdf.

**Comment by xinru1414** [comment]
@mjpost I think it does? This is the "Corrected.pdf". 

<img width="719" alt="Screenshot 2022-11-01 at 6 23 47 PM" src="https://user-images.githubusercontent.com/27436920/199372762-6f052bdf-9d42-4e1f-a7e3-44b3ff2d09ab.png">

We might be looking at different files?

**Comment by mjpost** [comment]
Oh, I see, each has a different highlight. @darthskyy please submit a revised version without any highlighting. The revision is meant to stand on its own.

**Comment by xinru1414** [comment]
@darthskyy any updates? otherwise closing.

**Comment by xinru1414** [comment]
Closing because haven't heard back from the submitter for several months.
