### ISSUE TITLE
Correction to Anthology ID 2022.findings-naacl.127

### ISSUE THREAD

**Issue by gpsbhargav** [acl-org/acl-anthology#2098]
Anthology ID: 2022.findings-naacl.127
Link to the published paper: https://aclanthology.org/2022.findings-naacl.127/

## Metadata correction

The link to the source code mentioned on the webpage of the paper is incorrect. 
The correct link is https://github.com/IBM/NeSLET

## Revision or erratum
- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

### Summary of changes
Personally identifiable information, such as the names of public figures, has been masked in Tables 12 and 13 of the appendix.

### New version of the paper
[ZEL_masked.pdf](https://github.com/acl-org/acl-anthology/files/9302246/ZEL_masked.pdf)

**Comment by xinru1414** [comment]
@gpsbhargav do you mean the paperwithcode link? It's directly from pwc and we can't change it on our end.

**Comment by gpsbhargav** [comment]
@xinru1414 Yes, I was referring to the "code" field. If I request paperswithcode, and if they correct the link, will that correction reflect on the anthology page as well?
