### ISSUE TITLE
prepopulate Google search box with current query

### ISSUE THREAD

**Issue by jeisner** [acl-org/acl-anthology#210]
When I do [a search](http://www.aclweb.org/anthology/search/?q=puns) using the new search box (#50) 🎉, the page of search results has a new empty search box in the upper right, for my next query.

Could that search box on the results page be prepopulated with the current query?  That reminds me exactly how the results on the current page were obtained, and lets me edit the search and retry.  

Most search facilities are set up in this way, including the one at google.com and the one for Google Custom Search.  Furthermore, when the search results page loads, usual practice is to put the edit focus on the prepopulated search box, with the cursor in the same place as before.

**Comment by mjpost** [comment]
+1. A variation on this would be to list the search query (and maybe repeat the search box?) just under the "Search Results" text.
