### ISSUE TITLE
Correction to Anthology ID 2022.acl-long.219

### ISSUE THREAD

**Issue by Eric-Wallace** [acl-org/acl-anthology#2111]
## Option 2: Revision or erratum

- [ x] I have attached the revised PDF or erratum to this issue
- [ x] I have written a brief description of the changes below

The results for the baseline Dr.Fill system have been updated to reflect recent improvements in the system. The results in the original version of the paper reflected an out-of-date version of the Dr.Fill software.

**Comment by Eric-Wallace** [comment]
Here is a link to the revised PDF
[https://github.com/Eric-Wallace-WebHost/Eric-Wallace-Webhost.github.io/raw/master/Automated_Crossword_Solving_Revised.pdf](url)

**Comment by xinru1414** [comment]
@Eric-Wallace link is invalid

**Comment by Eric-Wallace** [comment]
Not sure why clicking on the link doesn't work, but if you paste it in your browser it should be ok. Let me try with a new [link](https://github.com/Eric-Wallace-WebHost/Eric-Wallace-Webhost.github.io/raw/master/Automated_Crossword_Solving_Revised.pdf)

**Comment by Eric-Wallace** [comment]
@xinru1414 fixed above

**Comment by Eric-Wallace** [comment]
@xinru1414 following up again

**Comment by mjpost** [comment]
ping @xinru1414

**Comment by xinru1414** [comment]
Sorry about the delay!
