### ISSUE TITLE
Ingestion request: CLIB 2022 (2022-09-30)

### ISSUE THREAD

**Issue by DCL-IBL** [acl-org/acl-anthology#2113]
Venue identifier: CLIB
Venue name: Computational Linguistics in Bulgaria
Website: https://dcl.bas.bg/clib/
Volume title: Proceedings of the Fifth International Conference Computational Linguistics in Bulgaria (CLIB 2022)

Desired publication date: 30 September 2022

License: Proceedings are licenced under a Creative Commons Attribution 4.0. International License (CC BY 4.0) and upon submission authors have confirmed their agreement with the license's terms.
ISSN 2367-5578 (print)
ISSN 2367-5675 (online)

Contact email: clib2022@dcl.bas.bg 

Many thanks,
Ivelina Stoyanova

**Comment by xinru1414** [comment]
@DCL-IBL Please submit ingestion material soon. Thanks!

**Comment by DCL-IBL** [comment]
Dear @xinru1414 and @mjpost 

The data for CLIB 2022 is uploaded here:
https://drive.google.com/drive/folders/1A89OSQYyN2ufxNUje78CzC-aHnmchFqb

Apologies for the delay!

**Comment by DCL-IBL** [comment]
Hi @xinru1414,

Just a reminder that I added the data for 2022 - link above, in case you missed my message.

Many thanks,
ivelina

**Comment by xinru1414** [comment]
@DCL-IBL Before I ingest, just wanted to double check with you that the uploaded ingestion material is correct -- This request is for CLIB 2022, however all the dates in the ingestion material  (such as the pdfs and the meta file) is CLIB 2020.

**Comment by DCL-IBL** [comment]
Hi @xinru1414 
The shared folder contained both the data for 2020 and for 2022. I now removed the old one, so that only 2022 is left. Apologies for causing a confusion. 
https://drive.google.com/drive/folders/1A89OSQYyN2ufxNUje78CzC-aHnmchFqb

Best wishes,
Ivelina
