### ISSUE TITLE
Ingestion request: ICON 2022 (2022-12-10)

### ISSUE THREAD

**Issue by shadakhtar** [acl-org/acl-anthology#2118]
Venue identifier: https://aclanthology.org/venues/icon/
Venue name: Proceedings of the 19th International Conference on Natural Language Processing (ICON-2022)
Website: https://www.lcs2.in/ICON-2022/index.html

Desired publication date: 10th December 2022

Contact email: icon2022@iiitd.ac.in

Many thanks,
Md Shad AKhtar

**Comment by mjpost** [comment]
Thanks! How many volumes will you have?

**Comment by as3eem** [comment]
Hi @mjpost, I am on the organizing team of ICON.

1. We will have only one volume.
2. I would like to know if we have to make separate requests for workshops as we haven't finalized the number of workshops we will have.

**Comment by as3eem** [comment]
Hi @mjpost and @xinru1414,
Any update on this issue?

**Comment by xinru1414** [comment]
My understanding is that you don't need to make separate requests for workshops. @mjpost Please correct me if I'm wrong.

**Comment by mjpost** [comment]
Yes, please bundle it as a single request.

**Comment by as3eem** [comment]
Alright thanks! @mjpost and @xinru1414.
Lemme know if any extra details are needed from our end.

**Comment by xinru1414** [comment]
@as3eem just need the ingestion material ~10 days prior to your desired publication date

**Comment by as3eem** [comment]
Dear @xinru1414 and @mjpost,

I have compiled the proceedings data in a folder and have a pdf ready. Could you please let me know how to share the data with you?

**Comment by as3eem** [comment]
@mjpost , @xinru1414 
waiting for your update on this.

**Comment by mjpost** [comment]
Thanks. @xinru1414, I imagine you can handle this after the holidays?

**Comment by as3eem** [comment]
@xinru1414 Looking forward to your reply!

**Comment by as3eem** [comment]
Dear @xinru1414 and @mjpost,

We are getting late in releasing the proceedings. Would really appreciate your reply on this matter.

**Comment by mjpost** [comment]
@xinru1414 are you able to complete this ingestion today?

**Comment by as3eem** [comment]
Apologies for the delay.

Here is the link to the drive. Could you request access to it? 
All the requests are bundled into one place, as discussed earlier.

https://drive.google.com/drive/folders/1DKZrrXuDWdo6hECgZd8EhXDejrPX0QrW?usp=sharing

**Comment by as3eem** [comment]
@xinru1414 I see.  Let me look into it. I'll give it a check and update the main volume folder if needed.

**Comment by as3eem** [comment]
Hi @xinru1414, I have updated the folder with additional required files. Can you give it a check now?
Let me know.

**Comment by as3eem** [comment]
Hi @xinru1414 @mjpost,
Please let me know how to proceed if we find any typo and want to update the proceedings in the future.

**Comment by xinru1414** [comment]
@as3eem If you spot any issues in the preview (#2386) please leave comments under the PR. We will fix them and then publish. 

Once the proceedings is published, you will have to go through the [correction](https://aclanthology.org/info/corrections/) step.

**Comment by as3eem** [comment]
Hi @mjpost and @xinru1414, 

Thanks a lot for providing all the assistance so far. We are satisfied with the current version. 

However, there is one more workshop proceeding we are willing to add to the current list of workshop proceedings. Due to some unavoidable reasons, the organizers of that workshop were unable to provide the camera ready on time. 

If we provide you a drive link with just one workshop proceeding, can you please add it to the current list?  

I will appreciate your kind consideration.

**Comment by as3eem** [comment]
@xinru1414 @mjpost any update on this? This is a kind reminder.

**Comment by mjpost** [comment]
Yes we can always ingest more materials. Please share the info. CC: @anthology-assist
