### ISSUE TITLE
Correction to Anthology IDs 2021.sigmorphon-1.25, 2021.sigmorphon-1.27, and 2021.sigmorphon-1.29

### ISSUE THREAD

**Issue by tpimentelms** [acl-org/acl-anthology#2124]
## Option 1: Metadata correction

The titles of the following three paper do not have protected cases (with fixed-case tags):
2021.sigmorphon-1.25
2021.sigmorphon-1.27
2021.sigmorphon-1.29

**Comment by xinru1414** [comment]
@tpimentelms I'm not seeing other sigmorphon papers have "faixed-case" tags. Not sure if this is an issue?

**Comment by tpimentelms** [comment]
Hey @xinru1414 . Sorry, but I did not understand your message. I opened a (linked) PR which fixes the font cases of the paper titles which should be fixed: #2125
