### ISSUE TITLE
Ingestion request: MoL

### ISSUE THREAD

**Issue by ranitomeya** [acl-org/acl-anthology#2134]
Hi Matt,

With a huge delay, I would like to register the most recent meeting of SIGMOL, i.e., the Meeting on the Mathematics of Language (MoL), which took place in December. I apologize for not doing it much earlier. The data of the meeting is

Venue identifier: Meeting on the Mathematics of Language
Volume title: Proceedings of the 17th Meeting on the Mathematics of Language

Please let me know whether there is anything special to be observed or I should simply go on assembling the material. Obviously, the matter is not that time critical anymore, given the fact that 9 months have passed since the meeting. On the other hand, I feel that I should not unnecessarily let the authors wait even longer, so I will do my best to provide you with the required material asap.

Best,
Frank

**Comment by mjpost** [comment]
Hi,

Thanks for the note. 

1. Is this an ACL SIG?
2. Note that your identifier is [mol](https://aclanthology.org/venues/mol/)

Nothing special, please just note the [submission instructions](https://aclanthology.org/info/contrib/) (where relevant).

**Comment by ranitomeya** [comment]
Hi again, and thanks!

Yes, it's the ACL SIG SIGMOL.

**Comment by xinru1414** [comment]
@ranitomeya Please submit your ingestion material (per the submission instructions) and we'll proceed from there.
