### ISSUE TITLE
Ingestion request: COLING 2022 (2022-10-12)

### ISSUE THREAD

**Issue by nash2000** [acl-org/acl-anthology#2142]
Dear Anthology Director,

This is Seung-Hoon Na who is a publication chair of The 29th International Conference on Computational Linguistics (COLING 2022), with the conference website: https://coling2022.org/

I would like to register the meeting of COLING 2022 to ACL anthology, as follows:
1) The desired publication date: Oct 12, 2022
2) The venue identifier: coling

3) The complete list of volumes (including main conference volumes and workshops): The list is given below. 

- Proceedings of the 29th International Conference on Computational Linguistics
- Proceedings of the 29th International Conference on Computational Linguistics: System Demonstrations
- Proceedings of the 29th International Conference on Computational Linguistics: Tutorial Abstracts
- Proceedings of the 29th International Conference on Computational Linguistics: Industry Track 

- Proceedings of the Fifth Workshop on Technologies for Machine Translation of Low-Resource Languages (LoResMT 2022)
- Proceedings of the 6th Joint SIGHUM Workshop on Computational Linguistics for Cultural Heritage, Social Sciences, Humanities and Literature (LaTeCH-CLfL 2022)
- Proceedings of the 8th Workshop on Noisy User-generated Text (W-NUT 2022)
- Proceedings of Workshop on Pattern-based Approaches to NLP in the Age of Deep Learning (Pan-DL)
- Proceedings of Workshop on Automatic Summarization for Creative Writing
- Proceedings of the 5th Workshop on Computational Models of Reference, Anaphora and Coreference (CRAC 2022)
- Proceedings of the 3rd Workshop on Computational Approaches to Discourse (CODI)
- Proceedings of the Third Workshop on Scholarly Document Processing (SDP 2022)
- Proceedings of Workshop on When Creative AI Meets Conversational AI
- Proceedings of the First Workshop on Transcript Understanding (TU)
- Proceedings of the Third Workshop on Threat, Aggression and Cyberbullying (TRAC-2022)
- Proceedings of the First Workshop on Customized Chat Grounding Persona and Knowledge
- Proceedings of the 9th Workshop on Argument Mining
- Proceedings of the 9th Workshop on Asian Translation (WAT2022)
- Proceedings of Workshop on Graph-based Methods for Natural Language Processing (TextGraphs-16)
- Proceedings of the First Workshop on NLP applications to field linguistics
- Proceedings of the 7th Workshop on Social Media Mining for Health Research and Applications (SMM4H)
- Proceedings of the Ninth Workshop on NLP for Similar Languages, Varieties and Dialects (VarDial)
- Proceedings of Workshop on Performance and Interpretability Evaluations of Multimodal, Multipurpose, Massive-Scale Models
- Proceedings of the CRAC 2022 Shared Task on Multilingual Coreference Resolution
- Proceedings of the CODI-CRAC 2022 Shared Task on Anaphora, Bridging, and Discourse Deixis in Dialogue

I would appreciate if you check whether all necessary information for Anthology registration is provided

Please let me know if there is any missing information or issue. 

Thank you, 
Best regards,

Seung-Hoon Na

**Comment by mjpost** [comment]
Thanks. This looks good—what's missing is the proposed venue codes (e.g., "coling" for [COLING](https://aclanthology.org/venues/coling), "latechclfl" for [LaTeCH-CLfL](https://aclanthology.org/venues/latechclfl/)). This is especially needed for new venues, but we also need to match up existing ones. Can you please add these to the workshops?

**Comment by nash2000** [comment]
Dear Matt,

Thank you for your handling our ingestion request. The proceedings are almost ready, so they will be submitted soon. 

As you requested, here are the venue codes for all workshops, by maximally matching with the existing ones in anthology. 
 - please see the field of details, which are categorized into "exists", "distributed", and "newly proposed", according to whether its venue code is available in anthology.


===========================================================
1. Proceedings of the 29th International Conference on Computational Linguistics
  - venue code: coling 
  - details: exists (the venue corresponds to the conference or the workshop exists)

2. Proceedings of the Fifth Workshop on Technologies for Machine Translation of Low-Resource Languages (LoResMT 2022)		
  - venue code: loresmt
  - details: distributed (the same workshop exists in several volumes but its single venue is not available)	
   
3. Proceedings of the 6th Joint SIGHUM Workshop on Computational Linguistics for Cultural Heritage, Social Sciences, Humanities and Literature (LaTeCH-CLfL 2022)	 
  - venue code: latechclfl	
  - details: exists

4. Proceedings of the 8th Workshop on Noisy User-generated Text (W-NUT 2022)											
  - venue code: wnut	
  - details: exists
												
5. Proceedings of Workshop on Pattern-based Approaches to NLP in the Age of Deep Learning (Pan-DL)		
  - venue code: pandl
  - details: newly proposed (this is the first workshop this year).	
												
6. Proceedings of Workshop on Automatic Summarization for Creative Writing		
  - venue code: creativesumm	
  - details: newly proposed
												
7. Proceedings of the 5th Workshop on Computational Models of Reference, Anaphora and Coreference (CRAC 2022)		
  - venue code: crac	
  - details: exists
												
8. Proceedings of the 3rd Workshop on Computational Approaches to Discourse (CODI)		
  - venue code: codi	
  - details: exists

9. Proceedings of the Third Workshop on Scholarly Document Processing (SDP 2022)		
  - venue code: sdp	
  - details: exists

10. Proceedings of Workshop on When Creative AI Meets Conversational AI	
  - venue code: craiconvai	
  - details: newly proposed  
												
11. Proceedings of the First Workshop on Transcript Understanding (TU)	
  - venue code: tu
  - details: newly proposed 	
												
12. Proceedings of the Third Workshop on Threat, Aggression and Cyberbullying (TRAC-2022)
  - venue code: trac
  - details: exists

13. Proceedings of the First Workshop on Customized Chat Grounding Persona and Knowledge	
  - venue code: ccgpk
  - details: newly proposed	
	
14.  Proceedings of the 9th Workshop on Argument Mining	
  - venue code: argmining
  - details: exists
												
15. Proceedings of the 9th Workshop on Asian Translation (WAT2022)		
  - venue code: wat
  - details: exists
																		
16. Proceedings of Workshop on Graph-based Methods for Natural Language Processing (TextGraphs-16)
  - venue code: textgraphs
  - details: exists

17. Proceedings of the First Workshop on NLP applications to field linguistics	
  - venue code: fieldmatters
  - details: newly proposed 	
				
18. Proceedings of the 7th Workshop on Social Media Mining for Health Research and Applications (SMM4H)	
  - venue code: smm4h
  - details: distributed	

19. Proceedings of the Ninth Workshop on NLP for Similar Languages, Varieties and Dialects (VarDial)	
  - venue code: vardial	
  - details: exists
		
20. Proceedings of Workshop on Performance and Interpretability Evaluations of Multimodal, Multipurpose, Massive-Scale Models		
  - venue code: mmmpie	
  - details: newly proposed 
				
21. Proceedings of the CRAC 2022 Shared Task on Multilingual Coreference Resolution	
  - venue code: crac  (this is the shared track of CRAC, so it should belong to CRAC workshop)
  - volume name: crac-coref
  - details: exists

22. Proceedings of the CODI-CRAC 2022 Shared Task on Anaphora, Bridging, and Discourse Deixis in Dialogue		
  - venue code: crac;codi	(this is the shared track co-organized by CRAC and CODI workshops, so it should belong to CRAC and CODI workshops)
  - volume name: codi-sharedtask
  - details: exists

===========================================================

We are sorry for being delayed on submitting our proceedings to ACL anthology. But we will let you know quickly when the proceeding tarball file becomes available. 

Please let us know if you have any questions or issues with the above list. 

Thank you, 
Best regards, 

Seung-Hoon Na

**Comment by nash2000** [comment]
Dear Matt,

Among the codes suggested in the previous message, we are sorry for making this request, 
but could you please use the revised venue code for the following workshop?      

========================================================
10. Proceedings of Workshop on When Creative AI Meets Conversational AI

- venue code: cai
- details: newly proposed
========================================================


Thank you, 
Best regards,

Seung-Hoon Na

**Comment by nash2000** [comment]
Dear Matt,

The zipped proceedings of COLING 2022 (for the main conference and workshops) are now ready in the following links:
- https://nlp.jbnu.ac.kr/coling2022/coling2022_data.tgz
Or you can download it from Google drive here:
- https://drive.google.com/file/d/1NJ2b0RfKSoREnVKjzvD-ZhSe1Y_JO-qI/view?usp=sharing

Could you please ingest them to ACL anthology by Oct 11 AoE, if possible?

Below is the list of subdirectories for proceedings of the main conference and workshops in COLING 2022.  
=============================================================
// <subdirectory>: <proceeding title>

1. coling2022-papers: Proceedings of the 29th International Conference on Computational Linguistics
2. LoResMT_2022: Proceedings of the Fifth Workshop on Technologies for Machine Translation of Low-Resource Languages (LoResMT 2022)                                       
3. LaTeCH-CLfL_2022: Proceedings of the 6th Joint SIGHUM Workshop on Computational Linguistics for Cultural Heritage, Social Sciences, Humanities and Literature (LaTeCH-CLfL 2022)   
4. W-NUT_2022: Proceedings of the 8th Workshop on Noisy User-generated Text (W-NUT 2022)                                       
5. Pan-DL: Proceedings of Workshop on Pattern-based Approaches to NLP in the Age of Deep Learning (Pan-DL)                                       
6. ASCW_2022: Proceedings of Workshop on Automatic Summarization for Creative Writing                                       
7. CRAC_2022: Proceedings of the 5th Workshop on Computational Models of Reference, Anaphora and Coreference (CRAC 2022)                                       
8. CODI: Proceedings of the 3rd Workshop on Computational Approaches to Discourse (CODI)   
9. SDP_2022: Proceedings of the Third Workshop on Scholarly Document Processing (SDP 2022)   
10. Cr_AI_Conv_AI: Proceedings of Workshop on When Creative AI Meets Conversational AI       
11. TU: Proceedings of the First Workshop on Transcript Understanding (TU)   
12. TRAC-2022: Proceedings of the Third Workshop on Threat, Aggression and Cyberbullying (TRAC-2022)
13. CCGPK: Proceedings of the First Workshop on Customized Chat Grounding Persona and Knowledge   
14. AM_2022: Proceedings of the 9th Workshop on Argument Mining
   - This subdirectory is currently not available, because its proceedings are not ready. Once finalized, we would let you know later.
                                       
15. WAT2022: Proceedings of the 9th Workshop on Asian Translation (WAT2022)                                       
16. TextGraphs-16: Proceedings of Workshop on Graph-based Methods for Natural Language Processing (TextGraphs-16)
17. NLP-FL_2022: Proceedings of the First Workshop on NLP applications to field linguistics       
18. 7thSMM4H: Proceedings of the 7th Workshop on Social Media Mining for Health Research and Applications (SMM4H)   
19. VarDial_2022: Proceedings of the Ninth Workshop on NLP for Similar Languages, Varieties and Dialects (VarDial)   
20. PIEM3SM: Proceedings of Workshop on Performance and Interpretability Evaluations of Multimodal, Multipurpose, Massive-Scale Models                                   
21. CRAC2022-COREF: Proceedings of the CRAC 2022 Shared Task on Multilingual Coreference Resolution
22. COCR: Proceedings of the CODI-CRAC 2022 Shared Task on Anaphora, Bridging, and Discourse Deixis in Dialogue       
=============================================================

We are sorry again for being delayed for this submission.
But, we would really appreciate if you publish them in ACL anthology before our conference begins.

Please let us know if there is any issue or problem.

Thank you,
Best regards,

Seung-Hoon Na

**Comment by xinru1414** [comment]
Ingested (#2167). Missing `AM_2022` material.

**Comment by nash2000** [comment]
Dear Xinru Yan.

Thank you very much for ingesting our proceedings on ACL anthology despite the urgent request.

The remaining proceedings for the workshop on Argument Mining are now available, directly from the following link:
https://nlp.jbnu.ac.kr/coling2022/coling2022_wm2022_data.tgz

Or you can download the tarball file from Google drive:
https://drive.google.com/file/d/1nTNbD455meu_zncIagSUF0xiiWjjmuGS/view?usp=sharing

We are really sorry again for making an urgent request, but could you please ingest this workshop to the anthology by Oct 11 AoE too?
===========================================================
* AM_2022: Proceedings of the 9th Workshop on Argument Mining
===========================================================             

We would deeply appreciate if you could understand our current situation and make all our proceedings successfully published before COLING 2022 starts.

Please let us know if there are any problems or issues.

Thank you,
Best regards,

Seung-Hoon Na
