### ISSUE TITLE
Correction to Anthology ID 2021.naacl-main.459

### ISSUE THREAD

**Issue by abhirut** [acl-org/acl-anthology#2149]
# Instructions

**Please be sure to add the Anthology ID in the Issue title**

Please review [our correction policy](https://aclanthology.org/info/corrections/),
then fill out the information below.

## Option 1: Metadata correction

The links to code and dataset in our paper are incorrect. We have not released any code with the paper, shruikan20/spoken-tutorial-dataset is the dataset used in the paper and the PHINC dataset was not used by our paper.

New information should be as follows -

Code: Not Available
Data: [shruikan20/spoken-tutorial-dataset](https://github.com/shruikan20/spoken-tutorial-dataset)

**Comment by abhirut** [comment]
PHINC dataset was not released* by our paper. It is from an existing paper.

**Comment by mbollmann** [comment]
This correction must be done on Papers with Code, as we automatically sync this information from them.
https://paperswithcode.com/paper/training-data-augmentation-for-code-mixed
