### ISSUE TITLE
Paper PDFs are 404

### ISSUE THREAD

**Issue by Luminite2** [acl-org/acl-anthology#215]
As of right now, I don't appear to be able to access any paper PDFs, and am getting the 404 page. A handful of URLs that give the 404 for me:

https://aclweb.org/anthology/D18-1461
https://aclweb.org/anthology/D18-1285
https://aclweb.org/anthology/W18-5424
http://www.aclweb.org/anthology/N18-1116
https://aclweb.org/anthology/Q17-1026

**Comment by mjpost** [comment]
Sorry, playing around with Apache rewrite rules. This should be fixed now.

**Comment by evanmiltenburg** [comment]
This may not be fixed just yet. I'm getting a 404 for this paper: https://www.aclweb.org/anthology/E/E14/E14-1049.pdf

(Improving Vector Space Word Representations. Using Multilingual Correlation. Manaal Faruqui and Chris Dyer. 2014)

**Comment by mjpost** [comment]
Where did you get that URL from? It works if you use the canonical URL: https://www.aclweb.org/anthology/E14-1049.

**Comment by evanmiltenburg** [comment]
I got it from the search results:

<img width="1000" alt="Screen Shot 2019-03-27 at 12 08 44" src="https://user-images.githubusercontent.com/1513355/55078668-f2c9ae00-509a-11e9-9d1a-98eddeb50c99.png">

And earlier I found the same link through Google.

**Comment by mjpost** [comment]
Ah, okay. These links should be working again now, though this suggests that we should add 301 redirects for them.

**Comment by mjpost** [comment]
(Also I'll note for the record that this is great to see `aclweb.org/anthology` being surfaced as the top hit!)

**Comment by evanmiltenburg** [comment]
Thanks for the quick fix!
