### ISSUE TITLE
Ingestion Request SigDial 2022

### ISSUE THREAD

**Issue by malihealikhani** [acl-org/acl-anthology#2150]
Hi, This is the link to the videos:
https://drive.google.com/file/d/1Rh3_n2lI8I3COvT3GVEFUldmb7KBj4QM/view?usp=sharing

[sigdial_2022_videos.tsv.zip](https://github.com/acl-org/acl-anthology/files/9649002/sigdial_2022_videos.tsv.zip)

**Comment by xinru1414** [comment]
Thank you for sharing the videos. However i don't think we have the complete ingestion material (pdfs, bibs etc) for SigDial 2022. Could you please upload them here as well? @malihealikhani

**Comment by sabithsn** [comment]
Hi, Here is the link to the tar file:
https://drive.google.com/file/d/1fQyfrXb8X5Lpff8TfpAL5tTZ_OrDJO6i/view?usp=sharing

The pdfs, bibs etc are inside the cdrom folder. If you need anything else, please let us know,

**Comment by mjpost** [comment]
What date do you want these published?

**Comment by malihealikhani** [comment]
As soon as possible. Thanks!
Malihe

**Comment by xinru1414** [comment]
@mjpost for the video files, do we store them somewhere?

**Comment by mjpost** [comment]
@xinru1414 please

1. Name them using the Anthology IDs
2. Place them under `videos/sigdial/`

We should also add another `<video>` tag linking to our local copy, but we can do that in a separate PR. Just please make a note of it!
