### ISSUE TITLE
Canonical paths for attachments

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#216]
Currently hugo generates the complete nested path for attachments, e.g., http://anthology.aclweb.org/attachments/W/W18/W18-6319.Poster.pdf (e.g., from here: https://aclweb.org/anthology/W18-6319/). There are two issues with this:

- It makes it hard to move files around on the server
- It seems it should use the canonical host name + path instead of `anthology.aclweb.org`

Can we do something like https://aclweb.org/anthology/W18-6319.Poster.pdf instead? At the same time we can add a rule to the htaccess file that lets me point to where the file really is.

**Comment by mjpost** [comment]
(With this done, I could add `--delete` to the rsync command; I can't currently, since `attachments` is a symlinked folder in the target directory).

**Comment by mbollmann** [comment]
This should be as simple as changing [this line](https://github.com/acl-org/acl-anthology/blob/master/bin/anthology/data.py#L25) and (if the URL is no longer in hierarchical format) [its formatting here](https://github.com/acl-org/acl-anthology/blob/master/bin/anthology/utils.py#L80).

**Comment by mjpost** [comment]
Do you see any problems if I also change these URLs to HTTPS?

**Comment by mjpost** [comment]
Okay, with commit 0d29289cda279a4742f0e4f7a99cfe557280e51d, we are now using a canonical path for attachments, and the site is live with them.
