### ISSUE TITLE
Correction to Anthology ID 2022.lrec-1.804

### ISSUE THREAD

**Issue by jonfd** [acl-org/acl-anthology#2160]
Anthology ID: 2022.lrec-1.804
Link to the published paper: https://aclanthology.org/2022.lrec-1.804/

## Metadata correction

The name of the primary author is incorrect. It should be Jón Friðrik Daðason.

**Comment by mjpost** [comment]
If you want to edit the file `data/xml/2022.lrec.xml`, make the correction, and create a PR, we can merge this soon. Else it will be processed at the end of the month with October's corrections.
