### ISSUE TITLE
Correction to Anthology ID 2022.lrec-1.326

### ISSUE THREAD

**Issue by 10-Is-Mana** [acl-org/acl-anthology#2161]
## Metadata correction

https://aclanthology.org/2022.lrec-1.326.pdf
This revision corrects the last author's name; the first and the last name should be inversed. It should be as written in the following line: https://github.com/acl-org/acl-anthology/blob/3f1dbb15c008b0de1e7635acbc261b7bb71b2ae9/data/xml/2020.aacl.xml#L1291

**Comment by mjpost** [comment]
If you like, create a PR with the correction (in file `data/xml/2022.lrec.xml`). We can then process this right away. Otherwise, we will fix it and process it at the end of the month with October's corrections.
