### ISSUE TITLE
Add workshop links

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#2180]
Prior to 2020, workshops were automatically gathered under the "ws" venue tag, such that one could easily peruse all workshops in a given year (e.g., [2019](https://aclanthology.org/events/ws-2019/)). With 2020's new ID system, that linkage is no longer automatic, and while we seemed to do this for a bit in 2020, we haven't in 2021 and 2022. This removes a feature that some people have found useful.

We should go back and, for all main conference venues (NAACL, ACL, EMNLP, CoNLL, and COLING), add each workshop as joint with "ws" in `data/yaml/joint.yaml`.

**Comment by mjpost** [comment]
@xinru1414 can you pull this together when you have a moment?

**Comment by dowobeha** [comment]
Thanks! I encountered this today, when I was surprised to find my COLING workshop paper listed under COLING 2022 instead of WS.
