### ISSUE TITLE
Correction to Anthology ID 2022.coling-1.48

### ISSUE THREAD

**Issue by dxlong2000** [acl-org/acl-anthology#2183]
Hi, I am one of the authors of the paper: ```2022.coling-1.48``` (Xuan Long Do). I am also one of the authors of the paper ```2022.findings-acl.177``` (Do Long). It seems that 2 accounts are not linked together. Could you help to merge ```Xuan Long Do``` and ```Do Long``` to become ```Xuan Long Do```?

Thanks!

**Comment by dxlong2000** [comment]
Hi @xinru1414, so far I haven't seen they were merged yet, may I know if you fixed the issue?

https://aclanthology.org/people/d/do-long/
https://aclanthology.org/people/x/xuan-long-do/

Thanks!

**Comment by dxlong2000** [comment]
Hi @xinru1414, have you fixed it successfully? Thanks!

**Comment by mjpost** [comment]
This has been fixed and will be merged as part of October's corrections at the end of the month.

**Comment by dxlong2000** [comment]
Hi Mr. @mjpost , I still haven't seen the 2 pages merged yet. Do you have any suggestions?

https://aclanthology.org/people/d/do-long/
https://aclanthology.org/people/x/xuan-long-do/

**Comment by mjpost** [comment]
We may have missed this correction. But you can do it yourself if you like: edit data/xml/2022.findings.xml, find your name and correct it, and create a PR. We can then handle it immediately. 

Otherwise we will fix it and process it at the end of the month.

**Comment by dxlong2000** [comment]
Dear @mjpost, please help me to fix it and process it at the end of this month. Thank you very much!

Best regards,

**Comment by mjpost** [comment]
@xinru1414 can you fix this?

**Comment by dxlong2000** [comment]
Hi @xinru1414, please help me on this matter.

Thanks!

**Comment by mjpost** [comment]
@xinru1414 actually the metadata on https://aclanthology.org/2022.findings-acl.177/ should be fixed to "Do Xuan Long". I suspect this didn't get merged because the first/last portions are not lined up correctly (but haven't checked).

@dxlong2000 sorry for the very long delays on this.

**Comment by dxlong2000** [comment]
@mjpost @xinru1414 Much appreciate your help, thanks very much!! I am waiting to see the merge updated on the https://aclanthology.org/people/x/xuan-long-do/!

**Comment by mjpost** [comment]
@dxlong2000 Is this preview correct? https://preview.aclanthology.org/feb-23-correction/people/x/xuan-long-do/

If so, and if you want to expedite the fix, you can create your own PR with the same fix in @xinru1414's push referenced above. Then I can approve and merge right away. Else it will happen at the end of the month.

**Comment by dxlong2000** [comment]
> @dxlong2000 Is this preview correct? https://preview.aclanthology.org/feb-23-correction/people/x/xuan-long-do/
> 
> If so, and if you want to expedite the fix, you can create your own PR with the same fix in @xinru1414's push referenced above. Then I can approve and merge right away. Else it will happen at the end of the month.

Yes I think it is correct. Thank you very much. I’ll wait for the end of this month
