### ISSUE TITLE
Correction to Anthology events - coling-2022 & crac (CRAC workshop in COLING 2022)

### ISSUE THREAD

**Issue by nash2000** [acl-org/acl-anthology#2184]
Dear anthology directors, 

Thank you again for ingesting our COLING 2022 proceedings to anthology. 

But, our workshop organizers checked the proceedings and found that one workshop is missing and a title of CRAC workshop should be changed.

In other words, here are the original requests for these aforementioned workshops:  
---------------------------------------------------------------------------------------------------------------------------------------------------------
7.  CRAC_2022: Proceedings of the 5th Workshop on Computational Models of Reference, Anaphora and Coreference (CRAC 2022)
    venue code: crac
    details: exists

21. CRAC2022-COREF: Proceedings of the CRAC 2022 Shared Task on Multilingual Coreference Resolution
    venue code: crac (this is the shared track of CRAC, so it should belong to CRAC workshop)
    volume name: crac-coref
    details: exists
---------------------------------------------------------------------------------------------------------------------------------------------------------
However, the resulting ingested proceedings do not fully reflect the above requests, for some reasons. 

So, we would like to make correction requests, as follows.
--------------------------------------------------------------------------------------------------------------------------------------------------
1) Could you please change the workshop title of CRAC 2022 below such that it becomes the fifth one (currently, it is the fourth one)
https://aclanthology.org/volumes/2022.crac-1/ 

2) Could you add the missing workshop with the subdirectory "CRAC2022-COREF" for "Proceedings of CRAC 2022 Shared Task on Multilingual Coreference Resolution"
using "crac-coref" as venue or volume names? 
--------------------------------------------------------------------------------------------------------------------------------------------------

We are sorry for making this request again. But, we are really appreciate if you fix the issues by Oct 14 AoE if possible, before the CRAC 2022 workshop begins.

Thank you, 
Best regards,

Seung-Hoon Na

**Comment by nash2000** [comment]
Dear anthology directors, 

Our workshop oragnizsers found that the following workshop (i.e Argument Mining) is also missing. 

==========================================================================
14.  AM_2022: Proceedings of the 9th Workshop on Argument Mining
    venue code: argmining
    details: exists
==========================================================================
We guess that the proceedings of this workshop are separatedly submitted later, so not being included finally.
 
Could you please add the above workshop too, by Oct 15 AoE, if possible, before the CRAC 2022 workshop begins? 

Thank you,
Best regards,

Seung-Hoon Na

**Comment by xinru1414** [comment]
@nash2000, 1) CRAC 2022  is updated to fifth. 2) Workshop argmining and the CRAC 2022 Shared Task on Multilingual Coreference Resolution proceedings were ingested: 

https://aclanthology.org/volumes/2022.argmining-1/
https://aclanthology.org/volumes/2022.crac-mcr/ 
 
They were not linked to the COLING page. I just fixed that as well. 

These changes should be reflected on anthology soon.

**Comment by xinru1414** [comment]
@mjpost for `Proceedings of CRAC 2022 Shared Task on Multilingual Coreference Resolution` -- it's clearly a shared task, not a workshop. Do shared tasks get linked in the joint yaml file?

**Comment by mjpost** [comment]
Yes, it gets added to the joint file because it was colocated with that event.
