### ISSUE TITLE
Correction to Anthology ID 2022.coling-1.520

### ISSUE THREAD

**Issue by Husamx** [acl-org/acl-anthology#2185]
## Option 2: Revision or erratum

*Please add the following information*

- :white_check_mark: I have attached the revised PDF or erratum to this issue
- :white_check_mark: I have written a brief description of the changes below

> This revision corrects typos in Figure 3 and Table 1. 
> - In the plots in Figure 3, the label “RWR” should be “C-BERT” to match its reference in the text – there is no reference for RWR in the text. Following the feedback from the reviewers, we renamed RWR to C-BERT and although we reflected the necessary changes in the text, we missed out on the plots. 
>
>- In Table 1, there is a typo in the task name: DBpedia-2 should be DBpedia.

[2022.coling-1.520_fixed.pdf](https://github.com/acl-org/acl-anthology/files/9765347/2022.coling-1.520_fixed.pdf)

**Comment by Husamx** [comment]
@xinru1414 Hi, an update on this would be much appreciated. Thank you!

**Comment by mbollmann** [comment]
@Husamx We process corrections once a month, at the end of the month.

**Comment by Husamx** [comment]
@xinru1414 @mbollmann Can you please let me know when the corrections will be reflected on the ACL website?
When I select pdf, I still get the old version (without the corrections).
https://aclanthology.org/2022.coling-1.520/

**Comment by xinru1414** [comment]
The corrected pdf is already on the website https://aclanthology.org/2022.coling-1.520v2.pdf, but the xml file wasn't updated. Should be good by the end of Nov.

**Comment by Husamx** [comment]
@xinru1414 @mjpost this issue hasn't been fixed yet. The webpage https://aclanthology.org/2022.coling-1.520/ still links to the old pdf. Please mark this urgent as it's been 2 months since I opened this issue

**Comment by mjpost** [comment]
Hi, I see two different PDFs. I suggest you refresh your browser cache?

**Comment by Husamx** [comment]
@mjpost can see it now, thank you!
