### ISSUE TITLE
Correction to Anthology ID 2022.wnut-1.21

### ISSUE THREAD

**Issue by maihoangdao** [acl-org/acl-anthology#2186]
## Option 1: Metadata correction

Please change the name of the first author "Mai Dao" to "Mai Hoang Dao".

**Comment by xinru1414** [comment]
@maihoangdao Could you provide your first name and last name separately please?

**Comment by maihoangdao** [comment]
@xinru1414  hi, thank you for fixing the issue, but this issue has been open for 14 days and is still pending. Who could I contact to merge the commit?

**Comment by mbollmann** [comment]
@maihoangdao We merge all corrections in a batch at the end of each month.
