### ISSUE TITLE
Correction to Anthology ID 2022.fieldmatters-1.8

### ISSUE THREAD

**Issue by dowobeha** [acl-org/acl-anthology#2188]
## Option 1: Metadata correction

DOI at the bottom of the PDF links to a different paper

**Comment by xinru1414** [comment]
@dowobeha Thank you for pointing this out.  @mjpost we can't modify neither of these (pdf and DOI), correct? Any suggestions?

**Comment by mjpost** [comment]
This happens sometimes that workshop organizers add a DOI link, which is always incorrect. We could reingest the complete proceedings if the organizers regenerated.

**Comment by xinru1414** [comment]
Contacted COLING organizers, waiting on response.
