### ISSUE TITLE
Wrong DOI in papers of CODI-CRAC 2022 Shared Task proceedings

### ISSUE THREAD

**Issue by maciej-ogrodniczuk** [acl-org/acl-anthology#2197]
Dear Editors,

I have just noticed that papers from the Proceedings of the CODI-CRAC 2022 Shared Task on Anaphora, Bridging, and Discourse Deixis in Dialogue](https://aclanthology.org/volumes/2022.codi-crac/) have wrong DOIs in the citation stamp (on the first page of the article), all pointing to a RANLP 2019 paper. Could you please remove them?

Best,
Maciej (CRAC 2022 organizer)

**Comment by mbollmann** [comment]
The PDFs are not modified by us in any way. We can replace them if we get an updated version from you or your publication chair(s).

**Comment by xinru1414** [comment]
@maciej-ogrodniczuk in case you missed the comment.

**Comment by maciej-ogrodniczuk** [comment]
I was just a humble messenger who noticed this problem, I don't even have access to CODI-CRAC shared task at SoftConf. Carolyn Rose (who was responsible for preparing the proceedings for the CODI-CRAC shared task) sent the modified tarball to Francis Bond and Seung-Hoon Na on Oct 19 so it is probably fixed already in the system. Can you check it in SoftConf and regenerate the proceedings in the ACL anthology if DOI links were removed?

**Comment by mbollmann** [comment]
Thanks, got it. We don't typically have access to SoftConf for each event. The publication chairs/organizers export their data from SoftConf and generate the proceedings; we just ingest them afterwards. So it's really the publication chairs/organizers who'd need to take action here. If you could ping them and direct them to this issue, and they can provide us with updated files, we can fix it in the Anthology.

**Comment by maciej-ogrodniczuk** [comment]
Carolyn sent me the tarball from SoftConf – I hope this is all you need to close this issue. I took a look inside and the DOI links are removed from papers. Here is the link: http:://mozart.ipipan.waw.pl/~maciek/proceedings.tgz
