### ISSUE TITLE
Docker Container with minimal install

### ISSUE THREAD

**Issue by cfedermann** [acl-org/acl-anthology#22]
**S/N:** 23
**Priority:** Low
**Title:** Docker Container with minimal install
**Proposer:** Nitin Madnani
**Notes:** In progress

**Comment by CTNLP** [comment]
I was under the impression this was done now. Should this issue still be open?

**Comment by knmnyn** [comment]
#28 was from when I was taking charge of the Anthology. I think @mjpost has a different prioritization for Docker.

**Comment by mjpost** [comment]
My impression was this was mostly needed for managing the dependency chain for the Rails app, right? Or were there further uses planned for it?

**Comment by knmnyn** [comment]
Hi Matt, all:

You're right it was originally for the difficult problem of the setup of
the Anthology app.  We had also envisioned having a network of Anthology
mirrors so that we can distribute the materials and not have a single point
of failure.

**Comment by mbollmann** [comment]
With the static rewrite, the required dependencies for generating the site will probably be much more manageable. What's more, we can probably just offer an archive of the fully generated site as a source for mirroring.

However, static rewrite doesn't mean we can't have any server-side components at all, like scripts getting called or database interaction. I'm not yet sure to what extent this will be needed.

**Comment by mjpost** [comment]
My vision here is that the hosting server will pull from the repo each night and regenerate the site, in an entirely automated fashion. We could easily make available a Docker container to do that if there were interest in hosting local mirrors.

The issue with mirroring entirely is that the entire site (with all PDFs) is about 35 GB. Not monstrous, but not small, either.

**Comment by mbollmann** [comment]
FWIW, the entire site *without* the PDFs and attachments is at 112 MB (compressed) now.

However, full mirroring including the PDFs and attachments is not as trivial as pull & build, since the URLs for those [are hardcoded in `bin/anthology/data.py`](https://github.com/acl-org/acl-anthology/blob/master/bin/anthology/data.py). I would need to make those relative or configurable somehow before full mirroring is possible.

**Comment by mjpost** [comment]
Yes, right. I think this issue is a low priority.

**Comment by akoehn** [comment]
We currently don't need a docker container and I see no reason why this should change in the future.  The relevant aspects of mirroring are better discussed in other issues such as #295.
