### ISSUE TITLE
Correction to Anthology ID 2022.acl-long.243

### ISSUE THREAD

**Issue by arendu** [acl-org/acl-anthology#2200]
Name correction for  Anthology ID 2022.acl-long.243

## Option 1: Metadata correction

The correction has been name in this PR: #2199 
The PR fixes the author name to be inline with the PDF.

**Comment by xinru1414** [comment]
@arendu Thank you for the PR!

**Comment by arendu** [comment]
Thanks for the quick approval! @mjpost and @xinru1414
