### ISSUE TITLE
Correction to Anthology ID 2020.acl-tutorials.1

### ISSUE THREAD

**Issue by boknilev** [acl-org/acl-anthology#2206]
# Instructions

**Please be sure to add the Anthology ID in the Issue title**

Please review [our correction policy](https://aclanthology.org/info/corrections/),
then fill out the information below.

## Option 1: Metadata correction

Multiple people have been asking for the tutorial slides. Please add the attached slides (a PDF) as metadata, so that people can access them. 

[slides.pdf](https://github.com/acl-org/acl-anthology/files/9820568/slides.pdf)

**Comment by xinru1414** [comment]
@mjpost Could you remind me how to process this?

**Comment by mjpost** [comment]
This is not metadata but an attachment. Grep for `<attachment` in some of the older (maybe 2015) ACLs. Make sure to use an appropriate type (e.g., "slides") and follow the naming convention.

**Comment by boknilev** [comment]
Yes, I couldn't find instructions on how to open an issue for adding attachments, so metadata seemed like the closest thing. I hope this can still be done.

**Comment by mjpost** [comment]
No problem. @xinru1414 there is also a script, add_attachment.py

**Comment by xinru1414** [comment]
followed convention [here](https://aclanthology.org/attachments/P19-4001.Presentation.pdf)
