### ISSUE TITLE
Correction to Anthology ID 2022.coling-1.148

### ISSUE THREAD

**Issue by entslscheia** [acl-org/acl-anthology#2212]
## Option 2: Revision or erratum

Revised PDF: 
[COLING22_camera_ready_revised.pdf](https://github.com/acl-org/acl-anthology/files/9848985/COLING22_camera_ready_revised.pdf)

Brief description:
> This revision corrects numbers on WebQSP in Table 2(c).

**Comment by xinru1414** [comment]
See #2211 as welll
