### ISSUE TITLE
Volume bibs

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#222]
We used to create volume-level bibs, which is often convenient, e.g., https://aclanthology.coli.uni-saarland.de/volumes/17th-annual-meeting-of-the-association-for-computational-linguistics.bib. 

It seems with the static rewrite we no longer do this. Can we (easily?) restore this? But using the ACL IDs, e.g., https://aclweb.org/anthology/P18-1.bib.

**Comment by mbollmann** [comment]
We do, actually: https://aclweb.org/anthology/volumes/P18-1.bib

I'm a bit surprised though that it doesn't seem to be linked from anywhere. Maybe an oversight. I should add this into the volume page template.

**Comment by mbollmann** [comment]
Actually just a minor logic error in the template. PR soon.

**Comment by mjpost** [comment]
It looks like we are still not displaying full-volume bibs. For example, no link here:

https://aclweb.org/anthology/events/acl-2018/

Is this an easy fix?
