### ISSUE TITLE
https certificates are expired on https://aclanthology.org

### ISSUE THREAD

**Issue by treitmaier** [acl-org/acl-anthology#2222]
#### Issue description
The certificate for aclanthology.org expired on Wed, 26 Oct 2022 15:56:27 GMT

#### Steps to reproduce the issue
Visit https://aclanthology.org/

#### What's the expected result?
https://aclanthology.org/

A secure connection to the website

#### What's the actual result?
An insecure connection and warning of a potential security risk.

#### Additional details / screenshot
<img width="833" alt="Screenshot 2022-10-28 at 14 29 24" src="https://user-images.githubusercontent.com/1515455/198611219-94f09767-98e1-4332-945a-ca8af535c01c.png">

**Comment by mjpost** [comment]
Thanks for reporting—I've submitted an internal ticket and will close this when the issue is resolved.
