### ISSUE TITLE
Correction to Anthology entity linking for “Huy Nguyen”

### ISSUE THREAD

**Issue by manning** [acl-org/acl-anthology#2226]
The page for for Huy Nguyen:

https://aclanthology.org/people/h/huy-nguyen/

wrongly merges multiple people. I guess “Huy Nguyen” is the “John Smith” of Vietnamese. 

The 2003 and 2004 publications that I am on are for one Huy T Nguyen, who is not author of any of the other publications. All the publications with Diane Litman are from Huy Viet Nguyen, who was at U. Pittsburgh and then went to Amazon. So it seems reasonable to assume the 2022 publication is also his.

https://people.cs.pitt.edu/~huynv/publications.html
https://openreview.net/profile?id=~Huy_V._Nguyen1

While I don’t know the other facts as solidly, from the dates and coauthor relationships, the best hypothesis is that the 2002 and 2019 paper Huy Nguyen’s are from a third and fourth person that are neither of the above.

**Comment by xinru1414** [comment]
@manning Thanks for the insight! 

@mjpost The author for [the 2019 paper](https://aclanthology.org/W19-4450/) has left liulishuo. I couldn't track down the author for [the 2002 paper](https://aclanthology.org/C02-1041/) either. I will link other authors to their correct papers.

**Comment by mjpost** [comment]
Thanks for the report and quick split. @xinru1414 can you expand the comments (and possibly also the ids) in the name variants file? I'm afraid pgh etc are too opaque.
