### ISSUE TITLE
Ingestion Request: TLT (2023-03-07)

### ISSUE THREAD

**Issue by ddakota** [acl-org/acl-anthology#2228]
Venue identifier: TLT
Website: https://cl.indiana.edu/tlt2023/
Volume title: Proceedings of the 21st International Workshop on Treebanks and Linguistic Theories
SIG: SIGPARSE
Submission date: 15 November 2022
Desired publication date: 7 March 2023

**Comment by ddakota** [comment]
Here is the link to the tgz file for ingestion: https://drive.google.com/drive/folders/1WKj-8syDQpBRP4lMtDKEGnk3H83uBvfr?usp=sharing

I would like to bring up that when the proceedings are compiled, the resulting pdf has an issue in the Outline sidebar where everything is "templatetitle'  and it is unclear why this is the output and we assume it has something to o with the pdf metadata. This is also seen when creating the output proceeedings for the provided sigdial example in the repo. If this is something that can be fixed on our side due to a configuration we are not using, please let us know. The same problem exists for #2229, #2230, and #2231.

**Comment by ddakota** [comment]
It is the actual proceedings.pdf file provided in each output tgz. But if this is not ingested, then perhaps not does not matter?

**Comment by xinru1414** [comment]
@ddakota thanks for the clarification, it shouldn't be an issue!

**Comment by nschneid** [comment]
@ddakota if you used the code from https://github.com/acl-org/ACLPUB, you could ask there about the TEMPLATETITLE issue. (I guess it shouldn't block the Anthology publication though—we can always update the 4 proceedings PDFs later.)

**Comment by ddakota** [comment]
@nschneid The current recommended code for OR is actually https://github.com/rycolab/aclpub2

**Comment by nschneid** [comment]
Oh I see. Then it's rycolab/aclpub2#138
