### ISSUE TITLE
Ingestion Request: CxGs+NLP 2023

### ISSUE THREAD

**Issue by ddakota** [acl-org/acl-anthology#2231]
Venue identifier: CxGs+NLP
Venue name: Workshop on Construction Grammars and NLP
Website: https://sites.google.com/view/cxgsnlpworkshop
Volume title: Proceedings of the First International Workshop on Construction Grammars and NLP
SIG: SIGPARSE
Submission date: 15 November 2022
Desired publication date: 7 March 2023

This is a new venue in ACL anthology and will require confirmation on venue identifier.

**Comment by nschneid** [comment]
Thanks @ddakota. To clarify, this, #2230, #2229, and #2228 are all bundled under the same event—[GURT 2023](https://gurt.georgetown.edu/gurt-2023/) (which has no main session, just these 4 workshops).

**Comment by xinru1414** [comment]
@nschneid thank you for the clarification. 

@mjpost could you confirm the venue identifier? 

@ddakota please submit ingestion material by Feb 21st, 2023 for the desired publication date.

**Comment by mjpost** [comment]
The venue identifier for Anthology ID purposes will be  cxgsnlp. CxGs+NLP will be displayed on web pages.

**Comment by ddakota** [comment]
Here is the link to the tgz file for ingestion: https://drive.google.com/drive/folders/1WKj-8syDQpBRP4lMtDKEGnk3H83uBvfr?usp=sharing

**Comment by xinru1414** [comment]
@ddakota Not sure if this is true for the other three workshops, but for CxGs+NLP at least, all paper abstracts are missing in the ingestion material (specifically, in the `papers.yml` file). Detailed requirement see [acl pub2](https://github.com/rycolab/aclpub2). Could you fix this (and other workshops if applicable)?

**Comment by ddakota** [comment]
@xinru1414 This has been fixed and new versions updated
