### ISSUE TITLE
Correction to Anthology page https://aclanthology.org/sigs/sigann/

### ISSUE THREAD

**Issue by DetmarM** [acl-org/acl-anthology#2240]
On the sigann webpage https://aclanthology.org/sigs/sigann/ the link to the [Website of SIGANN](http://www.cs.vassar.edu/sigann/)
when clicked results in a "403 forbidden" error.

**Comment by nschneid** [comment]
The new website is https://sigann.github.io/

**Comment by DetmarM** [comment]
Right, but someone with the relevant permissions needs to update the page  https://aclanthology.org/sigs/sigann/  which one gets to from the main acl anthology page https://aclanthology.org/ when clicking on ANN in the SIGs listing.

**Comment by xinru1414** [comment]
@nschneid thanks for the pointer!
