### ISSUE TITLE
Correction to Anthology 2022.acl-long.587

### ISSUE THREAD

**Issue by PumpkinPieTroelf** [acl-org/acl-anthology#2248]
## Option 1: Metadata correction

The Anthology page links "data" to SNLI, which is not used in the paper. Instead the paper introduces two new datasets. They can be found on [HuggingFace saf_micro_job_german](https://huggingface.co/datasets/JohnnyBoy00/saf_micro_job_german) and [saf_communication_networks_english](https://huggingface.co/datasets/JohnnyBoy00/saf_communication_networks_english)

**Comment by mbollmann** [comment]
Thanks for the issue. This has to be corrected on the Papers with Code website (https://paperswithcode.com/paper/your-answer-is-incorrect-would-you-like-to-1), as we automatically sync this information from them.
