### ISSUE TITLE
Ingestion request: LDK (2023-09-13)

### ISSUE THREAD

**Issue by anacastrosalgado** [acl-org/acl-anthology#2251]
Dear Sirs,

I'm Ana Salgado, the Proceedings Chair of LDK 2023 – 4th Conference on Language, Data and Knowledge.
I'm writing to register our intention to submit our proceedings. Below, you will find the information needed:

**Venue Identifier:** LDK
**Volume Title:** ​Proceedings of the 4th Conference on Language, Data and Knowledge (LDK)
**Sub-Volumes Title:** 
Proceedings of the 4th Conference on Language, Data and Knowledge (LDK): Long Papers
Proceedings of the 4th Conference on Language, Data and Knowledge (LDK): Short Papers
Proceedings of the 4th Conference on Language, Data and Knowledge (LDK): Workshops/Tutorials
**Venue Name:** Conference on Language, Data and Knowledge
**Website:** http://2023.ldk-conf.org/
**Publication date:** 12 September 2023

Waiting for your approval,
Ana Salgado

**Comment by mjpost** [comment]
Looks good. @xinru1414 will process when you have a proceedings ready.

**Comment by anacastrosalgado** [comment]
@mjpost and @xinru1414 Hello! I have a doubt and I was wondering if you could help me. The LDK proceedings are going to be published as part of ACL Ontology. Will the proceedings be automatically indexed by Thompson Web of Knowledge or/and Scopus?

**Comment by mjpost** [comment]
SCOPUS indexing isn't automatic, and is something we only handle for main ACL conferences, unfortunately. You can contact Seza Doğruöz if you have questions.

**Comment by anacastrosalgado** [comment]
@mjpost Thanks, Matt. I will try to contact Seza Doğruöz.

**Comment by anacastrosalgado** [comment]
@mjpost As I made this request, I think ​you can assume that the proceedings could appear as part of ACL events; or not? I'm asking this concerning ISBN issues.
Thanks again.

**Comment by anacastrosalgado** [comment]
@xinru1414 Here I found information about ISBN Numbers: If you need to assign ISBN numbers, please provide the exact titles of each volume to be assigned an ISBN and forward this information to Priscilla Rasmussen, ACL Business Manager.
Do you have the contact of Priscilla Rasmussen?

**Comment by anacastrosalgado** [comment]
@mjpost I try to contact Jennifer Rachford, but there needs to be a contact. Can you help me, please?

"If you plan to publish or print your proceedings, you will need an ISBN. The ACL can provide these for *ACL conferences. Please provide the exact titles of each volume to be assigned an ISBN and send this information to Jennifer Rachford."

**Comment by mjpost** [comment]
Hi @anacastrosalgado—The Anthology will host your materials, but we are not the publisher. As a result I don't think that we can assign ISBNs.

**Comment by anacastrosalgado** [comment]
@mjpost Dear Matt, the data folder of the LDK Proceedings is available on:
https://drive.google.com/file/d/1VK3yRVBgyvCGa1nacaMVtg98oz1QQ-wW/view?usp=drive_link
Should I send it to anyone else?

**Comment by mjpost** [comment]
Thanks! @anthology-assist, can you process this?

**Comment by anacastrosalgado** [comment]
@anthology-assist Hi! Do you have any updates about these proceedings? Thanks.

**Comment by mjpost** [comment]
Hi @anacastrosalgado, can you clarify? The desired publication date is September 12, right? You can see the preview [here](https://preview.aclanthology.org/ldk-23-ingestion/volumes/2023.ldk-1/).

**Comment by anacastrosalgado** [comment]
@mjpost Great, Matt! I want to be sure that everything is all right. Thanks a lot.

**Comment by anacastrosalgado** [comment]
@mjpost  and @anthology-assist , the venue is not correct here:
https://preview.aclanthology.org/ldk-23-ingestion/venues/loresmt/
Will you change this? The venue must be: LDK 2023 or LDK.

**Comment by anacastrosalgado** [comment]
@mjpost  and @anthology-assist : The words with diacritics need to appear better.  How can we fix this?

**Comment by anacastrosalgado** [comment]
@mjpost Dear Matt, I thought that the proceedings would be published this week. Do you have any updates?

**Comment by mjpost** [comment]
Hi @anacastrosalgado, if you look at the comment thread on the PR #2756, you can see that there are problems with the material that was delivered to us. The encoding is not correct. It should be UTF-8 encoded for proper ingestion.

**Comment by anacastrosalgado** [comment]
@mjpost  I will introduce some corrections sent by the authors, and then, I will fix the data and send it UTF-8 encoded.

**Comment by mjpost** [comment]
Thanks, @anacastrosalgado. Any progress on this?

**Comment by illlp** [comment]
@mjpost We gave one week for authors to send corrections. I know what I did wrong in the submission, so I will resubmit the data when I'm done with the modifications. I'm counting on sending you the folder next week. Is that OK?

**Comment by anacastrosalgado** [comment]
We gave one week for authors to send corrections. I know what I did wrong in the submission, so I will resubmit the data when I'm done with the modifications. I'm counting on sending you the folder next week. Is that OK?

**Comment by anacastrosalgado** [comment]
@mjpost Dear Matt, the data folder of the LDK Proceedings (FINAL VERSION) is available on:
[](https://drive.google.com/drive/folders/1Jo0FXoEkI1FY5I5TBu7EIKXzxoi00abH)

The data files are UTF-8 encoded now.

**Comment by anacastrosalgado** [comment]
Any news? I'm seeing the internal preview here: https://preview.aclanthology.org/ldk-2023-ingestion/volumes/2023.ldk-1/

**Comment by mjpost** [comment]
It's merged and should be live soon.

**Comment by anacastrosalgado** [comment]
Thanks!
