### ISSUE TITLE
Front matter from ACL conferences are missing and full proceedings links broken

### ISSUE THREAD

**Issue by dtraum** [acl-org/acl-anthology#226]
The conferences don't seem to have links to front matter material. While I agree that these should not appear like regular papers, they are extremely useful information for tracking the history of conference and include important information relating to the papers themselves, such as acceptance rate.
For many conferences, these can be retrieved from the full volume, but this seems unnecessarily burdensome, compared to providing a direct link to a much shorter file. Also some conferences full volume links are broken, e.g. 1987, 88, 93,...
https://www.aclweb.org/anthology/P87-1
https://www.aclweb.org/anthology/P88-1
https://www.aclweb.org/anthology/P93-1

**Comment by mbollmann** [comment]
> The conferences don't seem to have links to front matter material.

Judging from the live website, journals seem to (erroneously) list front matter entries, while all other proceedings (erroneously) do not. This looks like a mistakenly flipped boolean value in the code to me; I'll investigate that. (For now, front matter should indeed show up like a regular paper, although this could of course be improved.)

I don't know anything about the broken full volume links, unfortunately.

**Comment by mbollmann** [comment]
Update: Yep, the first issue was just a missing `not` in the code... \*sigh\*... Thanks for noticing!

**Comment by mjpost** [comment]
We do not have PDFs for the front matter from many old proceedings and journals. It would be nice to not print a link for these. Even better, it would be great to recover them somehow—maybe some old-timer still has the proceedings on their shelf?

**Comment by dtraum** [comment]
I’m a little confused - the previous message from marcel seemed to indicate this was a bug that was fixed? I don’t see any changed or pdfs for front-matter from even fairly recent years. I’m pretty sure a lot of these used to be in the anthology.

I have 87 and 89- fairly recent on my shelf, could scan if needed.

—David

Dr. David R. Traum                     email: traum@ict.usc.edu<mailto:traum@ict.usc.edu>
USC/ICT                                      phone: +1 (310) 574-5729
12015 Waterfront Drive                  fax: +1 (310) 574-5725
Playa Vista, CA 90094        http://www.ict.usc.edu/~traum

On Mar 28, 2019, at 7:50 PM, Matt Post <notifications@github.com<mailto:notifications@github.com>> wrote:


We do not have PDFs for the front matter from many old proceedings and journals. It would be nice to not print a link for these. Even better, it would be great to recover them somehow—maybe some old-timer still has the proceedings on their shelf?

**Comment by mjpost** [comment]
Hi David—he pushed the change to the repo, but the site hasn't been rebuilt yet.

That would be *really great* if you could scan missing front matter and send them to me as PDFs. I will then put them in place posthaste.

**Comment by dtraum** [comment]
Sure, just tell me what’s missing. But note that I was right and this stuff used to be there - see the wayback machine, e.g.:
https://web.archive.org/web/20060310063244/http://acl.ldc.upenn.edu/

I found from 87 (my oldest) and older conferences, so it’s probably easier to recover these files than rescan.

best,

—David

Dr. David R. Traum                     email: traum@ict.usc.edu<mailto:traum@ict.usc.edu>
USC/ICT                                      phone: +1 (310) 574-5729
12015 Waterfront Drive                  fax: +1 (310) 574-5725
Playa Vista, CA 90094        http://www.ict.usc.edu/~traum

On Mar 28, 2019, at 8:21 PM, Matt Post <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi David—he pushed the change to the repo, but the site hasn't been rebuilt yet.

That would be really great if you could scan missing front matter and send them to me as PDFs. I will then put them in place posthaste.

**Comment by mjpost** [comment]
Oh, the file is still there: https://www.aclweb.org/anthology/P87-1000

The convention is that front matter gets ID 00 (or 000), so P87-1000. The full volume gets 1, so P87-1. What's missing are the complete volumes, but that's not a problem.

These links will get generated when I rebuild the site.

**Comment by mjpost** [comment]
I rebuilt the site, and the links are now visible, e.g., https://www.aclweb.org/anthology/P93-1000.

**Comment by mbollmann** [comment]
> What's missing are the complete volumes, but that's not a problem.

Well, except for broken links appearing on the site. Since the PDFs are not part of the build process I can't check for them, but it would be good to either hide them or produce the full proceedings PDFs where they are missing.

**Comment by mjpost** [comment]
We could script a quick one-time check for missing volume PDFs. Is there an easy way to encode their absence in the XML?

**Comment by mbollmann** [comment]
Isn't it simpler to just `pdf-stapler cat P87-1???.pdf P87-1.pdf` and provide them to users?

**Comment by mjpost** [comment]
That's smarter. I just emailed you the file list. Whoever gets to the it first can do it.

**Comment by aryamccarthy** [comment]
Bump—this also applies to L16 (LREC 2016).

**Comment by mjpost** [comment]
I'm not sure there's any point to providing a single-volume PDF at all, and in particular if there wasn't one made available when published. Commit #324 now corrects the mistake of printing PDF links when there was no PDF, so I'm going to close this out. If someone finds this important and wants to take it up, we can reopen it.
