### ISSUE TITLE
Correction to Anthology ID 2021.findings-emnlp.64

### ISSUE THREAD

**Issue by kellymarchisio** [acl-org/acl-anthology#2264]
The video linked to this paper is not the correct one.  https://aclanthology.org/2021.findings-emnlp.64.mp4 appears to actually be paper 2021.findings-emnlp.210.

**Comment by xinru1414** [comment]
@mjpost @davidstap I'm wondering if more papers have the same issue. Any input?

**Comment by davidstap** [comment]
We spot-checked a lot of video/paper matches. Not sure what went wrong here. I’ll fix this and will investigate.

**Comment by kellymarchisio** [comment]
Hi there - any update on this one?

**Comment by davidstap** [comment]
Hi, I’ll fix this on Sunday.

**Comment by davidstap** [comment]
I did some more checks for EMNLP 2021 (Findings) videos, and did not find any additional mismatches. @kellymarchisio can you share a link to the video if you still have it? If not I'll contact Underline.

**Comment by kellymarchisio** [comment]
I actually cannot find it, so it would be great if you could contact
Underline

**Comment by davidstap** [comment]
I received the video and matched it to your paper. Thanks for the heads-up!

**Comment by kellymarchisio** [comment]
Excellent, thank you, David!
