### ISSUE TITLE
Feature: create a proper package

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#2301]
It would be nice to turn the files under `bin/anthology` into a proper Python package. This would involve, at minimum:

* Rearranging the files under a root `anthology/` folder
* Creating installation scripts
* Adding proper versioning

**Comment by mbollmann** [comment]
Duplicate of #913? And see discussion there.

**Comment by mjpost** [comment]
Oh, yes, should have at least searched first.
