### ISSUE TITLE
Correction to Anthology ID 2022.constraint-1.4

### ISSUE THREAD

**Issue by jayeshbankoti007** [acl-org/acl-anthology#2315]
There were 2 co-authors for the given paper as mentioned: Jayesh Bankoti and Ludovic Kun are both the first co-authors of the paper. I have mentioned that with asterisks in the Paper. 
Can we please update the metadata to match the authors' contribution to the paper?

**Comment by xinru1414** [comment]
@jayeshbankoti007 the meta data author order matches the paper pdf author order. Meta data can't reflect the co-author detail.
