### ISSUE TITLE
EMNLP 2022 Proceedings

### ISSUE THREAD

**Issue by lck042** [acl-org/acl-anthology#2326]
Hi, when will the EMNLP 2022 Formal Proceedings be published? Currently, it is only available in the preview version and cannot be found within this link https://aclanthology.org/. Thanks!

**Comment by xinru1414** [comment]
We are waiting on the correct ingestion material for the main volume and findings volume, and several other workshops.

**Comment by habernal** [comment]
Any news regarding this issue?

**Comment by akoehn** [comment]
Follow this pull request, it has all the relevant updates from our side: https://github.com/acl-org/acl-anthology/pull/2283
