### ISSUE TITLE
Ingestion request

### ISSUE THREAD

**Issue by anacastrosalgado** [acl-org/acl-anthology#2337]
Dear Sirs, 
1) I created a ticket on 21st November registering our intention to submit our proceedings for LDK2023:
[(https://github.com/acl-org/acl-anthology/issues/2251)]

2) We also want to confirm if the last version of the ACL Paper Styles is here:
[(https://github.com/acl-org/acl-style-files)]

Thanks in advance.
Ana Salgado

**Comment by mjpost** [comment]
Yes, those should be the latest style files.

Closing as duplicate of #2251.
