### ISSUE TITLE
Bug report: Missing demo and industry papers for EMNLP 2022

### ISSUE THREAD

**Issue by chywang** [acl-org/acl-anthology#2340]
#### Issue description

Missing demo and industry papers for EMNLP 2022.

See https://preview.aclanthology.org/emnlp-22-ingestion/events/emnlp-2022/.

![image](https://user-images.githubusercontent.com/8896039/212102315-94ac857f-02d9-42bf-abed-f9fc2e54994f.png)

**Comment by akoehn** [comment]
This is not a bug, you are looking at an (internal) preview of an incomplete pull request. There are no proceedings for emnlp 2022 yet.
