### ISSUE TITLE
Bug report for https://aclanthology.org/2021.inlg-1.8/

### ISSUE THREAD

**Issue by anantkha** [acl-org/acl-anthology#2343]
I have this paper published in 2021, till now it is discoverable on google scholar as HTML doc and not PDF, however, the Arxiv version is discoverable as pdf. Also, i am not able to add this to my profile as ACL proceedings but instead i am keeping this as HTML doc which is not discoverable when trying to add proceedings paper as main doc.

**Comment by anantkha** [comment]
Paper Link: https://aclanthology.org/2021.inlg-1.8/

**Comment by mjpost** [comment]
Unfortunately, we don't have control over third-party indexing services.
