### ISSUE TITLE
Correction to Anthology ID 2022.gem-1.21

### ISSUE THREAD

**Issue by amarfurt** [acl-org/acl-anthology#2350]
# Metadata correction
Our paper has the wrong title in the metadata on the [anthology preview](https://preview.aclanthology.org/emnlp-22-ingestion/2022.gem-1.21/). The PDF is correct. The correct title is: Unsupervised Token-level Hallucination Detection from Summary Generation By-products

**Comment by amarfurt** [comment]
#2283 is now merged, and our paper still has the wrong title and citation information. Can it be fixed now?

**Comment by amarfurt** [comment]
If it is just about fixing the xml, I took a stab at this in PR #2375 
@xinru1414 maybe more needs to be done? For example, is the anthology.bib automatically generated from the xml or do I need to correct the bibkey there as well?

**Comment by akoehn** [comment]
It just the xml that needs to be changed, the bibtex files are generated from that info. Will enable the wf in your pr, thx!

**Comment by amarfurt** [comment]
Thank you!
