### ISSUE TITLE
Ingestion: PACLIC 2022

### ISSUE THREAD

**Issue by ditas19** [acl-org/acl-anthology#2354]
Hello!

I am Dr Shirley Dita, the conference chair of PACLIC 36 (2022). I would like to submit the proceedings of PACLIC 2022 to ACL Anthology:

Here's the link to the PACLIC2022 Proceedings: https://drive.google.com/file/d/1d4up2eJIyvzGX2-GspcDUMT0CfeX6_op/view?usp=share_link

Thank you!

**Comment by mjpost** [comment]
Hi @ditas19, can you post the full material? If not, we will close this issue.

**Comment by ditas19** [comment]
Hi!We have spotted some lapses in the former version. My team will send next week.Many thanks,S.-- SHIRLEY N. DITA, Ph.D.Chair & Associate ProfessorDepartment of English and Applied Linguistics (DEAL)Br. Andrew Gonzalez FSC College of Education (BAGCED)De La Salle University2401 Taft Avenue, Manila 1004, PhilippinesTels: (63) 2 8524-4611 to 26 loc. 530Mobile: (63) 917 812-3482 (DITA)Sent from my iPhoneOn Feb 25, 2023, at 5:03 AM, Matt Post ***@***.***> wrote:﻿
Hi @ditas19, can you post the full material? If not, we will close this issue.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

DISCLAIMER AND CONFIDENTIALITY NOTICE The information contained in this e-mail, including those in its attachments, is confidential and intended only for the person(s) or entity(ies) to which it is addressed. If you are not an intended recipient, you must not read, copy, store, disclose, distribute this message, or act in reliance upon the information contained in it. If you received this e-mail in error, please contact the sender and delete the material from any computer or system. Any views expressed in this message are those of the individual sender and may not necessarily reflect the views of De La Salle University.

**Comment by anthology-assist** [comment]
@ditas19 any updates on the material?

**Comment by ditas19** [comment]
Hi! Here's the link to the PACLIC2022 Proceedings: https://drive.google.com/drive/folders/1k1Ea_fFNxo_aMBonjSfr0G9k7cOCnCDF

**Comment by ditas19** [comment]
I hope you find everything in order.

**Comment by tattoi** [comment]
Hi, this is Nathaniel.  I am helping @ditas19 compile the proceedings.  Here is the updated package: [link](https://drive.google.com/drive/folders/1k1Ea_fFNxo_aMBonjSfr0G9k7cOCnCDF?usp=share_link).  The organizers used EasyChair for submission management.

**Comment by anthology-assist** [comment]
@tattoi @ditas19 Looks like paclic 2022 has already been ingested: https://aclanthology.org/volumes/2022.paclic-1/. Are there any problems?

**Comment by anthology-assist** [comment]
Closing due to lack of response from the submitter.
