### ISSUE TITLE
Correction to Anthology ID 2022.cogalex-1.1

### ISSUE THREAD

**Issue by norahollenstein** [acl-org/acl-anthology#2357]
Metadata correction:

The DOI in the PDF of this paper leads to a different paper (https://aclanthology.org/2022.cogalex-1.1.pdf).
This is the incorrect DOI: https://doi.org/10.26615/978-954-452-056-4_001

**Comment by mbollmann** [comment]
We can't change the content of PDFs, unfortunately. If the workshop organizers can provide a corrected version of the PDF, we can re-ingest it.
