### ISSUE TITLE
IWPT 2013 proceedings

### ISSUE THREAD

**Issue by andreasvc** [acl-org/acl-anthology#236]
It says the IWPT 2013 proceedings were ingested, but the proceedings are not there.

It is listed as:
W13-56xx
Proceedings of the The 13th International Conference on Parsing Technologies (SIGPARSE)

However, W13-56xx is NODALIDA 2013 in the anthology.

I happen to have a copy of the proceedings around:
http://andreasvc.github.io/iwpt2013proceedings.pdf

What would it take to get it into the anthology?

**Comment by mjpost** [comment]
Thanks for reporting this. We can split the PDF if need be and import it, but we really need the original bibtex files, which are then converted into XML. Do you have the original BibTeX as well?

**Comment by andreasvc** [comment]
I don't have the original BibTeX, but I have emailed someone who might.
Is it an issue of data entry, or are there particular pieces of information you need from it?
If the former, I volunteer to do the data entry. I assume you mean a file like https://aclweb.org/anthology/volumes/W11-29.bib

**Comment by mjpost** [comment]
Yes, we can import from BibTeX. But our authoritative storage format is actually XML, e.g., 

    https://github.com/acl-org/acl-anthology/blob/2de24587ea9ed6e6868d3c6224767c286fc9d001/data/xml/W05.xml#L2944

We have scripts that will consume BibTeX and turn it into this XML. IWPT is small enough that perhaps it could just be done by hand.

I don't know if you're the person to ask this, but it would also be nice to import IWPT 1989 to 2003. Do you know if digital files exist for these?

**Comment by andreasvc** [comment]
I entered the data in the XML format:
https://gist.github.com/andreasvc/0d9e09cec6c8fd20475da5b29fe0977a

I assigned the first available ID to the papers, i.e., W13-57xx.
For the first entry (with the preface and TOC etc.), I entered page numbers 1-6 but in the PDF there are roman numerals.
Let me know if you need anything else.

I don't have access to any other unpublished IWPT proceedings.

**Comment by mjpost** [comment]
Thank you, this is great! Do you want to create this as a pull request against [W13.xml](https://github.com/acl-org/acl-anthology/blob/2de24587ea9ed6e6868d3c6224767c286fc9d001/data/xml/W13.xml)? That way it would record you as the contributor.

Do you have time to split up the PDF? The style is:

- Full volume: W13-57.pdf
- Front matter: W13-5700.pdf
- Paper 1: W13-5701.pdf
- etc.

(You should of course feel free to say no, but otherwise this will get queued, and I may not have time to get to it for some time.)

**Comment by andreasvc** [comment]
I did the PR. I also updated the gist to fix the XML and add a split script. The resulting splitted PDFs are here: [iwpt2013.zip](https://github.com/acl-org/acl-anthology/files/3077213/iwpt2013.zip)

What's missing from these files is PDF metadata and an official ACL footer on the bottom of the first page, but I assume this might be automated?

**Comment by mjpost** [comment]
Thanks a ton for this! The site is now rebuilding and should be in place soon.

What do you mean by PDF metadata?

There is code for stamping PDFs in https://github.com/acl-org/ACLPUB. I can queue this up, but if you find time to figure it out and do it, it will help to expedite it.

**Comment by andreasvc** [comment]
PDF metadata is author, title, year, etc. info stored inside the file, read by tools like citation managers:
```
$ pdfinfo W13-0801 
Title:          A Semantic Evaluation of Machine Translation Lexical Choice
Subject:        SSST 2013
Keywords:       
Author:         Marine Carpuat
[...]
```

Such data can be set by `hyperref` when going from tex to pdf.
`pdftk` can update the information in a PDF file.

I'll leave the stamping of the PDFs to someone else, I don't feel like diving into Perl/sh scripts.
