### ISSUE TITLE
Ingestion request: DiscAnn 2021

### ISSUE THREAD

**Issue by kdekuthy** [acl-org/acl-anthology#2361]
Dear ACL anthology chairs,

last year we sent a request that we would like to submit the proceedings of our 2021 workshop on "Integrating Perspectives on Discourse Annotation” to the ACL anthology. It took longer than expected to collect all papers for the proceedings from the workshop participants. We have now arranged the DiscAnn proceedings into the ACLPUB format, and the tar file with the complete data directory can be found here: http://www.sfs.uni-tuebingen.de/~kdk/data.tar

We very much hope that our proceedings can still be published on the ACL anthology site.

Best,

Kordula De Kuthy and Detmar Meurers

**Comment by mjpost** [comment]
Hi, can you provide more information? Where was the workshop held? Was it colocated with a larger venue? Is there a web page associated with your venue?

**Comment by kdekuthy** [comment]
The workshop was originally planned to be part of the ESSLLI 2020 summerschool, but was then postponed and took place at the University of Tübingen on October 4-5th 2021, the workshop website is https://discannworkshop.github.io/
 The original information that I sent to the ACL anthology about our workshop can be found in the attached here: 
https://docs.google.com/spreadsheets/d/16IQdrmCn4qqPXQuhr1uppdYsQnyWXk2XcyKrSaTfKeM/edit#gid=0

Best,

Kordula

**Comment by kdekuthy** [comment]
Yes, that is what we did. We arranged all papers of our proceedings into one volume in the ACLPUB format as described in the anthology documentation using the template provided there. We put the end result in a data directory which can be found here: http://www.sfs.uni-tuebingen.de/~kdk/data.tar

Best, Kordula
