### ISSUE TITLE
Missing EMNLP 2022 items

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#2363]
Open issues on missing items, awaiting delivery from EMNLP organizers.

- [x] ~Full-volume PDF for main~ (we're skipping this)
- [ ] Frontmatter (missing for both findings and main): https://aclanthology.org/2022.emnlp-main.0
- [ ] Full-volume PDF for Findings (currently corrupted): https://aclanthology.org/2022.findings-emnlp
- [ ] Attachments for main and Findings
- [x] Complete industry volume
- [x] Complete system demonstrations volume
- [x] Author affiliation metadata
- [x] DOIs (#2420)

**Comment by xinru1414** [comment]
For the main conference tutorial volume, author affiliation information was not provided.

**Comment by xinru1414** [comment]
@mjpost should we ingest EMNLP DOIs for the published portion?

**Comment by jangoepfert** [comment]
@mjpost @xinru1414 Can you please add the DOIs? The conference was held 7 months ago. Without DOIs, the papers are not properly indexed, which will have a significant affect on their reach and citation.

**Comment by jantrienes** [comment]
I noticed TSAR is not listed as colocated workshop on the EMNLP contents and also does not have DOIs, yet. https://aclanthology.org/volumes/2022.tsar-1/

**Comment by mjpost** [comment]
Thanks @jantrienes: #2751.

**Comment by janmbuys** [comment]
Could the frontmatter / full volume for EMNLP Findings 2022 please be added? The current links give broken PDFs. I require this information so that our publication can "count" for my university.

**Comment by silviatti** [comment]
Hi, any updates on this? I would also need the pdf of the full volume.

**Comment by mespla** [comment]
Hi, I am in the same situation. I already tried contacting the editors of the proceedings, but got no response. I really need the front matter of the proceedings for my University...

**Comment by mjpost** [comment]
I just pinged the pub chairs again. There will not be a full volume—it's 12,000 pages long—but I am hoping we can post the front matter.
