### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#239]
I am unable to access aclweb.org at the moment, and the Anthology was similarly unavailable for a period of time about a week ago. Is there some sort of regular server maintenance period that users should plan around, or is this unexpected downtime?

**Comment by mjpost** [comment]
I didn’t notice last week, but also cannot access it now. I’ve sent an email to our web admin.

**Comment by mjpost** [comment]
It’s back up. If this happened last week, too, then perhaps it’s a weekly maintenance thing. I’ll post here if I hear back.

**Comment by mbollmann** [comment]
It happened April 2 around 14:30 UTC. I know because colleagues immediately messaged me. ;)

Apparently it was resolved within 10-15 minutes though.

**Comment by davidweichiang** [comment]
I thought I saw it happen intermittently over a much longer period of time.

**Comment by mjpost** [comment]
It seems that our hosting provider (Bluehost) goes down from time to time but usually comes back up with ten minutes or so. The ACL IT team is looking at alternatives but the earliest we'd switch is June. I'll close this for now.
