### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by kdonnay** [acl-org/acl-anthology#2406]
*Use this issue template to help file your issue.
Please delete portions of this textthat are not relevant, and feel free to change it or add sections.*

#### Issue description

Dear editors,

I am writing on behalf of a team of authors of a paper that was accepted to the Findings of the 2022 EMNLP conference (https://aclanthology.org/volumes/2022.findings-emnlp/) but has so far not appeared in the ACL Anthology. 

We have already contacted the editors, Yoav Goldberg and Yue Zhang, a few weeks back but other than a first acknowledgment that they will check back what the problem might be, have not heard anything.

The paper in question is:
Ana Kotarcic, Dominik Hangartner, Fabrizio Gilardi, Selina Kurer and Karsten Donnay. (2022). Human-in-the-Loop Hate Speech Classification in a Multilingual Context. In _Findings of the Association for Computational Linguistics: EMNLP 2022_, Abu Dhabi, United Arab Emirates. Association for Computational Linguistics.

Please advise on how this problem will be addressed. 

With thanks,
Karsten

**Comment by mbollmann** [comment]
You were correct to contact the EMNLP editors; from the side of the ACL Anthology, we cannot do anything to resolve this issue, as we do not act as editors and only archive & publish material that is given to us by conference and journal editors.

I hope they will be able to resolve this issue soon!

**Comment by mjpost** [comment]
Yes, I am sorry, but there is nothing we can do. We only host data that is delivered to us by conference chairs. I suggest you continue to email the EMNLP program chairs. You might also try contacting [SIGDAT](https://sigdat.org), which runs EMNLP.

**Comment by kdonnay** [comment]
Thanks a lot Marcel and Matt, I appreciate your prompt responses!

In that case I’ll recontact the editors once again but this has already been dragging on without resolution for weeks. Never had this issue before and find it pretty incomprehensible. And thanks for the suggestion to contact SIGDAT, we will definitely do that if this doesn’t resolve soon.

Thanks again, I really appreciate all of your and your colleagues work on the ACL Anthology.
