### ISSUE TITLE
DOI for EMNLP 2022 papers

### ISSUE THREAD

**Issue by emnlp2022doi** [acl-org/acl-anthology#2420]
Given items for EMNLP 2022 are unlikely to be completed anytime soon, can we get DOIs for the published papers first? That could be essential for indexing and getting the papers to be seen in many platforms.

**Comment by emnlp2022doi** [comment]
@xinru1414 hi, may I ask if the DOIs will be ready soon?

**Comment by emnlp2022doi** [comment]
@anthology-assist I suggest ingesting DOIs first as this might have effects on the reach of the papers and citations. By now, some researchers likely have already skipped certain papers in year 2022 of EMNLP and moved on to other conferences.

**Comment by jangoepfert** [comment]
I would like to echo the suggestion of @emnlp2022doi. Could you please add DOIs to the papers? The conference was held 6 months ago. Without DOIs, the papers are not properly indexed, which will have a significant affect on their reach and citation.

**Comment by mjpost** [comment]
We had a number of issues with our account that have now been resolved. This should be done soon: see #2721.
