### ISSUE TITLE
Ingestion request: COMPUTEL-6 workshop proceedings

### ISSUE THREAD

**Issue by Aditi138** [acl-org/acl-anthology#2421]
Venue identifier: computel
Volume title: Proceedings of the Sixth Workshop on the Use of Computational Methods in the Study of Endangered Languages (COMPUTEL-6)
Data: https://drive.google.com/file/d/1KASOuu7XuSoqgcDTtIzLRAhAUUTqG1tC/view?usp=share_link

**Comment by xinru1414** [comment]
@Aditi138 Could you let us know the desired publish date?

**Comment by Aditi138** [comment]
Hello, we would like to get this published at the earlier actually (if its possible) as the workshop is starting today only.

**Comment by Aditi138** [comment]
@xinru1414 We actually had some edits in the proceedings, could you please use the data in this link: https://drive.google.com/file/d/1ORTzc9p49Ql4po2LoTmytzLL49VOvs4J/view?usp=sharing.

**Comment by xinru1414** [comment]
Updated, please follow #2422
