### ISSUE TITLE
Remove abstract from bib files

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#243]
I think we should remove abstracts from BibTeX files. Thoughts?

I think I argued for the opposite before, thinking it would help with indexing, but I now think that having the abstracts on the HTML pages, together with everything under one site, is sufficient. Abstracts in bibs aren't helpful and often get in the way.

**Comment by mbollmann** [comment]
I'm not sure I agree. I've used JabRef as a citation manager for a while, which is based on bib files, and having abstracts in your citation manager can be a useful thing. I also fail to see how they might "get in the way" - can you elaborate?

**Comment by mjpost** [comment]
I just mean it takes longer to page through a buffer of citations in emacs, and that fewer references fit in the screen at a time. It's a minor inconvenience in that setting where the abstract is also not useful. I suppose the situation is different if you're using a more full-featured citation management system.

**Comment by nschneid** [comment]
Sounds good to me once we get HTML importers working properly. Right now the Zotero importer is getting the abstract from the BibTeX but not the HTML.

**Comment by danielgildea** [comment]
I like my bibtex short and sweet.

**Comment by knmnyn** [comment]
+1 @danielgildea @nschneid @mjpost .  It is useful to have a version with the full abstract and all of the other metadata that *could* go in, but I agree that the standard (only?) version should not contain extraneous fields.

**Comment by mbollmann** [comment]
I made this change in a branch; @mjpost, feel free to PR and merge if you think this should be implemented.

**Comment by mjpost** [comment]
I have been thinking about this and do find myself preferring a thinner bibtex.

Does the ‘copy to bibtex’ button still include the abstract? That could be a nice way to effect a compromise.

I have also been thinking of publishing our YAML paper files as a sort of hidden API. These are easy to parse and people could write tools around them.

**Comment by mbollmann** [comment]
> Does the ‘copy to bibtex’ button still include the abstract?

No, the template simply reads the contents of the generated .bib file for this, so they will always match. I could add the BibTeX to the YAML and read it from there, which would allow different treatment. But I'm not sure this behaviour would be useful or intuitive, I can already see the bug issues being filed for this... :)

**Comment by akoehn** [comment]
We could store both the bibtex with abstract and the one without (foo.bib and foo-wa.bib), have some small button somewhere like "Settings: include abstract in bibtex" which sets a cookie and then a js one-liner to change the bibtex links to "-wa.bib" if that cookie is set.

I like abstracts as it makes searching easier.  (As @mjpost I use emacs, but with ebib and helm-bibtex.)

**Comment by mjpost** [comment]
I think we have a working solution on this, so I'm closing it out.

**Comment by jabalazs** [comment]
Hi!

Is there an easy way to obtain the full anthology as a bibtex including the abstracts? As @akoehn mentioned, having the abstracts makes searching easier.

**Comment by mjpost** [comment]
You could clone the repo, change [this line](https://github.com/acl-org/acl-anthology/blob/14ceeee008343f7d9c60079564a3cc71f3ac3507/bin/create_bibtex.py#L83) to

```
                        file_full.write(contents)
```

and run `make`.

I wonder though if we should generate both `anthology.bib.gz` and `anthology+abstracts.bib.gz` in the build, for people who want this.

**Comment by jabalazs** [comment]
Thank you for the quick response!

I'm pretty sure some people would find it useful to be able to download the `anthology+abstracts.bib.gz` file, without having to clone the repo and build the site 😄
