### ISSUE TITLE
Mistake in bibtex

### ISSUE THREAD

**Issue by rgalhama** [acl-org/acl-anthology#246]
(I am posting this as a github issue, as I've been asked in previous e-mail communication)
---

I have found a problem in the bibtex file associated to my publications in ACL Anthology: my name should appear as Raquel G. Alhama (not Raquel Garrido Alhama). 

This affects the following publications:

1) https://aclweb.org/anthology/papers/W/W16/W16-1909.bib

2) https://aclweb.org/anthology/papers/D/D17/D17-1174.bib

Could you please change it? 

Thank you.

**Comment by davidweichiang** [comment]
Done -- if your START profile still has your name as "Raquel Garrido Alhama," please update it so that it's written the way you want it to appear in the future. Thanks!
