### ISSUE TITLE
[2023-08-10] Ingestion Request: FinNLP-2023

### ISSUE THREAD

**Issue by ChunJiChen** [acl-org/acl-anthology#2460]
(1) Venue Identifier: finnlp

(2) Volume Title: Proceedings of the Joint Workshop of the 5th Financial Technology And Natural Language Processing (FinNLP) and the 2nd Multimodal AI For Financial Forecasting (Muffin)

More details: 
(a) The full title: Joint Workshop of The 5th Financial Technology And Natural Language Processing (FinNLP) And 2nd Multimodal AI For Financial Forecasting (Muffin)

(b) The publishing date: August 10th, 2023

(c) Event Type: non-ACL event. (In conjunction with IJCAI-2023)

(d) Workshop Site: https://finnlp-muffin-ijcai23.github.io/

(e) Conference Management Tool: EasyChair

(f) Submission Site: https://easychair.org/conferences/?conf=finnlpmuffin2023

(g) The proceedings of the prior workshop: https://aclanthology.org/venues/finnlp/

**Comment by anthology-assist** [comment]
@ChunJiChen Could you please follow instructions [here](https://aclanthology.org/info/contrib/) section `Submit your data` to submit the conference material?

**Comment by ChunJiChen** [comment]
The data of FinNLP-2023 workshop proceedings is uploaded to the following link: https://drive.google.com/file/d/1bZSSpvV6pIzIV9p66rqSF8ObxkBFf9WJ/view?usp=sharing

I already checked the submitted data with "Sanity check." It shows, "This script doesn't do anything yet. So you're all good!" Please let me know if there are any problems.

If the data is ok, could you make it live anytime before August 18th, please?

**Comment by ChunJiChen** [comment]
Hi @anthology-assist 

May I know the expected time that our proceedings will be officially available on ACL Anthology?

**Comment by ChunJiChen** [comment]
Hi @anthology-assist, 

Thank you so much for your help. 

After the page was available, we checked the pages and noticed that the papers' (1-6, 1-7, 1-8, and 1-9) authors on the pages were not correct. 

Apologize that it's a problem from my side. The bib of these 4 papers was generated incorrectly. 

I corrected the full bib (FinNLP-2023.bib) and the data in the bib folder. I also made a revised "FinNLP_data.tgz", which contains all the revised data. (Google Drive: https://drive.google.com/drive/folders/1YcsF7jIfd2bGZZtFqat7nJ70aZqXe5RR?usp=sharing)

Could you help us to upload the proceedings again, please?

**Comment by ChunJiChen** [comment]
Dear Prof. Post (@mjpost), 

I'm sorry that we found some errors after we saw that page for our proceedings. 

Could you help us upload the proceedings with the new data, please?

Please let me know if we need to follow other procedures. Thank you, and I apologize again.
