### ISSUE TITLE
title page and table of contents of EMNLP 2022

### ISSUE THREAD

**Issue by phoenixsecularbird** [acl-org/acl-anthology#2462]
When will the title page and table of contents of EMNLP 2022 be available?

**Comment by anthology-assist** [comment]
@phoenixsecularbird do you mean [this page](https://aclanthology.org/events/emnlp-2022/) ?

**Comment by phoenixsecularbird** [comment]
yes, I want some file like this https://aclanthology.org/2021.emnlp-main.0.pdf

**Comment by nschneid** [comment]
The front matter. The Anthology will add it when it is delivered by EMNLP. See #2363 (any updates will be posted there).
