### ISSUE TITLE
Ingestion Request: ICON-2018

### ISSUE THREAD

**Issue by singhakr** [acl-org/acl-anthology#2467]
(1) Venue Identifier: icon

(2) Volume Title: Proceedings of the 15th International Conference on Natural Language Processing (ICON-2018)

More details:

(a) The full title: Proceedings of the 15th International Conference on Natural Language Processing (ICON-2018)

(b) Publishing date: April 13th, 2019

(c) Event Type: non-ACL event

(d) Conference Site: [https://ltrc.iiit.ac.in/icon2018]

(e) Conference Management Tool: Microsoft CMT

(f) Submission Site: [https://cmt3.research.microsoft.com/ICON2018]

(g) Proceedings of prior conferences: [https://aclanthology.org/venues/icon]

The compiled proceedings based on the conventions followed till 2017 or 2018 for ACL Anthology have been shared with the editorial team in a Google Drive folder. I can rename the files according to the new conventions if necessary.

**Comment by singhakr** [comment]
I had shared it on email. It seems the mail was missed. Should I send again by email or share a link, say, of Google Drive folder?

**Comment by singhakr** [comment]
> I had shared it on email. It seems the mail was missed. Should I send again by email or share a link, say, of Google Drive folder?

Or it may be that I have the wrong or older email id.

**Comment by singhakr** [comment]
Thank you.

**Comment by mjpost** [comment]
Just bumping this @anthology-assist

**Comment by anthology-assist** [comment]
@singhakr Sorry about the delay. I've looked at the ingestion material and found that it's missing some key files such as `meta`, and the `pdf` and `bib` files should be under `cdrom` folder.  Specific details see: https://acl-org.github.io/ACLPUB/anthology.html

Could you recompile the ingestion material?

**Comment by singhakr** [comment]
I don't have access to the conference submission site and I don't even have a backup as it was many years ago. In any case, submission was through Microsoft CMT. I had compiled earlier ICON proceedings (before 2020) using Perl aclpub code that I had from 2008, which now only seems to work on a MacBook, which I don't have now.

However, if the only problems are those mentioned (meta and the cdrom folder), I can do that easily. Will that work?

**Comment by mjpost** [comment]
That should be sufficient. For the ACLPUB format, we just need the meta file and the cdrom directory with the .bib and (watermarked) .pdf files.

**Comment by singhakr** [comment]
Are the HTML and CSS files also needed inside the cdrom directory? I noticed in the sample proceedings given on GitHub that these files are not present in the cdrom directory.

**Comment by anthology-assist** [comment]
@singhakr The HTML and CSS files are not needed.

**Comment by singhakr** [comment]
I have corrected the ICON-2018 proceedings for ingestion in ACL Anthology and have shared the Google Drive link by email. I have also corrected the file names and URL in BibTeX entries to match the current convention as far as possible. Could you please check if it is OK?
