### ISSUE TITLE
Ingestion request ALTA 2023 (30th Nov to 1st Dec)

### ISSUE THREAD

**Issue by xuqiongkai** [acl-org/acl-anthology#2469]
G'day,

We are preparing the proceedings for the ALTA 2023 conference.

The conference title is *Proceedings of the 20th Annual Workshop of the Australasian Language Technology Association*. The venue identifier is *alta*.

The conference will happen on 30th Nov 2023 (Thursday) to 1st Dec 2023 (Friday). We would like to negotiate the publication date 29th Nov (one day before the ALTA conference starts).

Thank You,
Qiongkai Xu

**Comment by mjpost** [comment]
Hi, this sounds good, thanks. Please let us know when you have the material.

**Comment by xuqiongkai** [comment]
> Hi, this sounds good, thanks. Please let us know when you have the material.

We have collected all the paper, meta data and compiled the proceedings for the conference. How should I proceed to the next step?

**Comment by anthology-assist** [comment]
@xuqiongkai Could you share the drive link here?

**Comment by xuqiongkai** [comment]
Here is the Github repo we worked on.
https://github.com/xuqiongkai/ALTA23-proceedings
The meta data for the papers are collected in 'paper.yml' and all papers
are under the 'papers' folder.
If other information is needed, please feel free to let me know.

Best regards,
Qiongkai Xu

anthology-assist ***@***.***> 于2023年12月21日周四 06:54写道：

**Comment by anthology-assist** [comment]
@xuqiongkai Could you share a zipped file including all ingestion material?

**Comment by xuqiongkai** [comment]
Here is the zip file for our working project.
Please let me know if you want other information.
[ALTA23-proceedings.zip](https://github.com/acl-org/acl-anthology/files/13802603/ALTA23-proceedings.zip)

**Comment by anthology-assist** [comment]
@xuqiongkai I'm not seeing the `proceedings` folder in the material you submitted. Could you double check our guideline here: https://acl-org.github.io/ACLPUB/anthology.html?

**Comment by xuqiongkai** [comment]
The whole file `ALTA23-proceedings.zip` is a single `proceedings` folder, which can be compiled by aclpub2.

The meta conference information is in `conference_details.yml`.
The paper information is in `papers.yml`.

**Comment by anthology-assist** [comment]
@xuqiongkai  Thank you for the clarification, I was under the impression that you are using aclpub (instead of aclpub2).

I do see the `conference_details.yml` and the `papers.yml` file. However the `watermarked_pdf` folder (which contains all watermakred paper pdfs), the `attachments` folder and the `inputs` folder are missing.

Could you double check the information on the aclpub2 page https://github.com/rycolab/aclpub2 ? Please let me know if anything is unclear.

**Comment by xuqiongkai** [comment]
We have no attachments, so the 'attachments' folder is missing.
I assume 'inputs' folder is the place to put all papers, they are under 'papers' folder.

Aclpub2 (w. minor twists for a better template) was used to compile this project. I followed the 'no_papers' example, so the definitions of some folders are quite free.

**Comment by xuqiongkai** [comment]
Hi, Thanks for following up this issue.

We have no attachments, so the 'attachments' folder is missing. I assume
'inputs' folder is the place to put all papers, they are under 'papers'
folder.
Aclpub2 (w. minor twists for a better template) was used to compile this
project. I followed the 'no_papers' example, so the definitions of some
folders are quite free.

Best regards,
Qiongkai Xu

anthology-assist ***@***.***> 于2024年2月10日周六 14:10写道：

**Comment by mjpost** [comment]
Hi—you should run [this script](https://github.com/acl-org/acl-anthology/blob/master/bin/aclpub2_format_check.py) to check that your output is correctly formatted.

**Comment by xuqiongkai** [comment]
Thanks Matt, now I see the expected structure. The script seems to require
watermarked pdf to pass the test, is it mandatory? If so, where can I find
the tool to watermark the papers? Otherwise, can I copy the original files
to this folder?

Matt Post ***@***.***> 于2024年2月12日周一 00:30写道：

**Comment by xuqiongkai** [comment]
Hi Matt, I have fixed the issues and structured the folders.
 ALTA23-proceedings-ACL-Anthology.zip
<https://drive.google.com/file/d/1XNd7xJKpa1YuZjMlMGtk_Osk1YhIRmHU/view?usp=drive_web>
It is larger than the limitations so attached to Google Drive.
Please check and let me know if it does not work.

qiongkai xu ***@***.***> 于2024年2月12日周一 10:24写道：
