### ISSUE TITLE
Correction to Anthology ID 2021.scil-1.9

### ISSUE THREAD

**Issue by sidharthranjan** [acl-org/acl-anthology#2470]
We had raised this [issue](https://github.com/acl-org/acl-anthology/issues/2458#issue-1643697870) to revise the current PDF on the ACL Anthology. However, the request PDF has not been updated and GitHub issue also was closed stating that the issue has been resolved. 

Further message: https://github.com/acl-org/acl-anthology/issues/2458#issuecomment-1497317040

I would sincerely request you to look into it.

**Comment by anthology-assist** [comment]
@sidharthranjan I believe this has been addressed, please see [here](https://aclanthology.org/2021.scil-1.9v2.pdf)

**Comment by sidharthranjan** [comment]
@anthology-assist: Thank you! :+1:
