### ISSUE TITLE
Ingestion request: NSURL (2023-04-09)

### ISSUE THREAD

**Issue by icnlsp** [acl-org/acl-anthology#2475]
Venue Code: NSURL
Volume name: 1
Venue identifier: https://aclanthology.org/venues/nsurl/
Venue name: Proceedings of the third International Workshop on NLP Solutions for Under Resourced Languages (NSURL 2022) co-located with ICNLSP 2022
Venue URL: http://nsurl.org/
Date of publication: 30 April 2023

**Comment by abrahami** [comment]
Has this been published already?

**Comment by yotamnahum** [comment]
@icnlsp @anthology-assist 
I would also like to know when it will be published.

**Comment by mjpost** [comment]
Yes, it can be found here: https://aclanthology.org/volumes/2022.nsurl-1/
