### ISSUE TITLE
Correction to Anthology ID 2022.icon-main.37

### ISSUE THREAD

**Issue by Srijeyarankesh** [acl-org/acl-anthology#2477]
# Instructions

**https://aclanthology.org/2022.icon-main.37.pdf**

## Option 1: Metadata correction

*We would like to have the names of the author in metadata changed as per the author's names in the revised final camera ready version of our paper submission.*

## Option 2: Revision or erratum

- I have attached the revised PDF or erratum to this issue 
- I have written a brief description of the changes below 

> This revision contains the final camera ready version of the team's paper submission for ICON 2022 which was attached before the deadline got over. The paper published however, is not the final camera ready version but the initial draft. 
> The screenshot for the submission of camera ready version is attached below for the committee's reference.
![ICON snippet](https://user-images.githubusercontent.com/58742948/230946073-075c0317-3a6b-463b-ade9-acc1ba3fc583.PNG)
> The revision committee is requested to publish the revised edition of the paper.

[A Comprehensive study of Mahabharat using Semantic and Sentiment Analysis - Camera Ready (1).pdf](https://github.com/acl-org/acl-anthology/files/11191933/A.Comprehensive.study.of.Mahabharat.using.Semantic.and.Sentiment.Analysis.-.Camera.Ready.1.pdf)

**Comment by Srijeyarankesh** [comment]
Can the authors/repo owners kindly merge the change to master branch as soon as possible?

**Comment by mbollmann** [comment]
As a rule, corrections are merged into master collectively at the end of each month.

**Comment by Srijeyarankesh** [comment]
Thank you for the quick response @mbollmann .

**Comment by Srijeyarankesh** [comment]
@mbollmann Can you please provide an ETA as to when the changes will get merged? April has ended and still the changes haven't been merged
