### ISSUE TITLE
Ingestion request: nodalida (05-19-2023)

### ISSUE THREAD

**Issue by alumae** [acl-org/acl-anthology#2481]
I would like to register a new meeting for publiblishing in the ACL Anthology.

Venue identifier: nodalida
Volume title: Proceedings of the 24th Nordic Conference on Computational Linguistics (NoDaLiDa)
Desired publication date: May 19, 2023

**Comment by anthology-assist** [comment]
@alumae Thank you for your request. Please follow [instructions](https://aclanthology.org/info/contrib/) to submit your data.

**Comment by alumae** [comment]
Since we were using OpenReview for the conference, I used ACLPUB2 to compile the proceedings. The compressed 'output' directory in ACLPUB2 format is uploaded here: https://drive.google.com/file/d/1h6FZcka_Qio7Bi4HdR-0t531ExQkuDqj/view?usp=sharing

I have verified that the output directory can be ingested by the `bin/ingest_aclpub2.py` tool.
