### ISSUE TITLE
Ingestion request : TAL journal volumes from year 2006 - 2016

### ISSUE THREAD

**Issue by mcandito** [acl-org/acl-anthology#2483]
Hello,

This is an ingestion request for the last missing volumes of the TAL journal:

http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2006.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2007.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2008.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2009.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2010.zip
(year 2011 has been ingested already)
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2012.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2013.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2014.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2015.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2016.zip
(years from 2017 to 2021 already ingested)

You might consider handling the bug reported in #2478 first, but not mandatory if the bug takes time to handle.
Thanks
Marie

**Comment by mcandito** [comment]
Hello,
any update on this?
Thanks

**Comment by mcandito** [comment]
Hi @xinru1414 
was this request forgotten or is it just that you are overwhelmed??
Thanks
Marie

**Comment by mcandito** [comment]
Hi @mjpost @anthology-assist ,
was this request forgotten ?
I would appreciate some feedback about the timeline
Thank you!

**Comment by mjpost** [comment]
Hi @mcandito—sorry for the lack of response. We'll be in touch soon.

**Comment by mcandito** [comment]
Hello,
I'd like to remind you of this request.
I don't know how you proceed to prioritize all the requests,
when do you expect to be able to process this one??
Thanks

**Comment by mcandito** [comment]
Hello @mjpost @anthology-assist,
I'd like to remind you of this request.
I don't know how you proceed to prioritize all the requests,
when do you expect to be able to process this one??
Thanks

**Comment by mjpost** [comment]
@anthology-assist can you please comment when you're back online?

**Comment by anthology-assist** [comment]
Sorry about the delay. Please follow https://github.com/acl-org/acl-anthology/pull/2660.

**Comment by mcandito** [comment]
@anthology-assist thanks !

**Comment by mjpost** [comment]
@mcandito it would be good if you could follow the preview links and click around over the volumes to make sure everything looks okay.

**Comment by mjpost** [comment]
#2660
