### ISSUE TITLE
Ingestion of GURT/SyntaxFest 2023 paper videos 

### ISSUE THREAD

**Issue by lauren-lizzy-levine** [acl-org/acl-anthology#2484]
Hello!

As described in these instructions:
https://github.com/acl-org/acl-anthology/wiki/Ingesting-videos

We have the paper presentation videos uploaded to a Google Drive folder: 
https://drive.google.com/drive/folders/17t0__MEjnBdEmEOC1zKPHSoEiNfsHknN

Please let us know when you are done downloading the videos so we can take them down from Drive.

The folder also contains a tsv file (anthology_id.tsv) with the anthology_id of the papers, but we do not have the videos hosted anywhere externally, so the presentation_url column is blank.

Thank you!

**Comment by anthology-assist** [comment]
@lauren-lizzy-levine thank you for submitting the videos. We have downloaded them. Ingestion will take sometime.

**Comment by lauren-lizzy-levine** [comment]
Great, thank you!
