### ISSUE TITLE
Bug report - NoDaLiDa Conference missing from front page

### ISSUE THREAD

**Issue by jkkummerfeld** [acl-org/acl-anthology#2506]
#### Issue description

The NoDaLiDa conference appears in the anthology (https://aclanthology.org/venues/nodalida/), but I do not see a way to reach it from the homepage of the anthology.

#### Proposed solution

Adding a row in the "Non-ACL Events" table for it.

Note - I am happy to put together a PR for this, I just didn't want to work on it before confirming this is the right solution.

**Comment by mbollmann** [comment]
While we have the current front page (it's really becoming a liability especially with the addition of more and more venues...), this would be the desired solution, yes. If you could do a PR this would be awesome!

**Comment by jkkummerfeld** [comment]
In the process of looking into this, I have realised there are a range of cases. For example, the 2020, 2022, and 2023 WiNLP workshops are showing on the Workshop pages, but the 2021 one isn't.

Looking at the repository, it seems like workshops should have a line in their xml metadata that is "<venue>ws</venue>" and they should also appear in the `[year].ws.xml` file. Is that correct? If so, I can write a script to check for inconsistencies and prepare a PR that makes all of these accessible.

**Comment by mbollmann** [comment]
NoDaLiDa has been added to the front page. #4123
