### ISSUE TITLE
Ingestion Request: {NoDaLiDa 2023 Workshop RESOURCEFUL}

### ISSUE THREAD

**Issue by sdobnik** [acl-org/acl-anthology#2516]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

~nodalida~
resourceful

### Volume Title

Proceedings of the Second Workshop on Resources and Representations for Under-Resourced Languages and Domains (RESOURCEFUL-2023)

### Venue Name (only if you are submitting a new venue)

~Nordic Conference of Computational Linguistics (NoDaLiDa)~
Workshop on Resources and Representations for Under-Resourced Languages and Domains

### Venue Website (only if you are submitting a new venue)

~https://www.nodalida2023.fo~
https://resourceful-workshop.github.io/resourceful-2023/

### Date of Publication

2023-05-19

### Supporting Information

This workshop is a part of the Nordic Conference of Computational Linguistics (NoDaLiDa).

**Comment by anthology-assist** [comment]
@sdobnik Please submit ingestion material following instructions here https://aclanthology.org/info/contrib/

**Comment by nilinykh** [comment]
We have used OpenReview for the conference and, accordingly, used ACLPUB2 to generate the proceedings. You can download the 'output' folder here:

https://gunet-my.sharepoint.com/:u:/g/personal/nikolai_ilinykh_gu_se/EY3uwPbRugBIp6tm8Otws4QB8gEFgPRvpo871318og-3BQ?e=TGgcf2

I have tried to verify the ingestion by running ``bin/ingest_aclpub2.py``, but it kept giving the following message to me:

> event name should start with Workshop or The Workshop, instead it started with The Workshop

This does not look like an error to me - the event name already starts with 'The Workshop'.

Let me know if you need more information or have any questions.

**Comment by nilinykh** [comment]
There is a minor edit to the watermarked PDFs - the signature on the bottom of the first page of each paper was not formatted properly. It exceeded the borders; check uploaded papers at https://preview.aclanthology.org/nlp4call-ingestion/volumes/2023.resourceful-1/

This is fixed now; here are the new watermarked PDFs formatted properly. Could you re-upload them?

https://gunet-my.sharepoint.com/:u:/g/personal/nikolai_ilinykh_gu_se/EVQNE6pBA-tNpGtliIeXok4BTF47Gxm6hUCeOJnWZ59RjQ?e=ha7fKx
