### ISSUE TITLE
[Documentation] How does search work?

### ISSUE THREAD

**Issue by evanmiltenburg** [acl-org/acl-anthology#252]
Using the search function, it's not clear what the different options do.

<img width="269" alt="Screen Shot 2019-04-12 at 09 14 02" src="https://user-images.githubusercontent.com/1513355/56018850-876f1580-5d03-11e9-9ff1-c28463b546a5.png">

For example, if I search for "token", the Author tab doesn't give me all authors that have "token" in their name, but rather all authors with an article that has the word "token" in it. Maybe it's good to have some explanation for what the different options do.

[Reiter (2018)](https://www.mitpressjournals.org/doi/full/10.1162/coli_a_00322) notes that he "searched the ACL Anthology using a title search on the search words listed in Figure 1; this was done in late June 2017. Title search is not ideal, but unfortunately the ACL Anthology does not support abstract or keyword search."

It seems that using custom Google search fixes this issue, but it would be nice to know for sure (and to let other people know). If others are planning to carry out structured reviews, it's good to know what the search function can and cannot do.

**Comment by mbollmann** [comment]
There is now explanation for what the different options do, but there might still be room for improvement, so I'm leaving this open for a while longer to gather some feedback.

**Comment by mbollmann** [comment]
No one has complained or suggested improvements, so I'm closing this for now.
