### ISSUE TITLE
Paper Revision 2023.eacl-main.136

### ISSUE THREAD

**Issue by wanmok** [acl-org/acl-anthology#2536]
### Anthology ID

2023.eacl-main.136

### Type of Change

Revision

### PDF of the Revision or Erratum

[Iterative_Document_level_Extraction_via_Imitation_Learning_revision.pdf](https://github.com/acl-org/acl-anthology/files/11473558/Iterative_Document_level_Extraction_via_Imitation_Learning_revision.pdf)

### Brief Description of Changes

This revision corrects naming of metrics used in the paper. It further explains differences among CEAF-family metrics.

**Comment by anthology-assist** [comment]
@wanmok The revision pdf has arxiv watermark on it. Please update.

**Comment by wanmok** [comment]
> @wanmok The revision pdf has arxiv watermark on it. Please update.

I've updated the PDF. Please let me know whether it works or not. Thanks!

**Comment by wanmok** [comment]
@anthology-assist Hi, I wonder if the new version works. Please let me know if you need any additional information.

**Comment by mjpost** [comment]
@anthology-assist can you process this with August's corrections?
