### ISSUE TITLE
Ingestion request: PROPOR (03-10-2024)

### ISSUE THREAD

**Issue by hgoliv** [acl-org/acl-anthology#2542]
General information for this request:

I am submitting a request for a new venue that does not exist in the ACL Anthology yet.

**New venue identifier**
propor

**Venue name**
International Conference on the Computational Processing of the Portuguese Language (PROPOR)

**Two volumes**
Main Conference and Co-Located events

Main Volume title:
"Proceedings of the 16th International Conference on the Computational Processing of the Portuguese Language (PROPOR 2024) -- Main Conference"

Co-Located Events Volume title:
"Proceedings of the 16th International Conference on the Computational Processing of the Portuguese Language (PROPOR 2024) -- Co-Located Events"

**Desired publication date**
10th March 2024

**Website**
https://propor2024.citius.gal/

**Comment by mjpost** [comment]
Thanks, sounds good. Please take note of [the ingestion instructions](https://aclanthology.org/info/contrib/), though there's a chance they may be updated by the time you submit.

By the way, if PROPOR wishes to have older volumes archived in the Anthology, we can take those, as well.

**Comment by anthology-assist** [comment]
@hgoliv any updates?

**Comment by hgoliv** [comment]
Hi. We currently have all but two papers (expected early next week) for the main volume, as well as their copyrights.
I plan to generate an initial draft of the proceedings still this week, just to make sure that everything is ok.
If I cannot have the first volume ready until the middle of next week, it will have to wait for another week, because I will be away. I hope that 16th February is still ok for the desired publication date?

As for the second volume, we will only have the papers in mid/late February. I am not sure if they will be ready in time for being published in the desired date...

**Comment by hgoliv** [comment]
Hi,
The archive with volume 1 can be found here: https://eden.dei.uc.pt/~hroliv/propor2024/propor2024_data.tgz
Could you please check if everything is as it should? I tried to run the sanity check but, apparently, it is not implemented.

Thank you.

Best,
Hugo

**Comment by anthology-assist** [comment]
@hgoliv The main volume is ingested here: https://github.com/acl-org/acl-anthology/pull/3079. You can take a look at the preview and let us know if it looks good. 

The co-located events volume will be ingested under the same PR once we receive the ingestion material.

**Comment by hgoliv** [comment]
Thank you.
I can definitely see the links to the contents in: https://preview.aclanthology.org/proper-2024-ingestion/events/propor-2024/

However, I noted the following issues:
1) The "pdf" links do not lead to the PDFs. Is this expected in the preview?
2) Only the first three papers have a "bib" link.

How can this be fixed?

Also, the acronym of the conference is "PROPOR", and not "PROPER" as in the URL.

**Comment by hgoliv** [comment]
Thanks. Then, everything seems ok.
Anyway, I was asked to change one logo in the frontmatter. Would it be possible to download again the proceedings, from the same link? https://eden.dei.uc.pt/~hroliv/propor2024/propor2024_data.tgz

Thank you!

Best,
Hugo

**Comment by mjpost** [comment]
ping: @anthology-assist

**Comment by hgoliv** [comment]
Hi, just to make sure, is everything ready for having the proceedings published in the 10/11th March?

Thanks.

**Comment by hgoliv** [comment]
Hi,

I just compiled the volume of the co-located events and created an archive that includes the main volume as well, with minor updates. It can be downloaded from: http://eden.dei.uc.pt/~hroliv/propor2024/propor2024_data.tgz

If everything is ok, it can be published whenever you have the time.
Otherwise, let me know what I did wrong.

Thanks,
Hugo

**Comment by hgoliv** [comment]
@anthology-assist I still don't see the Volume 2 online. Is there anything I should do?
Thanks.
