### ISSUE TITLE
Paper Revision{2023.eacl-main.118}

### ISSUE THREAD

**Issue by shaybcohen** [acl-org/acl-anthology#2558]
### Anthology ID

2023.eacl-main.118

### Type of Change

Revision

### PDF of the Revision or Erratum

[eacl23.pdf](https://github.com/acl-org/acl-anthology/files/11581611/eacl23.pdf)

### Brief Description of Changes

1. Rearrangement of sections 3 and 4 - there was a \section command instead of \subsection command, and that leads to a confusion.
2. (A few minor typos were fixed.)

**Comment by anthology-assist** [comment]
@shaybcohen Please include anthology id.

**Comment by shaybcohen** [comment]
I included it at the ticket itself. It is 2023.eacl-main.118.
