### ISSUE TITLE
Ingestion Request: IWCS (06-20-2023)

### ISSUE THREAD

**Issue by vtourneur** [acl-org/acl-anthology#2563]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

iwcs

### Volume Title

Proceedings of the 15th International Conference on Computational Semantics (IWCS 2023)

### Date of Publication

2023-06-20

### Supporting Information

Hello,

We will aim to provide the papers of the main conference and the 5 workshops on the 2023-06-06. But if it is possible for you, some more days (2 or 3) would help us a little bit to get all things sorted out.

The website of this year event is here : https://iwcs2023.loria.fr/

We have long and short papers, and the 5 workshops are:
[NALOMA’23](https://sites.google.com/view/naloma4/home): Natural Logic meets Machine Learning 2023
    [InqBnB4](https://iwcs2023.loria.fr/inqbnb4-inquisitiveness-below-and-beyond-the-sentence-boundary/): Inquisitiveness Below and Beyond the Sentence Boundary
    [DMR 2023](https://dmr2023.github.io/): The Fourth International Workshop on Designing Meaning Representation
    [ISA-19](https://sigsem.uvt.nl/isa19/): 19th Joint ACL – ISO Workshop on Interoperable Semantic Annotation
    [SemInOrgCom](https://sodestream.github.io/seminorgcom/): Semantics in Organisational Communication

Have a good day,

**Comment by anthology-assist** [comment]
@vtourneur Thanks! Please submit ingestion material soon.

**Comment by evanmiltenburg** [comment]
@vtourneur: any news on when the proceedings will be ready?

**Comment by vtourneur** [comment]
Hello,

Sorry for the delay, I'm waiting for the ISBN before submitting the proceedings as documented here: https://aclanthology.org/info/contrib/
I sent an email to Priscilla Rasmussen with the titles of the volumes requesting an ISBN but I have not received an answer for now.

But I'm not sure that the ISBN are required to submit the proceedings, so maybe I can send them now and we will add the ISBN later.

Thank you,

**Comment by nschneid** [comment]
@mjpost is Priscilla still the right contact for ISBNs?

**Comment by mjpost** [comment]
No, Priscilla has retired. Contact Jenn Rachford (acl.rachford@gmail.com). Docs will be updated soon (#2588).

**Comment by nschneid** [comment]
@vtourneur any updates? Should I try to find Jenn at ACL?

**Comment by vtourneur** [comment]
I sent an email to Jenn, I am still waiting for an answer. Maybe she will have more time to answer in a few days, when ACL will be over.

**Comment by nschneid** [comment]
@vtourneur - If Jenn hasn't replied, maybe this would be a good time to send a reminder?

**Comment by vtourneur** [comment]
Ok, I just sent her a reminder. I will keep you updated when I have an answer.

**Comment by mjpost** [comment]
The ISBN is typically only recorded in the frontmatter. So I suppose we could update the frontmatter and whole PDF. Maybe CC me on one of your emails to Jenn, first?

**Comment by lorenzoscottb** [comment]
Hi, is there any update on this issue?

**Comment by nschneid** [comment]
> Is your ISBN issue resolved? Did you get ahold of Jenn?

Unless there has been progress on that front I vote for ingesting without the ISBN and adding it later.

**Comment by vtourneur** [comment]
Sorry for the delay. I received the ISBN this week, so I'm finishing preparing the proceedings. When it's done, should I just send them here ? Or use an other communication channel ?

**Comment by evanmiltenburg** [comment]
I've generally submitted proceedings using a Google Drive link, e.g. [here](https://github.com/acl-org/acl-anthology/issues/2311#issue-1504601260). I guess you can just comment in this issue with a link to a zip archive. (Or maybe even attach it directly to the comment, if the file isn't very big.)

**Comment by anthology-assist** [comment]
I believe we are still waiting on the ingestion material?

**Comment by mjpost** [comment]
Is the link in the previous comment not right?

**Comment by nschneid** [comment]
I think it's an example from another event.

**Comment by evanmiltenburg** [comment]
It is. I was trying to help by providing an example.

**Comment by mjpost** [comment]
Ah I see. I was trying to catch up and read a bit hastily.

**Comment by evanmiltenburg** [comment]
@vtourneur: any update on the proceedings?

**Comment by lorenzoscottb** [comment]
Quoting the last comment, do we have any idea when the proceedings will be available?

**Comment by mjpost** [comment]
For my own benefit (since I have to refresh myself every time I come across this issue), we are still waiting for the proceedings, presumably from @vtourneur. Let us know if we can provide any help.

**Comment by vtourneur** [comment]
Hello, sorry for the long delay. We are still waiting to receive the proceedings of one satellite workshop of IWCS. I'm sending you the current version of the proceedings (with everthing except the last workshop), so that you can publish it now if you want, and update it later when we get the remaining proceedings.

Here is the download link: https://pimo.id/8dc82965

Let me know I there is a problem with the archive, so that I can fix it.

(Sorry for the lack of answer, I don't know why but I didn't receive the Github notifications)

Thank you

**Comment by vtourneur** [comment]
Hello, we received the proceedings of the last workshop! I updated the archive at the above link (https://pimo.id/8dc82965). It now contains the complete proceedings of IWCS 2023 and its 4 satellite workshops.

Thank you

**Comment by evanmiltenburg** [comment]
So after @xinru1414's commit, NALOMA is now the only workshop that has been published on the ACL Anthology. I don't think that fully closes the issue, since the others are not in the Anthology yet, even though @vtourneur provided all the data.

**Comment by lorenzoscottb** [comment]
Is there any update from @mjpost on the whole proceedings ingestion? Why a single workshop was pushed instead of the entire proceedings? @vtourneur was presumably coordinating this, no?

**Comment by mbollmann** [comment]
That does not appear to be the case, I see commits for the other workshops on the relevant PR as well: #2847

Note that none of this has actually been merged & published on the ACL Anthology yet.

**Comment by evanmiltenburg** [comment]
Ah sorry for the confusion, I only saw NALOMA in the commit message and that's also the only workshop at the top of [this page](https://aclanthology.org/sigs/sigsem/) but that seems to be last year's edition. So I misread the year.
