### ISSUE TITLE
Ingestion Request: The 2023 CLASP Conference on Learning with Small Data (LSD) (09-08-2023)

### ISSUE THREAD

**Issue by sdobnik** [acl-org/acl-anthology#2566]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

CLASP

### Volume Title

Proceedings of the 2023 CLASP Conference on Learning with Small Data

### Venue Website (only if you are submitting a new venue)

https://sites.google.com/view/learning-with-small-data/home?authuser=0

### Date of Publication

2023-09-08

### Supporting Information

https://aclanthology.org/venues/clasp/

**Comment by sdobnik** [comment]
Ups, sorry I made an error about the year by copying old information. It is of course a 2023 event.

**Comment by anthology-assist** [comment]
@sdobnik Thanks for the info! When's the conference?

**Comment by sdobnik** [comment]
@anthology-assist Conference: 2023 September 11-12, https://sites.google.com/view/learning-with-small-data/call-for-papers

**Comment by nilinykh** [comment]
Please find the proceedings below.

We used SoftConf to generate them, we would like them to be published by September 8th AOE for the conference on Monday GMT +2.

If possible, we would like to add two changes to the final version. We are waiting for the ISBN from Jennifer and for an abstract of one of the invited talks.

https://gunet-my.sharepoint.com/:u:/g/personal/nikolai_ilinykh_gu_se/EciX_W0L7sJOkpittv3WdNYB3lk4xCXjBEQPKfUBl4Yf4g

**Comment by anthology-assist** [comment]
@nilinykh Thank you for submitting the ingestion material. The `meta` file information is wrong. Please follow instructions [here](https://acl-org.github.io/ACLPUB/anthology.html) to check your material.

**Comment by nilinykh** [comment]
@anthology-assist

Please find below the updated file with materials for proceedings. The `meta` file now has correct information, hopefully.

https://gunet-my.sharepoint.com/:u:/g/personal/nikolai_ilinykh_gu_se/EciX_W0L7sJOkpittv3WdNYB3lk4xCXjBEQPKfUBl4Yf4g?e=MLJN0b
