### ISSUE TITLE
Ingestion Request: PACLIC 37 (11-20-2023)

### ISSUE THREAD

**Issue by ManuAndOscar** [acl-org/acl-anthology#2570]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

paclic

### Volume Title

Proceedings of the 37th Pacific Asia Conference on Language, Information and Computation (PACLIC 37)

### Date of Publication

2023-11-20

### Supporting Information

Website of the 2023 edition in Hong Kong: [https://paclic2023.github.io/](url)

**Comment by anthology-assist** [comment]
Thanks! Please submit ingestion material ~2 weeks prior to the publication date.

**Comment by ManuAndOscar** [comment]
Proceedings of [PACLIC 37] (https://drive.google.com/file/d/1UtS7xl5UY8IysQgT3b-j7QFDbkkJUewo/view?usp=sharing)

**Comment by anthology-assist** [comment]
@ManuAndOscar requested access
