### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Manowen** [acl-org/acl-anthology#258]
Use this template to request a correction to the ACL Anthology.

Please ensure that you:

- [ ] ...have read and understood the [criteria for corrections](http://aclanthology.info/corrections).
- [ ] ...have included (if relevant) the ACL Anthology ID (e.g., J93-2003).

If approved, we will follow up with information about how to submit the correction.

**Comment by mbollmann** [comment]
What is your correction request? Please specify and we can re-open this issue.
