### ISSUE TITLE
Paper Revision {D19-1218}

### ISSUE THREAD

**Issue by jschluger** [acl-org/acl-anthology#2596]
### Anthology ID

D19-1218

### Type of Change

Revision

### PDF of the Revision or Erratum

[namechange_revision.pdf](https://github.com/acl-org/acl-anthology/files/11886005/namechange_revision.pdf)
[sup.pdf](https://github.com/acl-org/acl-anthology/files/11886006/sup.pdf)

### Brief Description of Changes

This revision updates author Charlotte Schluger's name for consistency with later publications.

**Comment by anthology-assist** [comment]
We don't support supplemental material corrections currently.
