### ISSUE TITLE
Ingestion Request: Swiss Text Analytics Conference (SwissText) (08-31-2023)

### ISSUE THREAD

**Issue by SwissNLP** [acl-org/acl-anthology#2601]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

SwissText

### Volume Title

Proceedings of the 8th Swiss Text Analytics Conference (SwissText 2023)

### Venue Name (only if you are submitting a new venue)

Swiss Text Analytics Conference (SwissText)

### Venue Website (only if you are submitting a new venue)

https://www.swisstext.org/

### Date of Publication

2023-08-31

**Comment by SwissNLP** [comment]
Dear @acl-org-github, 

could you kindly let us know about the planned timeline for processing our ingestion request?
We will need confirmation from you before we can proceed with the next steps.

Best wishes,
SwissNLP team

**Comment by anthology-assist** [comment]
@mjpost Could you approve this?

**Comment by mjpost** [comment]
We approve this and the requested Venue ID (SwissText) is great. Please pay careful attention to [the submission instructions](https://aclanthology.org/info/contrib/).

**Comment by Emmanuel-desalis** [comment]
I have followed the instructions, waiting on the Anthology Director contact to send the data file.

**Comment by mjpost** [comment]
The data is here @anthology-assist: https://filesender.switch.ch/filesender2/?s=download&token=8cfe275b-7425-4ed5-a7d3-bb074c00886c

**Comment by anthology-assist** [comment]
@Emmanuel-desalis The link has unfortunately expired. Could you share again?

**Comment by Emmanuel-desalis** [comment]
It will take me a bit of time before I can create a new link. In the meantime, could you check on your side? I saw that the data were downloaded a few times on the 11.11.23.

**Comment by Emmanuel-desalis** [comment]
Hello @anthology-assist, 
It seems that the table of contents and the preface are missing, I don't know why this happened. Should I have added them manually after running the python script? Or send them separately? How can we correct this so the the proceedings ar complete?

**Comment by Emmanuel-desalis** [comment]
Hello @anthology-assist, @mjpost:
After reviewing the proceedings, the front matter is missing. 
The updated data is here: https://filesender.switch.ch/filesender2/?s=download&token=9872fd5f-ffae-4b4a-836d-5c52f1d74d53 
Thank you for creating the new proceedings.
