### ISSUE TITLE
Correction to Anthology ID 2023.acl-short.45

### ISSUE THREAD

**Issue by edoost** [acl-org/acl-anthology#2610]
The reported losses in the paper correspond to a model of smaller size than reported in the paper, as our experiments involved using different model sizes in incremental steps. While this error does not impact the conclusions drawn in our paper, it is crucial for maintaining reproducibility.

[Paper_3052.pdf](https://github.com/acl-org/acl-anthology/files/11995731/Paper_3052.pdf)

**Comment by mbollmann** [comment]
Can you use the "Submission of Revision or Erratum" form for this instead of a blank issue, please? :)

**Comment by edoost** [comment]
Sorry. My bad. Came here from an old link. Now I found the link to the form.
