### ISSUE TITLE
Paper Revision 2023.findings-acl.452

### ISSUE THREAD

**Issue by shirley-wu** [acl-org/acl-anthology#2616]
### Anthology ID

2023.findings-acl.452

### Type of Change

Revision

### PDF of the Revision or Erratum

https://arxiv.org/pdf/2306.00887.pdf

### Brief Description of Changes

1. The email address of the author Sha Li has been corrected. The previous email was incorrectly stated as "shali2". The correct email should be "shal2".
2. There was an error in the column header of Table 1. The second "OpenPI" has been corrected to "OpenPI-C".

**Comment by anthology-assist** [comment]
@shirley-wu Can you please submit an updated PDF, instead of the arxiv version?

**Comment by shirley-wu** [comment]
Sure! Sorry I did not notice the arxiv version is different from the ACL template. Attached is the updated pdf
[openpi-c typo corrected.pdf](https://github.com/acl-org/acl-anthology/files/12423975/openpi-c.typo.corrected.pdf)
