### ISSUE TITLE
Specific versions of libraries missing in requirements.txt?

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#262]
I am following the instructions in `README.md` and `README_detailed.md` to compile the website, but it is not working for me. Here's my environment:

  * Debian 9 (Stretch)
  * Python 3.7, downloaded and compiled (since it is not provided in this release of Debian)
  * Hugo v0.55.1-223B3C2EE/extended (downloaded and installed from Github)
  * Other dependencies installed with `pip install -r requirements.txt`

When I run `bin/build_hugo`, I get an error trace ending in

```
  File "/home/villalba/Proyectos/acl-anthology/bin/anthology/texmath.py", line 198, in etree_to_html
    self._parse(TexSoup.TexSoup(element.text).expr.everything, result)
AttributeError: 'TexEnv' object has no attribute 'everything'
```

Following a bug report on a different issue, I tried to bypass this error by replacing `expr.everything` in `texmath.py` line 198 with `expr.all` (and also in line 98). I didn't get to see whether it works, because then I get the error

```
  File "/home/villalba/Proyectos/acl-anthology/bin/anthology/texmath.py", line 111, in _parse_command
    args = list(code.arguments)
AttributeError: 'TexCmd' object has no attribute 'arguments'
```

My current theory is that I need specific versions of some requirements - it is possible that an older version of (for instance) `texsoup` was installed for some other package, and therefore no newer version is installed.

I can try newer libraries to see where the issue is, but I would need someone who can successfully compile the Anthology to give me their current versions of the packages `latexcodec`, `stop-words`, `tqdm`, and `texsoup`.

**Comment by mbollmann** [comment]
Have you tried it after I merged the hotfix in #261 earlier today? It is actually a newly released version of texsoup that broke this.

**Comment by mbollmann** [comment]
Oh, and a general tip: Since we're using Travis, if the build is passing there, you can check their logs to see the exact versions of everything that's installed to build successfully:
https://travis-ci.org/acl-org/acl-anthology/branches

**Comment by villalbamartin** [comment]
The hotfix did solve the issue. Closing it now.
