### ISSUE TITLE
Paper Metadata: {2023.findings-acl.83}

### ISSUE THREAD

**Issue by nnkennard** [acl-org/acl-anthology#2626]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.findings-acl.83

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Hello, I'm not sure if this is the right place to ask this, but I've accidentally created three separate author entries on the ACL Anthology:

(1) [Neha Nayak](https://aclanthology.org/people/n/neha-nayak/)
(2) [Neha Kennard (2022)](https://aclanthology.org/people/n/neha-kennard/) (PDF says Neha Nayak Kennard)
(3) [Neha Nayak Kennard (2023)](https://aclanthology.org/people/n/neha-nayak-kennard/) (PDF says Neha Nayak Kennard)

Following the note on the form, I checked that my details on OpenReview say:
```
Names
---------
Neha Nayak Kennard (Preferred)
```

and on Softconf:
```
First Name: | Neha Nayak
Last Name: | Kennard
```

But I must have updated them after NAACL 2022. Would it be possible to merge (2) and (3), and maybe even (1)? 

If not, could you confirm that based on the current names everything will map on to [Neha Nayak Kennard (2023)](https://aclanthology.org/people/n/neha-nayak-kennard/) going forward?

Thank you so much, and apologies for the inconvenience!

**Comment by mbollmann** [comment]
We can fix (2) in our XML (since there's a mismatch with the PDF) and add (1) as a name variant to (3), so that all papers will show up on one author page.

@anthology-assist (2) is 2022.naacl-main.89
