### ISSUE TITLE
Dead link for IWCS 2017

### ISSUE THREAD

**Issue by minimalparts** [acl-org/acl-anthology#263]
Hi,

the link https://www.aclweb.org/anthology/W17-69 is throwing a 404. Same problem for https://www.aclweb.org/anthology/W17-68.

Thanks for checking!
Aurelie

**Comment by mbollmann** [comment]
Just a few minutes ago, I have created a comprehensive list of broken links in #264, so we can hopefully take care of all of these instances there. I'm closing this as duplicate now, but thank you nonetheless for the report!
