### ISSUE TITLE
Paper Metadata: {2023.bionlp-1.40}

### ISSUE THREAD

**Issue by mobashgr** [acl-org/acl-anthology#2630]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.bionlp-1.40

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Hi,
My paper is part of BioNLP workshop proceeding https://aclanthology.org/2023.bionlp-1.40. There is a serious issue with a co-author spelling as follows:  It is Wolfgang Müller, not Wolfgang  Mller.  The spelling in the paper PDF itself is correct. I would appreciate it if this problem can be fixed soon so that I can share it with colleagues to better advertise my work.
Best,
Ghadeer

**Comment by mobashgr** [comment]
Any updates, please?

**Comment by mbollmann** [comment]
Metadata corrections are processed and ingested once a month, around the end of the month. You can submit a PR with the changes yourself to speed up the process.
