### ISSUE TITLE
Download videos from vimeo

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#2637]
Many videos (e.g., ACL 2017) are just links to Vimeo. These should be downloaded in bulk and linked to locally.

Tasks:
- [x] Take stock of which proceedings link to Vimeo
   - [ ] D15.xml
   - [ ] D16.xml
   - [ ] D17.xml
   - [ ] D18.xml
   - [ ] N15.xml
   - [ ] N18.xml
   - [ ] N19.xml
   - [ ] P17.xml
   - [ ] P18.xml
   - [ ] P19.xml
   - [ ] Q14.xml
   - [ ] Q15.xml
   - [ ] Q16.xml
   - [ ] Q17.xml
   - [ ] Q18.xml
   - [ ] Q19.xml
   - [ ] W18.xml
- [ ] Download and label them all
- [ ] Switch links
- [ ] Double-check that all these videos are imported (we have these on Dropbox):

<img width="270" alt="image" src="https://github.com/acl-org/acl-anthology/assets/455256/96bcc2be-26a0-4ebb-a352-0fadebf63917">

**Comment by davidstap** [comment]
I'm currently downloading and labeling all Vimeo videos. I also noticed a lot of videos pointing to slideslive, should I also download these? Also, I don't think I have access to the Dropbox you're referring to, can you share it with me?

**Comment by davidstap** [comment]
Short update; this is a bit delayed (was busy with a lot of EMNLP reviews, and move to Germany for internship). I'll finish it next week.

**Comment by mjpost** [comment]
I had forgotten we'd started this. I've updated the description with a  list of XML files that have video links. One idea would be to download them from the XML link so that we could set the name. The goal should be to change all the links to local storage. We could add also add an attribute to the `<video>` tag that retains the external link.

**Comment by davidstap** [comment]
Yes, I made a start but never got around to finishing it. I'll continue working on it after ingesting the ACL / EMNLP videos (almost done).

**Comment by mjpost** [comment]
Folks, now that this is nearing completion, there's a question of what to do about the videos on Vimeo.

The options are:
1. Keep them up, but delete the XML references to them
1. Keep them up, and redundantly retain the XML
1. Delete them, along with the XML references
1. Delete them, but keep the XML references

We can rule out (4) as silly. My inclination is (3), since we already have backups, maintaining them is work, and I'm not sure that Vimeo adds much in terms of value.

poke @mbollmann @akoehn

**Comment by akoehn** [comment]
Agree with 3 plus checking whether we can save money on that account (is a pro membership still needed?)

**Comment by mjpost** [comment]
Good thought, I bet we could ditch the pro membership. But I'll wait until they resolve our #3121...

**Comment by davidstap** [comment]
I found quite a few dead vimeo links (see #3125), similar to #3121. I can't find these videos anywhere else. Is there any way to restore them?

**Comment by davidstap** [comment]
Update: I found a total of 103 videos with broken vimeo links ("Unauthorized") in #3125

**Comment by mjpost** [comment]
can you post the list of them as a text file to this thread? I have an email in to Vimeo support and I'm waiting to hear back. 

It's strange to me that we can't find these videos anywhere, but we don't get a message that they don't exist. I'm hoping this means that they're still there somehow.

**Comment by davidstap** [comment]
A list of broken links: [broken_links.txt](https://github.com/acl-org/acl-anthology/files/14588060/broken_links.txt)

Most of these have the "Unauthorized" issue, but others such as [this one](https://vimeo.com/238231072) have a different error: "Sorry, we couldn't find that page".
