### ISSUE TITLE
Paper Metadata: 2023.americasnlp-1.6

### ISSUE THREAD

**Issue by mikahama** [acl-org/acl-anthology#2640]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.americasnlp-1.6

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

My last name is wrong in the metadata: Hmlinen, it should be Hämäläinen

**Comment by anthology-assist** [comment]
Closing because the last name is correct https://aclanthology.org/2023.americasnlp-1.6/
