### ISSUE TITLE
*SEM and SemEval

### ISSUE THREAD

**Issue by guyemerson** [acl-org/acl-anthology#2647]
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

SemEval and *SEM used to be the same top-level venue in the Anthology. Now that they have been split, it seems that some proceedings have been incorrectly assigned.

https://aclanthology.org/venues/starsem/ -- for 2018 and 2016, incorrectly gives links to SemEval instead of *SEM

The affected proceedings are:

* https://aclanthology.org/volumes/S16-1/
* https://aclanthology.org/volumes/S16-2/
* https://aclanthology.org/volumes/S18-1/
* https://aclanthology.org/volumes/S18-2/

**Comment by mbollmann** [comment]
Ping @nschneid
