### ISSUE TITLE
Ingestion Request: 2nd Edition of the Universal Dependencies Brazilian Festival (09-20-2023)

### ISSUE THREAD

**Issue by ud-portugues** [acl-org/acl-anthology#2657]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

UDFestBR

### Volume Title

Proceedings of the 2nd Edition of the Universal Dependencies Brazilian Festival

### Date of Publication

2023-09-20

### Supporting Information

If any checking step is necessary, the webpage of this edition of the workshop is at https://sites.google.com/icmc.usp.br/udfest-br2023

**Comment by anthology-assist** [comment]
@ud-portugues Please submit ingestion material two weeks prior to the publication date.

**Comment by mjpost** [comment]
@anthology-assist download link here: https://www.dropbox.com/scl/fi/depvrf2r5olue6726r7b9/udfestbr_data.tgz?rlkey=mwp881iybgcxlabpecdjtzdul&dl=0
