### ISSUE TITLE
Paper Metadata: 2023.americasnlp-1.18

### ISSUE THREAD

**Issue by alvations** [acl-org/acl-anthology#2663]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.americasnlp-1.18

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

The paper was wrongly attributed to me (Liling Tan), it should have been [Nat Gillin](https://aclanthology.org/people/n/nat-gillin/) and a new ACL contributor `Brian Gummibaerhausen`

**Comment by anthology-assist** [comment]
Closing because the author names are correct https://aclanthology.org/2023.americasnlp-1.18/
