### ISSUE TITLE
Paper Metadata: 2023.americasnlp-1.21

### ISSUE THREAD

**Issue by danaesavi** [acl-org/acl-anthology#2676]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.americasnlp-1.21

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Second author's name (and author's page) is wrong, i.e., a with accent (á) is missing in the surname. 
Second author's first name is Danae and surname is Sánchez Villegas. This is the correct second author's ACL page: https://aclanthology.org/people/d/danae-sanchez-villegas/

Author name list:
Current: [Edward Gow-smith](https://aclanthology.org/people/e/edward-gow-smith/), [Danae Snchez Villegas](https://aclanthology.org/people/d/danae-snchez-villegas/)

CORRECT: [Edward Gow-smith](https://aclanthology.org/people/e/edward-gow-smith/), [Danae Sánchez Villegas](https://aclanthology.org/people/d/danae-sanchez-villegas/)

For this reason bibtex is also wrong. Please could you fix it? Thanks

**Comment by anthology-assist** [comment]
Closing because author name is correct: https://aclanthology.org/people/d/danae-sanchez-villegas/
