### ISSUE TITLE
Paper Metadata: {2023.findings-acl.204}

### ISSUE THREAD

**Issue by baudzhou** [acl-org/acl-anthology#2690]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.findings-acl.204

### Type of Paper Metadata Correction

- [ ] Paper Title
- [X] Paper Abstract
- [X] Author Name(s)

### Correction to Paper Abstract

To fully evaluate the overall performance of different NLP models in a given domain, many evaluation benchmarks are proposed, such as GLUE, SuperGLUE and CLUE. The field of natural language understanding has traditionally focused on benchmarks for various tasks in languages such as Chinese, English, and multilingual, however, there has been a lack of attention given to the area of classical Chinese, also known as "wen yan wen (文言文)", which has a rich history spanning thousands of years and holds significant cultural and academic value.
For the prosperity of the NLP community, in this paper, we introduce the WYWEB evaluation benchmark, which consists of nine NLP tasks in classical Chinese, implementing sentence classification, sequence labeling, reading comprehension, and machine translation. We evaluate the existing pre-trained language models, which are all struggling with this benchmark. We also introduce a number of supplementary datasets and additional tools
to help facilitate further progress on classical Chinese NLU. The github repository is https://github.com/baudzhou/WYWEB.

### Correction to Author Name(s)

Bo Zhou, Qianglong Chen, Tianyu Wang, Xiaomi Zhong, Yin Zhang

**Comment by KoichiYasuoka** [comment]
Hi @baudzhou I've just tried to connect https://github.com/baudzhou/WYWEB but it is still "404 not found" even now. Where is your WYWEB?
