### ISSUE TITLE
Look at DOIs for frontmatter

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#2724]
We didn't get DOIs in frontmatter for EMNLP 22 or ACL 23.

**Comment by anthology-assist** [comment]
I thought we do not ingest frontmatter anymore?

**Comment by mjpost** [comment]
We ingest it if it's there. Most of ACL had frontmatter. We need to check why we didn't assign DOIs. I am think we did in the past.

**Comment by akoehn** [comment]
You changed the logic floor them in the doi generation script recently -- maybe that has something to do with it? Did we change how frontmatters are represented in the xml and then had the doi generation script in am outdated state until you changed it?

**Comment by mjpost** [comment]
Actually, though, this reminds me that I also change the ingestion script (post-EMNLP) to always generate the `<frontmatter>`. If there's no frontmatter PDF, we still need the block, we just don't generate the `<url>` tag inside it. We need to add this to EMNLP.

**Comment by mbollmann** [comment]
Whatever the reasoning for always generating the `<frontmatter>` block was, I still suspect it's the wrong solution to a problem I don't yet understand.

**Comment by mjpost** [comment]
`<frontmatter>` is just the special stub for paper 0. If we don't generate it, then no bibtex is generated for the volume itself. We want to generate this volume bibtex even if there is no PDF. (If there _is_ a PDF, we add a `<url>` tag within frontmatter, as we do for papers.) This is all a separate issue.

We don't generate DOIs for the complete volume or frontmatter, and haven't for some time. If we want to, we just need to figure it out. I haven't had time to do this. See also #726.
