### ISSUE TITLE
ACL 2023 Workshops Missing DOIs?

### ISSUE THREAD

**Issue by neubig** [acl-org/acl-anthology#2733]
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

Thank you for all of your help with the anthology!

It seems that the ACL 2023 workshops are missing DOIs (which now makes it impossible to submit the papers along with NSF reports...)

- ACL 2023 paper (has DOI): https://aclanthology.org/2023.acl-long.36/
- *SEM 2023 paper (missing DOI): https://aclanthology.org/2023.starsem-1.14/
- SIGMORPHON 2023 paper (missing DOI): https://aclanthology.org/2023.sigmorphon-1.22/

I'd be happy to contribute if there is a way I can help rectify the issue.

**Comment by nschneid** [comment]
Some of the ACL workshops do have them, e.g. LAW: https://aclanthology.org/2023.law-1.3/

**Comment by mbollmann** [comment]
No idea why not all workshops received DOIs in #2723. @anthology-assist ?

**Comment by anthology-assist** [comment]
We missed linking some workshops for acl 2023. Looks like it's taken care of in #2720. I'll create DOIs for these workshops.
