### ISSUE TITLE
Ingestion Request: EAMT-2023

### ISSUE THREAD

**Issue by kjp-souza** [acl-org/acl-anthology#2739]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

EAMT

### Volume Title

Proceedings of the 24th Annual Conference of the European Association for Machine Translation

### Supporting Information

Here is the link to the folder containing the [.tgz file](https://studentuef-my.sharepoint.com/:u:/g/personal/kpatteri_uef_fi/EV65_aHXbMNDlVcsMGRxYosBa9LkI3BbrbPekUgRX1MOig?e=pDsXP0)

**Comment by anthology-assist** [comment]
When's the expected publish date? @kjp-souza

**Comment by kjp-souza** [comment]
As far as I know, I am the EAMT assistant responsible for publishing the proceedings, since I was the one who compiled it.
ANd I have just compiled the latest version of it.
Please, don't publish #2707. The EAMT's organization is not aware of this one and might not even know which files are in it. I am in contact with the main organizers and we've just agreed to publish it now. Please, contact EAMT's official channel https://events.tuni.fi/eamt23/
to confirm [eamt2023@tuni.fi](mailto:eamt2023@tuni.fi) before proceeding with #2707 (I don't advise publishing it in any way)

The expected publishing

**Comment by kjp-souza** [comment]
> When's the expected publish date? If this is a repetition of #2707 Please close that one out. @kjp-souza

Also, I have one doubt: is it even possible to include only the pdf files to publish to ACL? Since  [the official instructions](https://acl-org.github.io/ACLPUB/anthology.html) require running ACLPUB scripts to compile the ./data folder. 
Issue #2707 only has the pdf file for the main conference in a link - would this even work?

**Comment by kjp-souza** [comment]
So, with the previous issue closed and if everything is right now, when could we expect it to be published?

**Comment by mjpost** [comment]
We should be able to ingest it within the next few days. @anthology-assist can you attend to this?

**Comment by mjpost** [comment]
@kjp-souza can you please look through [the preview](https://preview.aclanthology.org/eamt-23-ingestion/events/eamt-2023/) and verify that everything looks okay?

**Comment by kjp-souza** [comment]
> @kjp-souza can you please look through [the preview](https://preview.aclanthology.org/eamt-23-ingestion/events/eamt-2023/) and verify that everything looks okay?

Hi @mjpost -please, before we proceed, I've posted 2 doubts (I'm not we should correct) on this PR: https://github.com/acl-org/acl-anthology/pull/2757
