### ISSUE TITLE
Paper Metadata: 2022.ccl-1.81

### ISSUE THREAD

**Issue by Starcollector** [acl-org/acl-anthology#2750]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2022.ccl-1.81

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Jiaxin Yuan, Cunliang Kong, Chenhui Xie, Liner Yang, Erhong Yang

**Comment by Starcollector** [comment]
@anthology-assist  hi, the Anthology ID is 2022.ccl-1.81

**Comment by mjpost** [comment]
Ping @anthology-assist
