### ISSUE TITLE
Paper Revision 2023.findings-acl.382

### ISSUE THREAD

**Issue by wangchiew** [acl-org/acl-anthology#2755]
### Anthology ID

2023.findings-acl.382

### Type of Change

Revision

### PDF of the Revision or Erratum

[PostText_ACL.pdf](https://github.com/acl-org/acl-anthology/files/12448415/PostText_ACL.pdf)

### Brief Description of Changes

The link https://aclanthology.org/2023.findings-acl.382.pdf is not pointing to the right paper. It is pointing to a different paper now.

**Comment by anthology-assist** [comment]
@wangchiew Thank you for catching this!
