### ISSUE TITLE
Paper can not search in Google Scholar.

### ISSUE THREAD

**Issue by zhouzihao501** [acl-org/acl-anthology#2760]
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

Hi, when I want to add my paper in Google scholar personal page, I can not search it in Google scholar. 
Just can find my arxiv version. I don't what happen, could you help me solve it? Thanks for your help!

My paper title is: 
<Learning by Analogy: Diverse Questions Generation in Math Word>. Paper ID is: zhou-etal-2023-learning-analogy

**Comment by mbollmann** [comment]
Unfortunately we cannot help with Google Scholar issues, as we have no control at all over how and what Google Scholar indexes. We provide full and correct information for Google Scholar in the format that they require.

If it's a relatively newly published paper (you gave the bibkey, not the paper ID, so I can't check), maybe it's just a matter of time until Google Scholar re-indexes the page.
