### ISSUE TITLE
Paper Metadata: {2023.ccl-1.28}

### ISSUE THREAD

**Issue by 17835204280** [acl-org/acl-anthology#2766]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.ccl-1.28

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Peng Xue (薛鹏), Yang Li (李旸), Suge Wang (王素格), Jian Liao (廖健), Jianxing Zheng (郑建兴), Yujie Fu (符玉杰), Deyu Li (李德玉)

This is to match the PDF

**Comment by anthology-assist** [comment]
Closing because author names and the order are correct.

<img width="1294" alt="Screenshot 2023-09-04 at 1 35 08 PM" src="https://github.com/acl-org/acl-anthology/assets/126604033/87ddc082-731b-4048-af08-56c79caabf34">

**Comment by 17835204280** [comment]
> Closing because author names and the order are correct.
> 
> <img alt="Screenshot 2023-09-04 at 1 35 08 PM" width="1294" src="https://user-images.githubusercontent.com/126604033/265525651-87ddc082-731b-4048-af08-56c79caabf34.png">

The third author's name is incorrect.
[old]
Suming Wang (王素格)

[New]
Suge Wang (王素格)
