### ISSUE TITLE
Ingestion Request: IWCLUL (2023-12-02）

### ISSUE THREAD

**Issue by flammie** [acl-org/acl-anthology#2767]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

IWCLUL

### Volume Title

Proceedings of the Eighth International Workshop on Computational Linguistics of Uralic Languages

### Venue Website (only if you are submitting a new venue)

https://rootroo.com/en/joint-nlp4dh-iwclul-2023/

### Date of Publication

2023-12-02

### Supporting Information

The eighth IWCLUL is organised jointly with NLP4DH c.f. #2742. Is it preferable to prepare/publish/ingest jointly or one each? IWCLUL is also organised by ACL SIG: SIGUR.

**Comment by anthology-assist** [comment]
It's okay to prepare+ingest separately since IWCLUL has its own venue: https://aclanthology.org/venues/iwclul/ 

Please submit ingestion material at least 2 weeks prior to the publication date in this ticket.

**Comment by mikahama** [comment]
We made a joint proceedings for IWLCUL and NLP4DH.

The files in ACLPUB2 format are here: https://www.dropbox.com/scl/fi/rey9pg2ar2uu3zzdqoihs/nlp4dh_iwclul.zip?rlkey=oevv2c9otwrla0t4xyrnbh9su&dl=0

**Comment by mikahama** [comment]
@anthology-assist if there's anything more needed from our part, please let us know.

**Comment by anthology-assist** [comment]
@mikahama Could you double check that the material is following the aclpub2 format: https://github.com/rycolab/aclpub2 I don't see a `watermarked_pdf` folder.

**Comment by mikahama** [comment]
I added the watermarked_pdf folder to this one https://www.dropbox.com/scl/fi/n0dq8aruwxonh03yc2k1t/aclpub2.zip?rlkey=8440wqj862oyw1nqlamoszx0x&dl=0 . The aclpub2 instructions are not quite clear, but I did produce the files using the repository you linked. @anthology-assist

**Comment by mckurz** [comment]
Hi @anthology-assist @mjpost, may I know the status of this update? Thank you very much!

**Comment by mjpost** [comment]
Hi—I agree the aclpub2 format isn't very clear. @anthology-assist can you work with what the provided? We also have [updated instructions here](https://github.com/acl-org/acl-anthology/wiki/ACLPUB2), include a format-checking script.

**Comment by anthology-assist** [comment]
@mikahama The new ingestion material you provided is for `nlp4dh`. It doesn't contain any content for `IWCLUL` (or maybe I missed something here?)

`nlp4dh` is ingested here #3059.

**Comment by mikahama** [comment]
@anthology-assist it's the joint proceedings of NLP4DH and IWCLUL. If it's possible to have two identifiers, then both iwclul and nlp4dh should be used.

**Comment by anthology-assist** [comment]
@mjpost Question for you: do we allow two identifiers?

**Comment by mjpost** [comment]
We have to choose one of them for the file name, but it can be listed under both pages (e.g., https://aclanthology.org/venues/nlp4dh/ and https://aclanthology.org/venues/iwclul/) by adding a `<venue>` tag for both names to each volume.

**Comment by mikahama** [comment]
@mjpost and @anthology-assist Is there any estimate when the proceedings will be online? Some authors are asking.
