### ISSUE TITLE
Ingestion Request: The First Workshop on South East Asian Language Processing (11-01-2023)

### ISSUE THREAD

**Issue by kfnks** [acl-org/acl-anthology#2788]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

sealp

### Volume Title

Proceedings of the First Workshop on South East Asian Language Processing

### Venue Name (only if you are submitting a new venue)

Workshop on South East Asian Language Processing

### Venue Website (only if you are submitting a new venue)

https://sealp-workshop.github.io

### Date of Publication

2023-11-1

**Comment by kfnks** [comment]
The volume is to be included in https://aclanthology.org/events/ijcnlp-2023/ as a workshop of IJCNLP-AACL 2023.

**Comment by anthology-assist** [comment]
@mjpost Could you approve this new venue?

**Comment by mjpost** [comment]
LGTM, but closing since this is included in #2791.
