### ISSUE TITLE
Ingestion Request: The Second Workshop on Natural Language Interfaces (2023-11-01)

### ISSUE THREAD

**Issue by kfnks** [acl-org/acl-anthology#2789]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

nlint

### Volume Title

Proceedings of the Second Workshop on Natural Language Interfaces

### Venue Name (only if you are submitting a new venue)

Workshop on Natural Language Interfaces

### Venue Website (only if you are submitting a new venue)

https://nlint-workshop.github.io

### Date of Publication

2023-11-1

### Supporting Information

The volume is to be included in https://aclanthology.org/events/ijcnlp-2023/ as a workshop of IJCNLP-AACL 2023.

**Comment by anthology-assist** [comment]
@mjpost Could you approve the new venue?

**Comment by mjpost** [comment]
Oh, I see this this is included with #2791. Thanks for the notice.
