### ISSUE TITLE
Casing issues

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#279]
I did a spot check of ACL 2018 and most of the curly braces look right. I did notice:

https://aclweb.org/anthology/papers/P/P18/P18-1055.bib should be `{M}inimalist {G}rammars`
https://aclweb.org/anthology/papers/P/P18/P18-1203.bib should be `{D}eep {D}yna-{Q}`

Also, should title-initial lowercase words be protected?:
https://aclweb.org/anthology/papers/P/P18/P18-2109.bib

**Comment by davidweichiang** [comment]
Thanks! I'm not sure about your second question, though. I can think of arguments both ways.
