### ISSUE TITLE
Ingestion Request: The ART of Safety: Workshop on Adversarial testing and Red-Teaming for generative AI

### ISSUE THREAD

**Issue by kfnks** [acl-org/acl-anthology#2790]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

artofsafety

### Volume Title

Proceedings of The ART of Safety: Workshop on Adversarial testing and Red-Teaming for generative AI

### Venue Name (only if you are submitting a new venue)

The ART of Safety: Workshop on Adversarial testing and Red-Teaming for generative AI

### Venue Website (only if you are submitting a new venue)

https://sites.google.com/view/art-of-safety/home

### Date of Publication

2023-11-1

### Supporting Information

The volume is to be included in https://aclanthology.org/events/ijcnlp-2023/ as a workshop of IJCNLP-AACL 2023.

**Comment by mjpost** [comment]
LGTM, but closing since this is included in #2791.
