### ISSUE TITLE
Ingestion Request: IJCNLP-AACL (11-01-2023)

### ISSUE THREAD

**Issue by kfnks** [acl-org/acl-anthology#2791]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

ijcnlp, aacl

### Volume Title

Proceedings of the 13th International Joint Conference on Natural Language Processing and the 3rd Conference of the Asia-Pacific Chapter of the Association for Computational Linguistics

### Date of Publication

2023-11-1

### Supporting Information

This event will include following volumes ({volume identifier}; {volume name}) .
* **2023.ijcnlp-long**;  Proceedings of the 13th International Joint Conference on Natural Language Processing and the 3rd Conference of the Asia-Pacific Chapter of the Association for Computational Linguistics (Volume 1: Long Papers)
* **2023.ijcnlp-short**; Proceedings of the 13th International Joint Conference on Natural Language Processing and the 3rd Conference of the Asia-Pacific Chapter of the Association for Computational Linguistics (Volume 2: Short Papers)
* **2023.ijcnlp-srw**; Proceedings of the 13th International Joint Conference on Natural Language Processing and the 3rd Conference of the Asia-Pacific Chapter of the Association for Computational Linguistics: Student Research Workshop
* **2023.ijcnlp-demo**; Proceedings of the 13th International Joint Conference on Natural Language Processing and the 3rd Conference of the Asia-Pacific Chapter of the Association for Computational Linguistics: System Demonstrations
* **2023.ijcnlp-tutorials**; Proceedings of the 13th International Joint Conference on Natural Language Processing and the 3rd Conference of the Asia-Pacific Chapter of the Association for Computational Linguistics: Tutorial Abstracts
* **2023.findings-ijcnlp**; Findings of the Association for Computational Linguistics: IJCNLP-AACL 2023
* **2023.nlpmc**; Proceedings of the Third Workshop on NLP for Medical Conversations
* **2023.wiesp**; Proceedings of the Second Workshop on Information Extraction from Scientific Publications
* **2023.eval4nlp**; Proceedings of the Fourth Workshop on Evaluation & Comparison of NLP Systems
* **2023.socialnlp**; Proceedings of the 11th International Workshop on Natural Language Processing for Social Media
* **2023.sealp**; Proceedings of the First Workshop on South East Asian Language Processing
  * https://github.com/acl-org/acl-anthology/issues/2788
* **2023.finnlp**; Proceedings of the 6th Workshop on Financial Technology and Natural Language Processing
* **2023.nlint**; Proceedings of the Second Workshop on Natural Language Interfaces
  * https://github.com/acl-org/acl-anthology/issues/2789
* **2023.artofsafety**; Proceedings of the ART of Safety: Workshop on Adversarial testing and Red-Teaming for generative AI
  * https://github.com/acl-org/acl-anthology/issues/2790

#2788, #2789 and #2790 are new venue submissions.

If I should make a separated issue for each volume, please let me know.

Thank you for your help!

**Comment by anthology-assist** [comment]
@kfnks Thank you for submitting the request. Please submit the conference ingestion material two weeks prior to the desired publication date.

**Comment by kfnks** [comment]
@mjpost @anthology-assist Thank you!

**Comment by kfnks** [comment]
@mjpost @anthology-assist 
I am experiencing an error with a particular paper pdf (372_Paper.pdf) and cannot compile book.pdf. 
To my memory, it was working before but at a some time point it started causing the error.
As far as I see, the paper pdf has no problem when I open it with macOS preview.app.
If I remove the paper #372 from the order file, I can compile book.pdf properly.
Do you have any workaround with this issue?
```
$ make shipout
quietly running pdflatex book.tex ...
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
pdflatex failed on book.tex; see book.log for details
make[1]: *** [book.idx] Error 1
make[1]: *** Deleting file `book.idx'
make: *** [shipout] Error 2
$ tail book.log
(pdftex.def)             Requested size: 597.50682pt x 845.04504pt.
File: final/368/368_Paper.pdf Graphic file (type pdf)
<use final/368/368_Paper.pdf, page 9>
Package pdftex.def Info: final/368/368_Paper.pdf , page9 used on input line 144
.
(pdftex.def)             Requested size: 597.50682pt x 845.04504pt.
[174 <./final/368/368_Paper.pdf>]
!pdfTeX error: pdflatex (file ./final/372/372_Paper.pdf): xpdf: reading PDF ima
ge failed
 ==> Fatal error occurred, no output PDF file produced!
```

**Comment by mjpost** [comment]
Sorry, I have no insights into this process. Are you using aclpub2? You might file an issue there: https://github.com/rycolab/aclpub2/issues

**Comment by kfnks** [comment]
@mjpost Thank you for your reply.
I am using the proceedings/Makefile in the zip file generated by START with the environment variable ACLPUB=../ . I believe I'm using aclpub, not aclpub2.

**Comment by mjpost** [comment]
I believe we are waiting for the material from @kfnks.

**Comment by kfnks** [comment]
@mjpost @flipz357 Sorry for leaving you suspended. Currently another pub chair is handling data finalization. Please wait for a while.

**Comment by mjpost** [comment]
Any updates?

**Comment by kfnks** [comment]
We are still handling copyright transfer issues. Sorry for this trouble.

**Comment by kfnks** [comment]
@mjpost @flipz357 
We have decided to send only the data of copyright-confirmed volumes.
Please download the zip file from [here](https://www.dropbox.com/scl/fi/oupimysskjd55hz4lposp/ijcnlp-aacl-2023_data_copyright-confirmed_231223.zip?rlkey=9t7tz4tf3r67okip26fat1u17&dl=0).

It lacks the data of ijcnlp-aacl demo, eval4nlp, sealp, and socialnlp. The data of those volumes will be shared later.

Thank you for your help. We wish your nice holidays.

**Comment by anthology-assist** [comment]
@kfnks Existing volumes have been ingested: https://github.com/acl-org/acl-anthology/pull/3003 

Please let me know once the missing volumes are uploaded.

**Comment by kfnks** [comment]
@anthology-assist Thank you for your help.
Please ingest [the data of copyright-confirmed demo volume (2023.ijcnlp.demo)](https://www.dropbox.com/scl/fi/5tzzeycrzxaghs1jmtk03/ijcnlp-aacl-2023_data_copyright-confirmed_demo.zip?rlkey=8iql59cfa486bla5w1mb7765b&dl=0), too.

Also, in accordance with [the description in the anthology](https://aclanthology.org/info/contrib/), we also share [the data of  the remaining three workshops.](https://www.dropbox.com/scl/fi/cu4hrhh5eeddd2d6vozn8/ijcnlp-aacl-2023_data_copyright-unconfirmed_workshops.zip?rlkey=5a5nedif7qn8zw5eaag9d8qnw&dl=0), although their copyright transfers have not been obtained yet.

> For both current and legacy events, it is good practice for the organizers to attempt to obtain copyright transfers for their materials, but we will ingest materials even if no copyright transfers are on file.

Thank you again for your patience.

**Comment by kfnks** [comment]
@anthology-assist 
Please find the attached files of confirmed copyright transfer signatures for SEALP and SocialNLP.
[copyright-signatures_sealp.txt](https://github.com/acl-org/acl-anthology/files/13903156/copyright-signatures_sealp.txt)
[copyright-signatures_socialnlp.txt](https://github.com/acl-org/acl-anthology/files/13903158/copyright-signatures_socialnlp.txt)

**Comment by kfnks** [comment]
@anthology-assist 
Here is the last agreement signatures file for Eval4NLP.
[copyright-signatures_eval4nlp.txt](https://github.com/acl-org/acl-anthology/files/13914714/copyright-signatures_eval4nlp.txt)

**Comment by kfnks** [comment]
@anthology-assist @mjpost Thank you for your kind help.
If there is any action that I am expected to take, please let me know.

**Comment by anthology-assist** [comment]
@kfnks All volumes and workshops have been ingested except for workshop eval4nlp, please look at the preview in #3003 and let me know if anything's wrong. 

eval4nlp ingestion material doesn't follow aclpub2 format, specifically the `papers.yaml` file. Requirements see https://github.com/rycolab/aclpub2 . Could you update the file?

**Comment by kfnks** [comment]
@anthology-assist Thank you for the preview. Unfortunately, we have found that there was an error in the message from the general chair. Could you please replace the relevant PDF files [with those in this zip file](https://drive.google.com/file/d/1y3L8YIQEFgcRQVp1dfdl8UnKBxXNv9aB/view?usp=drive_link) ? The others look great.

As for eval4nlp, we are waiting the feedback from the workshop organizers. Many thanks.

**Comment by flipz357** [comment]
@mjpost Imo this issue is not yet fully solved. Eval4NLP 2023 has not yet been integrated. We collected copyright from the attendents as request about a month ago and sent them to the responsible person at AACL. I think what was left do was some bug about the proceedings compilation that is probably now fixed too. 

Linking @danieldeutsch here, since he may know more about this.

**Comment by danieldeutsch** [comment]
The `papers.yml` file that was generated by aclpub2 did not match the format specified in the aclpub2 repository, even though I successfully used it to compile the Eval4NLP proceedings. Lun-Wei from AACL asked me to update the `papers.yml` and I did my best to change it to match the format in the repository. I sent Lun-Wei the updated proceedings and `papers.yml` file on January 21 but did not hear back.

**Comment by ChunJiChen** [comment]
Hi @anthology-assist, 

I noticed that the page for the FinNLP workshop (https://aclanthology.org/volumes/2023.finnlp-1/) was mixed with the other workshop. Some papers in FinNLP were removed, and some papers from the other workshop were listed on the page. 

Additionally, the page of the Fifth FinNLP disappeared. It was done this Oct. (https://github.com/acl-org/acl-anthology/issues/2460). 

Please let me know if I need to prepare documents for solving this issue.

**Comment by mjpost** [comment]
Thanks, I reverted this in #3072.

It appears that FinNLP met twice in 2023: once with IJCAI (non-Anthology), and once with IJCNLP-AACL.

@anthology-assist can you please re-ingest FinNLP, as a second volume, with volume ID "2"? Then re-link it to IJCNLP.

**Comment by kfnks** [comment]
@anthology-assist Here is the updated papers.yml from @danieldeutsch . Does this work?

As for FinNLP, our first delivery data on Dec. 23 wrongly duplicated *.bib and *.pdf from ArfOfSafety in finnlp/proceedings/cdrom/{bib,pdf}. Sorry for this trouble.

**Comment by flipz357** [comment]
@anthology-assist is there any update on the Eval4NLP@AACL ingestion, or can we somehow provide more information?

**Comment by mjpost** [comment]
This is closed, so let's create a new issue for Eval4NLP? That will help it avoid getting lost.
