### ISSUE TITLE
Creating URLs for papers using their bibtex index

### ISSUE THREAD

**Issue by alvations** [acl-org/acl-anthology#2808]
The URL for papers are indexed by their workshop/conference IDs, e.g. https://aclanthology.org/D19-1410/

but what if, we also use the bibtex citation and forward it to the current URL, e.g.  https://aclanthology.org/reimers-gurevych-2019-sentence

----

I'm not exactly sure what's the exact use case for most people. But for me personally when reading/writing/editing latex, I would like to check the paper and instead of going to the `.bib` file or scroll down to the references and copy+paste the paper title to google, I was thinking, why don't I just paste the bibtex index to the ACL anthology site.

**Comment by mbollmann** [comment]
The Anthology ID is a stable identifier guaranteed not to change, while the bibkey is not. If bibkeys work in URLs, people will almost certainly start linking to them on websites and social media, effectively using them like a permanent identifier. Granted, with us providing the full Anthology BibTeX and encouraging people to use it, we have an interest in not changing bibkeys unnecessarily, but I'm not sure I'd want to open that can of worms.

I will add "finding a paper quickly by its bibkey" to the long list of advantages if we had a better search solution (#165), though :)

**Comment by akoehn** [comment]
There is also sometimes the *need* to change bibkeys, e.g. on retroactive name changes (which have happened, although mostly given names) and author list changes.

If e.g. there was a mixup and Marcel was attributed as an author instead of me (this case has also happened ...) then I would not be happy to have the bibtex and URL always as `https://acl.org/bollmann-2025-magnificient-breakthrough` 😬

**Comment by mjpost** [comment]
If we did this, we would of course add a redirect so that the displayed URL would be the canonical one. This would prevent people from copying-and-pasting such a link. But I agree it runs the risk of fracturing the incoming linkspace. It would be better if we provided this through a search interface, even using GET-style URLs.

**Comment by mjpost** [comment]
Yeah, good point—I hadn't given much thought to the implementation, and both of these are probably non-starters. Though I wonder if there's a way to write an index to a file and have htaccess use that for lookup. 

Anyway, thanks for submitting the request, @alvations, but it seems we'll have to table this for the moment until we have a better search solution.

**Comment by alvations** [comment]
Agree on having better search solution. BTW, quick suggestion if the bibtex ID is added into the page's meta, it'll help in search in the future too, e.g.  https://colab.research.google.com/drive/1vIdWh9MDH3qSbDh6lXBNvx_tSpPzhhod?usp=sharing

Then in google, usually people do this: https://www.google.com/search?q=%22Causal+Intervention%22+inurl%3Aaclanthology.org+inmeta%3A%22Ziwei+Chen%22 with:

```
"Causal Intervention" inurl:aclanthology.org inmeta:"Ziwei Chen"
```

If the bibtex in `<meta>` of the HTML, then this is possible:

```
"Causal Intervention" inurl:aclanthology.org inmeta:"chen-etal-2023-causal"
```

Meanwhile, to get it automatically, users can still do something like:

```python
import requests
from bs4 import BeautifulSoup

response = requests.get('https://aclanthology.org/2023.acl-long.37/')

bsoup = BeautifulSoup(response.content.decode('utf8'))
bsoup.find('span', attrs={'id':'citePaperBibkey'}).text
```

Hope the info above helps! Look forward to more search features from ACL Anthology

**Comment by mbollmann** [comment]
> Meanwhile, to get the bib ID automatically, users can still do something like:
> 
> ```python
> import requests
> from bs4 import BeautifulSoup
> 
> response = requests.get('https://aclanthology.org/2023.acl-long.37/')
> 
> bsoup = BeautifulSoup(response.content.decode('utf8'))
> bsoup.find('span', attrs={'id':'citePaperBibkey'}).text
> ```

Going through some old issues I had saved, and wanted to note that by now, users can already do

```python
from acl_anthology import Anthology

anthology = Anthology.from_repo()
anthology.get("2023.acl-long.37").bibkey
```
