### ISSUE TITLE
Ingestion Request: SIGDIAL 2023

### ISSUE THREAD

**Issue by Merterm** [acl-org/acl-anthology#2814]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

SIGDIAL

### Volume Title

Proceedings of the 24th Annual Meeting of the Special Interest Group on Discourse and Dialogue

### Supporting Information

Please find the tarball file of the proceedings in this link: [https://drive.google.com/file/d/10lNHA8GdYxn4ku1-V7GJmJyJCqxgc-Uu/view?usp=sharing](url)

**Comment by anthology-assist** [comment]
@Merterm When's the desired publication date?

**Comment by Merterm** [comment]
> @Merterm When's the desired publication date?

The conference already happened, so as soon as possible. Thank you!

**Comment by Merterm** [comment]
I would like to add a workshop proceedings that happened during this conference. I opened a new issue here #2852, but do I need to do anything else? Thank you very much!
