### ISSUE TITLE
INLG cleanup

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#2823]
@anthology-assist can you please:

* Add a `<venue>sigdial</venue>` tag to all INLG 2023 main conference volumes
* Add a `<venue>ws</venue>` tag to all workshops that were just imported
* Add the SIG affiliations per @nschneid's request above?

We could also create an event block in the `2023.sigdial.xml` file and list all these workshops as affiliated with it, too, to they'll appear on both event pages (https://aclanthology.org/events/sigdial-2023/ and https://aclanthology.org/events/inlg-2023/).

_Originally posted by @mjpost in https://github.com/acl-org/acl-anthology/issues/2730#issuecomment-1745726948_

**Comment by mdingemanse** [comment]
Let me note here that this open issue is relevant as SIGdial and INLG are both mentioned there as venues that for some reason stopped getting DOIs: https://github.com/acl-org/acl-anthology/issues/2836
