### ISSUE TITLE
Ingestion Request: MT Summit 2023

### ISSUE THREAD

**Issue by ksudoh** [acl-org/acl-anthology#2824]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

MTSummit

### Volume Title

Proceedings of Machine Translation Summit XIX

### Supporting Information

The conference already happened in the last month, and all the proceedings volumes are ready:
https://drive.google.com/file/d/1nOZoTWPaKLEpVJzyNH8-IIKGMVVEjxOq/view?usp=drive_link

**Comment by anthology-assist** [comment]
@mjpost There is a workshop called `coco4MT`, which is associated with [amta](https://aclanthology.org/volumes/2022.amta-coco4mt/) last year.  This year it's associated with [mtsummit](https://aclanthology.org/venues/mtsummit/). Do we want to ingest it as a colocated event with its standalone venue (i.e. `2023.coco4mt-1`) which results in a new venue 'coco4mt', or do we want to ingest it as a mtsummit volume (i.e. 2023-mtsummit-coco4mt)?

**Comment by ksudoh** [comment]
@anthology-assist @mjpost The workshop organizers prefer "to ingest it as a mtsummit volume (i.e. 2023-mtsummit-coco4mt)".
