### ISSUE TITLE
Paper Metadata: 2023.sigdial-1

### ISSUE THREAD

**Issue by Merterm** [acl-org/acl-anthology#2825]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.sigdial-1

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

There is a request from the organizing committee to change the ordering of the names in the proceedings from the current "David Schlangen, Svetlana Stoyanchev, Shafiq Joty, Ondrej Dusek, Casey Kennington, Malihe Alikhani" to "Svetlana Stoyanchev, Shafiq Joty, David Schlangen, Ondrej Dusek, Casey Kennington, Malihe Alikhani". Is it possible to do this? The first author essentially will be moved to the third author position. Please let me know if I need to do something else other than commenting here for this. The PDF does not contain the author ordering, so this is only going to be a correction in the metadata. Thank you very much in advance!

I have also made a comment on this issue here: #2817

**Comment by Merterm** [comment]
Hello, I wanted to get an update on this. When will this change be live?

**Comment by mbollmann** [comment]
@Merterm We process corrections in batches at the end of each month or shortly after.
