### ISSUE TITLE
Ingestion Request: 12th Global Wordnet Conference

### ISSUE THREAD

**Issue by arademaker** [acl-org/acl-anthology#2849]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

GWC

### Volume Title

Proceedings of the 12th Global Wordnet Conference

### Venue Name (only if you are submitting a new venue)

The 12th Global Wordnet Conference

### Venue Website (only if you are submitting a new venue)

https://www.hitz.eus/gwc2023/home

### Date of Publication

2023-01-01

### Supporting Information

Link to the files
https://www.dropbox.com/scl/fi/gc2ucx5ddtw02ic4knaba/gwc2023_data.tgz?rlkey=x7xftnzfn6tlppg8ae57s38a7&dl=0

Two SIGs accepted to endorse the Global Wordnet Conference: SIGSEM and SIGLEX. Do you know if ACL Anthology can provide the DOI numbers described in https://aclanthology.org/faq/?

We obtained the ISBN of this volume directly from the conference's local organizers. It is on the second page of the proceedings. I didn’t find a field in the meta file to add the ISBN.

Please let me know of any missing information. Could you please confirm if you have all you need to publish the proceedings in the ACL Anthology? The previous proceedings are https://aclanthology.org/venues/gwc/

**Comment by arademaker** [comment]
Any update here? Can I help somehow?

**Comment by anthology-assist** [comment]
@arademaker Please checkout the preview in #2861 and let me know if anything looks incorrect.

**Comment by arademaker** [comment]
See https://github.com/acl-org/acl-anthology/pull/2861#issuecomment-1786115732
