### ISSUE TITLE
Ingestion Request: SIGDIAL Workshop Taming Large Language Models (TLLM)

### ISSUE THREAD

**Issue by Merterm** [acl-org/acl-anthology#2852]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

SIGDIAL

### Volume Title

Proceedings of the 1st Workshop on Taming Large Language Models

### Venue Name (only if you are submitting a new venue)

Workshop on Taming Large Language Models

### Venue Website (only if you are submitting a new venue)

https://ctrlnlg.github.io/

### Date of Publication

2023-09-12

### Supporting Information

Please find the zip [here](https://drive.google.com/file/d/1xhAgLxf6K-cGwEl-9zgrRbn4RKVoqdqw/view?usp=sharing). This is a workshop proceedings that happened in SIGDIAL 2023. Would you be able to make it available online as soon as possible?  I was not sure how to exactly open a new issue on the proceedings of a workshop, so I did it like a regular venue, if there are other necessary steps please let me know. Thank you very much! I also made a comment on issue #2814.

**Comment by mjpost** [comment]
@anthology-assist please make sure to add the workshop venue tag and backlink this from SIGDIAL.

**Comment by Merterm** [comment]
> @anthology-assist please make sure to add the workshop venue tag and backlink this from SIGDIAL.

How can I do the backlinking? The venue tag is the same as SIGDIAL, as it happened there. I checked previous workshops that happened in previous SIGDIALs, and they had the same venue tag as SIGDIAL, how should I proceed with that?

Thank you.

**Comment by anthology-assist** [comment]
@Merterm Do you want the tile to be fixed in #2862?

**Comment by Merterm** [comment]
> @Merterm Do you want the tile to be fixed in #2862?

Sure, I think Annual can be added yes please. Thanks!

**Comment by Merterm** [comment]
Hello, when will the proceedings for the TLLM be available online? Thank you very much!

**Comment by mjpost** [comment]
Just merged, should be live in ~20
