### ISSUE TITLE
Ingestion Request: CG-MTA 2023 (NoDaLiDa 2023 workshop)

### ISSUE THREAD

**Issue by alumae** [acl-org/acl-anthology#2857]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

cg-mta

### Volume Title

Proceedings of the NoDaLiDa 2023 Workshop on Constraint Grammar - Methods, Tools and Applications

### Venue Name (only if you are submitting a new venue)

Constraint Grammar - Methods, Tools, and Applications

### Venue Website (only if you are submitting a new venue)

https://edu.visl.dk/nodalida2023.html

### Supporting Information

This workshop was a part of the Nordic Conference of Computational Linguistics (NoDaLiDa) 2023.

**Comment by anthology-assist** [comment]
@alumae Could you submit ingestion material?

**Comment by alumae** [comment]
We are still waiting for ISBN from ACL. I wrote an e-mail to ACL Business Manager (acl.rachford@gmail.com), that's the correct process right?

**Comment by alumae** [comment]
@anthology-assist Gentle reminder that the material is ready for ingestion

**Comment by alumae** [comment]
@anthology-assist I see that the corresponding PR is waiting for a reviewer. I confirm that the preview site https://preview.aclanthology.org/CGMTA-ingestion-2023/2023.cgmta-1.0/ looks fine.

**Comment by alumae** [comment]
@anthology-assist @xinru1414 I beg you to tell me, what do I need to do to get this finalized?

**Comment by alumae** [comment]
Please, is there anything I can do to get this moving again?

**Comment by anthology-assist** [comment]
@mjpost Could you review this quick? Thank you!

**Comment by mjpost** [comment]
Hi @alumae, we are ready to make this live, but I am wondering if this workshop is a one-off workshop, or one that will likely happen against independently of nodalida? It affects whether we create it as a new venue or a nodalida-specific workshop.

**Comment by alumae** [comment]
It is likely that the workshop will happen again as a NoDaLiDa workshop.

**Comment by mjpost** [comment]
Okay, thanks. Instead of assigning it its own venue ID, then, I will create it as a NoDaLiDa-specific workshop (so its Anthology ID will be 2023.nodalida-cgmta). If that is a problem, please let me know. I will make the changes and merge this right away.

**Comment by alumae** [comment]
Thta's fine with us.
