### ISSUE TITLE
Ingest old IWPT proceedings

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#286]
We are missing a number of [early IWPT proceedings](https://aclweb.org/anthology/sigs/sigparse/):

- [x]  IWPT 2003
- [x]  IWPT 2001 (have PS from Giorgio S.)
- [x]  IWPT 2000 (Alberto L., Harry B.)
- [x]  IWPT 1997 (Harry B.)
- [x]  IWPT 1995 (Harry B., @dseddah)
- [x]  IWPT 1993 (Alberto L., Harry B.)
- [x]  IWPT 1991 (Alberto L.)
- [x]  IWPT 1989

I have sent an email to the SIGPARSE mailing list and found a number of both hard and digital copies, and will use this issue to track their ingestion. Check boxes above indicate PDFs I have in hand, while parenthetical notes mark folks who have indicated they have a hard copy of the proceedings that we could send in for scanning.

**Comment by dseddah** [comment]
Hey, I do have the 1995 proceedigns here.

**Comment by kilian-gebhardt** [comment]
The IWPT 1989 proceedings are in the CMU library: https://cmu.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma991001383809704436&context=L&vid=01CMU_INST:01CMU&search_scope=MyInst_and_CI&tab=Everything&lang=en

Maybe we can find someone who has access there to scan them/ask the library directly?

**Comment by mjpost** [comment]
This is great! I wonder if the library would do it for us. Do you have time to contact them?

**Comment by kilian-gebhardt** [comment]
> This is great! I wonder if the library would do it for us. Do you have time to contact them?

I wrote them an email. [[project-card]](https://github.com/acl-org/acl-anthology/projects/11#card-21898998)

**Comment by mjpost** [comment]
Awesome. I added a few completed projects, since I like to seed the DONE list.
