### ISSUE TITLE
Paper Metadata: 2023.rocling-1.8

### ISSUE THREAD

**Issue by karol-nowakowski** [acl-org/acl-anthology#2868]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.rocling-1.8

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Nowakowski, Karol and Ptaszynski, Michal

**Comment by anthology-assist** [comment]
@karol-nowakowski I do not see the metadata problem here: https://aclanthology.org/2023.rocling-1.8/

**Comment by karol-nowakowski** [comment]
> @karol-nowakowski I do not see the metadata problem here: https://aclanthology.org/2023.rocling-1.8/

Yes, now it's correct. Perhaps it has been edited by the conference organizers. Anyway, this issue can be closed, thank you!
