### ISSUE TITLE
J79-J83 should be "American Journal of Computational Linguistics"

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#287]
and changed its name only in 1984. The name "Computational Linguistics" is hard-coded, so I'm not sure if this is an easy change.

**Comment by davidweichiang** [comment]
Also, it appears that the way to cite articles in these years is not by volume and issue, but by microfiche number. The BibTeX would be something like:

```
@article {key,
  title = ...,
  author = ...,
  journal = "American Journal of Computational Linguistics",
  month = "April",
  year = "1977",
  note = "Microfiche 123",
  pages = "123--456",
```

Can we add a `note` field to the XML?

**Comment by davidweichiang** [comment]
Ideally, shouldn't the `journal`/`booktitle` field come from the `title` of the 000-numbered entry? @mbollmann

**Comment by mbollmann** [comment]
I think the reason for this being hardcoded—as I just copied that behavior over from the old website—might be that CL title fields look like `Computational Linguistics, Volume 40, Issue 1 - March 2014`; i.e., they contain the volume/issue title as it should appear on the website, not journal title only.

A cleaner solution would be to make the XML fields more BibTeX-like, i.e.,

```xml
<title>Computational Linguistics</title>
<volume>40</volume>
<issue>1</issue>
<month>04</month>
```

and have the Python scripts construct the correct display title for the website. As it is right now, they actually work the opposite way: there are regexes that parse those title strings for volume/issue information, as it's injected into the Google Scholar metadata tags.

**Comment by davidweichiang** [comment]
My commit above fixes this the easy way, but I agree that your proposed solution is the right one. Should we close this issue and start a new one?

**Comment by mjpost** [comment]
If #285 is ready to merge, we could close this and move to a new issue. But it wouldn't hurt to keep it all in place place.
