### ISSUE TITLE
Paper Revision{EMNLP-23 Paper ID: 396}

### ISSUE THREAD

**Issue by hqsiswiliam** [acl-org/acl-anthology#2870]
### Anthology ID

EMNLP-23 Paper ID: 396

### Type of Change

Revision

### PDF of the Revision or Erratum

PDF Revision Link:
[https://drive.google.com/file/d/1FCodk6PUFszjjQtDynOyKHVUlHCaV_YJ/view?usp=sharing](https://drive.google.com/file/d/1FCodk6PUFszjjQtDynOyKHVUlHCaV_YJ/view?usp=sharing)

### Brief Description of Changes

Update our submission to include the missing author's name. The change does not involve altering the content or the order of the authors but to correct the omission.

**Comment by anthology-assist** [comment]
@hqsiswiliam Please update the anthology ID
