### ISSUE TITLE
Paper Revision{2023.findings-emnlp.455}

### ISSUE THREAD

**Issue by SuperHalo** [acl-org/acl-anthology#2872]
### Anthology ID

2023.findings-emnlp.455

### Type of Change

Revision

### PDF of the Revision or Erratum

PDF Revision Link:
[https://drive.google.com/drive/folders/1AnO7xpA5cJguh4uAkNN7lu6eOgNY4VYc?usp=sharing](https://drive.google.com/drive/folders/1AnO7xpA5cJguh4uAkNN7lu6eOgNY4VYc?usp=sharing)

### Brief Description of Changes

- Add the Acknowledgements section
- Remove the braces around authors' email addresses
- Update Figure 1 to correct the sequence number of the selected frame in the Uniform frame selection method
- Replace the symbol $f_{T'}$ with $f_{V'}$  in the Interactive Frame Selection of Section 3.2.2

**Comment by anthology-assist** [comment]
@SuperHalo Please update the anthology ID

**Comment by SuperHalo** [comment]
Hello,

First of all, I would like to express my sincere gratitude for your diligent efforts in editing the file.

I have noticed that the original version is not available on the website(https://aclanthology.org/2023.findings-emnlp.455/). What's more, could you please guide me on how to add these page numbers and EMNLP footnotes back to the document? Where could I find the template for the published version? It would be immensely helpful for our documentation process.

Thank you very much.

**Comment by SuperHalo** [comment]
Hello,

First of all, I would like to express my sincere gratitude for your diligent efforts in editing the file.

I apologize for the oversight in the previous revised version of the paper, where the page numbers and conference name were missed in the footnotes. I have added these contents in the new revised paper, and you can find the updated version here:  [2023.findings-emnlp.455-v3](https://drive.google.com/file/d/1HAG35sOjTmOcYZHk5cz1H3Ufr2LxBbCW/view?usp=drive_link).

Thank you very much.
