### ISSUE TITLE
Paper Metadata: 2023.finnlp-1.7

### ISSUE THREAD

**Issue by lefterisloukasHelvia** [acl-org/acl-anthology#2878]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.finnlp-1.7

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Lefteris Loukas, Ilias Stogiannidis, Prodromos Malakasiotis, Stavros Vassos

**Comment by anthology-assist** [comment]
@lefterisloukasHelvia Could you clarify which names need to be corrected? https://aclanthology.org/2023.finnlp-1.7/ ?

**Comment by lefterisloukasHelvia** [comment]
The Support team fixed it already. Thank you very much! Closing this.
