### ISSUE TITLE
Ingestion Request: {ICNLSP (2023-12-31)}

### ISSUE THREAD

**Issue by icnlsp** [acl-org/acl-anthology#2879]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

ICNLSP

### Volume Title

Proceedings of the 6th International Conference on Natural Language and Speech Processing (ICNLSP-2023))

### Venue Name (only if you are submitting a new venue)

International Conference on Natural Language and Speech Processing

### Date of Publication

2023-12-31

**Comment by anthology-assist** [comment]
@icnlsp Please submit your ingestion material.

**Comment by icnlsp** [comment]
Done.

**Comment by icnlsp** [comment]
@anthology-assist done
