### ISSUE TITLE
Paper Revision: 2023.inlg-main.34

### ISSUE THREAD

**Issue by dmhowcroft** [acl-org/acl-anthology#2889]
### Anthology ID

2023.inlg-main.34

### Type of Change

Revision

### PDF of the Revision or Erratum

[2023_sgge_paper-2.pdf](https://github.com/acl-org/acl-anthology/files/13481374/2023_sgge_paper-2.pdf)
[2023_sgge_paper-2_supplemental.pdf](https://github.com/acl-org/acl-anthology/files/13459670/2023_sgge_paper-2_supplemental.pdf)

### Brief Description of Changes

This version corrects descriptive corpus statistics, because some conversations, summaries, and participants were erroneously excluded. There are 66 conversations (not 43), 106 summaries (not 61), and 24 participants (not 19). Changes can be found in the Abstract, the Corpus Analysis (Section 3), and the Appendix.

**Comment by dmhowcroft** [comment]
Used this code to add the copyright / proceedings detail overlay: https://gist.github.com/dmhowcroft/3e3a0f55917f8987132d277608de512f

**Comment by anthology-assist** [comment]
@dmhowcroft Could you update the paper anthology id? 2023.inlg-1.34  does not exist.

**Comment by dmhowcroft** [comment]
Updated! Sorry about that. This is the paper in question: https://aclanthology.org/2023.inlg-main.34/
