### ISSUE TITLE
Revision to Paper: Aligning Script Events with Narrative Texts

### ISSUE THREAD

**Issue by SimonOst** [acl-org/acl-anthology#289]
ACL Anthology ID: S17-1016

We found a bug in the evaluation script, which is now fixed. The numbers have changed, but this does not affect the final result of the paper. We attached an updated paper version.

[*SEM2017_NEU.pdf](https://github.com/acl-org/acl-anthology/files/3130454/SEM2017_NEU.pdf)

**Comment by SimonOst** [comment]
Hi,

it looks like the revised version cannot be accessed - I get a "File not found" error when I try to access it on https://www.aclweb.org/anthology/S17-1016v2 . 

Best
Simon

**Comment by mjpost** [comment]
Fixed.
