### ISSUE TITLE
Paper Revision{2023.findings-emnlp.913}

### ISSUE THREAD

**Issue by 9meo** [acl-org/acl-anthology#2894]
### Anthology ID

Paper ID: 2968

### Type of Change

Revision

### PDF of the Revision or Erratum

[EMNLP_2023__MTL_of_Generation_and_Classification__CRC-rv2.pdf](https://github.com/acl-org/acl-anthology/files/13538471/EMNLP_2023__MTL_of_Generation_and_Classification__CRC-rv2.pdf)

### Brief Description of Changes

paper titled "Multi-Task Learning of Query Generation and Classification for Generative Conversational Question Rewriting" (Paper ID: 2968).
Only Figure 4 needs changing, the source file called a different figure file, instead of the correct one; no change in text.

**Comment by anthology-assist** [comment]
@9meo Could you specify the anthology ID?

**Comment by 9meo** [comment]
@anthology-assist 

Anthology ID
2023.emnlp-finding.2968
