### ISSUE TITLE
Paper Revision(EMNLP2023-1713)

### ISSUE THREAD

**Issue by Patrick-Ni** [acl-org/acl-anthology#2896]
### Anthology ID

EMNLP2023-1713

### Type of Change

Revision

### PDF of the Revision or Erratum

[EMNLP2023_knowEE_Xuanfan_Ni.pdf](https://github.com/acl-org/acl-anthology/files/13557524/EMNLP2023_knowEE_Xuanfan_Ni.pdf)

### Brief Description of Changes

Fix a typo in page 2 "...We leverage five **extrenal** datasets and extract the most relevant samples.." -> "...We leverage five **external** datasets and extract the most relevant samples..."

**Comment by anthology-assist** [comment]
@Patrick-Ni Could you update the anthology ID?

**Comment by Patrick-Ni** [comment]
> @Patrick-Ni Could you update the anthology ID?

sure! the anthology ID of my paper is 2023.emnlp-main.771

**Comment by Patrick-Ni** [comment]
> @Patrick-Ni Could you update the anthology ID?

https://aclanthology.org/2023.emnlp-main.771/
