### ISSUE TITLE
Paper Metadata: {2022.emnlp-main.744}

### ISSUE THREAD

**Issue by boychaboy** [acl-org/acl-anthology#2899]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2022.emnlp-main.744

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

**AS-IS:**
Younghoon Jeong, Juhyun Oh, Jongwon Lee, Jaimeen Ahn, Jihyung Moon, Sungjoon Park, Alice Oh

**TO-BE:** (correction in **BOLD**)
**Younghun Jeong,** Juhyun Oh, Jongwon Lee, Jaimeen Ahn, Jihyung Moon, Sungjoon Park, Alice Oh

**Comment by boychaboy** [comment]
@xinru1414 Thank you for your support. I wonder why the process has been pended?

**Comment by mbollmann** [comment]
@boychaboy “Pending” means it has been handled and will be merged with all other corrections at the end of the month.
