### ISSUE TITLE
Incomplete abstracts for COLING2018

### ISSUE THREAD

**Issue by evanmiltenburg** [acl-org/acl-anthology#290]
The proceedings for [COLING2018](https://aclweb.org/anthology/volumes/proceedings-of-the-27th-international-conference-on-computational-linguistics/) have incomplete abstracts. Typically the abstracts only show (part of) the first sentence, e.g. https://aclweb.org/anthology/papers/C/C18/C18-1147/

**Comment by mjpost** [comment]
It's not all of them—the paper immediately [before](https://aclweb.org/anthology/C18-1146/) and [after](https://aclweb.org/anthology/papers/C18-1148/) have them. But I have found some others (e.g., [C18-1001](https://aclweb.org/anthology/papers/C18-1001/)), browsing through [the XML](https://github.com/acl-org/acl-anthology/blob/master/data/xml/C18.xml).

**Comment by evanmiltenburg** [comment]
Ah, I just checked one other paper to test whether it also applied to other papers. That's the one that I randomly clicked..

**Comment by mjpost** [comment]
My guess would have been that there was a stray LaTeX `%` character that wasn't properly dealt with. This seems more extensive. It has been there since at least commit ab4420ed8bd3bf958ff755bef9c3654a78d15564 (March 20), when the data was reorganized.

**Comment by davidweichiang** [comment]
It's been like that since `C18.xml` was added: https://github.com/acl-org/acl-anthology/blob/84d722312b476bbac18e65b2d92494ae6928a54a/import/C18.xml

**Comment by mjpost** [comment]
I found the original data, so this should be an easy fix with our new scripts.
