### ISSUE TITLE
Paper Metadata: {2023.banglalp-1.43}

### ISSUE THREAD

**Issue by AridHasan** [acl-org/acl-anthology#2922]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.banglalp-1.43

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

In our paper, the fourth author was not added to the metadata. The correct author order with the new author is given below: 

```Prerona, Tarannum; Md. Arid, Hasan; Krishno, Dey; Sheak Rashed Haider, Noori;```

Note: First name and Last name are comma (,) separated and authors are separated using a semicolon (;)

**Comment by anthology-assist** [comment]
@AridHasan Could you provide the last two authors' affiliation?

**Comment by AridHasan** [comment]
@anthology-assist Please check the following information for all the authors:
```
Prerona Tarannum
Daffodil International University, Dhaka, Bangladesh

Md. Arid Hasan
SE+AI Lab, University of New Brunswick, Fredericton, Canada

Krishno Dey
SE+AI Lab, University of New Brunswick, Fredericton, Canada

Sheak Rashed Haider Noori
Daffodil International University, Dhaka, Bangladesh
```

**Comment by AridHasan** [comment]
> @AridHasan Could you provide the last two authors' affiliation?

@anthology-assist Please check the following information for all the authors:

```
Prerona Tarannum
Daffodil International University, Dhaka, Bangladesh
prerona15-14134@diu.edu.bd

Md. Arid Hasan
SE+AI Lab, University of New Brunswick, Fredericton, Canada
arid.hasan@unb.ca

Krishno Dey
SE+AI Lab, University of New Brunswick, Fredericton, Canada
krishno.dey@unb.ca

Sheak Rashed Haider Noori
Daffodil International University, Dhaka, Bangladesh
drnoori@daffodilvarsity.edu.bd
```
