### ISSUE TITLE
Paper Metadata: 2023.emnlp-main.325, 2023.emnlp-main.336, 2023.emnlp-main.1037, 2023.findings-emnlp.962

### ISSUE THREAD

**Issue by jjessyli** [acl-org/acl-anthology#2927]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.emnlp-main.325, 2023.emnlp-main.336, 2023.emnlp-main.1037, 2023.findings-emnlp.962

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Hello, for these papers I have noticed that my name is listed as Junyi Li, but it should be Junyi Jessy Li (double first name, "Jessy" is not a middle name). Strangely, this is the first time that this happened; my OpenReview page has the correct name, and ACL Anthology ingestion was fine with ACL and NAACL in 2022 when OpenReview was also used. Please help look into this, thanks! -- Jessy

**Comment by mjpost** [comment]
Hi, I'll correct these manually. We made a call not to import the `middle_name` field because many authors list that name but do not want it to appear. We will work on clarifying the documentation on this.

**Comment by mjpost** [comment]
Note that in the files handed to us, "Jessy" is listed as your middle name.
