### ISSUE TITLE
Paper Revision: 2023.emnlp-main.167

### ISSUE THREAD

**Issue by BeneciaLee** [acl-org/acl-anthology#2932]
### Anthology ID

2023.emnlp-main.167

### Type of Change

Revision

### PDF of the Revision or Erratum

[A Framework for Vision-LanguageWarm-up Tasks in Multimodal(revision).pdf](https://github.com/acl-org/acl-anthology/files/13634656/A.Framework.for.Vision-LanguageWarm-up.Tasks.in.Multimodal.revision.pdf)

### Brief Description of Changes

Fixed the sponsor in the Acknowledgments section.

**Comment by BeneciaLee** [comment]
Hello,

First of all, I would like to express my sincere gratitude for your diligent efforts in editing the file.

I have noticed that in the current version being edited, the page numbers and EMNLP footnotes seem to have disappeared. Could you please guide me on how to add these page numbers and EMNLP footnotes back to the document? It would be immensely helpful for our documentation process.

Thank you very much.

**Comment by anthology-assist** [comment]
@BeneciaLee You'll need to modify the PDF by yourself.
