### ISSUE TITLE
Bad redirection

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#294]
The URL 
- [https://www.aclweb.org/anthology/N/N10/N10-1115.pdf](https://www.aclweb.org/anthology/N/N10/N10-1115.pdf)
redirects to the invalid URL 
- [https://www.aclweb.org/portal/https://www.aclweb.org/anthology/N10-1115/N10/N10-1115.pdf](https://www.aclweb.org/portal/https://www.aclweb.org/anthology/N10-1115/N10/N10-1115.pdf)
but it should redirect to 
- [https://www.aclweb.org/anthology/N10-1115](https://www.aclweb.org/anthology/N10-1115)
This is a problem with the `.htaccess` file that is not immediately obvious to me. It must have worked before, too, since our Google search gives the correct URL.

**Comment by mbollmann** [comment]
My gut feeling is that there's something in the root `.htaccess` that takes precedence over our own `.htaccess`, but only a server admin can verify that. :)
