### ISSUE TITLE
Correct the name of a co-author 

### ISSUE THREAD

**Issue by Khalid-AlKhatib** [acl-org/acl-anthology#2963]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.emnlp-main.166

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)

**Comment by anthology-assist** [comment]
@Khalid-AlKhatib Is this a #2964 duplicate?

**Comment by Khalid-AlKhatib** [comment]
Yes
