### ISSUE TITLE
Event metadata: address of EMNLP workshops 2023.bigpicture-1 & 2023.newsum-1

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#2965]
- [2023.bigpicture-1](https://aclanthology.org/volumes/2023.bigpicture-1/) has "Singapore, Singapore". Should be just "Singapore".
- [2023.newsum-1](https://aclanthology.org/volumes/2023.newsum-1/) has just "Hybrid". I would suggest "Singapore (Hybrid)", which a couple of the other workshops are using, or just "Singapore" echoing the main conference.

**Comment by yanaiela** [comment]
@nschneid?

**Comment by nschneid** [comment]
I'm not sure, maybe send the PDF to @xinru1414?
