### ISSUE TITLE
Paper Revision{2023.rocling-1.1.pdf to 2023.rocling-1.56.pdf}

### ISSUE THREAD

**Issue by ouartz99** [acl-org/acl-anthology#2994]
### Anthology ID

2023.rocling-1.1.pdf to 2023.rocling-1.56.pdf

### Type of Change

Revision

### PDF of the Revision or Erratum

https://drive.google.com/drive/folders/1HfyS8u9ViARrL5BfV40Mcla7Ceb5ahbf

### Brief Description of Changes

Add the page number for 2023.rocling-1.1.pdf to 2023.rocling-1.56.pdf
Thank you very much.

**Comment by anthology-assist** [comment]
@ouartz99 I'm not entirely sure I understand the problem here. Could you please explain again?

**Comment by ouartz99** [comment]
@anthology-assist 
The PDFs you currently see on rocling 2023 on aclanthology.org do not have page numbers. For example: 2023.rocling-1.1.pdf (https://aclanthology.org/2023.rocling-1.1.pdf)

As a result, we have added page numbers to all the PDFs. All PDFs that need to be changed will change from 2023.rocling-1.1.pdf to 2023.rocling-1.56.pdf. You can access all our PDFs with added page numbers on Google Drive (https://drive.google.com/drive/folders/1HfyS8u9ViARrL5BfV40Mcla7Ceb5ahbf).

Thank you very much.

**Comment by mjpost** [comment]
If you want to add proper footers, we will need to do a complete re-ingestion from the original materials.

**Comment by anthology-assist** [comment]
Yes I was going to suggest the same thing. We will need to reingest, which means we will need the complete new ingestion material.

**Comment by ouartz99** [comment]
@mjpost  and @anthology-assist  Thank you for your reply, I will prepare all the data and proceed with the new ingestion.

**Comment by anthology-assist** [comment]
dupe https://github.com/acl-org/acl-anthology/issues/3085
