### ISSUE TITLE
Ingestion Pipeline documentation

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#30]
Documentation for ingesting new documents from STARTv2 into the Rails app shall be put up on the GitHub Wiki.

**Comment by knmnyn** [comment]
Here are some sample files from NoDaLiDa 1999.  Usually we get the entire proceedings.tgz archive with the cdrom/ subdirectory which we process.  This is a simple example which has no attachments or abstracts that represent more advanced cases of ingestion.

[](url)
[proceedings_cdrom.zip](https://github.com/WING-NUS/acl/files/748603/proceedings_cdrom.zip)

**Comment by CTNLP** [comment]
There is now some documentation concerning the ingestion focused on the NoDaLiDa 99 proceedings here: https://github.com/acl-org/acl-anthology/wiki/Ingestion Martín will try to add more information on where to put the relevant pdfs and additional data. It would be great if @knmnyn could check if this documentation matches with the general workflow. Then we can use it to train other people to do the ingestion.

**Comment by knmnyn** [comment]
Hi @CTNLP , all:

I've spent a bit of time hyperlinking and adding detail to the document.  The basic process should be clearer now.  Please help check.  If you think adequate for the time being, feel free to close.

**Comment by CTNLP** [comment]
Just checked it and it seems much better now. Thanks @knmnyn . I think other people should be able to do ingestion based on this documentation.
