### ISSUE TITLE
Paper Metadata: 2023.findings-emnlp.1054

### ISSUE THREAD

**Issue by boblus** [acl-org/acl-anthology#3004]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.findings-emnlp.1054

### Type of Paper Metadata Correction

- [X] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)

### Correction to Paper Title

Please change the paper title appeared in Cite (ACL) and Cite (Informal) to "Measuring Pointwise 𝒱-Usable Information In-Context-ly"

**Comment by anthology-assist** [comment]
@boblus could you point out specifically what's wrong? https://aclanthology.org/2023.findings-emnlp.1054/

**Comment by boblus** [comment]
The title appears in Cite (ACL) and Cite (Informal) is “Measuring Pointwise 𝒱-Usable Information In-Context-ly-Usable Information In-Context-ly,” which is incorrect.

**Comment by mbollmann** [comment]
@anthology-assist This looks like a bug in the code, not a metadata problem. I'll check.
