### ISSUE TITLE
Coauthor lists contain duplicates

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#305]
If person X coauthors with person Y and X uses two name variants X1 and X2, then Y's name will appear twice in X's coauthor list (https://aclweb.org/anthology/people/i/ioannis-kakadiaris/)

Also, X will appear twice in Y's coauthor list, under two different names (https://aclweb.org/anthology/people/a/anastasia-krithara/)

Both of these are bugs, right? Should `AnthologyIndex.coauthors` use only canonical names (or unique IDs when we have them), not names?

**Comment by mbollmann** [comment]
Up to interpretation, I guess, but I do feel it would make more sense to use canonical names here, yes.
