### ISSUE TITLE
Ingestion Request [09-01-2024]:  20th Conference on Natural Language Processing (KONVENS 2024)

### ISSUE THREAD

**Issue by peluz** [acl-org/acl-anthology#3062]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

konvens

### Volume Title

Proceedings of the 20th Conference on Natural Language Processing (KONVENS 2024) 

### Date of Publication

2024-09-01

### Supporting Information

We will also have proceedings for the co-located workshops.

**Comment by tschomacker** [comment]
Hi, we would like to register this year's GermEval Shared Task 2 (https://german-easy-to-read.github.io/statements/).
**Volume Title:** Proceedings of the GermEval 2024 Shared Task Statement Segmentation in German Easy Language

How should we provide the papers? Can we upload it to our GitHub repository and share the links with you?
Best,
Thorben

**Comment by peluz** [comment]
@tschomacker 
Dear Thorben,

You can find instructions on how to prepare proceedings here: https://aclanthology.org/info/contrib/.
You should generate your proceedings and assemble the data in the format described here (https://acl-org.github.io/ACLPUB/anthology.html).
Then you can share the link to the data here.

Kind regards,
Pedro (Publication Chair)

**Comment by irehbein** [comment]
Dear Pedro,
here's the link for the CPSS workshop proceedings:
https://gigamove.rwth-aachen.de/en/download/2e4a58c1c920ca3d7e6b9d01338656b2
Best,
Ines

**Comment by brgitte** [comment]
Dear Pedro, 
via the link https://www.ofai.at/germeval2024/f9488e8acce4381099cbfccbddd93/ you find a zip file containg 
- a directory with the copyright forms, 
- a directory with the input files and directories to aclpub2 for generating the proceedings,
- the generated PDF proceedings file
best, 
Brigitte

**Comment by peluz** [comment]
Dear @anthology-assist,

Please find the KONVENS 2024 proceedings and copyright transfers in the following link: https://drive.google.com/file/d/1moO_Glb2GOFptoAY74Bm7JjtDc1aM5W6/view?usp=drive_link
Is it enough to share the link here, or should we send the data elsewhere?

Kind regards,
Pedro

**Comment by brgitte** [comment]
Dear Pedro, 
this is the link to the corrected GerMS-Detect 2024 proceedings 
https://drive.google.com/file/d/1YeyVH5ZotIun_smu8-NiG3wkTD4F6n06/view?usp=sharing
regards, 
Brigitte

**Comment by tschomacker** [comment]
Dear @anthology-assist and @peluz 
I am very sorry for the delay! Here are the proceedings of our co-located workshop:
- StaGE: https://drive.google.com/file/d/1Y2r7aLtd9DJKXdT9V7AVk3fI62PQFQX1/view?usp=sharing 

Thank you for support in this. If anything is not in accordance with the proceedings requirements, please contact me.

**Comment by anthology-assist** [comment]
@peluz CPSS link is invalid. Could you update? 

Main and other workshops have been ingested here: https://github.com/acl-org/acl-anthology/pull/3883

**Comment by peluz** [comment]
@irehbein could you update the CPSS link? It's giving a 404 code.

**Comment by peluz** [comment]
@anthology-assist Here is a working link for CPSS: 
https://gigamove.rwth-aachen.de/en/download/ec0432ec62d31de37975f6f0a266c91f

**Comment by peluz** [comment]
@anthology-assist Thank you for supporting us with the ingestion of the proceedings. I see that the proceedings are now in the ACL Anthology.

I've noticed that the proceedings URL does not link to the complete proceedings pdf (https://aclanthology.org/volumes/2024.konvens-main/)
The expected webpage for the pdf (https://aclanthology.org/2024.konvens-main.pdf) raises a 404 error.

I am not sure what the proper way to solve this is. Should I create a Bug Report issue?

Best,
Pedro
