### ISSUE TITLE
Paper Revision 2023.findings-emnlp.647

### ISSUE THREAD

**Issue by shaigrt** [acl-org/acl-anthology#3067]
### Anthology ID

2023.findings-emnlp.647

### Type of Change

Revision

### PDF of the Revision or Erratum

[LMU___EMNLP_2023-22.pdf](https://github.com/acl-org/acl-anthology/files/14129534/LMU___EMNLP_2023-22.pdf)

### Brief Description of Changes

Removing ethics section; Omitting one author

**Comment by shaigrt** [comment]
[[EXTERNAL] Re: Request to remove author.pdf](https://github.com/acl-org/acl-anthology/files/14129552/EXTERNAL.Re.Request.to.remove.author.pdf)

Attached is permission from PCs of EMNLP for the removal of one author.

Unfortunately I am not sure how to add the EMNLP footer so I hope you can manage that. Thank you

**Comment by mbollmann** [comment]
> Unfortunately I am not sure how to add the EMNLP footer so I hope you can manage that. Thank you

We do not add footers or modify PDFs in any way. You can try adding it yourself (I believe the template should be https://github.com/rycolab/aclpub2/blob/main/aclpub2/templates/watermarked_pdf.tex) or we can process it without the footer also.

**Comment by shaigrt** [comment]
Hi, ok, please process it without
