### ISSUE TITLE
Reingestion: calcs

### ISSUE THREAD

**Issue by gentaiscool** [acl-org/acl-anthology#3068]
I am the organizer of calcs 2023 workshop. We found out that the hyperlinks on the proceedings do not work (https://aclanthology.org/2023.calcs-1.0/). We made fixes and wanted to update the proceedings. 

We want to get assistance in determining the best way to proceed. Thank you.

**Comment by mjpost** [comment]
Can you elaborate? What hyperlinks are you referring to?

**Comment by gentaiscool** [comment]
hi @mjpost thank you for replying. The citations on the papers should have clickable links that will direct us to the citations on the reference. But, in the current proceeding, the links are not clickable and broken. 

Let me know if you need more information about this.

**Comment by mjpost** [comment]
If you are talking about links inside the PDFs, that is not up to us, that is up to the individual authors who generated the papers.

If you are talking about something else, please provide a screenshot and explicit example.

**Comment by mbollmann** [comment]
@mjpost It seems you're talking past each other — it sounds like @gentaiscool is the workshop organizer and has generated the fixed PDFs.

**Comment by gentaiscool** [comment]
Thank you for mentioning @mbollmann I am one of the workshop organizers. 

Let me give you an example: the citation (Joshi, 1982) should be clickable and when it is clicked, it should direct us to the citation on the reference page.
<img width="398" alt="Screenshot 2024-02-07 at 7 03 56 PM" src="https://github.com/acl-org/acl-anthology/assets/2089264/9ee2e48a-3065-46c2-aba9-81c6a9e73c86">

I checked the original PDF sent by the authors and they are clickable. The issue is in the compilation stage and I have generated the fixed PDFs to replace the current proceeding. Let me know if you have more question @mjpost. Thank you for the help.

**Comment by anthology-assist** [comment]
@gentaiscool I think we will need to re ingest the entire volume (assuming the fix affects all papers). Could you link the updated ingestion material here?

**Comment by gentaiscool** [comment]
This is the link to the ingestion material https://github.com/gentaiscool/calcs2023_ingest

Thank you for the help.

**Comment by anthology-assist** [comment]
@gentaiscool I looked at the ingestion material here: https://github.com/gentaiscool/calcs2023_ingest and it seems incomplete. If you are following `aclpub2` format please follow instructions here: https://github.com/rycolab/aclpub2 and submit the `output` folder specified in the `Expected output` section.

**Comment by mjpost** [comment]
@gentaiscool You can run this script, which will tell you what's missing from your repository: https://github.com/acl-org/acl-anthology/blob/master/bin/aclpub2_format_check.py. We can't ingest until all the material is there.

**Comment by gentaiscool** [comment]
hi @mjpost I have updated the files and successfully run the script. Thanks

**Comment by gentaiscool** [comment]
hi @mjpost I want to follow up on the request. Let me know if you need anything from me. Thank you.

**Comment by mjpost** [comment]
ping @anthology-assist
