### ISSUE TITLE
2022.acl-long.275 - video is for a different paper

### ISSUE THREAD

**Issue by guyemerson** [acl-org/acl-anthology#3082]
For the paper 2022.acl-long.275 "Learning Functional Distributional Semantics with Visual Data", the linked video is for the paper "Automatic Error Analysis for Document-level Information Extraction", which appears to be for 2022.acl-long.274 instead.

**Comment by guyemerson** [comment]
@anthology-assist Could I have some kind of update on this?

**Comment by guyemerson** [comment]
Here is a related issue: https://github.com/acl-org/acl-anthology/issues/2264

**Comment by guyemerson** [comment]
@mjpost @davidstap @xinru1414 Could you help?

**Comment by davidstap** [comment]
Thanks for the tag I'll take a look soon!

**Comment by davidstap** [comment]
The video is not on our server, so I reached out to Underline. They should share the file soon, after which I'll fix the incorrect link. Thanks for your patience :)

**Comment by davidstap** [comment]
@guyemerson This is fixed now, thanks for your patience.
