### ISSUE TITLE
Reingestion Request: ROCLING (10-20-2023)

### ISSUE THREAD

**Issue by ouartz99** [acl-org/acl-anthology#3085]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

ROCLING

### Volume Title

Proceedings of the 35th Conference on Computational Linguistics and Speech Processing (ROCLING 2023)

### Venue Name (only if you are submitting a new venue)

Conference on Computational Linguistics and Speech Processing

### Venue Website (only if you are submitting a new venue)

https://rocling2023.github.io/

### Date of Publication

2023-10-20

### Supporting Information

Dear Anthology Director,

I'm Hou-Chiang Tseng who the publication chair of the 35th annual Conference on Computational Linguistics and Speech Processing (ROCLING 2023).

The conference website: https://rocling2023.github.io/

We want to register the ROCLING 2023 to ACL Anthology. Please see following two items:
(a) the complete list of volumes: please see the attached file,
and (b) all the new material can be downloaded from the following URL:
https://drive.google.com/drive/folders/1dxt_gYlUvmuLiNETgDRg9cGpiJxVGwbD?usp=sharing

If there is any question, please let me know.
[Anthology.Volume_ROCLING.2023.xlsx](https://github.com/acl-org/acl-anthology/files/14318157/Anthology.Volume_ROCLING.2023.xlsx)

Best regards,
Dr. Hou-Chiang Tseng

**Comment by anthology-assist** [comment]
Rocling 2023 has been ingested: https://aclanthology.org/volumes/2023.rocling-1/ Is there a reason for re-ingestion?

**Comment by ouartz99** [comment]
@anthology-assist 

After the discussion here: https://github.com/acl-org/acl-anthology/issues/2994#issuecomment-1934764637

mjpost and anthology-assist have informed me that I need to reingestion.

So I have prepared all the data and am proceeding with this re-ingestion.

I'm not sure if my current approach is correct; can you help me?

Thank you very much.

**Comment by anthology-assist** [comment]
@ouartz99 got it, thank you! I will re-ingest shortly.

**Comment by anthology-assist** [comment]
Closed by #3109
