### ISSUE TITLE
Paper Metadata: {2023.findings-emnlp.690}

### ISSUE THREAD

**Issue by mindojune** [acl-org/acl-anthology#3087]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.findings-emnlp.690

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

I am writing to request a correction in the author metadata currently listed in the ACL Anthology database for my publications. The present metadata incorrectly identifies my name as follows:

    First Name: Do
    Last Name: Min

This is inaccurate. My correct name, as it should appear, is detailed below:

    First Name: Do June
    Last Name: Min

For clarity, "Do June" is my first name, and "Min" is my last name, contrary to the current listing that separates my first name as "Do". I kindly ask that this correction be made to reflect the accurate representation of my name in all associated records and publications.

You can verify the correct metadata through this link: [ACL Anthology Author Page for Do June Min](https://aclanthology.org/people/d/do-june-min/).

I appreciate your attention to this matter and your prompt action to update the records accordingly. Please let me know if you require any further information or clarification from my side.

Thank you for your cooperation and understanding.

**Comment by anthology-assist** [comment]
Fixed: https://aclanthology.org/2023.findings-emnlp.690/
