### ISSUE TITLE
Ingestion Request [07-27-2024]: ACL 2024

### ISSUE THREAD

**Issue by MirunaClinciu** [acl-org/acl-anthology#3092]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

ACL

### Volume Title

Proceedings of the 62st Annual Meeting of the Association for Computational Linguistics 

### Venue Website (only if you are submitting a new venue)

https://2024.aclweb.org/

### Date of Publication

2024-07-27

**Comment by anthology-assist** [comment]
@MirunaClinciu Thank you for submitting the issue! Please allow two weeks for ingestion i.e. ingestion material should be received on 2024-07-13.

**Comment by MirunaClinciu** [comment]
Hi there, here is the whole material: https://drive.google.com/drive/folders/1xwv9v7inByGL57lYLE9tgzOrWYXBTCny?usp=drive_link

**Comment by mjpost** [comment]
@anthology-assist I have word from @MirunaClinciu that there are updates coming. Ideally this will all be online by August 11 at the latest, but earlier is better (once we have the updates).

**Comment by anthology-assist** [comment]
@mjpost @MirunaClinciu waiting on updates.

**Comment by mjpost** [comment]
@anthology-assist I have word from @MirunaClinciu that this is read to ingest. If people want further updates it will have to move to corrections.

**Comment by anthology-assist** [comment]
@MirunaClinciu I need the `output` folder specified [here](https://github.com/rycolab/aclpub2) and I'm not seeing it in the Gdrive you shared. Without it the conference can't be ingested. Can you please update?

**Comment by MirunaClinciu** [comment]
everything is updated.

**Comment by mjpost** [comment]
Can you share paths? I don't see any updates for `long`, `findings`, or `tutorials`.

**Comment by mbollmann** [comment]
More than one person is reporting that their accepted paper is missing from the ingestion, see #3733 or https://twitter.com/yuvalpi/status/1823258677320822804 — @MirunaClinciu

**Comment by MirunaClinciu** [comment]
Hi @mbollmann 

We encountered an unforeseen issue with some papers from both the short and long proceedings that falls outside of my access rights as a publication chair. We've identified the missing papers and have started the process of adding them back into the proceedings. We appreciate your understanding and patience as we work to resolve this.

Best wishes,
Miruna C.
