### ISSUE TITLE
Wrong FinNLP Proceedings in IJCNLP-AACL-2023

### ISSUE THREAD

**Issue by ChunJiChen** [acl-org/acl-anthology#3098]
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

Hi @anthology-assist,

I want to clarify the problem in this discussion (https://github.com/acl-org/acl-anthology/pull/3072). In sum, we have two FinNLP proceedings (IJCAI and IJCNLP-AACL) in 2023, but only one proceedings (IJCAI) was uploaded. The correct version for FinNLP@IJCNLP-AACL has still not been uploaded.

(1) The current FinNLP-2023 on ACL Anthology (https://aclanthology.org/volumes/2023.finnlp-1/) is the event we hosted in IJCAI-2023. It should not been shown together with IJCNLP-AACL (https://aclanthology.org/events/aacl-2023/)

(2) The correct version that should be shown together with IJCNLP-AACL is that shared by the IJCNLP-AACL proceedings chair. For your convenience, here is the data generated by ACLPUB from the SoftConf system: https://drive.google.com/drive/folders/1VkekfSDvzrJCRE5ds1E4HjLrBjNd7n_x?usp=sharing

Could you help to upload this proceedings, and link it with IJCNLP-AACL-2023, please?

**Comment by anthology-assist** [comment]
@ChunJiChen @mjpost I'm still a bit confused. Why does FinNLP have two separate proceedings, and why are they hosted in different venues? I don't think anthology: https://aclanthology.org/ host `IJCAI`, therefore the existing FinNLP proceedings https://aclanthology.org/volumes/2023.finnlp-1/ should be deleted? 

If both FinNLP proceedings should exist, do they share the same venue_id i.e. finnlp but different volumes i.e. one of them is volume 1 and the other is 2?  

FYI, the new link contains incomplete ingestion material. Meta file is missing in the `cdrom` dir. Could you update?

**Comment by mjpost** [comment]
First, I assume this is actually the same workshop. Can you confirm this? It's odd that it had two meetings in one year, but that is not impossible.

When @anthology-assist ingests the correct one, we will disconnect the current one from its association with AACL.

**Comment by mjpost** [comment]
@anthology-assist FinNLP met twice this year, first with IJCAI (which we do not host). This is a second meeting. So we should not touch the existing FinNLP, but create this as a volume `2` in the FinNLP file, and associate just that volume with IJCNLP (and AACL, since they were joint).

If the data to ingest is not correct, please point them to the format-checking script.

**Comment by anthology-assist** [comment]
@mjpost Just to clarify
- the existing FinNLP volume content stays as is, but this volume should NOT be associated with IJCNLP/AACL
- the to-be-ingested FinNLP volume should have volume `2` and should be associated with both IJCNLP and AACL.

**Comment by ChunJiChen** [comment]
Hi @mjpost, 

Thank you for helping us to check this issue. FinNLP has become a twice-a-year workshop, one in IJCAI and one in *ACL conferences. Participants have given good feedback on this design, and thus, we plan to keep it if possible. 

Hi @anthology-assist, 

Thank you so much. Yes, these are correct. 

> (1) The existing FinNLP volume content stays as is, but this volume should NOT be associated with IJCNLP/AACL
> 
> (2) The to-be-ingested FinNLP volume should have volume 2 and should be associated with both IJCNLP and AACL.

I checked the zip I shared, and the "meta" file is there. The content is as follows. Please let me know if there are other issues or questions. 

```
abbrev FinNLP2023
title The 6th Workshop on Financial Technology and Natural Language Processing
url https://sites.google.com/nlg.csie.ntu.edu.tw/finnlp2023/home
booktitle Proceedings of The 6th Workshop on Financial Technology and Natural Language Processing
shortbooktitle Proceedings of FinNLP-2023
volume 2
month November
year 2023
location Bali, Indonesia
publisher Association for Computational Linguistics
chairs Chung-Chi Chen
chairs Hen-Hsen Huang
chairs Hiroya Takamura
chairs Hsin-Hsi Chen
chairs Hiroki Sakaji
chairs Kiyoshi Izumi
```
