### ISSUE TITLE
Ingestion Request [07-15-2024]: Joint Workshop of the 8th Financial Technology and Natural Language Processing and the 1st Agent AI for Scenario Planning

### ISSUE THREAD

**Issue by ChunJiChen** [acl-org/acl-anthology#3124]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

finnlp

### Volume Title

Proceedings of the Joint Workshop of the 8th Financial Technology and Natural Language Processing and the 1st Agent AI for Scenario Planning

### Date of Publication

2024-07-15

**Comment by ChunJiChen** [comment]
Dear @anthology-assist , 

Sorry for the delay in submitting the proceedings' data. I understood that it may need two weeks to upload it to the ACL Anthology. Could you please have our proceedings ready on the ACL Anthology by July 19th? 

Here is the data of the proceedings: https://drive.google.com/file/d/1dUHn2PWALPkAt65aVe7AbYYIlB2rlclX/view?usp=sharing

Here is the copyright-transfers folder: https://drive.google.com/drive/folders/1vYfVR3716fgygEw9sEn_w6S-Uy4X9tIL?usp=sharing

Please let me know if you have any questions. 

Many thanks.

**Comment by ChunJiChen** [comment]
@anthology-assist @mjpost 

Could you please let me know if there are any problems?

**Comment by mjpost** [comment]
@anthology-assist should process this soon

**Comment by ChunJiChen** [comment]
Dear @anthology-assist 

The workshop is going to happen on Aug. 3rd (GMT+9). Could you please help to upload our proceedings?

**Comment by anthology-assist** [comment]
@ChunJiChen Please review preview here https://github.com/acl-org/acl-anthology/pull/3711

**Comment by ChunJiChen** [comment]
Hi @anthology-assist 

Thank you so much for your reply. 

It looks great, and only one thing may need to change. 

As I stated in "meta", the "volume_name" is 2, because we already have volume 1 (https://aclanthology.org/volumes/2024.finnlp-1/) this year. 

Thus, I think the "Anthology ID" of this volume should be "2024.finnlp-2".

**Comment by anthology-assist** [comment]
@ChunJiChen I misunderstood, I thought volume 2 was a mistake. Sorry about that. Could you send me volume 1 again?

**Comment by mjpost** [comment]
[Volume 1 is already ingested](https://aclanthology.org/volumes/2024.finnlp-1/). [FinNLP](https://aclanthology.org/venues/finnlp/) has multiple meetings a year.

**Comment by mjpost** [comment]
Oh drat, when you uploaded the PDFs, you overwrote the old volume. Can you restore these from the previous ingestion?

**Comment by ChunJiChen** [comment]
Hi @anthology-assist 

Sorry. I should mention it when I submit the data. 

Here is the first volume in LREC-COLING-2024: https://drive.google.com/file/d/10UPjORUvOLaDNLg93WR_WDNn7VIRAh0o/view?usp=drive_link
