### ISSUE TITLE
Paper Metadata: 2024.findings-eacl.30

### ISSUE THREAD

**Issue by mateuk** [acl-org/acl-anthology#3137]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-eacl.30

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)
- [X] Other

### Correction to Software/Note fields:

I want the Software/Note fields to be removed from the paper metadata.

Both of them were filled with files from ARR OpenReview that were in a "draft" stage and were meant only for the paper reviewers, not for the public, The final version is being hosted on GitHub: https://github.com/ufal/UNMHG, which can be added into the "Code" metadata field.

**Comment by anthology-assist** [comment]
The github link can be added with a paper pdf revision if you would like. Please submit a separate issue for that.

**Comment by mbollmann** [comment]
> The github link can be added with a paper pdf revision if you would like. Please submit a separate issue for that.

They’re talking about the metadata field on the website. @mateuk This comes from the Papers with Code integration; if you add your paper to [Papers with Code](https://paperswithcode.com/) with the appropriate dataset information, it will get automatically synced to the Anthology.
