### ISSUE TITLE
Paper Revision 2024.eacl-long.79

### ISSUE THREAD

**Issue by sonlam1102** [acl-org/acl-anthology#3140]
### Anthology ID

2024.eacl-long.79

### Type of Change

Revision

### PDF of the Revision or Erratum

[EACL_2024.pdf](https://github.com/acl-org/acl-anthology/files/14626519/EACL_2024.pdf)

### Brief Description of Changes

- Adding the City (Ho Chi Minh City) and Country (Vietnam) for the first affiliation.
- Adding the Country (Vietnam) for the second affiliation.

**Comment by sonlam1102** [comment]
Dear ACL Anthology,
I found that the new version has no conference stamp or page number. Can you reverse this file to the original version on the ACL Anthology? (I saw that the file has been updated on the ACL anthology)
Thank you very much.

**Comment by sonlam1102** [comment]
If it is fine, please reverse this issue to the original version (2024.eacl-long.79), which has the conference stamp and page number. And close this issue. 
Thank you

**Comment by sonlam1102** [comment]
@anthology-assist please process my above comments. Thank you

**Comment by sonlam1102** [comment]
@mbollmann Dear Mr. Bollman,
I don't want to update this version anymore. I want to keep the first original version. 
However, when I checked on my paper at ACL Anthology (https://aclanthology.org/2024.eacl-long.79/), the PDF has been changed (there are no conference stamp as the first version). So, please change it to the first original version.

Thank you

**Comment by sonlam1102** [comment]
@mbollmann @anthology-assist Thank you for your support.

**Comment by sonlam1102** [comment]
@mbollmann @anthology-assist when you reverted the pdf file, please kindly close this issue (cause I cannot close). Thank you

**Comment by sonlam1102** [comment]
@mbollmann @anthology-assist I had closed this issue.

**Comment by sonlam1102** [comment]
> @sonlam1102 Thanks for clarifying. In this case, @anthology-assist can revert the PDF as well as commit [7256511](https://github.com/acl-org/acl-anthology/commit/72565114bcd9980350518908c434b04c5e8438a9), but please allow a few working days for this to be processed.

@anthology-assist @mbollmann when you reverted the PDF file and the commit, please kindly close this issue. Thank you very much.

**Comment by sonlam1102** [comment]
> @sonlam1102 Thanks for clarifying. In this case, @anthology-assist can revert the PDF as well as commit [7256511](https://github.com/acl-org/acl-anthology/commit/72565114bcd9980350518908c434b04c5e8438a9), but please allow a few working days for this to be processed.

Dear @mbollmann and @anthology-assist,

Please kindly check and revert this commit and the PDF file. 
Sorry for bothering you. I'm posting this just for reminding. If you had done, please ignore this. 

Thank you very much.

**Comment by sonlam1102** [comment]
@mbollmann Dear Mr. Bollman,
I checked on the ACL Anthology (https://aclanthology.org/2024.eacl-long.79/), and the PDF file has still not been changed (maybe the commit has not been reverted). 
Could you please check this? 
Thank you very much

**Comment by mbollmann** [comment]
I can't change PDFs on the server unfortunately, @anthology-assist will have to do that.

**Comment by sonlam1102** [comment]
> @sonlam1102 Thanks for clarifying. In this case, @anthology-assist can revert the PDF as well as commit [7256511](https://github.com/acl-org/acl-anthology/commit/72565114bcd9980350518908c434b04c5e8438a9), but please allow a few working days for this to be processed.

@anthology-assist please process this. Thank you very much
