### ISSUE TITLE
2023.wmt-1.23

### ISSUE THREAD

**Issue by phikoehn** [acl-org/acl-anthology#3143]
### Anthology ID

2023.wmt-1.23

### Type of Change

Revision

### PDF of the Revision or Erratum

[Uploading 2023.wmt-1.23.pdf…]()

### Brief Description of Changes

Change in paper not yet updated in anthology - I am just forwarding this as the WMT pub chair.
At least some systems were falsely named in Section 5.1

**Comment by anthology-assist** [comment]
@phikoehn Thank you for submitting the issue. Do you mind updating the link? Currently it doesn't contain the updated version of the pdf.

**Comment by phikoehn** [comment]
[2023.wmt-1.23.pdf](https://github.com/acl-org/acl-anthology/files/14644916/2023.wmt-1.23.pdf)
