### ISSUE TITLE
Paper Metadata: 2024.eacl-demo.22

### ISSUE THREAD

**Issue by Alaa24ahmed** [acl-org/acl-anthology#3146]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.eacl-demo.22

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Ahmed Sajwani, Alaa El Setohy, Ali Mekky, Diana Turmakhan, Lara Hassan, Mohamed El Zeftawy, Omar El Herraoui, Osama Mohammed Afzal, Qisheng Liao, Tarek Mahmoud, Zain Muhammad Mujahid, Muhammad Umar Salman, Muhammad Arslan Manzoor, Massa Baali , Jakub Piskorski, Nicolas Stefanovitch, Giovanni Da San Martino, Preslav Nakov

**Comment by anthology-assist** [comment]
@Alaa24ahmed Thank you for the full author list. Could you only add the missing authors name and affiliation? If I understand it correctly, `Zain Muhammad Mujahid, Muhammad Umar Salman, Muhammad Arslan Manzoor, Massa Baali , Jakub Piskorski, Nicolas Stefanovitch, Giovanni Da San Martino, Preslav Nakov` are the missing authors.

**Comment by Alaa24ahmed** [comment]
yes, these are the names of the missing authors

**Comment by anthology-assist** [comment]
@Alaa24ahmed Thank you. Could you add their affiliations?

**Comment by Alaa24ahmed** [comment]
Yeah sure!
Zain Muhammad Mujahid: MBZUAI, 
Muhammad Umar Salman: MBZUAI, 
Muhammad Arslan Manzoor: MBZUAI, 
Massa Baali: MBZUAI, 
Jakub Piskorski: Polish Academy of Sciences, 
Nicolas Stefanovitch: European Commission Joint Research Centre, 
Giovanni Da San Martino: University of Padova, 
Preslav Nakov: MBZUAI
