### ISSUE TITLE
Ingestion: GEM 2023

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#3148]
This is a 2023 EMNLP workshop. The inputs can be found here: https://github.com/emnlp-2023/W11-GEM/tree/main/output. Make sure to mark it as a workshop and list it with EMNLP 2023 workshops.

**Comment by anthology-assist** [comment]
@mjpost I do not have access to that link. Can you add me?

**Comment by mjpost** [comment]
Done: https://github.com/emnlp-2023/W11-GEM/
