### ISSUE TITLE
Paper Metadata: 2024.eacl-long.100

### ISSUE THREAD

**Issue by jonorthwash** [acl-org/acl-anthology#3155]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.eacl-long.100

### Type of Paper Metadata Correction

- [X] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)

### Correction to Paper Title

[something less demeaning to speakers of Turkic languages other than Turkic]

**Comment by mbollmann** [comment]
Please contact the authors of the paper if you believe the title is inappropriate, or alternatively the program chairs of the conference. The Anthology can’t make these decisions.

**Comment by jonorthwash** [comment]
I believe I will.  But this is what worst-case complicity looks like.  Dismissing non-inclusive language out of hand as "someone else's problem."

**Comment by jonorthwash** [comment]
@lksenel, @KnlG, @codogogo, I want to draw your attention to this (and the others authors, whose github usernames I couldn't find easily).  The use of the term "Big Brother" to refer to the relation between Turkish and other Turkic languages has not been well received in the Turkic NLP community.  It's experienced as demeaning, antithetical to inclusivity, and broadly harmful.

The ACL ethics committee may be contacted about this—not for any punative reason, but because this is not just your failing, but a failing at every level of the process, including reviewers, editors, program organisers, awards committee, and now Anthology editors.

**Comment by mbollmann** [comment]
I just want to clarify that the Anthology does not perform any kind of editorial function. We are simply volunteers who are organizing the technical hosting of materials and ensuring correctness of metadata. We have neither the capacity nor the authority to make editorial decisions. That’s the only reason why I closed your issue — not because I don’t believe that the question isn’t important, or the concern isn’t warranted.

**Comment by jonorthwash** [comment]
> I just want to clarify that the Anthology does not perform any kind of editorial function. We are simply volunteers who are organizing the technical hosting of materials and ensuring correctness of metadata. We have neither the capacity nor the authority to make editorial decisions. That’s the only reason why I closed your issue — not because I don’t believe that the question isn’t important, or the concern isn’t warranted.

Yes, thank you for your rationalising and your volunteer hours.  Surely you have the power to raise such issues to the attention of the editors or otherwise "push it up the chain"—that would be a good way to show that believe this question is important / concern is warranted.

**Comment by jonorthwash** [comment]
Surely if more "obviously" harmful language in a title were included in a title it would have been caught and brought to someone's attention.  I'm only asking for that level of attention to be given here—and it hasn't been.

Perhaps relying on unpaid labour is not the best way for things like this to be caught.

**Comment by mbollmann** [comment]
I don’t have any more power to bring this to anyone’s attention than anyone else.

It’s clear where the responsibility ultimately lies — with the chairs of the conference where this was published. I don’t see how I (or any other Anthology volunteer) would be better suited to bring this issue up with them than someone who has clearly already spend a lot more thought on this and appears to be familiar with the affected communities. If you see this as dismissive, then so be it; I simply tried to point you in the right direction for a matter like this.

**Comment by mbollmann** [comment]
> I really wish you would help point me in the right direction.

I tried to do this in my very first comment here: beyond contacting the authors and asking them to consider changing the title (which, if they agree to do so, would be the easiest way to go), the right people to contact are the program chairs of the conference. They have the role of editors of the proceedings; the ACL Anthology does not have “editors”. I really don’t want to be pedantic or argumentative by saying this; it’s simply that the ACL Anthology is not involved in any step of the decision-making process for publishing proceedings.

Going by the [EACL 2024 website](https://2024.eacl.org/committees/organization/), the program chairs can be reached via e-mail under eacl2024pcs@googlegroups.com, so my recommendation is to address all the arguments you’ve brought forward here in an e-mail to them.
