### ISSUE TITLE
Paper Revision{2024.findings-eacl.32}

### ISSUE THREAD

**Issue by David-Li0406** [acl-org/acl-anthology#3165]
### Anthology ID

2024.findings-eacl.32

### Type of Change

Revision

### PDF of the Revision or Erratum

[EACL (6).pdf](https://github.com/acl-org/acl-anthology/files/14790818/EACL.6.pdf)

### Brief Description of Changes

This revision corrects the citation display problem in the Appendix

**Comment by anthology-assist** [comment]
@David-Li0406 The paper link is invalid. Could you update?

**Comment by David-Li0406** [comment]
> @David-Li0406 The paper link is invalid. Could you update?

Thanks for remindering, I have updated the paper link
