### ISSUE TITLE
Paper Revision 2024.case-1.2

### ISSUE THREAD

**Issue by Meaganium** [acl-org/acl-anthology#3166]
### Anthology ID

2024.case-1.2

### Type of Change

Revision

### PDF of the Revision or Erratum

[_CASE24__Fine_Tuning_Language_Models.pdf](https://github.com/acl-org/acl-anthology/files/14771450/_CASE24__Fine_Tuning_Language_Models.pdf)

### Brief Description of Changes

- Affiliation of the first author has been updated (the original version had two affiliations, the updated version has one affiliation).
- The last author's name has been updated (middle initial has been removed). 
- The corresponding city and country of all the authors have been added.

**Comment by Meaganium** [comment]
Hi! I am quite unfamiliar with paper revisions, so I have one question regarding the revision I just submitted: my published paper at https://aclanthology.org/2024.case-1.2 includes the following footer text on each page:

_Proceedings of the 7th Workshop on Challenges and Applications
of Automated Extraction of Socio-political Events from Text (CASE 2024), pages 6–23
March 22, 2024 ©2024 Association for Computational Linguistics_

However, this footer was added by the conference committee and\or publisher, not by me. Therefore, the revised PDF that I submitted in this Github issue does not include this footer. Will ACL add this footer to the revised PDF? Thanks!

**Comment by mbollmann** [comment]
@Meaganium We unfortunately don’t modify PDFs we receive in any way. We can process your revision without this footer no problem. If you prefer the footer to appear in the revision, you can have a look at how it’s added in https://github.com/rycolab/aclpub2/blob/main/aclpub2/templates/watermarked_pdf.tex and add it yourself in the same way.

**Comment by Meaganium** [comment]
Thanks for your swift response! I would indeed prefer the footer to appear in the revision, so I can send a revised version with the footer in it today. Is it okay if I upload that version to a comment in this thread?

**Comment by Meaganium** [comment]
The revised PDF with the footer:

[NEW-2024.case-1.2.pdf](https://github.com/acl-org/acl-anthology/files/14773273/NEW-2024.case-1.2.pdf)

**Comment by mbollmann** [comment]
Perfect, this works!

@anthology-assist Please also check if the author’s name needs to be updated in the metadata.
