### ISSUE TITLE
Paper Revision{2024.ltedi-1.31}

### ISSUE THREAD

**Issue by S-ArunaDevi06** [acl-org/acl-anthology#3171]
### Anthology ID

2024.ltedi-1.31

### Type of Change

Revision

### PDF of the Revision or Erratum

[DRAVIDIAN_LANGUAGE__LT_EDI_2024_Pretrained_Transformer_based_Automatic_Speech_Recognition_system_for_Elderly_People.pdf](https://github.com/acl-org/acl-anthology/files/14793010/DRAVIDIAN_LANGUAGE__LT_EDI_2024_Pretrained_Transformer_based_Automatic_Speech_Recognition_system_for_Elderly_People.pdf)

### Brief Description of Changes

This revision corrects the mistakes in the format of the names of the authors.

**Comment by mjpost** [comment]
Hi @anthology-assist, they didn't mention it, but this also requires updating the names in the metadata, can you do this?
