### ISSUE TITLE
Updating Paper Metadata for 2024.eacl-demo.23

### ISSUE THREAD

**Issue by firojalam** [acl-org/acl-anthology#3177]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.eacl-demo.23

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

@inproceedings{dalvi-etal-2024-llmebench,
    title = "{LLM}e{B}ench: A Flexible Framework for Accelerating {LLM}s Benchmarking",
    author = "Dalvi, Fahim  and
      Hasanain, Maram  and
      Boughorbel, Sabri  and
      Mousi, Basel  and
      Abdaljalil, Samir  and
      Nazar, Nizi  and
      Abdelali, Ahmed  and
      Chowdhury, Shammur Absar  and
      Mubarak, Hamdy  and
      Ali, Ahmed and
      Hawasly, Majd and 
      Durrani, Nadir  and
      Alam, Firoj",
    editor = "Aletras, Nikolaos  and
      De Clercq, Orphee",
    booktitle = "Proceedings of the 18th Conference of the European Chapter of the Association for Computational Linguistics: System Demonstrations",
    month = mar,
    year = "2024",
    address = "St. Julians, Malta",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/2024.eacl-demo.23",
    pages = "214--222",
    abstract = "The recent development and success of Large Language Models (LLMs) necessitate an evaluation of their performance across diverse NLP tasks in different languages. Although several frameworks have been developed and made publicly available, their customization capabilities for specific tasks and datasets are often complex for different users. In this study, we introduce the LLMeBench framework, which can be seamlessly customized to evaluate LLMs for any NLP task, regardless of language. The framework features generic dataset loaders, several model providers, and pre-implements most standard evaluation metrics. It supports in-context learning with zero- and few-shot settings. A specific dataset and task can be evaluated for a given LLM in less than 20 lines of code while allowing full flexibility to extend the framework for custom datasets, models, or tasks. The framework has been tested on 31 unique NLP tasks using 53 publicly available datasets within 90 experimental setups, involving approximately 296K data points. We open-sourced LLMeBench for the community (https://github.com/qcri/LLMeBench/) and a video demonstrating the framework is available online ([https://youtu.be/9cC2m{\_}abk3A)](https://youtu.be/9cC2m%7B%5C_%7Dabk3A)).",
}

**Comment by anthology-assist** [comment]
@firojalam Could you highlight missing or incorrect author names?

**Comment by firojalam** [comment]
@anthology-assist , 
The following authors name are missing: 

Hawasly, Majd and
Durrani, Nadir and
Alam, Firoj


Thank you

**Comment by mjpost** [comment]
This correction was made to the wrong paper. Can we please carefully check the author lists for the following two papers?

* https://aclanthology.org/2024.eacl-demo.23/
* https://aclanthology.org/2024.eacl-long.30/

**Comment by firojalam** [comment]
Dear Matt,
Thanks for your email.
Unfortunately, now bibs are incorrect for both of our papers.

Regards
Firoj


................
Firoj Alam, PhD
http://sites.google.com/site/firojalam/

**Comment by anthology-assist** [comment]
This issue has been solved.
