### ISSUE TITLE
Ingestion Request [09-10-2024]:  INLG 2024

### ISSUE THREAD

**Issue by ChunJiChen** [acl-org/acl-anthology#3188]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

inlg

### Volume Title

Proceedings of the 17th International Conference on Natural Language Generation

### Date of Publication

2024-09-10

**Comment by ChunJiChen** [comment]
Dear @anthology-assist  and @mjpost , 

Thank you for organizing ACL Anthology matters. 

Here are the proceedings of INLG-2024. Could you please upload them by September 17th? The conference will start on Sep. 23rd. 

Data: https://drive.google.com/file/d/1YR0iFMdUq25J-o6HXGbkbyrH9iKN30Ub/view?usp=sharing

It includes four proceedings, and all of them are generated by ACLPUB (Softconf System): 

Main Conference:
(1) Proceedings of the 17th International Conference on Natural Language Generation

(2) Proceedings of the 17th International Conference on Natural Language Generation: System Demonstrations

Workshops: 
(3) Proceedings of the Workshop on AI Werewolf and Dialog System 2024 (AIWolfDial2024)

(4) Proceedings of the 2nd Workshop on Practical LLM-assisted Data-to-Text Generation

**Comment by ChunJiChen** [comment]
Dear @anthology-assist  and @mjpost , 

Could you please confirm if our proceedings will be processed before September 17th?

**Comment by mjpost** [comment]
Hi @ChunJiChen, we can make sure to have these ingested by the 17th. We will look soon to make sure all the materials are in order.

**Comment by mjpost** [comment]
You can see [the preview here](https://preview.aclanthology.org/ingest-inlg/events/inlg-2024/). Please take a look at the [preview checklist](https://github.com/acl-org/acl-anthology/wiki/Ingestion-preview-checklist).

**Comment by ChunJiChen** [comment]
Dear @mjpost 

Thank you so much!

We followed the checklist to check the preview version. 

(1) We noticed that the editor list of the tutorial is not correct, and the tutorial organizers also changed their preface. I have already corrected the metadata and regenerated the proceedings. Could you please use this version (https://drive.google.com/file/d/1mgHTLLEBG-Vfeyu5udJESCeirZdpQYF9/view?usp=drive_link) for "inlg-2024/#2024inlg-tutorials"? 

(2) I wonder whether it is possible to put workshop proceedings together with the proceedings of the main conference on the same page (as most *ACL conferences). It would be helpful for participants to access papers in INLG-2024 easily.

**Comment by mjpost** [comment]
These are finished and should be live in the preview soon. Thanks for the review. Let me know when it looks good and I will merge it.

**Comment by ChunJiChen** [comment]
Thank you so much! We checked the preview, and it looks good. Please help to merge it.  I appreciate your help. 

Sorry for one more question: 
We have one more proceeding (Proceedings of the 17th International Conference on Natural Language Generation: Generation Challenges) that is still under preparation, and the challenge organizers still need more time to prepare their papers. I'll share that once it is ready. Should we keep this repo open so I can share the data in this thread?

**Comment by mjpost** [comment]
I can merge this PR now, so that it will be available, and then handle the other one later.

Or I can wait and handle them together. It's up to you. Let me know.

**Comment by ChunJiChen** [comment]
Please merge this PR first and make it available.  

We can handle the other one later.

**Comment by ChunJiChen** [comment]
Dear @mjpost  @anthology-assist , 

The last proceedings (Proceedings of the 17th International Conference on Natural Language Generation: Generation Challenges) is ready now. 

Could you help us upload it, please? 

Here is the data: https://drive.google.com/file/d/1xLUrkAMko9rFVXQ5JhKphGEMjPd11ciI/view?usp=sharing
