### ISSUE TITLE
Paper Meta Data Correction 2024.eacl-long.34

### ISSUE THREAD

**Issue by Div290** [acl-org/acl-anthology#3189]
### Anthology ID

2024.eacl-long.34

### Type of Change

Metadata correction (Abstract)

### PDF of the Revision or Erratum

[73_fair_filtering_of_automaticall (2).pdf](https://github.com/acl-org/acl-anthology/files/14901727/73_fair_filtering_of_automaticall.2.pdf)

### Brief Description of Changes

We had submitted this file in the final version but in the proceedings, the anonymous version was published, I guess it was a mistake. Please upload this, it has some minor changes and a non-anonymous version of our submission.

**Comment by mbollmann** [comment]
This appears to be https://aclanthology.org/2024.eacl-long.34.pdf ? If so, that does not appear to be anonymized?

**Comment by Div290** [comment]
The abstract that appears in the proceedings is not same as this abstract.
Please have a check.

**Comment by mbollmann** [comment]
You mean the abstract that appears on the website?

Okay, in that case this is not a paper revision (since the paper itself appears to be correct), but a metadata correction. @anthology-assist can make the change.
