### ISSUE TITLE
Paper Metadata: Rob van der Goot

### ISSUE THREAD

**Issue by robvanderg** [acl-org/acl-anthology#3192]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-eacl.9

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

"Rob Goot" should become first name: "Rob", last name "van der Goot"
This needs to be done for all papers assigned to "Rob Goot": https://aclanthology.org/people/r/rob-goot/

If there is a way to fix this in OpenReview, I would love to know how. I checked my profile there and my name seems to be correct (https://openreview.net/profile?id=~Rob_van_der_Goot1)

**Comment by mbollmann** [comment]
Might be related to https://github.com/acl-org/acl-anthology/issues/2926#issuecomment-1851248005.
