### ISSUE TITLE
Author Metadata: {Santosh T.y.s.s}

### ISSUE THREAD

**Issue by santoshTYSS** [acl-org/acl-anthology#3217]
### Author Pages

https://aclanthology.org/people/t/t-y-s-s-santosh/
https://aclanthology.org/people/s/santosh-t-y-s-s/
https://aclanthology.org/people/s/santosh-tokala/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [X] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Please merge the other two profiles into https://aclanthology.org/people/s/santosh-t-y-s-s/

Scholar link 
https://scholar.google.co.in/citations?user=aYytWsAAAAAJ&hl=en

**Comment by anthology-assist** [comment]
@santoshTYSS Thanks for the ticket. Please be consistent with your name in future publications.

**Comment by santoshTYSS** [comment]
@anthology-assist , Sure I would maintain it consistent in future. Is there any more information needed from my end?
