### ISSUE TITLE
Author Metadata: Katharina Hämmerl

### ISSUE THREAD

**Issue by KathyHaem** [acl-org/acl-anthology#3219]
### Author Pages

https://aclanthology.org/people/k/katharina-hammerl/
https://aclanthology.org/people/k/katharina-haemmerl/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [X] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

DBLP: https://dblp.org/pid/316/9896.html
The correct spelling with Umlaut available is "Hämmerl"; however it's typical to rewrite the Umlaut as "ae" when it's not possible to use "ä", hence the two versions.
Please merge to the first page ("Hämmerl").

**Comment by anthology-assist** [comment]
@mjpost Do you know why EMNLP 2023 and ACL 2022 allow the correct version of umlaut spelling but not acl 2023 and 2024?

**Comment by mjpost** [comment]
I don't think it's a matter of allowing, just that the metadata got entered incorrectly for those conferences. The PDFs all have ä; we should just correct the metadata for the papers [on this page](https://aclanthology.org/people/k/katharina-haemmerl/), and all will be fixed.
