### ISSUE TITLE
Author Metadata: {maria berger}

### ISSUE THREAD

**Issue by mariamoritz** [acl-org/acl-anthology#3225]
### Author Pages

https://aclanthology.org/people/m/maria-moritz/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [X] This author has permanently changed their name.

### Supporting Information

Hello, I have two ACL URLs:
https://aclanthology.org/people/m/maria-moritz/ (former name)
https://aclanthology.org/people/m/maria-berger/ (current name)
Can you merge the publications of both names into maria-berger only?

**Comment by mjpost** [comment]
Hi @mariamoritz: Our approach here is typically to keep the metadata to match the name on the paper PDF. We could then merge the profiles so that they would all appear on a single page, i.e., https://aclanthology.org/people/m/maria-berger/. Would that be acceptable?
