### ISSUE TITLE
Paper Metadata: 2024.eacl-long.127

### ISSUE THREAD

**Issue by xzhao-tkl** [acl-org/acl-anthology#3238]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.eacl-long.127

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Xin Zhao
The profile linked to my name does not correspond to me, but rather to another individual who has similar name and also contributed a paper to EACL 2024.

**Comment by anthology-assist** [comment]
@xzhao-tkl Thank you for the ticket. Could you list the anthology ids of your publications on acl?

**Comment by xzhao-tkl** [comment]
@anthology-assist Thanks for your reply. I have only one paper currently, which is: 2024.eacl-long.127 
Please use it for the creation of my page. Thanks

**Comment by xzhao-tkl** [comment]
@anthology-assist The issue is still not fixed

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.eacl-long.127](https://aclanthology.org/2024.eacl-long.127)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
