### ISSUE TITLE
Author Metadata: Chao Zhang

### ISSUE THREAD

**Issue by cz277-thu** [acl-org/acl-anthology#3243]
### Author Pages

Author Pages
https://aclanthology.org/people/c/chao-zhang/

### Type of Author Metadata Correction

- [X] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

The author page of Chao Zhang conflates multiple people with the same name.
Here is my google scholar containing my publication list: https://scholar.google.co.uk/citations?view_op=list_works&hl=en&hl=en&user=Imkhv-YAAAAJ&sortby=pubdate
Please help to correct it. Thank you!

**Comment by anthology-assist** [comment]
@cz277-thu Thank you for the ticket. Could you list the anthology ids of your publications on acl?

**Comment by cz277-thu** [comment]
Thanks. I don't often publish on ACL. At the moment:
2023.acl-long.873.pdf
2023.ccl-4.3.pdf

**Comment by cz277-thu** [comment]
The new ACL Anthology page created for me is still wrong: https://aclanthology.org/people/c/chao-zhang-tu/
