### ISSUE TITLE
Volume Revision: Anthology ID 2023.ijcnlp-demo

### ISSUE THREAD

**Issue by kfnks** [acl-org/acl-anthology#3253]
### Anthology ID

2023.ijcnlp-demo

### Type of Change

Revision

### PDF of the Revision or Erratum

Full volume data: https://drive.google.com/file/d/1W5AcGNq0K1ojaiPH0JSURBQcctBxU6UQ/view?usp=drive_link

### Brief Description of Changes

The current volume misses the paper of Pengfei Zhu+, "ERNIE-Music: Text-to-Waveform Music Generation with Diffusion Models", even though it is listed as the 9th (last) paper in the contents page of the volume cover PDF. (Fundamentally, this is due to the flaw in the original volume data from the publication chairs.) Thank you for your help.

**Comment by anthology-assist** [comment]
@kfnks Thank you for the issue. Could you confirm that the missing paper is added at the end of the proceedings? We don't want to change orders of the already published papers.

**Comment by kfnks** [comment]
@anthology-assist  Yes. The last paper of the proceedings (Please refer to https://aclanthology.org/2023.ijcnlp-demo.0.pdf, p. xi) is missing and it should be added at the end.

**Comment by pfZhu** [comment]
@anthology-assist @kfnks I'm sorry but it seems this paper is still missing on the anthology website. Is it resolved now?

**Comment by anthology-assist** [comment]
@kfnks Could you update the ingestion material? Meta file is missing.

**Comment by kfnks** [comment]
@anthology-assist Please find the attached file. I think it is the requested one. (I added `.txt` to upload)
[meta.txt](https://github.com/acl-org/acl-anthology/files/15374113/meta.txt)

**Comment by pfZhu** [comment]
@kfnks @anthology-assist I'm sorry but it seems the whole demo track is missing on the website now.

**Comment by anthology-assist** [comment]
@pfZhu What do you mean? https://aclanthology.org/volumes/2023.ijcnlp-demo/

**Comment by mjpost** [comment]
It is not listed from [the AACL page](https://aclanthology.org/events/aacl-2023/), it seems

**Comment by pfZhu** [comment]
@anthology-assist Demo track is not listed here
![image](https://github.com/acl-org/acl-anthology/assets/34863406/81929c84-ede7-4b4c-becc-6bfa1e38d6ff)
https://aclanthology.org/events/aacl-2023/
