### ISSUE TITLE
Author Metadata: {Brenda Salenave Santana}

### ISSUE THREAD

**Issue by brendasalenave** [acl-org/acl-anthology#3255]
### Author Pages

NA

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

My name is Brenda Salenave Santana. There is no author page when realizing a search in the ACL system looking for my name.

Google scholar for reference: https://scholar.google.com/citations?user=RTdb41EAAAAJ&hl=pt-BR&oi=ao

**Comment by akoehn** [comment]
See #3257
