### ISSUE TITLE
Author Metadata: {Shihao Ran}

### ISSUE THREAD

**Issue by sran-dataminr** [acl-org/acl-anthology#3256]
### Author Pages

NA

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

My name is Shihao Ran. No author page was created for me.

Google Scholar page: https://scholar.google.com/citations?user=CdNrn1IAAAAJ&hl=en

**Comment by akoehn** [comment]
See #3257 (again here: where does the assumption come from that we generate author pages for everyone)?
