### ISSUE TITLE
Author Metadata: {Yifan Peng}

### ISSUE THREAD

**Issue by pyf98** [acl-org/acl-anthology#3259]
### Author Pages

https://aclanthology.org/people/y/yifan-peng/

### Type of Author Metadata Correction

- [X] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Hi, this page contains more than one author with the same name: Yifan Peng.

One of them should be: https://scholar.google.com/citations?user=wH2FALMAAAAJ&hl=en

I'm not sure about the others.

**Comment by anthology-assist** [comment]
@pyf98 Thank you for the ticket. Could you list the anthology id(s) of your publication on acl?

**Comment by pyf98** [comment]
- 2023.acl-demo.38
- 2023.iwslt-1.20
- 2022.iwslt-1.27
