### ISSUE TITLE
Phrasal title casing

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#326]
I decided to try a quick and dirty heuristic for multiword phrases with fixed case (as discussed in #123).

A heuristic that looks for title n-grams that are consistently capitalized in the paper's abstract for at least 2 papers, and where the n-gram is not more often lowercased across the corpus, returns just 227 hits (many of which are overlapping n-grams).

Excluding items which would be flagged anyway using single-word fixed case heuristics, these can be classified as follows:

* __Names of shared tasks:__ these are by far the most common. Examples include "Semantic Textual Similarity", "Community Question Answering", "Chinese Grammatical Error Diagnosis", "Customer Feedback Analysis", "Discriminating between Dutch and Flemish", "E2E NLG Challenge", "Surface Realization Shared Task".
* __Names of dialects/languages:__ "Sorani Kurdish", "Modern Hebrew", "Indo Aryan", "South Slavic", "Mandarin Chinese"
* __Names of corpora/resources:__ "Balanced Corpus of Contemporary Written Japanese", "Paraphrase Database" (actually matches multiple resources), "ACL Anthology"
* __Kinds of neural networks:__ "Fusion Network", "Recurrent Neural Net", "Gated Recurrent Neural", "Gated Graph Neural Networks", "Self Governing Neural Networks", "Neural Belief", "Long Short Term Memory", "Stack LSTMs"
* __Terms of art that should probably be capitalized:__ "Universal Dependencies", "Adaptor Grammars", "Latent Dirichlet Allocation", "Abstract Meaning Representation", "Conditional Random Fields", "Open IE", "Open Information Extraction", "Gradient Boosting Regression Tree", "Gaussian Process", "Gaussian Mixture Model", "Combinatory Categorial", "Support Vector", "Noise Contrastive Estimation", "Deep Dyna Q"
* __Terms of art that are borderline:__ "Native Language Identification", "Multi Word Expressions", "Enhanced Attention", "Universal Language Model"
* __Other named entities:__ "Macquarie University"

Note that some of these are missing a head noun, largely because of morphological variation ("Support Vector Machine(s)", "Combinatory Categorial Grammar(s)").

Surprisingly, "Modern Standard Arabic" turns up in just 18 titles, and only one of them has a corresponding abstract, so it doesn't meet the threshold. Thus, I gather that this method is fairly low-recall due to the large number of papers missing abstracts.

Does it seem worth it to implement fixed-case for the few terms above that should clearly be capitalized? Or is there a plan to import abstracts for a much wider swath of the database, which would allow us to compile a higher-recall list?

**Comment by davidweichiang** [comment]
I think it would definitely be worthwhile and not that difficult to modify `protect.py` to handle multiword expressions in `truelist`. We can manually add all of the examples you've listed above, plus any others that we can think of.

Upgrading the trainer to automatically learn MWEs would be a bit more work, but maybe not that bad either.

**Comment by nschneid** [comment]
I started working on support for a phrasal truelist. One wrinkle is what to do about hyphens that different authors may use differently. It turns out that that `tokenize()` function actually removes hyphens and slashes:

https://github.com/acl-org/acl-anthology/blob/006f7e00f34645182335da77cc6adc93f3ccbfe4/bin/fixedcase/common.py#L30

@davidweichiang was that intentional? Making the pattern a capturing group, i.e. `re.split(r"([-–/])", tok)`, splits on hyphen/token characters but retains them as individual tokens.

**Comment by davidweichiang** [comment]
I totally can't remember if that was intentional :)

**Comment by nschneid** [comment]
OK. Next question: Should I be running protect.py on the files in the data/xml directory, which already have fixed-case in titles as discovered by previous heuristics? It doesn't seem to be retrieving XML nodes correctly; maybe there is a more raw version of the XML that it expects?

**Comment by nschneid** [comment]
It works if I change an XPath (maybe the XML schema changed recently).

I am treating hyphens as optional word separators. The phrasal truelist omits hyphens, and hyphens in the title are ignored when matching against it.

Treating hyphens as separators means we will not detect that the second word in a dataset name like "Naija-Tweets" should be fixed-case. But I don't see a way around that.

**Comment by nschneid** [comment]
It looks like there were some recent additions to the single-word truelist ("Twitter", "AI") that haven't been incorporated into 2019 papers.

**Comment by nschneid** [comment]
I've got this working (modulo code formatting). Tested on a few of the XML files, with no false positives.
