### ISSUE TITLE
Author Metadata: Kathy Reid 

### ISSUE THREAD

**Issue by KathyReid** [acl-org/acl-anthology#3270]
### Author Pages

Author page was not automatically created; wish to add ACL Anthology author URL to my OpenReview profile. 

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

I am the first author of this paper: 
https://aclanthology.org/2023.alta-1.6/

My ORCID id is linked to my GitHub profile for verification. 

Kind regards, 
Kathy Reid

**Comment by mbollmann** [comment]
If you have a paper on the Anthology, your author page is always created, and can be reached by clicking on your name on the paper page. In your case, it's here: https://aclanthology.org/people/k/kathy-reid/

**Comment by KathyReid** [comment]
Thank you so much @mbollmann - super helpful, and appreciated.
