### ISSUE TITLE
DOIs for Eval4NLP 2022 not working

### ISSUE THREAD

**Issue by flipz357** [acl-org/acl-anthology#3278]
Hi, 

I noticed that the DOIs for [Eval4NLP 2022](https://aclanthology.org/events/eval4nlp-2022/) are not working. Clicking on the DOI for any paper results in a "404", e.g.,

![image](https://github.com/acl-org/acl-anthology/assets/59831412/8e9fd39e-0dac-4593-96c8-bb2d366447c4)

I have checked for other instances of EVAL4NLP and there the DOIs seem to work fine, the issue is just with the 2022 version. All papers of 2022 seem affected. Thanks for any help.

Juri

**Comment by flipz357** [comment]
@anthology-assist I was unsure what specific label I should attach to this issue. Could you attach the appropriate label?

**Comment by flipz357** [comment]
@mjpost Many apologies for pinging you here, but it seems that this issue is still open. And @anthology-assist so far hasn't reacted, so I don't know what to do.

If I can resolve this in some way, please let me know.

**Comment by mjpost** [comment]
Hi, was this an ACL workshop, presented at an ACL conference?

**Comment by flipz357** [comment]
Yes to your question, and thanks for the help!
