### ISSUE TITLE
Ingestion Request: EAMT 2024 - The 25th Annual Conference of the European Association for Machine Translation

### ISSUE THREAD

**Issue by carolscarton** [acl-org/acl-anthology#3282]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

eamt

### Volume Title

Proceedings of the 25th Annual Conference of the European Association for Machine Translation: Products & Projects papers

### Date of Publication

2024-06-24

**Comment by anthology-assist** [comment]
Duplicate #3281
