### ISSUE TITLE
Name corrections for Ranran Haoran Zhang

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#3292]
I checked the updated page. They still have conflicts. The papers below are NOT mine:

1. [Word Embedding for Response-To-Text Assessment of Evidence](https://aclanthology.org/P17-3013/)
2. [Co-Attention Based Neural Network for Source-Dependent Essay Scoring](https://aclanthology.org/W18-0549/)
3. [Incorporating Inner-word and Out-word Features for Mongolian Morphological Segmentation](https://aclanthology.org/2020.coling-main.408/)
4. [Active Learning Approaches to Enhancing Neural Machine Translation](https://aclanthology.org/2020.findings-emnlp.162/)
5. [Automated Topical Component Extraction Using Neural Network Attention Scores from Source-based Essay Scoring](https://aclanthology.org/2020.acl-main.759/)
6. [Essay Quality Signals as Weak Supervision for Source-based Essay Scoring](https://aclanthology.org/2021.bea-1.9/)

_Originally posted by @WindChimeRan in https://github.com/acl-org/acl-anthology/issues/3265#issuecomment-2099623521_

**Comment by mjpost** [comment]
The metadata for many of [Ranran's papers](https://aclanthology.org/people/r/ranran-haoran-zhang/) is incorrect (e.g., Ranran on the PDF but not in the metadata). Please correct those. The other papers, where "Haoran Zhang" was used on the PDF and in the metadata but belongs to Ranran, will have to be linked with an ID. I suggest `ranran-haoran-zhang`.

**Comment by mjpost** [comment]
To be explicit: what we did before was assign all papers of "Haoran Zhang" to the "Ranran Haoran Zhang" page. But this is incorrect because there are some of those papers that don't belong to Ranran. So we need to (a) create an idea for Ranran (see suggestion above) and (b) pick only the "Haoran Zhang" papers that belong to Ranran and assign them that ID.

**Comment by aysafanxm** [comment]
Here is a list of all bibkeys of Ranran Haoran Zhang's actual papers:
1. zhang-etal-2020-minimize
2. wang-etal-2021-covid
3. fan-etal-2023-exploring
4. das-etal-2023-unified
5. zhang-etal-2023-conentail

I hope this helps.

**Comment by WindChimeRan** [comment]
Hi, is there any updates for this issue? @mjpost

**Comment by mjpost** [comment]
There is some confusion here. Can you please provide a link to every one of your papers that does *not* have the name "Ranran Haoran Zhang"?

**Comment by mjpost** [comment]
Cancel that request. It seems [this preview](https://preview.aclanthology.org/corrections-2024-09/people/ranran-haoran-zhang) is correct. This will be merged at the end of the month.

**Comment by WindChimeRan** [comment]
Confirmed! This preview is correct. Thank you so much!
