### ISSUE TITLE
Bib file prevents compiling

### ISSUE THREAD

**Issue by borgr** [acl-org/acl-anthology#3298]
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

When compiling with the anthology bib compiling fails, you miss a comma in two places I believe
<img width="697" alt="image" src="https://github.com/acl-org/acl-anthology/assets/6416600/81e8fdf3-ca42-442f-9979-b19447e65442">

**Comment by mbollmann** [comment]
Where is this bib file from? There are no arxiv URLs in the Anthology bib file.

**Comment by akoehn** [comment]
I just downloaded the bibliography to be sure and did a `grep arxiv` , the problem 100% does not come from that file, it must be from your own edits to it.

**Comment by mbollmann** [comment]
> I just downloaded the bibliography to be sure and did a `grep arxiv` , the problem 100% does not come from that file, it must be from your own edits to it.

Can confirm, that’s what I did as well.
