### ISSUE TITLE
Inconsistencies of entry types of workshop paper

### ISSUE THREAD

**Issue by buechel** [acl-org/acl-anthology#33]
I noticed that for papers in workshop proceedings the bib-file sometimes uses the entry type "inbook" (which from my point of view doesn't make sense) while for other "inproceedings" is used.

Compare http://aclanthology.info/papers/feelings-from-the-past-adapting-affective-lexicons-for-historical-emotion-analysis.bib and http://aclanthology.info/papers/semeval-2007-task-14-affective-text.bib

**Comment by knmnyn** [comment]
Now a duplicate of #46, will solve there.

**Comment by knmnyn** [comment]
@buechel this has been solved now, by @danielgildea 's PR which has been merged.  Thanks for your bug report !
