### ISSUE TITLE
Ingestion Request [10-23-2024]: NLP4CALL

### ISSUE THREAD

**Issue by daalft** [acl-org/acl-anthology#3303]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

nlp4call

### Volume Title

Proceedings of the 13th Workshop on Natural Language Processing for Computer Assisted Language Learning

### Date of Publication

2024-10-23

**Comment by anthology-assist** [comment]
Thank you for the ticket! Please submit ingestion material 2 weeks prior to the publication date.

**Comment by anthology-assist** [comment]
@daalft any updates?

**Comment by daalft** [comment]
Waiting for the preface to be ready, the proceedings should be ready this week.

**Comment by daalft** [comment]
The data can be found here:
https://drive.google.com/file/d/1j_1wg7svguaxQDO436vBcbsClipsinXo/view?usp=sharing
