### ISSUE TITLE
Correction to Paper Metadata

### ISSUE THREAD

**Issue by dongqi-me** [acl-org/acl-anthology#3324]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.lrec-main.1258

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

The author's name should be changed from Jia E. Loy to Jia Loy to align with the PDF version.

**Comment by anthology-assist** [comment]
@dongqi-me Please specify paper anthology id.

**Comment by dongqi-me** [comment]
The Anthology ID: 2024.lrec-main.1258
