### ISSUE TITLE
Ingestion Request [11-28-2024]: IWCLUL 2024

### ISSUE THREAD

**Issue by mikahama** [acl-org/acl-anthology#3331]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

iwclul

### Volume Title

Proceedings of the 9th International Workshop on Computational Linguistics for Uralic Languages

### Venue Website (only if you are submitting a new venue)

https://acl-sigur.github.io/iwclul2024.html

### Date of Publication

2024-11-28

### Supporting Information

IWCLUL is organized by ACL SIGUR

**Comment by anthology-assist** [comment]
@mikahama Thank you for the ticket. Please submit ingestion material at least 2 weeks prior to the date of publication.

**Comment by nessa01macias** [comment]
Hello @anthology-assist @mjpost 
These are the files for the IWCLUL2024
[IWCLUL_data](https://drive.google.com/file/d/14uWy8xPBItNEZ2Zsr1C_2nPskvosy1jF/view?usp=sharing)

**Comment by mikahama** [comment]
Here is the proceedings with open access rights: https://www.dropbox.com/scl/fi/19is41t677wscshfxy04q/IWCLUL_data.zip?rlkey=kpayyovi74mnst675tx0j0hxb&st=z4cxceyn&dl=0
