### ISSUE TITLE
The co-authors names in the page are missing

### ISSUE THREAD

**Issue by Sajjaddadkhah** [acl-org/acl-anthology#3339]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.lrec-main.1463

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Mohammadamin Kanaani, Sajjad Dadkhah, Ali A. Ghorbani

**Comment by Sajjaddadkhah** [comment]
Hi I was wondering how long it is going to take to correct this?

**Comment by akoehn** [comment]
Corrections are processed once a month. If someone wants a metadata correction more quickly, they are invited to create a properly formatted pull request.
