### ISSUE TITLE
Paper Revision{2024.lrec-main.405}

### ISSUE THREAD

**Issue by kevindragon221** [acl-org/acl-anthology#3341]
### Anthology ID

2024.lrec-main.405

### Type of Change

Revision

### PDF of the Revision or Erratum

https://arxiv.org/pdf/2402.15264

### Brief Description of Changes

This revision corrects a typo in Section **3.1 Generating Diverse Experts**, formula (2), there is an extra letter 'M' at the end.

**Comment by anthology-assist** [comment]
@kevindragon221 We can not ingest the arxiv version.

**Comment by kevindragon221** [comment]
This is a holiday auto-reply email from QQ mailbox.Hello, I am recently on holiday and cannot reply to your email personally. I will reply to you as soon as possible after the holiday is over.

**Comment by kevindragon221** [comment]
This revision corrects a typo in (https://aclanthology.org/2024.lrec-main.405.pdf) Section 3.1 Generating Diverse Experts, formula (2), there is an extra letter 'M' at the end.

**Comment by ylwangy** [comment]
> @kevindragon221 We can not ingest the arxiv version.

Can we upload the corrected pdf directly? How can we update a new version of **https://aclanthology.org/2024.lrec-main.405.pdf**

**Comment by ylwangy** [comment]
> @kevindragon221 We can not ingest the arxiv version.



> This revision corrects a typo in (https://aclanthology.org/2024.lrec-main.405.pdf) Section 3.1 Generating Diverse Experts, formula (2), there is an extra letter 'M' at the end. ![image](https://private-user-images.githubusercontent.com/13981431/335636426-7cdceb52-a0ac-4493-8fde-cd3fb5b6d4a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzgyMDksIm5iZiI6MTcxNzIzNzkwOSwicGF0aCI6Ii8xMzk4MTQzMS8zMzU2MzY0MjYtN2NkY2ViNTItYTBhYy00NDkzLThmZGUtY2QzZmI1YjZkNGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDEwMzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZjQ2MjE2ZjBhZGNjZTEyOGQ4ZmJlNzU2ZDRmODZhMDI0ZDM5MDc5YzA5MmIxN2E2NDhjNDIyOTkwZTRmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zIB9iozC0pTlI8pUdMKFzy-tY1jbDCBLcrXl7xvnKKw)

This is the corrected version. (I'm the second author of this paper :)
[COLING_24__corrected_version.pdf](https://github.com/user-attachments/files/15521344/COLING_24__corrected_version.pdf)

Yile

**Comment by kevindragon221** [comment]
> > @kevindragon221 We can not ingest the arxiv version.
> 
> > This revision corrects a typo in (https://aclanthology.org/2024.lrec-main.405.pdf) Section 3.1 Generating Diverse Experts, formula (2), there is an extra letter 'M' at the end. ![image](https://private-user-images.githubusercontent.com/13981431/335636426-7cdceb52-a0ac-4493-8fde-cd3fb5b6d4a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzgyMDksIm5iZiI6MTcxNzIzNzkwOSwicGF0aCI6Ii8xMzk4MTQzMS8zMzU2MzY0MjYtN2NkY2ViNTItYTBhYy00NDkzLThmZGUtY2QzZmI1YjZkNGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDEwMzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZjQ2MjE2ZjBhZGNjZTEyOGQ4ZmJlNzU2ZDRmODZhMDI0ZDM5MDc5YzA5MmIxN2E2NDhjNDIyOTkwZTRmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zIB9iozC0pTlI8pUdMKFzy-tY1jbDCBLcrXl7xvnKKw)
> 
> This is the corrected version. (I'm the second author of this paper :) [COLING_24__corrected_version.pdf](https://github.com/user-attachments/files/15521344/COLING_24__corrected_version.pdf)
> 
> Yile

Please use this version, Thanks!

**Comment by kevindragon221** [comment]
Sorry to bother you again. The first page of this version (https://aclanthology.org/2024.lrec-main.405.pdf) is **missing the watermark with the meeting information**. Like this: 
![image](https://github.com/acl-org/acl-anthology/assets/13981431/0bc7b626-de42-4a64-ba76-0dfa16d45919)
Could you please help us add it?

**Comment by mbollmann** [comment]
@kevindragon221 We are only handling the metadata of publications, we don’t make any changes to PDFs we receive. I am not sure how LREC generates its watermarks, but one way of doing it is here: https://github.com/rycolab/aclpub2/blob/main/aclpub2/templates/watermarked_pdf.tex

**Comment by kevindragon221** [comment]
Thank you! This is the revised version with the added watermark information.
[2024.lrec-main.405.pdf](https://github.com/user-attachments/files/15592880/2024.lrec-main.405.pdf)

**Comment by ylwangy** [comment]
> Thank you! This is the revised version with the added watermark information. [2024.lrec-main.405.pdf](https://github.com/user-attachments/files/15592880/2024.lrec-main.405.pdf)

@mbollmann @anthology-assist  Hi, could you please handle this?

**Comment by ylwangy** [comment]
> > Thank you! This is the revised version with the added watermark information. [2024.lrec-main.405.pdf](https://github.com/user-attachments/files/15592880/2024.lrec-main.405.pdf)
> 
> @mbollmann @anthology-assist Hi, could you please handle this?

Dear anthology assist，

Could you please help updating the pdf file?

Thx

**Comment by mbollmann** [comment]
@ylwangy Please have a little patience, it can take some time for @anthology-assist to get to all the issues here. (I myself don't have the ability to do this.)

**Comment by ylwangy** [comment]
@mjpost 
Sorry, the version for our paper is still incorrect. Please don't close this issue.

The current version pdf(v2) in https://aclanthology.org/2024.lrec-main.405/ is lack of conference and pages information, which we actually replace it with a newer one, posted by the first-author

> Thank you! This is the revised version with the added watermark information. [2024.lrec-main.405.pdf](https://github.com/user-attachments/files/15592880/2024.lrec-main.405.pdf)

This should be the final version, or pdf (v3), I suppose.

Thank you!
