### ISSUE TITLE
2024.findings-eacl.100

### ISSUE THREAD

**Issue by Eric-Khiu** [acl-org/acl-anthology#3360]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-eacl.100

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

I would like to update the affiliation of one of my author from "LT3, ID-Lab, Universiteit Gent, Belgium" to "LT3, IDLab, Universiteit Gent, Belgium" (no hyphen for IDLab)

Please also make sure that the EACL watermark is on the PDF, as in the first version. (The current version is missing the watermark)

Thank you.

**Comment by akoehn** [comment]
Hi @Eric-Khiu, we are only handling the metadata of publications, all the PDFs are ingested as-is. You will have to prepare a PDF yourself the way you want it to look like and submit it as a revision.

**Comment by anthology-assist** [comment]
@Eric-Khiu Ditto to what @akoehn said. Also, the original pdf (V1) has the watermarks and the V2 version doesn't. You will have to prepare that for the pdf as well.

**Comment by Eric-Khiu** [comment]
Thank you. I just submitted a new issue
https://github.com/acl-org/acl-anthology/issues/3384. Thank you so much for
your time and apologies for all the trouble!

**Comment by anthology-assist** [comment]
#3384 dupe
