### ISSUE TITLE
Paper Metadata: {2024.lrec-main.1021}

### ISSUE THREAD

**Issue by Goolk** [acl-org/acl-anthology#3364]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.lrec-main.1021

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

The correct author list: Hongyu Guo, Wenbo Shang, Xueyao Zhang, Shubo Zhang, Xu Han, Binyang Li

With the permission of the conference chairs, we added two authors who contributed to this paper: Shubo Zhang and Xu Han.

**Comment by anthology-assist** [comment]
@Goolk Meta data need to match the paper pdf. Could you update the pdf as well?

**Comment by Goolk** [comment]
Of course. The updated PDF file has been submitted as Paper Revision{2024.lrec-main. 1021} (Issue #3365).

---Original---
From: ***@***.***&gt;
Date: Tue, Jun 11, 2024 07:02 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [acl-org/acl-anthology] Paper Metadata: {2024.lrec-main.1021}(Issue #3364)




 
@Goolk Meta data need to match the paper pdf. Could you update the pdf as well?

**Comment by Goolk** [comment]
Hi, I see that the PDF file with the correct author list has been uploaded to ACL Authology, so I want to ask when the metadata will be modified.



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 11, 2024 07:02 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [acl-org/acl-anthology] Paper Metadata: {2024.lrec-main.1021}(Issue #3364)




 
@Goolk Meta data need to match the paper pdf. Could you update the pdf as well?
