### ISSUE TITLE
Author Metadata: Li Zhang

### ISSUE THREAD

**Issue by zharry29** [acl-org/acl-anthology#3371]
### Author Pages

https://aclanthology.org/people/l/li-zhang/

### Type of Author Metadata Correction

- [X] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

My author page includes some papers that are not mine:

- [STEntConv: Predicting Disagreement between Reddit Users with Stance Detection and a Signed Graph Convolutional Network](https://aclanthology.org/2024.lrec-main.1327/)
- [Complementary Evidence Identification in Open-Domain Question Answering](https://aclanthology.org/2021.eacl-main.234/)
- [Multi-Level Gazetteer-Free Geocoding](https://aclanthology.org/2021.splurobonlp-1.9/)
- [SmartCiteCon: Implicit Citation Context Extraction from Academic Literature Using Supervised Learning](https://aclanthology.org/2020.wosp-1.3/)
- [CAN: Constrained Attention Networks for Multi-Aspect Sentiment Analysis](https://aclanthology.org/D19-1467/)
- Everything before 2012 inclusive.

It seems to have conflated me with some other authors with the same name.

**Comment by anthology-assist** [comment]
@zharry29 Could you list the anthology-ids of your papers and confirm your institution affiliation?

**Comment by zharry29** [comment]
I am affliated with the University of Pennsylvania.
My papers:
- 2024.lrec-main.285
- 2024.eacl-long.10
- 2023.ijcnlp-main.20
- 2023.findings-eacl.31
- 2023.nlrse-1.2
- 2023.acl-demo.1
- 2022.acl-long.214
- 2022.naacl-main.388
- 2022.naacl-main.411
- 2022.emnlp-main.638
- 2022.emnlp-demos.27
- 2021.inlg-1.19
- 2021.emnlp-main.165
- 2020.aacl-main.35
- 2020.emnlp-main.91
- 2020.emnlp-main.374
- S19-1005
- P18-1033

**Comment by zharry29** [comment]
Hi @mjpost ! Thanks for helping. It's still not correct. It appears the same as last time when I posted this issue. The following papers are not mine:

- [Generalizable and Stable Finetuning of Pretrained Language Models on Low-Resource Texts](https://preview.aclanthology.org/corrections-2024-10/2024.naacl-long.277/)
- [STEntConv: Predicting Disagreement between Reddit Users with Stance Detection and a Signed Graph Convolutional Network](https://preview.aclanthology.org/corrections-2024-10/2024.lrec-main.1327/)
- [Multi-Level Gazetteer-Free Geocoding](https://preview.aclanthology.org/corrections-2024-10/2021.splurobonlp-1.9/)
- [Complementary Evidence Identification in Open-Domain Question Answering](https://preview.aclanthology.org/corrections-2024-10/2021.eacl-main.234/)
- [CAN: Constrained Attention Networks for Multi-Aspect Sentiment Analysis](https://preview.aclanthology.org/corrections-2024-10/D19-1467/)
- Everything on and before 2012

As per my reply at https://github.com/acl-org/acl-anthology/issues/3371#issuecomment-2159520803 , my papers are the ones listed in that reply.

**Comment by mjpost** [comment]
@anthology-assist please correct this in #3937.
