### ISSUE TITLE
Paper Metadata: 2024.naacl-long.320

### ISSUE THREAD

**Issue by mahadi-nahid** [acl-org/acl-anthology#3401]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.naacl-long.320

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

I am writing to request a correction to my name as it appears on the ACL Anthology website. Currently, my name is shown as "Md Nahid" but it should be **"Md Mahadi Hasan Nahid"** with the following format:

First Name: "Md Mahadi Hasan"
Last Name: "Nahid"

Additionally, it would be greatly appreciated if you could update my profile url including my full name on the link (if not occupied): For example, https://aclanthology.org/people/m/md-mahadi-hasan-nahid/

Thank you for your assistance in resolving this matter. Please let me know if any further information is needed.

Email: mnahid@ualberta.ca

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.naacl-long.320](https://aclanthology.org/2024.naacl-long.320)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
