### ISSUE TITLE
Correction L16-1745

### ISSUE THREAD

**Issue by feralvam** [acl-org/acl-anthology#341]
Hello,

The name of the last author of the paper (ID: L16-1745) is incorrect. It says "Fernando Alva-Manchengo", but it should be "Fernando Alva-Manchego". The name is correct in the pdf, though.

Thanks!

**Comment by davidweichiang** [comment]
Is `Quispersaravia` also a typo, and should the third author have double last name `Sobrevilla Cabezudo`? Thanks!

**Comment by feralvam** [comment]
Thank you for the quick reply. Yes, `Quispersaravia` should be `Quispesaravia`, and it should be a double last name in `Sobrevilla Cabezudo`. What the pdf say is the correct version.

**Comment by davidweichiang** [comment]
Great, the correction has been merged now. The old incorrect spelling was given to us by START. Could you and your co-authors log in to START and see if your names there are spelled correctly? Thanks.
