### ISSUE TITLE
Author Metadata: {Haoyu Dong}

### ISSUE THREAD

**Issue by haoyudong-97** [acl-org/acl-anthology#3417]
### Author Pages

https://aclanthology.org/people/h/haoyu-dong/

### Type of Author Metadata Correction

- [X] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Hi there, this is my google scholar page (https://scholar.google.com/citations?hl=en&user=eZVEUCIAAAAJ&view_op=list_works&sortby=pubdate) and I don't have any publications related to ACL. However, I need to create an ACL author page for my recent submission to ARR-June.

**Comment by mbollmann** [comment]
We don't create author pages unless you have publications on the ACL Anthology, in which case your author page is created automatically. The respective ARR submission field should be optional.
