### ISSUE TITLE
Author Metadata: {Missing Author Page}

### ISSUE THREAD

**Issue by alimohammadbeigi** [acl-org/acl-anthology#3420]
### Author Pages

https://aclanthology.org/people/a/alimohammad-beigi/

### Type of Author Metadata Correction

- [X] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Hi

Missing author page: https://aclanthology.org/people/a/alimohammad-beigi/ URL does not exist. This is my google scholar page (https://scholar.google.com/citations?user=AG3mObUAAAAJ&hl=en&authuser=2) and I don't have any publications related to ACL. However, I need to create an ACL author page for my recent submission to ARR-June.

**Comment by mbollmann** [comment]
We don't create author pages unless you have publications on the ACL Anthology. Your author page is created automatically as soon as you have at least one publication that is hosted by the Anthology. The corresponding field for the ARR submission should be optional.
