### ISSUE TITLE
Author Metadata: {Missing Author}

### ISSUE THREAD

**Issue by Jureeseok** [acl-org/acl-anthology#3421]
### Author Pages

https://aclanthology.org/people/j/juree-seok/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [X] This author has permanently changed their name.

### Supporting Information

Missing author page. https://aclanthology.org/people/j/juree-seok/ URL does not exist. May I request a new author page?
This is my google scholar page (https://scholar.google.com/citations?view_op=list_works&hl=en&user=tqxwlngAAAAJ) and I don't have any publications related to ACL but need to create an ACL author page for new paper submission.

**Comment by mbollmann** [comment]
We don't create author pages unless you have publications on the ACL Anthology. Your author page is created automatically as soon as you have at least one publication that is hosted by the Anthology. The corresponding field for the ARR submission should be optional.
