### ISSUE TITLE
Author Metadata: {Missing Author}

### ISSUE THREAD

**Issue by tuyuge** [acl-org/acl-anthology#3423]
### Author Pages

https://aclanthology.org/people/a/yuge-tu/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Hi there, I did not find my name "Yuge Tu" in the ACL Anthology search. But I need to create an ACL author page for my recent submission to ARR-June. This is my Google Scholar link: https://scholar.google.com/citations?user=pgwERiAAAAAJ&hl=en

**Comment by mbollmann** [comment]
We don't create author pages unless you have publications on the ACL Anthology. Your author page is created automatically as soon as you have at least one publication that is hosted by the Anthology. The corresponding field for the ARR submission should be optional.
