### ISSUE TITLE
Author Metadata: {Ruihong Zeng}

### ISSUE THREAD

**Issue by zengrh3** [acl-org/acl-anthology#3430]
### Author Pages

Please help me create the personal page https://aclanthology.org/people/r/ruihong-zeng/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Hi there, I need to create an ACL author page for my recent submission to ARR-June. Thank you very much

**Comment by mbollmann** [comment]
We don't create author pages unless you have publications on the ACL Anthology. Your author page is created automatically as soon as you have at least one publication that is hosted by the Anthology. The corresponding field for the ARR submission should be optional.
