### ISSUE TITLE
Author Metadata: Arnav Goel

### ISSUE THREAD

**Issue by arnav10goel** [acl-org/acl-anthology#3479]
### Author Pages

https://aclanthology.org/people/a/arnav-goel/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Please create a new ACL author page for me (Arnav Goel) for the submission to ARR-June.

I currently do not have any ACL publications. Here are my relevant profiles:

https://scholar.google.com/citations?user=PPozs9sAAAAJ&hl=en

There are no conflicting authors as per the query: https://aclanthology.org/search/?q=Arnav+Goel

**Comment by arnav10goel** [comment]
Please complete this

**Comment by mbollmann** [comment]
You will automatically get an author page once you have a publication in the Anthology. We do not and cannot create them manually. The ARR submission asks for it, but it’s not mandatory to have one.
