### ISSUE TITLE
Author Metadata: {Divij Bajaj}

### ISSUE THREAD

**Issue by divij-bajaj** [acl-org/acl-anthology#3485]
### Author Pages

https://aclanthology.org/search/?q=Divij+Bajaj

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Please create a new ACL author page for the submission to ARR June 2024.

Details:
FirstName: Divij
LastName: Bajaj

I currently do not have any ACL publications. Here are my relevant profiles:
https://scholar.google.com/citations?user=Fq1C9fUAAAAJ&hl=en
https://www.linkedin.com/in/divij-bajaj-91292482

There are no conflicting authors as per the query: https://aclanthology.org/search/?q=Divij+Bajaj

**Comment by anthology-assist** [comment]
Author profiles are automatically created.
