### ISSUE TITLE
Author Metadata: {Abbas Maazallahi}

### ISSUE THREAD

**Issue by abbascs** [acl-org/acl-anthology#3487]
### Author Pages

https://aclanthology.org/search/?q=abbas+maazallahi

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Please create a new ACL author page for the submission to ARR June 2024.

Details:
FirstName: Abbas
LastName: Maazallahi

I currently do not have any ACL publications. Here are my relevant profiles:
https://scholar.google.com/citations?user=3UylW_cAAAAJ&hl=en
https://www.linkedin.com/in/a-maazallahi/

There are no conflicting authors as per the query: https://aclanthology.org/search/?q=abbas+maazallahi

**Comment by anthology-assist** [comment]
Author profiles are automatically created with the publication.
