### ISSUE TITLE
Author Metadata: {Abhishek Divekar}

### ISSUE THREAD

**Issue by adivekar-utexas** [acl-org/acl-anthology#3494]
### Author Pages

I don't have an author page, and am raising this request to create one. Please create a new ACL author page for the submission to ARR June 2024.

---

Details:
FirstName: Abhishek
LastName: Divekar

I currently do not have any ACL publications. Here are my relevant profiles:

https://scholar.google.com/citations?user=1Sf2oM4AAAAJ&hl=en
https://www.linkedin.com/in/ardivekar/

There are no conflicting authors as per the query: https://aclanthology.org/search/?q=Abhishek+Divekar

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

I don't have an author page, and am raising this request to create one. Please create a new ACL author page for the submission to ARR June 2024.

---

Details:
FirstName: Abhishek
LastName: Divekar

I currently do not have any ACL publications. Here are my relevant profiles:

https://scholar.google.com/citations?user=1Sf2oM4AAAAJ&hl=en
https://www.linkedin.com/in/ardivekar/

There are no conflicting authors as per the query: https://aclanthology.org/search/?q=Abhishek+Divekar

**Comment by anthology-assist** [comment]
Author profiles are created automatically with publication.
