### ISSUE TITLE
Paper Metadata: 2024.eacl-long.120

### ISSUE THREAD

**Issue by joelmoniz** [acl-org/acl-anthology#3497]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.eacl-long.120

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Hi, could you please update author "Joel Moniz" to "Joel Ruben Antony Moniz" ([ACL people link](https://aclanthology.org/people/j/joel-ruben-antony-moniz/)). And if possible, could you please help merge ACL People [Joel Ruben Antony Moniz](https://aclanthology.org/people/j/joel-ruben-antony-moniz/) and [Joel Moniz](https://aclanthology.org/people/j/joel-moniz/)?

Related issues: #3498 #3499

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.eacl-long.120](https://aclanthology.org/2024.eacl-long.120)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
