### ISSUE TITLE
Saarlands VM install missing facets for venue and SIGs

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#35]

**Comment by knmnyn** [comment]
Compare 

http://aclanthology.coli.uni-saarland.de:8080/catalog?utf8=%E2%9C%93&utf8=%E2%9C%93&search_field=venue_name&q=parsing

And 

http://aclanthology.info/catalog?utf8=%E2%9C%93&search_field=all_fields&q=parsing

**Comment by villalbamartin** [comment]
The server has been re-installed and the issue went away. I'm closing it now.
