### ISSUE TITLE
Author missing for Anthology ID W12-5808

### ISSUE THREAD

**Issue by jsalsman** [acl-org/acl-anthology#351]
https://www.aclweb.org/anthology/papers/W/W12/W12-5808/ has only two authors, missing Li Bo, who is shown correctly at https://www.aclweb.org/anthology/W12-5808 

This causes Google Scholar to also be missing the same author. Please add Bo to the bibliographic metadata. Thank you.

**Comment by davidweichiang** [comment]
Thanks. Could you please confirm whether Li is his/her surname?

**Comment by jsalsman** [comment]
Yes it is. He also goes by Troy Lee, if that helps.

**Comment by davidweichiang** [comment]
Done. If you happen to know if any of these other papers are by him, would you please let me know?
https://www.aclweb.org/anthology/people/bo-li

**Comment by jsalsman** [comment]
Thanks, David. I am sure that those papers are not the same Li Bo.
