### ISSUE TITLE
Paper Metadata: 2024.lrec-main.162

### ISSUE THREAD

**Issue by Shiniri** [acl-org/acl-anthology#3516]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.lrec-main.162

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

My profile (https://aclanthology.org/people/m/marie-bauer/) contains this paper, even though I am not one of the authors, presumably there is just a person with the same name as me among them. I would like to have the paper removed from my profile.

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.lrec-main.162](https://aclanthology.org/2024.lrec-main.162)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
