### ISSUE TITLE
Paper Metadata: 2022.mwe-1.11 and 2021.latechclfl-1.11

### ISSUE THREAD

**Issue by FelixSchneiderZoom** [acl-org/acl-anthology#3523]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2022.mwe-1.11 and 2021.latechclfl-1.11

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

I (https://aclanthology.org/people/f/felix-schneider/) am not the first author of these papers, it is someone else with the same name. They should not appear on my Anthology page.

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2022.mwe-1.11 and 2021.latechclfl-1.11](https://aclanthology.org/2022.mwe-1.11 and 2021.latechclfl-1.11)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
