### ISSUE TITLE
Author Metadata: {Ivan P. Yamshchikov }

### ISSUE THREAD

**Issue by i-yam** [acl-org/acl-anthology#3544]
### Author Pages

https://aclanthology.org/people/i/ivan-yamshchikov/
https://aclanthology.org/people/i/ivan-p-yamshchikov/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [X] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Both of these pages are mine, please, merge them into one https://aclanthology.org/people/i/ivan-p-yamshchikov/

all the papers listed under https://aclanthology.org/people/i/ivan-yamshchikov/ actually have Ivan P. Yamshchikov in the pdf.

**Comment by anthology-assist** [comment]
@i-yam Updated. Please use `Ivan P. (first name) Yamshchikov(last name)` consistently for future publications.
