### ISSUE TITLE
Author Metadata: {Guoxiong Gao}

### ISSUE THREAD

**Issue by Al2S3** [acl-org/acl-anthology#3545]
### Author Pages

https://aclanthology.org/people/g/guoxiong-gao/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Please create a new ACL author page for the submission to ARR June 2024.
Details:
FirstName: Guoxiong
LastName: Gao
I currently do not have any ACL publications. Here are my relevant profiles:
https://scholar.google.com/citations?hl=en&user=SoHYQTAAAAAJ
There are no conflicting authors as per the query: 
https://aclanthology.org/search/?q=Guoxiong+Gao

**Comment by anthology-assist** [comment]
@Al2S3 Once you publish a paper on anthology, your profile will be automatically created. We do not manually create author profiles.
