### ISSUE TITLE
Author Metadata: {Ziba Zamani}

### ISSUE THREAD

**Issue by ziba18** [acl-org/acl-anthology#3552]
### Author Pages

https://openreview.net/profile?id=~Ziba_Zamani1

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Please create a new ACL author page for the submission to ARR June 2024.

Details:
FirstName: Ziba
LastName: Zamani

I currently do not have any ACL publications.

There are no conflicting authors as per the query: https://aclanthology.org/search/?q=ziba+zamani

**Comment by anthology-assist** [comment]
@ziba18 If you do not have any publications on ACL, you do not get an author page. The author page will be created automatically with your publication.
