### ISSUE TITLE
Ingestion Request [09-11-2024] SIGDIAL2024

### ISSUE THREAD

**Issue by komatani** [acl-org/acl-anthology#3560]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

sigdial

### ACL SIG(s) sponsoring or endorsing the whole venue

SIGDIAL

### Volume Title

Proceedings of the 25th Annual Meeting of the Special Interest Group on Discourse and Dialogue

### Date of Publication

2024-09-11

### Location

Kyoto, Japan

### Supporting Information

Conference site URL: https://2024.sigdial.org/

**Comment by anthology-assist** [comment]
@komatani Thank you for the issue. Please submit ingestion material 2 weeks prior to the publication date.

**Comment by komatani** [comment]
@anthology-assist Sure, I will do that.

One question: We have a workshop YRRSDS, which already has its venue identifier, yrrsds: https://aclanthology.org/venues/yrrsds/
We will make the proceedings separately this year, as well as the last year.
Does the pub chair of YRRSDS need to be contanted here separately?

**Comment by anthology-assist** [comment]
@komatani No they don't need to contact us separately. You can submit ingestion material for both here. 
Is YRRSDS workshop colocated to SIGDIAL?

**Comment by komatani** [comment]
@anthology-assist Thanks for your response.
Yes, YRRSDS is cololated to SIGDIAL. Both will be held in Kyoto, Japan.  YRRSDS is September 16-17 and SIGDIAL is September 18-20.
https://sites.google.com/view/yrrsds2024/
https://2024.sigdial.org/

**Comment by komatani** [comment]
@anthology-assist The proceedings tarball for SIGDIAL2024 can be downloaded from the link below:
https://filesender.nii.ac.jp/?s=download&token=bbcc5f1d-5296-4815-af70-bbc8492d0f0d
I believe the DOIs will be assigned by the ACL Anthology. Please let me know if there is anything I need to to do.

The YRRSDS workshop has decided to publish its proceedings as post-proceedings after the workshop. I will send you their materials once they are ready.

**Comment by komatani** [comment]
@anthology-assist The proceedings tarball for SIGDIAL2024 can be downloaded from the link below:
https://filesender.nii.ac.jp/?s=download&token=bbcc5f1d-5296-4815-af70-bbc8492d0f0d
I believe the DOIs will be assigned by the ACL Anthology. Please let me know if there is anything I need to to do.

The YRRSDS workshop has decided to publish its proceedings as post-proceedings after the workshop. I will send you their materials once they are ready.

**Comment by komatani** [comment]
@anthology-assist 
It seems that the previous link expired after one week, so I have created a new link. Please download the proceedings tarball from the link below. This one will also be valid for one week from today.
https://filesender.nii.ac.jp/?s=download&token=43ebd1af-f0c3-4b21-bac0-04df2972f69b
If I have made any mistakes, please let me know. I believe we can publish the proceedings by the 11th as scheduled.

**Comment by komatani** [comment]
@anthology-assist @mjpost 
I have placed the same tarball on Google Drive.
https://drive.google.com/file/d/1jGaGqIEWYcSLI-sXJ1Lx5WY6pEP-G1et/view?usp=sharing

**Comment by komatani** [comment]
Dear @anthology-assist and @mjpost ,

Thank you for organizing ACL Anthology matters.
If you haven't downloaded the tarball yet, could you please use the following one? Some last-minute updates have been made. Thank you for your kind consideration.
https://drive.google.com/file/d/1AHFvVwvoqoGSM3MqF0y8cNMs6gT-7H7h/view?usp=sharing

It needs to be available by the end of this week. The conference will start next week (Japan time).

**Comment by komatani** [comment]
Dear @anthology-assist and @mjpost,
The conference will start on the morning of the 18th (Japan time; GMT+9), meaning the hard deadline in AoE is the 16th. I assume there are some review processes before publication. Thank you very much for your attention.

**Comment by mjpost** [comment]
Hi @komatani, sorry for the lack of response on this. I'll process this now.

**Comment by mjpost** [comment]
The preview will be built soon and linked automatically from the [PR](https://github.com/acl-org/acl-anthology/pull/3877). Once it's available, please take a look, using [this checklist](https://github.com/acl-org/acl-anthology/wiki/Ingestion-preview-checklist) as a rough guide.

**Comment by komatani** [comment]
Dear @mjpost, 
I appreciate your quick work. I have checked all the items on the checklist and confirmed that there are no issues. The .bib files are all 'Not Found,' but this seems to have been the case during last year’s preview as well. 
Could you please proceed? If there is anything I need to do on my end, please let me know. Thank you again.

**Comment by komatani** [comment]
Dear @mjpost 
Thank you very much! I just want to confirm one thing: Is there anything we needed to do for the DOIs to be assigned? Like previous conferences, we would like each paper to have a DOI assigned (in the bib file).
