### ISSUE TITLE
Closure of old server and DNS redirection

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#357]
The `aclanthology.info` server is now redirecting almost everything to the new version. Should we turn the old version off for good, change the DNS, and turn it into a mirror? Or do we want to keep it around for a bit longer?

The only reason we kept it around was for old author pages to keep redirecting. Seeing as we are redirecting all authors now, it might not be needed anymore.

**Comment by knmnyn** [comment]
Seems like a good idea.  Saarlands could save a heap of money to turn off the VM.  But I defer to @mjpost .

**Comment by knmnyn** [comment]
Seems like this is pending the closure of the project to finish the static rewrite (Project #4).  Seems like there's just one issue left on that project that needs to be closed.

**Comment by mjpost** [comment]
Just an update here, we are slated to do this by the end of 2019.

**Comment by akoehn** [comment]
@villalbamartin can you add a robots.txt to discourage crawlers from indexing e.g. https://aclanthology.coli.uni-saarland.de? I just checked and it still is a result on the first page of google results for "acl anthology"

**Comment by villalbamartin** [comment]
Fun fact! There was already a `robots.txt`, but it was not accessible because any attempt to access it would redirect to the new anthology. It should be accessible now.

As an update, I have checked the access logs since September 15, and I found that we served 1215 requests, of which 515 were `.png` images, 128 were `.bib` files, 113 were `.txt` and 22 were `.html` files. When removing bots, those requests go down to 706, of which 489 are requests for `.png` files that, in a closer inspection, turned out to be icons.

So it seems to me that the redirection has been mostly successful.

**Comment by akoehn** [comment]
I got a mail asking whether the aclanthology server is still needed. From my point of view it seems like it is not: it is curently non-functional due to a expired certificate and until last week was not working because the logs were not rotated and the disk was full.

Is there any data on the machine that should be preserved?

**Comment by mjpost** [comment]
There is nothing that I know of that needs to be saved. Maybe @knmnyn or @villalbamartin could comment.

**Comment by akoehn** [comment]
The VM is now turned off and archived (which seems to be the default procedure).  I think keeping that disk image around costs (nearly) nothing, so that should be fine. We can also ask to delete it if it is certain that the VM data is not needed anymore.
