### ISSUE TITLE
Paper Metadata: 2024.naacl-long.417

### ISSUE THREAD

**Issue by js0nwu** [acl-org/acl-anthology#3580]
### Confirm that this is a metadata correction

- [x] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.naacl-long.417

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

I erroneously made the OpenReview commitment entry using only my name. The OpenReview review entry had the correct author names, and authors were appropriately considered for peer review.

Correct author names (First Name Last Name)
Jason Wu, Eldon Schoop, Alan Leung, Titus Barik, Jeffrey Bigham, Jeffrey Nichols

**Comment by anthology-assist** [comment]
@js0nwu Would you like to provide author institution affiliation as well?

**Comment by js0nwu** [comment]
Sorry I left that part out. Here is the full author list:

Jason Wu
jsonwu@cmu.edu
Carnegie Mellon University

Eldon Schoop
eldon@apple.com
Apple

Alan Leung
alleu@apple.com
Apple

Titus Barik
tbarik@apple.com
Apple

Jeffrey Bigham
jbigham@apple.com
Apple

Jeffrey Nichols
jwnichols@apple.com
Apple
