### ISSUE TITLE
Author Metadata: {replace with author name}

### ISSUE THREAD

**Issue by keyboardAnt** [acl-org/acl-anthology#3583]
### Author Pages

https://aclanthology.org/people/n/nadav-timor/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Please create the following new profile. [No](https://aclanthology.org/search/?q=Nadav+Timor) other profiles in this name exist.

- First name: Nadav
- Last name: Timor
- Publication list: https://scholar.google.com/citations?user=HxcS1oYAAAAJ

Thanks.

**Comment by anthology-assist** [comment]
Do you have an published papers on anthology? The author profile is automatically created once you publish a paper.

**Comment by keyboardAnt** [comment]
> Do you have an published papers on anthology? The author profile is automatically created once you publish a paper.

Unfortunately no.

<img width="1225" alt="image" src="https://github.com/acl-org/acl-anthology/assets/15572698/f96a841c-4448-40e1-ac55-b264cb7d94b5">
