### ISSUE TITLE
IWCS event page?

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#359]
Thanks for posting the IWCS 2019 proceedings (#356)! Could the various sub-volumes be listed at https://aclweb.org/anthology/events/iwcs-2019/? Also, does IWCS deserve a row on the homepage?

**Comment by mjpost** [comment]
@akoehn, I merged this, and get this build error:

```
INFO     Creating and populating build directory...
INFO     Generating YAML files for Hugo...
INFO     Creating page templates for Hugo...
INFO     Reading the Anthology data...
INFO     Creating stubs for papers...
0it [00:00, ?it/s]
INFO     Creating stubs for volumes...
Traceback (most recent call last):
  File "bin/create_hugo_pages.py", line 243, in <module>
    create_volumes(dir_, clean=args["--clean"])
  File "bin/create_hugo_pages.py", line 106, in create_volumes
    with open(yamlfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/post/code/acl-anthology/build/data/volumes.yaml'
```
I've looked into it a bit but it's not clear to me what's wrong. Is this an easy fix for you?

**Comment by mjpost** [comment]
@mbollmann, what do you think about adding this to the main page? I also looked into this a bit, but wasn't sure where venue top-level status gets determined.

We could also replace ANLP (or if we did the decade column format per #307, it would hand this naturally)

**Comment by akoehn** [comment]
I can look into that, but probably tomorrow rather than today.

**Comment by mbollmann** [comment]
> @mbollmann, what do you think about adding this to the main page? I also looked into this a bit, but wasn't sure where venue top-level status gets determined.

Top-level venues (on the front page) are exactly those with their own letter prefix.

I don't want to comment on whether IWCS would be deserving of front-page status, but I'd like to note that there are a *lot* of other venues for which this argument could be made then as well. Just take a look at what's defined in [venues.yaml](https://github.com/acl-org/acl-anthology/blob/master/data/yaml/venues.yaml) -- what about INLG/ENLG, NoDaLiDa, WMT, ...

**Comment by mjpost** [comment]
Yes, NoDaLiDa and WMT are two other good candidates that have crossed my mind. I'm going to table this for the moment. The site is rebuilding with the venues updated.

**Comment by akoehn** [comment]
@mjpost: I don't know how to reproduce the error in [your previous comment](https://github.com/acl-org/acl-anthology/issues/359#issuecomment-495938558).  As the commit is already merged, the error should manifest itself in the master branch, right?

**Comment by mjpost** [comment]
After looking into this, I suspect it might be that some of the "static" sub-targets are being parallelized on OS X. Would this make sense?

**Comment by akoehn** [comment]
@mjpost yes. As all targets are phony, they don't depend on each other currently.  I could reproduce your problem by running `make -j2`.  I will add this to my list in #348.

**Comment by mjpost** [comment]
And I just fixed it with `make -j1`. Thanks, Arne.

**Comment by mjpost** [comment]
Closing this for now. Homepage row TBD (#307).
