### ISSUE TITLE
Author Metadata: {replace with author name}

### ISSUE THREAD

**Issue by keyboardAnt** [acl-org/acl-anthology#3612]
### Author Pages

ACL ARR requires having an ACL profile:

![image](https://github.com/acl-org/acl-anthology/assets/15572698/b09a4161-e3ff-4b92-beef-45051160c934)

which I do not yet have:

https://aclanthology.org/people/n/nadav-timor
![image](https://github.com/acl-org/acl-anthology/assets/15572698/e85a928c-c96a-4f08-aa0a-527338cc05ca)

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

How can I create one?
My name is Nadav Timor and here's my Google Scholar page: https://scholar.google.com/citations?user=HxcS1oYAAAAJ

**Comment by mbollmann** [comment]
You have one automatically once you have a publication in the Anthology, we do not create them manually and ARR does not require them (despite the email subject unfortunately suggesting this).
