### ISSUE TITLE
Remove non-compact RelaxNG schema

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#362]
The schema is currently validated using both the compact schema (`.rnc`) and the non-compact one (`.rng`).  AFAIU, the second one was automatically created from the first one (see #76).

In that case, there is
 - no need to keep the `.rng` in the repository, as it can be generated just in time
 - no need to validate using the `.rng` file as the XML is already validated against the `.rnc` file.

If you all agree, I will delete that file and its uses.

**Comment by mjpost** [comment]
SGTM.

**Comment by mjpost** [comment]
This was completed with commit 76ca46e3fa44a29b5aba4e252c784d2ce7dbd7bf.
