### ISSUE TITLE
20th International Conference on Natural Language Processing (ICON 2023)

### ISSUE THREAD

**Issue by aukbcvijay** [acl-org/acl-anthology#3632]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

ICON

### Volume Title

Proceeddings of 20th International Conference on Natural Language Processing (ICON 2023)

### Date of Publication

2023-12-15

### Location

Goa, India

### Supporting Information

https://drive.google.com/file/d/1alHjmSHYrDW3r1at-627do9VCRvDGyr3/view?usp=sharing

The above given google drive contain the meta file, main.bin, main.pdf which includes all the papers and separate folder containing pdf and bib files for all the individual papers.   

If we have missed out any information, please inform us.

**Comment by aukbcvijay** [comment]
We have corrected and uploaded the file in the following link 

https://drive.google.com/file/d/1q1a_qpHvLO6YnOGm_n-xI_xhGD5a2Vxg/view?usp=sharing

**Comment by anthology-assist** [comment]
@aukbcvijay Please review the preview here: https://github.com/acl-org/acl-anthology/pull/3659.
