### ISSUE TITLE
Paper Metadata: {2024.signlang-1.15}

### ISSUE THREAD

**Issue by akmmes** [acl-org/acl-anthology#3645]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.signlang-1.15

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Paper Abstract

Dear Concern

I hope you are doing well. Could you kindly update my name on the website from Hafiz Muhammad Sarmad Khan to simply Sarmad Khan? Everything else is correct. "Image Attached".

I am putting a second request as the previous request got completed without solving the issue.

Thank you in advance for your assistance.

![338950052-ed5dbde5-917d-40eb-a93e-e5de2b7604f4](https://github.com/acl-org/acl-anthology/assets/75969530/618c10b6-6f4c-4914-9cec-e96408b8a374)

### Correction to Author Name(s)

Previous (Last Name, First Name): 
Khan, Hafiz Muhammad Sarmad

New Request (Last Name, First Name):
Khan, Sarmad

**Comment by mbollmann** [comment]
The name on the ACL Anthology looks correct:

![image](https://github.com/acl-org/acl-anthology/assets/11348502/0dca6128-a625-47ca-89de-e1ea396461f4)

The image you shared is from the LREC Anthology, which is not managed by us.
