### ISSUE TITLE
Pull requests built twice by travis

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#365]
I just noticed that my pull requests are built by travis once because they are a pull request and in addition once because the are a branch.  @mjpost, maybe there is an easy fix for that, reducing our computational needs a bit.

**Comment by mjpost** [comment]
I just updated the web hook to run only on `push` events. Let's see if that does it, without creating other problems.

**Comment by akoehn** [comment]
Seems to still be the same as before, i.e. two builds are triggered.

**Comment by mjpost** [comment]
After looking through the config options, I don't see how to avoid this. I also know the same happens on <https://github.com/awslabs/sockeye/> where I got most of my Travis experience, so I think I will close this out.
