### ISSUE TITLE
Paper Metadata:  2024.semeval-1.272

### ISSUE THREAD

**Issue by nedjmaou** [acl-org/acl-anthology#3678]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

https://aclanthology.org/2024.semeval-1.272/

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Nedjma Ousidhoum, Shamsuddeen Hassan Muhammad, Mohamed Abdalla, Idris Abdulmumin, Ibrahim Said Ahmad, Sanchit Ahuja, Alham Fikri Aji, Vladimir Araujo,  Meriem Beloucif, Christine De Kock, Oumaima Hourrane, Manish Shrivastava, Thamar Solorio, Nirmal Surange, Krishnapriya Vishnubhotla, Seid Muhie Yimam, Saif M. Mohammad @shashwatup9k

**Comment by anthology-assist** [comment]
@nedjmaou Could you only list author names that need to be corrected?

**Comment by nedjmaou** [comment]
Hi @anthology-assist please add the following authors to the list:

**”Oumaima Hourrane, Manish Shrivastava, Thamar Solorio, Nirmal Surange, Krishnapriya Vishnubhotla, Seid Muhie Yimam, Saif M. Mohammad”**

Thank you.
