### ISSUE TITLE
Ingestion Request: {SCiL 2024}

### ISSUE THREAD

**Issue by goldengua** [acl-org/acl-anthology#3681]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

SCiL

### Volume Title

Proceedings of the Society for Computation in Linguistics 2024

### Location

California

### Supporting Information

https://drive.google.com/drive/folders/1tCQlUmUtyH4ncFvfAqZekDqgLIcmqMAs?usp=sharing

**Comment by anthology-assist** [comment]
@goldengua What's the desired publication date?

**Comment by goldengua** [comment]
The conference has ended so it can be published as soon as possible.
