### ISSUE TITLE
Incorrect video linked to 2024.eacl-long.159

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#3690]
Via e-mail:

> My name is Tilman Beck, I am the author of the following EACL 2024 paper:
> https://aclanthology.org/2024.eacl-long.159/
> I just realised that the video linked to the paper in the ACL Anthology link above is not correct, the video is from this paper https://arxiv.org/abs/2402.10811 which was supposedly accepted to ACL 2024 main.

Pinging @davidstap

**Comment by davidstap** [comment]
Thanks for pinging me @mbollmann. I've reached out to Underline to fix this (the video is not on our server).

**Comment by davidstap** [comment]
This is now resolved; I have replaced the incorrect file on the server after receiving the correct file from Underline. The issue was a mismatch at Underline.

**Comment by mjpost** [comment]
Thanks, all!
