### ISSUE TITLE
Author Metadata: {Marco Antonio Stranisci}

### ISSUE THREAD

**Issue by marcostranisci** [acl-org/acl-anthology#3696]
### Author Pages

https://aclanthology.org/people/m/marco-antonio-stranisci/
https://aclanthology.org/people/m/marco-stranisci/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [X] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

I have a page "Marco Stranisci" and a page "Marco Antonio Stranisci". I need to merge them in a unique page under the name "Marco Antonio Stranisci"

https://scholar.google.com/citations?user=93SGqksAAAAJ&hl=en&oi=ao

I did a pull request, also

**Comment by nschneid** [comment]
Thanks for raising the issue. For paper metadata, the Anthology's policy is to treat what is in the PDF as authoritative. https://aclanthology.org/2022.salld-1.2/ and https://aclanthology.org/2022.isa-1.3/ are actually "Marco A. Stranisci" in the PDF. Could you please update the XML files for those papers, and then list all 3 name variants in the YAML file?
