### ISSUE TITLE
Paper Metadata: 2024.naacl-srw.0

### ISSUE THREAD

**Issue by TristaCao** [acl-org/acl-anthology#3698]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.naacl-srw.0

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Add the following authors after the current authors (all in the format {first_name last_name}):
Marcos Zampieri, George Mason University
Francis Ferraro, University of Maryland Baltimore County 
Swabha Swayamdipta, University of Southern California

**Comment by anthology-assist** [comment]
@TristaCao They are listed as editors in metadata here: https://aclanthology.org/2024.naacl-srw.0/
