### ISSUE TITLE
Author Metadata: {Yash Kumar Atri}

### ISSUE THREAD

**Issue by yashkumaratri** [acl-org/acl-anthology#3699]
### Author Pages

https://aclanthology.org/people/y/yash-kumar/

https://aclanthology.org/people/y/yash-atri/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [X] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Hi,

Correct author name should be "Yash Kumar Atri". The pdf reflects the same name on the anthology.

Here are the pdfs
https://aclanthology.org/2023.emnlp-main.133/
https://aclanthology.org/2020.findings-emnlp.254/

Website: https://yashkumaratri.github.io

**Comment by mbollmann** [comment]
Could you please indicate which part of your name should be considered first vs. last name?

**Comment by yashkumaratri** [comment]
First name can be "Yash Kumar", and last can be "Atri".
