### ISSUE TITLE
ACL 2017 not indexing correctly on Google scholar.

### ISSUE THREAD

**Issue by soroushv** [acl-org/acl-anthology#37]
The dates and the publisher information is not being picked up by google scholar. Also, a lot of the references are not indexed with the correct metadata (i.e., they don't get added to the list of citations of the papers they cite).

**Comment by CTNLP** [comment]
I talked to the people at Google and they say that this is a byproduct of the fact that they have only been able to crawl the new version of the anthology with the meta-data and the pdfs recently (in August 2017 we slightly changed the way that hosting of the anthology is structured) and that it will take them until the next crawl for this to be fixed. From the E-Mail exchange:

"With the changes recently made to adjust the landing-page urls to include the common ID with the pdf url - and the Scholar engineers' work to tie those two urls together - once the content is recrawled, and then refreshed with the next full Scholar index rebuild (in ~late-December/early-January), authors will likely see considerable improvements in search results and to publication listings in their profiles.  

Note that the previously indexed content does need a full Scholar index refresh to update, but any new papers, never before discovered by the indexer, would have the changes taken into account just after they're crawled."

So it seems that this will be fixed from Google's side, but it will take at least until the end of the year. I will close this issue as there seems to be nothing we can do about it at the moment, but if the re-crawl does not fix it by the start of next year, then feel free to bring this to our attention again.
