### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by Ibrahimbodie** [acl-org/acl-anthology#3712]
Hello, I would like to have your dataset for a study project.

**Comment by mbollmann** [comment]
All of our data is freely available in this repo.

PDFs can be obtained by running [a mirroring script](https://github.com/acl-org/acl-anthology/blob/8e24ffe915ee8f8c79522418427889cfbc6e7b17/bin/create_mirror.py) or from other people who have prepared such datasets, for example https://huggingface.co/datasets/WINGNUS/ACL-OCL.
