### ISSUE TITLE
Paper Metadata: {2024.naacl-long.59}

### ISSUE THREAD

**Issue by funzac** [acl-org/acl-anthology#3718]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.naacl-long.59

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Olufunke O. Sarumi, Béla Neuendorf, Joan Plepi,  Lucie Flek,  Jörg Schlötterer, Charles Welch

**Comment by funzac** [comment]
The right order of my name has been corrected as shown on the PDF.  The correct citation should be :

Olufunke O. Sarumi, Béla Neuendorf, Joan Plepi, Lucie Flek, Jörg Schlötterer, and Charles Welch. 2024. [Corpus Considerations for Annotator Modeling and Scaling](https://aclanthology.org/2024.naacl-long.59). In Proceedings of the 2024 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies (Volume 1: Long Papers), pages 1029–1040, Mexico City, Mexico. Association for Computational Linguistics.

**Comment by anthology-assist** [comment]
@funzac Could you explain what's wrong with the citation?

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.naacl-long.59}](https://aclanthology.org/2024.naacl-long.59})) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.

**Comment by funzac** [comment]
Dear Matt,

Thank you for your email, and please pardon my late response. The bib key
currently shows oluyemi-etal-2024-corpus. The correct bib key should be
sarumi-etal-2024-corpus.

Oluyemi is my middle name not by first or last name.

This is the current status:
@inproceedings{oluyemi-etal-2024-corpus,
    title = "Corpus Considerations for Annotator Modeling and Scaling",
    author = {Sarumi, Olufunke O.  and
      Neuendorf, B{\'e}la  and
      Plepi, Joan  and
      Flek, Lucie  and
      Schl{\"o}tterer, J{\"o}rg  and
      Welch, Charles},
    editor = "Duh, Kevin  and
      Gomez, Helena  and
      Bethard, Steven",
    booktitle = "Proceedings of the 2024 Conference of the North American
Chapter of the Association for Computational Linguistics: Human Language
Technologies (Volume 1: Long Papers)",
    month = jun,
    year = "2024",
    address = "Mexico City, Mexico",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/2024.naacl-long.59",
    doi = "10.18653/v1/2024.naacl-long.59",
    pages = "1029--1040"

THIS IS WHAT IT SHOULD BE
@inproceedings{sarumi-etal-2024-corpus,
    title = "Corpus Considerations for Annotator Modeling and Scaling",
    author = {Sarumi, Olufunke O.  and
      Neuendorf, B{\'e}la  and
      Plepi, Joan  and
      Flek, Lucie  and
      Schl{\"o}tterer, J{\"o}rg  and
      Welch, Charles},
    editor = "Duh, Kevin  and
      Gomez, Helena  and
      Bethard, Steven",
    booktitle = "Proceedings of the 2024 Conference of the North American
Chapter of the Association for Computational Linguistics: Human Language
Technologies (Volume 1: Long Papers)",
    month = jun,
    year = "2024",
    address = "Mexico City, Mexico",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/2024.naacl-long.59",
    doi = "10.18653/v1/2024.naacl-long.59",
    pages = "1029--1040"


Thank you.
Regards,
Olufunke

**Comment by mjpost** [comment]
This will be merged with #4399.
