### ISSUE TITLE
Paper Metadata: 2024.findings-eacl.100

### ISSUE THREAD

**Issue by davidanugraha** [acl-org/acl-anthology#3726]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-eacl.100

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

[Eric Khiu](https://aclanthology.org/people/e/eric-khiu/), [Hasti Toossi](https://aclanthology.org/people/h/hasti-toossi/), [David Anugraha](https://aclanthology.org/people/d/david-anugraha/), [Jinyu Liu](https://aclanthology.org/people/j/jinyu-liu/), [Jiaxu Li](https://aclanthology.org/people/j/jiaxu-li/), [Juan Flores](https://aclanthology.org/people/j/juan-flores/), [Leandro Roman](https://aclanthology.org/people/l/leandro-roman/), [A. Seza Doğruöz](https://aclanthology.org/people/a/a-seza-dogruoz/), [En-Shiun Lee](https://aclanthology.org/people/e/en-shiun-lee/)

**Comment by anthology-assist** [comment]
@davidanugraha could you specify which author name needs to be updated?

**Comment by davidanugraha** [comment]
Seems like it has already been fixed, thanks!
