### ISSUE TITLE
Author Metadata: rahulseetharaman

### ISSUE THREAD

**Issue by rahulseetharaman** [acl-org/acl-anthology#3728]
### Author Pages

Author Pages
https://aclanthology.org/people/s/rahulseetharaman/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

I do not have any paper in ACL. I am trying to create an ACL anthology URL for an OpenReview account for my first paper submission.

**Comment by mbollmann** [comment]
We do not create these manually; you will automatically have an author page once you have a paper in the ACL Anthology. ACL does not require one for paper submission.
