### ISSUE TITLE
Paper Revision: {2024.iwslt-1.1}

### ISSUE THREAD

**Issue by esalesky** [acl-org/acl-anthology#3729]
### Anthology ID

2024.iwslt-1.1

### Type of Change

Revision

### PDF of the Revision or Erratum

https://drive.google.com/file/d/1UAE2q1Gl_6fjPVWbWWx0qbfTOsK3feR9/view?usp=sharing

### Brief Description of Changes

The current paper pdf links to the workshop's front matter, not the paper. The correct watermarked pdf is linked here.

**Comment by mjpost** [comment]
Fixed, sorry this took so long.

**Comment by esalesky** [comment]
Thanks!!
