### ISSUE TITLE
Missing Paper from ACL24 Anthology: DeVAn: Dense Video Annotation for Video-Language Models

### ISSUE THREAD

**Issue by TK-21st** [acl-org/acl-anthology#3733]
Our paper _DeVAn: Dense Video Annotation for Video-Language Models_ was registered and has been presented at ACL24 in Bangkok, but it is missing from the ACL24 anthology https://aclanthology.org/events/acl-2024/#2024acl-long.

Please let us know how to correct for this omission. 
Thank you!

**Comment by mjpost** [comment]
Thanks for your report. ACL 2024 is aware of this issue which appears to affect nearly 100 papers, and is looking into it. We hope to have an update from them soon.

**Comment by ylwangy** [comment]
@mjpost 

Our long paper is also missing:  _Reasoning in Conversation: Solving Subjective Tasks through Dialogue Simulation for Large Language Models_

hope it can be fixed as soon as possible. If there is anything that we need to do, please let us know.

Thank you!

**Comment by mjpost** [comment]
Hi—we are waiting for the ACL 2024 committee to deliver to use the complete proceedings. They are working on it and we hope to have an update soon.

**Comment by TK-21st** [comment]
> Thanks for your report. ACL 2024 is aware of this issue which appears to affect nearly 100 papers, and is looking into it. We hope to have an update from them soon.

Thank you! Please let us know when it's up!

**Comment by mjpost** [comment]
Now available:
* https://aclanthology.org/2024.acl-long.772/
* https://aclanthology.org/2024.acl-long.844/
