### ISSUE TITLE
Paper Revision: 2024.loresmt-1.10

### ISSUE THREAD

**Issue by Vitaly-Protasov** [acl-org/acl-anthology#3752]
### Anthology ID

2024.loresmt-1.10

### Type of Change

Erratum

### PDF of the Revision or Erratum

[2024.loresmt-1.10.pdf](https://github.com/user-attachments/files/16614528/2024.loresmt-1.10.pdf)

### Brief Description of Changes

Fix of small insignificant typos to improve the readability

**Comment by mbollmann** [comment]
No need to up this, it has already been addressed and will be merged together with all other fixes towards the end of the month.
