### ISSUE TITLE
Paper Metadata: {2023.arabicnlp-1.12, 2023.arabicnlp-1.89, 2022.umios-1.2}

### ISSUE THREAD

**Issue by niamaelkhbir** [acl-org/acl-anthology#3755]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.arabicnlp-1.12, 2023.arabicnlp-1.89, 2022.umios-1.2

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

In all the 3 papers, replace the name "Niama El Elkhbir" by "Niama El Khbir" 
First name: Niama
Last name: El Khbir

**Comment by anthology-assist** [comment]
Dupe

**Comment by niamaelkhbir** [comment]
Excuse me?

> Dupe
