### ISSUE TITLE
Ingestion Request [10-30-2024]: {ICNLSP 2024}

### ISSUE THREAD

**Issue by icnlsp** [acl-org/acl-anthology#3779]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

ICNLSP

### Volume Title

Proceedings of the 7th International Conference on Natural Language and Speech Processing (ICNLSP-2024))

### Date of Publication

2024-10-30

### Location

Trento, Italy

**Comment by anthology-assist** [comment]
Please submit ingestion material 2 weeks prior to desired publication date @icnlsp

**Comment by anthology-assist** [comment]
@icnlsp any updates?
