### ISSUE TITLE
Missing Paper from ACL24 Anthology: ArtPrompt: ASCII Art-based Jailbreak Attacks against Aligned LLMs

### ISSUE THREAD

**Issue by Django-Jiang** [acl-org/acl-anthology#3788]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.acl

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)

**Comment by Django-Jiang** [comment]
Our paper ArtPrompt: ASCII Art-based Jailbreak Attacks against Aligned LLMs is missing from the proceeding. Like #3733, still resolved.

**Comment by mjpost** [comment]
[Now available](https://aclanthology.org/2024.acl-long.809/).
