### ISSUE TITLE
Missing Paper from ACL24 Anthology: Disentangled Learning with Synthetic Parallel Data for Text Style Transfer (Submission number: 912)

### ISSUE THREAD

**Issue by hjx999222** [acl-org/acl-anthology#3791]
Our paper titled "Disentangled Learning with Synthetic Parallel Data for Text Style Transfer" (Submission number: 912) has been accepted as a long paper for the main conference at ACL 2024. However, it does not appear in the recently published list of accepted papers on official website.(https://aclanthology.org/volumes/2024.acl-long/)

**Comment by mbollmann** [comment]
See https://github.com/acl-org/acl-anthology/pull/3753

**Comment by mjpost** [comment]
[Now available](https://aclanthology.org/2024.acl-long.811/).
