### ISSUE TITLE
Character ń appears as ? in export files

### ISSUE THREAD

**Issue by AgnieszkaFalenska** [acl-org/acl-anthology#38]
The diacritic character ń is causing problems while generating export files. I have just checked my publications list:

http://aclanthology.info/catalog?utf8=%E2%9C%93&search_field=all_fields&q=Agnieszka+Falenska

The three papers which were published under surname "Faleńska" and not "Falenska" have errors in bibtex files (but also all other export files). There is "Fale?ska" without n on the authors list (it should be \\'{n} ).

It might cause problems for anybody who would like to cite those papers. And also for any other authors who have ń in their surnames.

**Comment by danielgildea** [comment]
Works in my local installation - with luck this will be fixed by pull request #36.

**Comment by AgnieszkaFalenska** [comment]
I checked and it looks ok now -- no question marks.
Some of the characters appear with additional brackets now:
ń -> {\'{n}}
Ç -> {\c{C}}
ğ -> {\u{g}}
but 
ö -> {\"o}
á -> {\'a}

Is this an intended behaviour? If yes then the issue can be closed.

**Comment by danielgildea** [comment]
I think the extra brackets are intended, though not strictly necessary.
In any case they come from the bibutils package.
