### ISSUE TITLE
Q19-1005 through 1014 are 404

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#380]
PDF links for TACL 2019 only work for me up to Q19-1004; the papers Q19-1005 and higher are 404.

**Comment by boknilev** [comment]
Same for me. 

In addition, Q19-1004, which is correct, appears in another entry as [N19-1338](https://aclweb.org/anthology/papers/N/N19/N19-1338), as if it's a NAACL paper (it's not). So, N19-1338 can probably be removed completely.

**Comment by aryamccarthy** [comment]
Cool, this error makes sense.

For TACL, I've mostly focused on getting correct metadata in the anthology. I've been handing off archive files containing the PDFs to somebody (Matt?) who's been handling their upload for me.

I should do this from now on. What are the steps? Which powers do I need?

**Comment by davidweichiang** [comment]
Also, N19-1338's PDF is just the author instructions. The other TACL papers at N19 should be checked as well.
