### ISSUE TITLE
Missing Paper from ACL24 Anthology: LooGLE: Can Long-Context Language Models Understand Long Contexts? (Submission number 2635)) 

### ISSUE THREAD

**Issue by lijiaqijane** [acl-org/acl-anthology#3804]
Our paper titled "LooGLE: Can Long-Context Language Models Understand Long Contexts?" (Submission number: 2635) has been accepted as a long paper for the main conference at ACL 2024.   

However, it does not appear in the recently published list of accepted papers on official website. (https://aclanthology.org/volumes/2024.acl-long/)

Please let us know how to correct for this omission.
Thank you!

**Comment by nschneid** [comment]
See #3753

**Comment by mjpost** [comment]
This has now been merged and [your paper is available](https://aclanthology.org/2024.acl-long.859/).
