### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by ohnlp** [acl-org/acl-anthology#381]
Use this template to submit supplemental material to the ACL Anthology (e.g., posters or slides).

Please:

- [ N19-5006] Note the ACL Anthology ID of your paper (e.g., P18-1021)
- [ [T6_Applications_of_NLP_in_Clinical_Research_and_Practice.pdf](https://github.com/acl-org/acl-anthology/files/3250574/T6_Applications_of_NLP_in_Clinical_Research_and_Practice.pdf)] Attach a file to this post
- [Slides for Tutorial 6: Applications of Natural Language Processing in Clinical Research and Practice ] Include a description

**Comment by mjpost** [comment]
Can I ask you to submit here instead? https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u

**Comment by mjpost** [comment]
Moved to spreadsheet.
