### ISSUE TITLE
Paper Metadata: 2024.findings-acl.532

### ISSUE THREAD

**Issue by kamigaito** [acl-org/acl-anthology#3813]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-acl.532

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Juseon-Do, Jingun Kwon, Hidetaka Kamigaito, Manabu Okumura

**Comment by kamigaito** [comment]
Thank you so much for your immediate update of the XML file!
However, It seems the wrong name `<author><first>Juseon-Do</first><last>Juseon-Do</last></author>` is not updated. If the current ACL anthology system cannot handle the hyphenation of the name, would it be possible to put a blank to the last name like `<author><first>Juseon-Do</first><last></last></author>`? I'm sorry for bothering you, but checking it will support people with a hyphened name.

**Comment by mbollmann** [comment]
This can be represented as `<author><last>Juseon-Do</last></author>`, which would lead to the paper being cited as "Juseon-Do et al.". Having hyphenation between first and last name is not representable in BibTeX and other citation formats, to my knowledge.

**Comment by kamigaito** [comment]
Thank you so much! I appreciate your immediate response! This information is quite helpful for us!
Then, could you update the information to `<author><last>Juseon-Do</last></author>`?
