### ISSUE TITLE
Ingestion Request [09-30-2024]: 16th Conference of the Association for Machine Translation in the Americas

### ISSUE THREAD

**Issue by ShivaliGoel** [acl-org/acl-anthology#3818]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

amta

### Volume Title

Proceedings of the 16th Conference of the Association for Machine Translation in the Americas

### Venue Website (only if you are submitting a new venue)

https://amtaweb.org/

### Date of Publication

2024-09-30

### Location

Chicago, United States of America

### Supporting Information

Volume identifier: amta-research
Volume Title: Proceedings of the 16th Conference of the Association for Machine Translation in the Americas: Research Papers 

Volume identifier: amta-presentations
Volume Title: Proceedings of the 16th Conference of the Association for Machine Translation in the Americas: Presentations

**Comment by mjpost** [comment]
Looks good, thank you!

**Comment by ShivaliGoel** [comment]
@mjpost how do I submit the data?

**Comment by mjpost** [comment]
You can upload or link to it here.

**Comment by ShivaliGoel** [comment]
@mjpost https://drive.google.com/file/d/1a9ERZElG63P_pIqYgQYc1VcevzuAShi-/view?usp=sharing

**Comment by mjpost** [comment]
Thanks. We can't guarantee this will be ingested before Sep. 30, but will try.

**Comment by mjpost** [comment]
@anthology-assist @davidstap Does one of you have time to process this in the next day or two?

**Comment by davidstap** [comment]
Yes I can process this tomorrow or Saturday.

**Comment by mjpost** [comment]
If you're able to check it sooner for mistakes that would help. Not sure if you've processed ACLPUB tarballs before but this one uses plain "ingest.py".

**Comment by davidstap** [comment]
@mjpost ready for review now

**Comment by ShivaliGoel** [comment]
Hi @davidstap @mjpost I noticed an error. Volume 2 is called presentations not user track. I checked meta file again it says presentations, can we please update it?

**Comment by mjpost** [comment]
@davidstap Can you correct the book title in the metadata and issue a PR?

**Comment by davidstap** [comment]
Fixed now, see #3921. Note that I chose `User Track` over `Presentations` to be consistent with earlier AMTA proceedings.
