### ISSUE TITLE
Ingestion of IWPT 1989

### ISSUE THREAD

**Issue by kilian-gebhardt** [acl-org/acl-anthology#382]
The digitization lab at CMU provided us with [scans of the IWPT 1989 proceedings in pdf and pdf-a](https://cmu.box.com/s/si2b55frzyxxiqw2pnhfpmnqzhoay81y).
The PDFs already have OCR.

Todos: 
- [x] split scan into individual papers
- [x] create anthology metadata. Might be automated by parsing [this table of contents](https://www.cs.cmu.edu/~sigparse/previousmeetings/iwpt89_toc.html).

**Comment by mjpost** [comment]
Whoa , cool. I assume we checked whether they have other years as well?

**Comment by kilian-gebhardt** [comment]
Yes, this seems to be the only volume of IWPT they have.

**Comment by mjpost** [comment]
I found the same one in the JHU library. It seems someone probably went to the trouble to get an ISBN for that first workshop but not subsequent ones.

**Comment by kilian-gebhardt** [comment]
@mjpost can you assign an anthology ID for this volume?

**Comment by mjpost** [comment]
It looks like there were no workshops in 1989! So I get the ID is

    W89-01%02

**Comment by kilian-gebhardt** [comment]
[This script](https://gist.github.com/kilian-gebhardt/f25c7d9124d7e45c2a09688ed81a40ad) creates bibtex entries based on TOC (with a few mistakes that require manual correction) and splits the main pdf into individual pdfs. More to come tomorrow.

Open:
- [ ] Front matter
- [ ] Fix typos/inconsistencies
- [ ] Abstracts – this will require many manual corrections, because the OCR is not that good

**Comment by kilian-gebhardt** [comment]
> It looks like there were no workshops in 1989! So I get the ID is
> 
> ```
> W89-01%02
> ```

`W89-01%02` is taken already by NODALIA 1989, see #450 . I take `W89-02%02` then.

**Comment by kilian-gebhardt** [comment]
The output of `anthology_xml.py` from ACLPUB's master branch produces xml that is not accepted by the compilation process as before. How can I produce valid anthology xml from a directory of the form 
`W/W18/...` populated with `.bib` files and `pdf`s at the moment? @mjpost

**Comment by mjpost** [comment]
run make_nested.py on the xml file.

**Comment by mjpost** [comment]
(I've got to update the instructions here to simplify this process—you might also want to run `normalize_anth.py` to apply fixed-case protection)
