### ISSUE TITLE
Paper Metadata: 2023.isa-1.4

### ISSUE THREAD

**Issue by MBoritchev** [acl-org/acl-anthology#3824]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.isa-1.4

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

[Johannes Heinecke](https://aclanthology.org/people/j/johannes-heinecke/)

**Comment by anthology-assist** [comment]
@MBoritchev Meta data looks right two me: https://aclanthology.org/2023.isa-1.4/

**Comment by mbollmann** [comment]
@anthology-assist [Maria Boritchev](https://aclanthology.org/people/m/maria-boritchev/) is listed as an author in the metadata, but not the PDF.
