### ISSUE TITLE
Addition: N19-5002 slides

### ISSUE THREAD

**Issue by sleepinyourhat** [acl-org/acl-anthology#383]
Slides for tutorial: Deep Learning for Natural Language Inference
N19-5002
File: https://nlitutorial.github.io/nli_tutorial.pdf

**Comment by mjpost** [comment]
I was just about to email folks and ask for these. Thanks for submitting!

**Comment by sleepinyourhat** [comment]
Michael Strube beat you to it.

**Comment by mjpost** [comment]
Would you mind submitting here instead? https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u

(this will allow me to bulk import)

**Comment by mjpost** [comment]
Moved to spreadsheet.
