### ISSUE TITLE
Paper Metadata: {2024.acl-long.748}

### ISSUE THREAD

**Issue by XinhaoZh23** [acl-org/acl-anthology#3848]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.acl-long.748

### Type of Paper Metadata Correction

- [X] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)

### Correction to Paper Title

Prototypical Reward Network for Data-Efficient RLHF

**Comment by anthology-assist** [comment]
The title is correct.
