### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by jacobeisenstein** [acl-org/acl-anthology#385]
Use this template to submit supplemental material to the ACL Anthology (e.g., posters or slides).

Please:

- [ ] Note the ACL Anthology ID of your paper (e.g., P18-1021)

N19-5003

- [ ] Attach a file to this post

[slides](https://github.com/jacobeisenstein/language-change-tutorial/blob/master/eisenstein-naacl-slides.pdf)

- [ ] Include a description

Slides from tutorial on Measuring and Modeling Change

**Comment by mjpost** [comment]
Moved to spreadsheet.
