### ISSUE TITLE
Paper Metadata: 2024.findings-acl.130

### ISSUE THREAD

**Issue by Yukyin** [acl-org/acl-anthology#3853]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.acl-long.130

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Yuyan Chen, Yiwen Qian, Songzhou Yan, Jiyuan Jia, Zhixu Li, Yanghua Xiao, Xiaobo Li, Ming Yang, Qingpei Guo

**Comment by anthology-assist** [comment]
@Yukyin You provided the wrong anthology id. Please update.

**Comment by Yukyin** [comment]
done

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.findings-acl.130](https://aclanthology.org/2024.findings-acl.130)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
