### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by XiaoYee** [acl-org/acl-anthology#386]
Use this template to submit supplemental material to the ACL Anthology (e.g., posters or slides).

Please:

- [ ] Note the ACL Anthology ID of your paper (e.g., P18-1021)
N19-1258
- [ ] Attach a file to this post
[NAACL2019.pptx](https://github.com/acl-org/acl-anthology/files/3254227/NAACL2019.pptx)
- [ ] Include a description

**Comment by mjpost** [comment]
Moved to the spreadsheet.
