### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by pdasigi** [acl-org/acl-anthology#387]
Use this template to submit supplemental material to the ACL Anthology (e.g., posters or slides).

Please:

- [x] Note the ACL Anthology ID of your paper (e.g., P18-1021): N19-1273
- [x] Attach a file to this post: [iterative_search_naacl2019 .pdf](https://github.com/acl-org/acl-anthology/files/3254282/iterative_search_naacl2019.pdf)
- [x] Include a description: Slides

**Comment by mjpost** [comment]
Moved to [the spreadsheet](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u).
