### ISSUE TITLE
Paper Metadata: {2024.arabicnlp-1.65}

### ISSUE THREAD

**Issue by BlqeesBusaidi** [acl-org/acl-anthology#3873]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.arabicnlp-1.65

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Blqees Al Busaidi
Al Manar Al Wardi
Malath Al Sibani
Hiba Al Siyabi 
Najma Al Zadjaly

**Comment by BlqeesBusaidi** [comment]
There are some mistakes in some of the authors' names.
So, I am writing this to request the journal editors to change the names.

**Comment by anthology-assist** [comment]
The meta data names match the names on the PDF.
