### ISSUE TITLE
Addition: Transfer Learning in NLP (N19-5004)

### ISSUE THREAD

**Issue by swabhs** [acl-org/acl-anthology#388]
Slides for **Transfer Learning in Natural Language Processing** Tutorial at _NAACL 2019_.

- ACL Anthology ID : N19-5004
[Transfer Learning in Natural Language Processing.pdf](https://github.com/acl-org/acl-anthology/files/3254542/Transfer.Learning.in.Natural.Language.Processing.pdf)

This tutorial presents an overview of modern transfer learning methods in NLP, with detailed discussion regarding pre-training approaches for obtaining representations of words, sentence and documents, including a historical perspective. This is followed by a further discussion on what information the representations they learn capture, and review examples and case studies on how these models can be integrated and adapted in downstream NLP tasks.

A hands-on [Colab](http://tiny.cc/NAACLTransferColab) and a [code repository](http://tiny.cc/NAACLTransferCode) is also provided.

**Comment by mjpost** [comment]
Moved to [the spreadsheet](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u).
