### ISSUE TITLE
Addition: N19-1006 talk slides

### ISSUE THREAD

**Issue by 0xSameer** [acl-org/acl-anthology#389]
- ACL Anthology ID: N19-1006
- [N19-1006 talk slides.pdf](https://github.com/acl-org/acl-anthology/files/3257652/N19-1006_talk_slides.pdf)

- Title: "Pre-training on high-resource speech recognition improves low-resource speech-to-text translation",  Sameer Bansal, Herman Kamper, Karen Livescu, Adam Lopez, Sharon Goldwater.

**Comment by mjpost** [comment]
Thank you! Can I ask you instead to submit using [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u)?

**Comment by mjpost** [comment]
Moved this over myself. We'll ingest within a week or so.

**Comment by 0xSameer** [comment]
Apologies if I used the incorrect submission link and thanks for moving it!

Regards,

-Sameer

**Comment by mjpost** [comment]
No, it's my fault—I am just now changing the submission process to better enable me to bulk import them. Thanks!

**Comment by 0xSameer** [comment]
Thanks for all the great work putting this together!
