### ISSUE TITLE
Addition: N19-1152 Poster

### ISSUE THREAD

**Issue by dpavot** [acl-org/acl-anthology#390]
-  ACL Anthology ID: N19-1152
- [NAACL_poster.pdf](https://github.com/acl-org/acl-anthology/files/3257945/NAACL_poster.pdf)
- Title: "A Silver Standard Corpus of Human Phenotype-Gene Relations". Authors: Diana Sousa, Andre Lamurias and Francisco M. Couto

**Comment by mjpost** [comment]
Thanks! Can I ask you to submit instead using [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u)?

**Comment by mjpost** [comment]
Thank you!
