### ISSUE TITLE
Paper Metadata: 2024.ml4al-1.8

### ISSUE THREAD

**Issue by lgessler** [acl-org/acl-anthology#3904]
### Author Pages

https://aclanthology.org/people/l/lydia-bremermccollum/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

There is a missing hyphen in this author's name in ACL Anthology, as can be seen from the contents of [the author's first paper](https://aclanthology.org/2024.ml4al-1.8.pdf).

**Comment by mbollmann** [comment]
Additional information for @anthology-assist (I checked this against the PDF):

### Anthology ID

2024.ml4al-1.8

### Correction to Author Name(s)

BremerMcCollum -> Bremer-McCollum

Additionally, "Cindy Li" needs to be corrected to `<first>Cindy</first><last>Tung Li</last>` (other sources give "Tung Li" as the last name component, e.g. [here](https://www.researchgate.net/publication/382331629_Lacuna_Language_Learning_Leveraging_RNNs_for_Ranked_Text_Completion_in_Digitized_Coptic_Manuscripts/citation/download)).
