### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by BordiaS** [acl-org/acl-anthology#392]
Use this template to submit supplemental material to the ACL Anthology (e.g., posters or slides).

Please:

-  ACL Anthology ID: N19-3002
-  Slides 
- Title: "Identifying and Reducing Gender Bias in Word-Level Language Models"

[Identifying and Reducing Gender Bias in Word-Level Language Models (slides).pdf](https://github.com/acl-org/acl-anthology/files/3258233/Identifying.and.Reducing.Gender.Bias.in.Word-Level.Language.Models.slides.pdf)

**Comment by BordiaS** [comment]
Use this template to submit supplemental material to the ACL Anthology (e.g., posters or slides).

Please:

-  ACL Anthology ID: N19-3002
-  Supplementary
[Identifying_and_Reducing_Gender_Bias_in_Word_Level_Language_Models (supplementary).pdf](https://github.com/acl-org/acl-anthology/files/3258235/Identifying_and_Reducing_Gender_Bias_in_Word_Level_Language_Models.supplementary.pdf)

- Title: "Identifying and Reducing Gender Bias in Word-Level Language Models"

**Comment by mjpost** [comment]
Hi, we're changing this submission system. Can I ask you to please re-submit using [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u)?

**Comment by BordiaS** [comment]
What about the supplementary material?

**Comment by mjpost** [comment]
Same, please.

**Comment by BordiaS** [comment]
I didn't see the option for supplementary so I added the attachment type as Note
