### ISSUE TITLE
Addition N19-1115

### ISSUE THREAD

**Issue by serhii-havrylov** [acl-org/acl-anthology#393]
slides for ACL Anthology ID: N19-1115
[N19-1115.pdf](https://github.com/acl-org/acl-anthology/files/3258624/N19-1115.pdf)

**Comment by mjpost** [comment]
Hi, we're changing this submission system. Can I ask you to please re-submit using [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u)?
