### ISSUE TITLE
Ingestion Request: JLCL

### ISSUE THREAD

**Issue by wartaal** [acl-org/acl-anthology#3933]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

JLCL

### Volume Title

Volume 36

### Venue Name (only if you are submitting a new venue)

Journal for Language Technology and Computational Linguistics

### Venue Website (only if you are submitting a new venue)

https://jlcl.org/

### Supporting Information

JLCL is a journal, noty a conference. I would start ingesting Volume 36 (2023) and once that works fine, do the same for some previous volumes.

We had already contact on this topic over e-mail.

**Comment by wartaal** [comment]
[jlcl36_data.tar.gz](https://github.com/user-attachments/files/17592224/jlcl36_data.tar.gz)

Yes, of course. I apologize for the delay.

**Comment by anthology-assist** [comment]
@wartaal 2023 volumes have been ingested. Could you check the preview here #3994 and let me know if you spot any problems? Also could you let me know the location of the journal?

If 2023 volumes look good, we can go ahead with other years.

**Comment by mjpost** [comment]
Hi, why are there two volumes, the second with just two papers? They both have the same volume name. The names should be different.

**Comment by wartaal** [comment]
Good morning,

in 2023 we published 2 issues of the journal: a regular issue and a special issue on song texts. My idea was to ingest each JLCL issue as a separate volume in the anthology.  The volumes are called "Journal for Language Technology and Computational Linguistics, Vol.36. No. 1" and  "... No. 2. (Or ist there a copy and paste error at some point?)  Indeed, we had only two publications in the regular issue.

If you think it is better to put all papers of all issues of one year into one ACL-Anthology volume, that would of course not be a problem to do so.

**Comment by mbollmann** [comment]
@mjpost I think the identical volume names arise because the venue is not properly marked as a journal in the metadata. The bibliographic info on the preview is for a conference proceedings.

**Comment by wartaal** [comment]
I think the bib-files are quite clear, but the problem is in the meta-files. Is that correct? How should the meta-file look like? I found only examples of this file for conference proceedings. What fields neend to be present for a journal?

**Comment by mjpost** [comment]
Multiple volumes is fine; the issue as I see it is that they are indistinguishable by name: https://preview.aclanthology.org/jlcl-ingestion/venues/jlcl/

![image](https://github.com/user-attachments/assets/4d924ed0-db17-4ec2-8501-930ec29516f0)

For example, for other journals, the issue information is added to the booktitle:

https://aclanthology.org/venues/cl/

![image](https://github.com/user-attachments/assets/f9d4dd50-7de2-43ed-b943-65792c167bb1)

Do you not want to do something similar?

**Comment by wartaal** [comment]
Yes! That is exactly what I would like to be it. What I put in the meta file is

abbrev JLCL
volume 1
title Issue 1
booktitle Journal for Language Technology and Computational Linguistics, Vol.36. No. 1
shortbooktitle Journal for Language Technology and Computational Linguistics
....


I guess the shortbooktitle  is the problem and I should make that identical to the booktiltle?

**Comment by mjpost** [comment]
Hmm, if that's what you had, then it seems we mis-parsed it. I just made the edit. If [the new preview](https://preview.aclanthology.org/jlcl-ingestion/venues/jlcl/) (should be live within half an hour) checks out, let me know, and I can merge this.

**Comment by wartaal** [comment]
Thanks a lot! The preview looks good for me!

**Comment by mjpost** [comment]
Hi, it's been live for some time! https://aclanthology.org/venues/jlcl/

Or did you mean you want it linked from the front page? We could do that, we just don't typically do it by default.
