### ISSUE TITLE
Ingestion Request: CLIB 2014, CLIB 2016, CLIB 2018

### ISSUE THREAD

**Issue by iva-dcl** [acl-org/acl-anthology#3935]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

CLIB

### Volume Title

Previous volumes of CLIB Proceedings

### Location

Sofia, Bulgaria

### Supporting Information

CLIB 2014
Proceedings of the First International Conference Computational Linguistics in Bulgaria (CLIB 2014)
Link to the material: https://drive.google.com/file/d/1-xNt6CgVnnrFaIJysENud1jqJFIOv8eb/view?usp=drive_link

CLIB 2016
Proceedings of the Second International Conference Computational Linguistics in Bulgaria (CLIB 2016)
Link to the material: https://drive.google.com/file/d/10MnHL07CbSkFkZr5aqDCOILysf5KX8UA/view?usp=drive_link

CLIB 2018
Proceedings of the Third International Conference Computational Linguistics in Bulgaria (CLIB 2018)
Link to the material: https://drive.google.com/file/d/1TcKBUGCrkTFpA-22c3PJ29nzuqcmTm7v/view?usp=drive_link

**License details for all volumes:** Proceedings are licensed under a Creative Commons Attribution 4.0. International License (CC BY 4.0) and upon submission authors have confirmed their agreement with the license's terms.
ISSN 2367-5578 (print)
ISSN 2367-5675 (online)

Contact email: [clib2024@dcl.bas.bg](mailto:clib2024@dcl.bas.bg)

Many thanks,
Ivelina Stoyanova

**Comment by anthology-assist** [comment]
@iva-dcl All years have been ingested #3953 Please take a look at the preview and let me know any issues. 

Looks like the editors are missing for all years (14, 16, 18 and #3934 ). Can you update?

**Comment by iva-dcl** [comment]
> @iva-dcl All years have been ingested #3953 Please take a look at the preview and let me know any issues.

Thanks a lot for that! I see no problems. 
 
> Looks like the editors are missing for all years (14, 16, 18 and #3934, and existing years https://aclanthology.org/venues/clib/).

Since it is a conference, we have no formal editors, but the Programme Committee serves as an editorial board. And the 'editor' field is optional in the @inproceedings bibtex entry. Would it be possible to include them without an editor? 
Many thanks!
Ivelina

**Comment by iva-dcl** [comment]
@mjpost, many thanks for your remarks!

> It's conventional to use the program committee as the list of editors for conference proceedings. Do you not want to do that?

Can we use the following as editors (chairs of the PC):
2014 - Svetlozara Leseva and Tsvetana Dimitrova and Ivelina Stoyanova and Ekaterina Tarpomanova and Rositsa Dekova
2016 - Svetla Koeva
2018 - Svetla Koeva and Mila Dimitrova-Vulchanova and Cvetana Krstev
2020 - Svetla Koeva and Petya Osenova
2022 - Svetla Koeva and Petya Osenova
2024 - Svetla Koeva and Petya Osenova 


> I also see on the preview page that you have changed the numbering convention, using written instead of numeric ordinals. Do you want to switch to numeric for consistency with prior volumes?

Yes, please. Or if it is easier, please change 4th > Fourth and 5th > Fifth. Whichever is easier to change.

Please let me know if you want me to make any changes.

Many thanks for your help!
Best wishes,
ivelina

**Comment by mjpost** [comment]
@anthology-assist can you add these names directly to the XML?
