### ISSUE TITLE
The EI retrieval system does not include my paper.

### ISSUE THREAD

**Issue by Heyest** [acl-org/acl-anthology#3942]
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

My paper, 'Boosting Textural NER with Synthetic Image and Instructive Alignment,' was published in the Findings of ACL 2024. However, when I searched for my paper in the EI database, I couldn't find it, while other papers from the Findings of ACL 2024 have generally been indexed by EI. Could you please help me check the indexing status of my paper in EI and explain why it might not have been included?

**Comment by mbollmann** [comment]
We have absolutely no control over or contact to external databases; we provide the metadata for all papers in the Anthology in the same way. I suggest you contact someone at the EI database.
