### ISSUE TITLE
Cross-listing workshops

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#396]
It would be nice if workshops were cross-listed under the conference they were associated with (e.g., workshops 13–30 on the [NAACL 2019](https://www.aclweb.org/anthology/events/naacl-2019/) pages).

**Comment by mbollmann** [comment]
This could already be achieved by adding the conference to the workshop IDs in `venues_joint_map.yaml`.

**Comment by mjpost** [comment]
Ah, thanks. This adds to the list of things I have to update manually on ingest, however, and these kinds of things really add up. I wonder about:

- Moving the information in `venues_joint_map.yaml` into the XML, say annotating it at the volume level (perhaps after the nested format is completed)
- Alternately, at least extending the ingestion XML format (from ACLPUB) to include this information, so it could be automatically added to the YAML file.

**Comment by mbollmann** [comment]
> * Moving the information in `venues_joint_map.yaml` into the XML, say annotating it at the volume level (perhaps after the nested format is completed)

It does depend on values that are only defined in `venues.yaml`, though. In other words, right now everything that refers to venues is somewhere in the `venues*.yaml` files, whereas putting it in the XML would mean having to make sure the content is valid with regard to `venues.yaml`.

Not saying it couldn't be a good idea nonetheless, just something to consider.
