### ISSUE TITLE
Applying Rhetorical Structure Theory to Student Essays for Automated Writing Feedback

### ISSUE THREAD

**Issue by kexin-yang** [acl-org/acl-anthology#399]
[Slides-Applying RST to student essays to provide automated writing feedback-compressed.pdf](https://github.com/acl-org/acl-anthology/files/3263780/Slides-Applying.RST.to.student.essays.to.provide.automated.writing.feedback-compressed.pdf)

We present a package of annotation resources, including annotation guideline, ﬂowchart, and an Intelligent Tutoring System for training human annotators. These resources can be used to apply Rhetorical Structure Theory (RST) to essays written by students in K-12 schools. Furthermore, we highlight the great potential of using RST to provide automated feedback for improving writing quality across genres.

**Comment by mjpost** [comment]
Please use the form here: https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u
