### ISSUE TITLE
Paper Metadata: 2023.conll-babylm.10

### ISSUE THREAD

**Issue by cainesap** [acl-org/acl-anthology#3995]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2023.conll-babylm.10

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

"{Diehl Martinez}, Richard  and
      McGovern, Hope  and
      Goriely, Zebulon  and
      Davis, Christopher  and
      Caines, Andrew  and
      Buttery, Paula  and
      Beinborn, Lisa"

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2023.conll-babylm.10](https://aclanthology.org/2023.conll-babylm.10)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
