### ISSUE TITLE
Paper Metadata: 2024.germeval-2.3

### ISSUE THREAD

**Issue by fmaoro** [acl-org/acl-anthology#4002]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.germeval-2.3

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

1. Falk (first name) Maoro (last name)
2. Michaela Geierhos (correct)

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.germeval-2.3](https://aclanthology.org/2024.germeval-2.3)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
