### ISSUE TITLE
Paper Metadata: 2024.bionlp-1.7

### ISSUE THREAD

**Issue by justin13601** [acl-org/acl-anthology#4010]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.bionlp-1.7

### Type of Paper Metadata Correction

- [X] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)

### Correction to Paper Title

Overview of the First Shared Task on Clinical Text Generation: RRG24 and Discharge Me!

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.bionlp-1.7](https://aclanthology.org/2024.bionlp-1.7)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
