### ISSUE TITLE
Paper Metadata: {2024.mrl-1.20} /Correction for my name

### ISSUE THREAD

**Issue by asdogruoz** [acl-org/acl-anthology#4015]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.mrl-1.20

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

My name appears wrong on the meta-data on ACL anthology for EMNLP24 (https://aclanthology.org/2024.mrl-1.20/). The correct version of my name should be "A. Seza Doğruöz" (not "A. Doğruöz"). Thanks for help!

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.mrl-1.20} /Correction for my name](https://aclanthology.org/2024.mrl-1.20} /Correction for my name)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
