### ISSUE TITLE
Paper Metadata: {2024.findings-emnlp.29}

### ISSUE THREAD

**Issue by long21wt** [acl-org/acl-anthology#4016]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-emnlp.29

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

[Doan Nam Long Vu](https://aclanthology.org/people/d/doan-nam-long-vu/), [Timour Igamberdiev](https://aclanthology.org/people/t/timour-igamberdiev/), [Ivan Habernal](https://aclanthology.org/people/i/ivan-habernal/)

**Comment by long21wt** [comment]
And btw the footnote on the first page say "Findings of the Association for Computational Linguistics: EACL 2024", it supposed to be "Findings of the Association for Computational Linguistics: EMNLP 2024"

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.findings-emnlp.29}](https://aclanthology.org/2024.findings-emnlp.29})) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
