### ISSUE TITLE
Paper Metadata: 2024.emnlp-main.200 and 2024.findings-emnlp.553

### ISSUE THREAD

**Issue by dilekh** [acl-org/acl-anthology#4019]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.emnlp-main.200 and 2024.findings-emnlp.553

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Please correct my name from "Dilek Tur" to "Dilek Hakkani-Tur" as listed in the pdf for both papers. 
First name: Dilek
Last name: Hakkani-Tur
Thanks!

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.emnlp-main.200 and 2024.findings-emnlp.553](https://aclanthology.org/2024.emnlp-main.200 and 2024.findings-emnlp.553)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
