### ISSUE TITLE
Paper Metadata: {024.genbench-1.11}

### ISSUE THREAD

**Issue by sagnik** [acl-org/acl-anthology#4020]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.genbench-1.11

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Please correct Sagnik Choudhury -> [Sagnik Ray Choudhury](https://aclanthology.org/people/s/sagnik-ray-choudhury/).

First name: Sagnik
Last name: Ray Choudhury

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([024.genbench-1.11}](https://aclanthology.org/024.genbench-1.11})) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
