### ISSUE TITLE
Ingestion: SwissText 2024

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#4025]
Data is here: https://fhgraubuenden-my.sharepoint.com/:f:/g/personal/capolcorsin_fhgr_ch/EvcZjQ0w7INGpSAeVPGbc-sBUUbGZaTzeXA_2pTuYJ1EcQ?e=xCA0jV

**Comment by muncca** [comment]
@mjpost When can we expect the publication of the proceedings?

**Comment by mjpost** [comment]
@anthology-assist can you comment here?

**Comment by mcieliebak** [comment]
is there any chance to get the proceedings published before end of year? Otherwise, we would have to inform the authors, who are waiting for the publication...
