### ISSUE TITLE
Open Graph protocol features in header

### ISSUE THREAD

**Issue by odashi** [acl-org/acl-anthology#403]
This is a request to add [Open Graph protocol (OGP)](http://ogp.me/) tags in the header of each paper page. 
Some websites that supports OGP can show users richer information, such as Slack with arXiv:
![Screenshot from 2019-06-10 16-05-52](https://user-images.githubusercontent.com/1023695/59178501-1b414e80-8b9a-11e9-8731-58748331f8c2.png)

**Comment by mjpost** [comment]
This is a good idea. Do you have any interest in adding it? The script you'd modify is [create_hugo_pages.py](https://github.com/acl-org/acl-anthology/blob/master/bin/create_hugo_pages.py), which generates all the template files that Hugo then fills. I imagine this should be pretty simple.

**Comment by mjpost** [comment]
Also the template is here: [hugo/layouts/papers/single.html](https://github.com/acl-org/acl-anthology/blob/master/hugo/layouts/papers/single.html).

**Comment by mbollmann** [comment]
It's pretty simple and should only require additions to the template, nothing else.

I started adding something like this when I looked into customizing the Google Custom Search results, but never finished it when I noticed GCS didn't offer the features I thought it did.

**Comment by odashi** [comment]
Thanks! As long as I checked arXiv's source, it contains at least following tags:
* `og:title`
* `og:site_name`
* `og:url`
* `og:description`

Maybe we can also provide `og:type` as `article` and [relevant metadata](http://ogp.me/#type_article) such as `published_time` and `author`.

**Comment by mjpost** [comment]
@odashi, would you be willing to add these to [the template listed above](https://github.com/acl-org/acl-anthology/blob/master/hugo/layouts/papers/single.html) and submit a PR? We'd love to have this in the Anthology but may not have time to do this for a while. We'd have a PR live within a day or so of acceptance!

**Comment by mjpost** [comment]
I still want to add custom paper images, but I'm not doing that at the moment...
