### ISSUE TITLE
Paper Metadata: 2024.mrl-1.11

### ISSUE THREAD

**Issue by guenthermi** [acl-org/acl-anthology#4069]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.mrl-1.11

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Rohan Jha, Bo Wang, Michael Günther, Georgios Mastrapas, Saba Sturua, Isabelle Mohr, Andreas Koukounas, Mohammad Kalim Akram, Nan Wang, Han Xiao

All names are in the format {first name} {last name} For "Mohammad Kalim Akram", "Mohammad Kalim" is the first name.

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.mrl-1.11](https://aclanthology.org/2024.mrl-1.11)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
