### ISSUE TITLE
Paper Metadata: 2024.acl-tutorials.3

### ISSUE THREAD

**Issue by AnejSvete** [acl-org/acl-anthology#4074]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.acl-tutorials.3

### Type of Paper Metadata Correction

- [ ] Paper Title
- [X] Paper Abstract
- [X] Author Name(s)

### Correction to Paper Abstract

Language models (LMs) are currently at the forefront of NLP research due to their remarkable versatility across diverse tasks. However, a large gap exists between their observed capabilities and the explanations proposed by established formal machinery. To motivate a better theoretical characterization of LMs’ abilities and limitations, this tutorial aims to provide a comprehensive introduction to a specific framework for formal analysis of modern LMs using tools from formal language theory (FLT). We present how tools from FLT can be useful in understanding the inner workings and predicting the capabilities of modern neural LM architectures. We cover recent results using FLT to make precise and practically relevant statements about LMs based on recurrent neural networks and transformers by relating them to formal devices such as finite-state automata, Turing machines, and analog circuits. Altogether, the results covered in this tutorial allow us to make precise statements and explanations about the observed as well as predicted behaviors of LMs, as well as provide theoretically motivated suggestions on the aspects of the architectures that could be improved.

### Correction to Author Name(s)

Alexandra Butoi, Robin Chan, Ryan Cotterell, William Merrill, Franz Nowak, Clemente Pasti, Lena Strobl, Anej Svete

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.acl-tutorials.3](https://aclanthology.org/2024.acl-tutorials.3)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
