### ISSUE TITLE
Paper Metadata: 2024.findings-acl.944

### ISSUE THREAD

**Issue by zainmujahid** [acl-org/acl-anthology#4086]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-acl.944

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Correct Author Name: Zain Muhammad Mujahid

First Name: Zain
Last Name: Muhammad Mujahid

Older/Incorrect Author Name: Zain Mujahid

The correct ACL Anthology URL of Zain Muhammad Mujahid is https://aclanthology.org/people/z/zain-muhammad-mujahid/

**Comment by mjpost** [comment]
Moved to #4177

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.findings-acl.944](https://aclanthology.org/2024.findings-acl.944)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
