### ISSUE TITLE
Paper Revision: {2024.findings-emnlp.600}

### ISSUE THREAD

**Issue by bflashcp3f** [acl-org/acl-anthology#4087]
### Anthology ID

2024.findings-emnlp.600

### Type of Change

Revision

### PDF of the Revision or Erratum

https://arxiv.org/pdf/2305.14336

### Brief Description of Changes

This revision improves the writing clarity, e.g., the definitions for the evaluation metrics used.

**Comment by anthology-assist** [comment]
@bflashcp3f we can not use arxiv. Please update the pdf.

**Comment by bflashcp3f** [comment]
Thanks for the response! The PDF file is attached.
[Table2JSON_camera_ready.pdf](https://github.com/user-attachments/files/17963913/Table2JSON_camera_ready.pdf)
