### ISSUE TITLE
Paper Metadata: {2024.iwclul-1.13}

### ISSUE THREAD

**Issue by mikahama** [acl-org/acl-anthology#4113]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.iwclul-1.13

### Type of Paper Metadata Correction

- [X] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)

### Correction to Paper Title

Prune or Retrain: Optimizing the Vocabulary of Multilingual Models for Estonian

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.iwclul-1.13}](https://aclanthology.org/2024.iwclul-1.13})) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
