### ISSUE TITLE
Paper Metadata: 2024.swisstext-1

### ISSUE THREAD

**Issue by muncca** [acl-org/acl-anthology#4130]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.swisstext-1.0

### Type of Paper Metadata Correction

- [X] Paper Title
- [ ] Paper Abstract
- [ ] Author Name(s)

### Correction to Paper Title

Preface

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.swisstext-1](https://aclanthology.org/2024.swisstext-1)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
