### ISSUE TITLE
Paper Metadata: 2024.nlp4pi-1.29

### ISSUE THREAD

**Issue by david-jenny** [acl-org/acl-anthology#4136]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.nlp4pi-1.29

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Rajat Rawat, Hudson McBride, Rajarshi Ghosh, Dhiyaan Nirmal, Jong Moon, Dhruv Alamuri, Sean O’Brien, Kevin Zhu

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.nlp4pi-1.29](https://aclanthology.org/2024.nlp4pi-1.29)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
