### ISSUE TITLE
Paper Metadata: 2024.findings-acl.752

### ISSUE THREAD

**Issue by swarnadeep8597** [acl-org/acl-anthology#4137]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-acl.752

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

The order of the author names needs to be changed to this in the bibtex to match the pdf
Nicholas Asher, Swarnadeep Bhar

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.findings-acl.752](https://aclanthology.org/2024.findings-acl.752)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
