### ISSUE TITLE
Paper Metadata: 2024.findings-acl.532

### ISSUE THREAD

**Issue by kamigaito** [acl-org/acl-anthology#4139]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-acl.532

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

Juseon Do, Jingun Kwon, Hidetaka Kamigaito, Manabu Okumura

**Comment by mjpost** [comment]
### ⓘ Notice

The Anthology has implemented a new, semi-automated workflow to better handle metadata corrections. We are closing this issue, and invite you to resubmit your request using our new workflow. Please visit your paper page ([2024.findings-acl.532](https://aclanthology.org/2024.findings-acl.532)) and click the yellow 'Fix metadata' button. This will guide you through the new process step by step.
