### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by anavaleriagonzalez** [acl-org/acl-anthology#414]
author correction

removing  line 1056:  <author><first>Isabelle</first><last>Augenstein</last></author>

A corrected PDF is also attched here
[CoAStaL_EmoContext (5).pdf](https://github.com/acl-org/acl-anthology/files/3296956/CoAStaL_EmoContext.5.pdf)

**Comment by mjpost** [comment]
Hi—what is the ACL ID, please?
