### ISSUE TITLE
Paper Metadata: 2024.findings-emnlp.604

### ISSUE THREAD

**Issue by ajsanjoaquin** [acl-org/acl-anthology#4143]
### Confirm that this is a metadata correction

- [X] I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.

### Anthology ID

2024.findings-emnlp.604

### Type of Paper Metadata Correction

- [ ] Paper Title
- [ ] Paper Abstract
- [X] Author Name(s)

### Correction to Author Name(s)

For author Ayrton San Joaquin:
First name: Ayrton
Last name: San Joaquin

Author ordering remains the same.

**Comment by mjpost** [comment]
Thanks. I see the author order is wrong, though: on the PDF, Philippe Muller is the penultimate author. We will correct that, too (closing in favor of #4173, which is being tested).
