### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by aidanematzadeh** [acl-org/acl-anthology#415]
[2019-june-NAACL-tutorial-slides.pdf](https://github.com/acl-org/acl-anthology/files/3297562/2019-june-NAACL-tutorial-slides.pdf)
Instead of filing a Github issue, please submit attachments to papers (posters, presentations, notes, and software) using [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u).

Please note that attachments will be distributed under the Anthology's [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) terms.

**Comment by mjpost** [comment]
Hello, please use this form to submit additions: https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u
