### ISSUE TITLE
Tutorial abstracts missing

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#418]
Many *ACL volumes did not submit tutorial abstracts. These should be in the Anthology as part of the permanent record, and also as a means of gathering the presentations.

Progress status (possibly incomplete list):

- [x] EMNLP: 
   - [x] 2018 (thanks to @pkolachi)
   - [x] 2017
   - [x] 2016   
   - [x] 2015
   - [x] 2014
- [x] EACL 2017
- [x] ACL 2016

**Comment by mjpost** [comment]
It seems these were often just left out. What we need to do is just manually create the XML for them, along with the abstracts. Now that we don't assume a PDF is available, we'll just leave out the `<url>` tags and all will be fine.

I hope we can find a volunteer for this. In case such a person appears, what we need to do is create a new `<volume>` for tutorials in the associated XML file, e.g., add `<volume id="3">` to [D18.xml, the XML file for EMNLP 2018](https://github.com/acl-org/acl-anthology/blob/master/data/xml/D18.xml). This will then contain single `<paper>` entries, with abstracts, but with no `<url>` lines. You can model it after the [ACL 2018 tutorial abstracts](https://github.com/acl-org/acl-anthology/blob/38dfcbc50ddef96ed2a38459507c980d77806aa9/data/xml/P18.xml#L4864).

 If no volunteer turns up, I'll likely end up doing it myself when I'm trying to avoid some other more pressing task.

**Comment by pkolachi** [comment]
Hi, it seems like I can add some of the others too soon (thanks for the easy instructions!). And perhaps I am cross-referencing multiple issues (#298), but does the format allow adding multiple videos for a tutorial, which can be in parts? Looking at Naacl 19 did not help in this.

**Comment by mbollmann** [comment]
@pkolachi, yes, there can be multiple `<video>` elements (as well as `<attachment>`) per entry.
