### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by bryorsnef** [acl-org/acl-anthology#431]
Use this template to request a correction to the ACL Anthology.

Please ensure that you:

- [x] ...have read and understood the [criteria for corrections](http://aclanthology.info/corrections).
- [x] ...have included (if relevant) the ACL Anthology ID (e.g., J93-2003).

If approved, we will follow up with information about how to submit the correction.

In the reference list for the paper Modeling Word Emotion in Historical Language: Quantity Beats Supposed Stability in Seed Word Selection in W19-2501, the name Bryor Snefjella is misspelled as Bryor Snejfella, in the reference at the top right of page 10.

**Comment by mjpost** [comment]
Hi, we are unable to correct PDFs unless we receive a corrected copy from the authors. Please feel free to reopen this if you pursuit that route.
