### ISSUE TITLE
W18 DOI assignation

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#435]
This is a placeholder issue for @knmnyn to assign DOIs to 2018 workshops.  

Crossreferencing #158.

**Comment by knmnyn** [comment]
ACL workshops W18-23 thru W18-37 need DOIs
SigDIAL needs DOIs W18-50
EMNLP workshops need DOIs W18-51 thru W18-64
INLG and workshops need DOIs W18-65 thru W18-70

**Comment by knmnyn** [comment]
All assigned.  Need to add the DOIs into the ACL Anthology XML.

**Comment by knmnyn** [comment]
@mjpost : I had a bit of difficulty with the `<fixed-case>` tags that were in the titles.  I had to strip them out of the CDATA text fields in the places where I encountered it in the current Anthology XML.  Hope that was ok when filing the metadata with Crossref.

**Comment by mjpost** [comment]
We should just write a helper function that returns the frontier of the `<title>` nodes. If you do that, we could put it in `anthology.utils.py`.

**Comment by knmnyn** [comment]
> We should just write a helper function that returns the frontier of the `<title>` nodes. If you do that, we could put it in `anthology/utils.py`.

Great.  I'm not sure how to do that in ElementTree.  I will search around later but if you know ready code that does this, please let me know.

**Comment by knmnyn** [comment]
@mjpost I can record the new DOIs assigned into any appropriate location, inclusive of http://bit.ly/aclAnthologyQ . Let me know if that's the current correct place to indicate this.

**Comment by mjpost** [comment]
Yes, please! Just use the first sheet (I just created two new columns)

**Comment by mjpost** [comment]
I can edit the code soon. It's actually already written in `anthology/formatter.py`. I'll add on to your PR but it may be a few days since I'm off from work this week.

**Comment by knmnyn** [comment]
Added the DOIs into the sheet.  Will try to inject them soon.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
