### ISSUE TITLE
Search not looking into content of PDF files

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#44]
The current search does not explore the text of the papers themselves, but only their metadata. As it has been pointed out in issue #39, this is less than ideal.

The search functionality would be greatly enhanced if we could look into the content of the PDF files themselves. This is likely to be quite complicated.

I'm opening this issue as a feature proposal, in order to collect ideas.

**Comment by knmnyn** [comment]
The current best thing to do is try to index the abstracts, some of which
are currently being exported into the ACL XML metadata per paper.  I
suggest doing some development along these lines after the basic problems
of ensuring replicability are solved.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by mjpost** [comment]
This should be fixed when the static rewrite goes live, since Google and others will index and link pages on the same host. The static rewrite also adds the abstracts to the paper pages, which should further help.
