### ISSUE TITLE
Correction: S19-2021

### ISSUE THREAD

**Issue by gentaiscool** [acl-org/acl-anthology#445]
The paper has a reference/citation issue (Our paper does not cite and receive any citations in Google Scholar) due to missing bibliography information. We have updated the paper and would like to request for a correction. 

Thank you

[CAiRE_HKUST_at_SemEval_2019_Task_3__Hierarchical_Models(5).pdf](https://github.com/acl-org/acl-anthology/files/3353965/CAiRE_HKUST_at_SemEval_2019_Task_3__Hierarchical_Models.5.pdf)

**Comment by mjpost** [comment]
Can you please be more specific about what is missing? What reference was fixed? Please post below a complete-sentence description of the change (this will be entered into the change log).

**Comment by gentaiscool** [comment]
We corrected a reference by adding a booktitle to fix the bibliography.

Before: Pascale Fung, Dario Bertero, Peng Xu, Ji Ho Park, Chien-Sheng Wu, and Andrea Madotto. 2018.  Empathetic dialog systems.

After: Pascale Fung, Dario Bertero, Peng Xu, Ji Ho Park, Chien-Sheng Wu, and Andrea Madotto. 2018. Empathetic dialog systems. In The International Conference on Language Resources and Evaluation. European Language Resources Association.

Thank you

**Comment by mjpost** [comment]
I understand now. Thank you! This will be live when #440 is merged.
