### ISSUE TITLE
Author order incorrect just on paper list page (D17 specifically)

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#47]
via email.

The author order seems likely to be a UI issue in the new anthology.
When I click on each of the papers, I see a different (correct) order of authors on the paper details page.
I also compared this to the old anthology. The old anthology appears to have the authors in the correct order too.

My guess is that the metadata has the correct order, but the web rendering is somehow reordering the authors on the page (only in paper list in the new anthology).

See screenshots:

**Comment by knmnyn** [comment]
The same code from the helper views/papers/_paper.html.erb seems to generate different orderings in the output when run by views/volume/show (incorrect) and views/people/show (correct).

@villalbamartin Was this a rails or ruby library update that changed any guarantees about how .each retrieves information?

**Comment by villalbamartin** [comment]
We didn't make any change to the ruby library. I can take a look to see why the order is not being respected.

**Comment by knmnyn** [comment]
This seems to be due to problems with the event view using the embedded papers view.  When using it embedded, the each operator appears to use person_id as a sort, instead of using the default collection enum.  Any ideas how to fix? @villalbamartin @CTNLP ?

**Comment by knmnyn** [comment]
Ok, fixed.  I took out the includes clause that was eager loading the people connected join table, which had the side effect of reordering the authors on the volume page.  Seems to work now.
