### ISSUE TITLE
Correction: combine author pages

### ISSUE THREAD

**Issue by sjgiorgi** [acl-org/acl-anthology#471]
The following authors are the same person:

https://www.aclweb.org/anthology/people/s/salvatore-giorgi/
https://www.aclweb.org/anthology/people/s/sal-giorgi/

Need to change the author Sal Giorgi to Salvatore Giorgi.

The single paper listed under the "Sal Giorgi" link has the name "Salvatore Giorgi" in the manuscript, so no changes to the current PDF needed.

**Comment by mjpost** [comment]
This occurred because the metadata for [W19-3005](https://www.aclweb.org/anthology/papers/W/W19/W19-3005/) was entered incorrectly.
