### ISSUE TITLE
Should the canonical URL be the landing page?

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#480]
I wonder if the canonical URL for Anthology pages should point to the *landing page* instead of the PDF. 

Arguments for:

- The landing page is more general and is also useful itself
- Other sites do this, e.g., DBLP and arXiv
- The PDF url is always inferable from the landing page (append `.pdf`), whereas the convention of appending a `/` is more of a hidden trick

Arguments against:

- It could/would break external dependencies

It might also be worthwhile thinking of making the pages more explicit via parallel URL schemes, e.g.,

- Landing page: `https://www.aclweb.org/anthology/papers/P18-1001` (or `/abs/` as arXiv uses)
- PDF: `https://www.aclweb.org/anthology/pdf/P18-1001`

**Comment by mjpost** [comment]
(The latter two we could implement now, via redirects)

**Comment by akoehn** [comment]
I am all for `/abs/` and `/pdf/` as most people already know this from arXiv.  I also think that the canonical URL being the landing page is more helpful.  Whether it outweighs the potential problems for legacy things: I don't know.

Anybody interested in talking about this for a bit at ACL?

**Comment by nschneid** [comment]
Maybe this is just me, but my conception of a canonical URL is that it is permanent and what it points to should not change. But I would be in favor of advertising the "/" trick prominently.

**Comment by knmnyn** [comment]
I will be at ACL and can find folks if we want to talk.  I like the abs/
and pdf/ distinction for papers but am also wary of discarding
conventions.  We should poll our constituents about it.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by davidweichiang** [comment]
I definitely think that the "append slash" trick ought to be something obvious and not tricky, and that it's strange for URLs that differ by only a trailing slash to point to different pages.

Also, the fact that the PDF URL does not have a `.pdf` extension was the cause for #377 and its kludgy fix.

**Comment by mjpost** [comment]
After talking with people at ACL, I propose the following:

1. The canonical URL remain the same (e.g., `https://www.aclweb.org/anthology/P18-1001`), but it will point to the landing page
2. We use a redirect rule to ensure that the nested version of a paper page (e.g., `https://www.aclweb.org/anthology/papers/P/P18/P18-1001/`) also redirects to canonical
3. We make PDFs available at `https://www.aclweb.org/anthology/P18-1001.pdf`. The reasons for doing this are:
   a. We want to have a PDF extension on PDFs, so the type is clear
   b. If we do `https://www.aclweb.org/anthology/pdf/P18-1001.pdf`, it slightly complicates manually moving from the PDF page back to the landing page (since you have to delete PDF twice)

I suggest we do this as soon as someone has the time to implement it. @mbollmann thought it shouldn't be too hard.

**Comment by knmnyn** [comment]
Sounds good to me.  Thanks for polling folks!

**Comment by mjpost** [comment]
Note: (2) above would also solve the problem of having the paper appear twice in search results, e.g., https://www.aclweb.org/anthology/search/?q=towards%20a%20generative%20model%20of%20alignment

**Comment by akoehn** [comment]
If there is a consensus to make the canonical URL the landing page, I am all for it and would also make the nested URLs either redirects or remove them as they are an added layer of complexity and the anthology never made a promise to keep these URLs; this is similar to the aclanthology.info site where we at least also not create new redirects for new publications.

Regarding the implementation: We would probably modify the pipeline to directly generate the HTML in the correct spot so that rewrite rules are not necessary, right?

**Comment by nschneid** [comment]
It sounds like having the canonical URL be the landing page and redirecting nested URLs is the consensus.

Perhaps there should be a target date for this change which is announced in advance so people have the opportunity to update links/tools that were based on the old scheme (e.g., the Zotero importer will have to change).

**Comment by mjpost** [comment]
@akoehn, not clear on your question? To be explicit (maybe this will answer your question):

- Change RewriteRules so that canonical URL loads the nested page
- Add RewriteRules so "{canon}.pdf" loads PDF, "{canon}.bib" loads bib, etc
- Replace all explicit nested links with canonical ones, e.g., `https://aclweb.org/anthology/papers/P/P19/P19-1010/` → `https://aclweb.org/anthology/P19-1010`

Once we have this implemented on a branch, we can announce per @nschneid's suggestion and give people a few weeks to prepare. As with everything, now that this idea is out there, it's an itch, and I'd love to have this done As Soon As Possible :)

**Comment by akoehn** [comment]
I meant: instead of generating the nested HTML and then putting RewriteRules infront, we could generate the HTML in the "canonical" spot directly.  This would remove one layer of complexity -- the rewrite rules.

I.e., generate the HTML here: `https://aclweb.org/anthology/P19-1010` instead of in `P/P19/P19-1010/`, get rid of a permanent rewrite rule.

I don't particularly care as I am not affected by the machinery behind the scenes, just wanted to point out the possibility of use this refactoring to get rid of RewriteRules. When neither using the nested format infront nor behind the scenes, the nested paths can be discarded at some point in the future, removing the complexity of keeping track of both the "real" and the "canonical" path in the building process.

Does that make more sense?

**Comment by mjpost** [comment]
I see. I do like this idea (the RewriteRules are a hidden complexity), but having tens of thousands of files in a single directory can also be problematic.

Had you considered this? This may be one of those things that is not a problem on modern UNIX systems, but was a problem when I "came of age" on UNIX and so has stuck with me.

**Comment by nschneid** [comment]
> When neither using the nested format infront nor behind the scenes, the nested paths can be discarded at some point in the future, removing the complexity of keeping track of both the "real" and the "canonical" path in the building process.

I think it would be problematic to remove nested path URLs for existing papers. This would break links in the wild when it is not technically necessary. (I have no opinion on how the directory structure should work under the hood.)

**Comment by akoehn** [comment]
@nschneid: We would not need to replicate the nested structure for new papers, we only need to keep the redirects for the old ones around.  This could even be a fixed RewriteRule or whatever fits best and does not need to be in our code base anymore.

@mjpost Starting with ext3 (and continuing with ext4), directory entries are [hash trees](https://ext4.wiki.kernel.org/index.php/Ext4_Disk_Layout#Hash_Tree_Directories) so accessing files is fast even when there are lots in a directory.

**Comment by mbollmann** [comment]
@akoehn I had all papers in a single directory once during development, and I can attest that a simple `ls` had several seconds delay.

**Comment by mbollmann** [comment]
(This was, in fact, the reason I created the nested structure in the first place--a flat one was unworkable on my system.)

**Comment by akoehn** [comment]
I'll do a short sed-based mockup for a flat system; keep in mind that ls does the same job as find would do on the current structure and that the web server never had to iterate over all files at once.

**Comment by mjpost** [comment]
A sed-based filesystem mockup sounds like a huge distraction!

I discovered an additional benefit to reducing the nested structure, which is that it should help with the move to ACL2020 IDs, since the Hugo generation logic hard-codes a lot of assumptions.

**Comment by akoehn** [comment]
`$ for i in $(find anthology -type f -name index.html); do cp $i $(echo $i | sed 's|/|-|g; s|-index.html|.html|; s|anthology-|anthology-flat/|'); done`

And now we can see whether there is a slow-down:

```$ cd anthology-flat
$ time ls > /dev/null

real	0m0.409s
user	0m0.345s
sys	0m0.065s
```

Looks like @mbollmann needs a new ssd ;-)

**Comment by mjpost** [comment]
Hi @acl-org/anthology (and @nschneid)—I think we should make this live on 1 October 2019. We will make the following changes:

- The canonical URL will point to the landing page (both <https://www.aclweb.org/anthology/W18-6319> and <https://www.aclweb.org/anthology/W18-6319>)
- The hidden PDF link on paper pages will be removed
- The link to PDFs will have an explicit extension of `.pdf`, e.g., <https://www.aclweb.org/anthology/W18-6319.pdf>

I think this is the right thing to do for the reasons discussed above. I also hope that having the prominent links *with* the extension will help with third-party indexing, which still seems to be problematic.

**Comment by davidweichiang** [comment]
I'm getting infinite redirects when accessing the landing page, e.g., https://www.aclweb.org/anthology/P19-1001/.

**Comment by mjpost** [comment]
Fixed temporarily, PR coming soon.
