### ISSUE TITLE
ACL proceedings from 1963 to 1978 are missing

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#481]
The first ACL proceedings present in the Anthology are from 1979, which was the 17th meeting.

**Comment by davidweichiang** [comment]
I don't think ACL had proceedings before that, with the exception of the one year that was published in AJCL.

From Bonnie Webber: "1979 was the first year that ACL published
full conference papers.  Before that, it followed the LSA practice of only
publishing abstracts.  That is why 1979 is the first year for which the
anthology has ACL conference proceedings."

The abstracts for other meetings might be in the FINITE STRING? I can't remember now.
