### ISSUE TITLE
Meetup at ACL 19?

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#482]
I know that a lot of people from the anthology team & contributors are at ACL 2019 (from the top of my head: @villalbamartin, @mbollmann, @mjpost, @nschneid (I think), @knmnyn and probably more).  Maybe we can meet on a break or so?  It would be nice to meet other anthology-interested people in person and talk a bit about the state of the anthology.

This is not really an issue but I figured it would be the easiest way reach people interested in anthology work.

**Comment by knmnyn** [comment]
Sure.  The Whova app is doing the lion's job of organizing meetups (I'm trying to do one for the local Singapore-related folks there -- although I'm not Singaporean).  I'll be happy to meet.

**Comment by villalbamartin** [comment]
I created a Whova group, titled "ACL Anthology team", and sent invitations to the people that @akoehn mentioned in his post. If you would like to attend, feel free to join.

**Comment by mjpost** [comment]
Closing since moved to Whova.
