### ISSUE TITLE
Correction: Adding corresponding author

### ISSUE THREAD

**Issue by nishiharu** [acl-org/acl-anthology#483]
I am the first author of the following two papers: P18-1116, and N19-1205.

I forgot to specify who should be the corresponding author for both papers. However, as a Ph.D. candidate, I have to specify the corresponding authors as my supervisor. Otherwise, I cannot graduate. 

Would anyone please help me to mark Tiejun Zhao (my supervisor) as the corresponding author? (i.e., adding a footnote with the content "corresponding author")

Thanks very much!

[P18-1116.pdf](https://github.com/acl-org/acl-anthology/files/3440327/P18-1116.pdf)
[N19-1205.pdf](https://github.com/acl-org/acl-anthology/files/3440328/N19-1205.pdf)

**Comment by mjpost** [comment]
We cannot change the PDFs. If you want to submit a revised PDF with the correction, we can process it.

**Comment by nishiharu** [comment]
Thanks very much! I have attached the corrected PDF files of both papers below.

[N19-1205-Correction.pdf](https://github.com/acl-org/acl-anthology/files/3445290/N19-1205-Correction.pdf)
[P18-1116-Correction.pdf](https://github.com/acl-org/acl-anthology/files/3445291/P18-1116-Correction.pdf)

**Comment by mjpost** [comment]
Sorry, we are revising our process. Please submit [here](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u). You'll need to submit twice, once for each paper.
