### ISSUE TITLE
Correction (Revision of a demo paper) P19-3031

### ISSUE THREAD

**Issue by alexanderpanchenko** [acl-org/acl-anthology#490]
I would like to ask to make a revision of the following paper https://aclweb.org/anthology/papers/P/P19/P19-3031/ at the ACL 2019 Demo session. 

The reason for this revision is that during the demo session we realized that a very important acknowledgment our work is based on was not mentioned in the paper. We (not intentionally) did not credit the original work front-end of our system is based on and the author asked us to try to fix this issue (@ines [Ines Motani](https://github.com/ines)). I am really sorry for bothering you with this, but I would not contact you unless it would be really important. 

The identifier of the paper is: P19-3031. 

The corrections in the paper are as follows: 

1. Adding the following in the acknowledgments. 

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1456830/62409517-fb963780-b5d8-11e9-801d-bba71e7589f4.png">

2. Adding the footnote to the GitHub repository on this page. 

<img width="723" alt="image" src="https://user-images.githubusercontent.com/1456830/62409510-ede0b200-b5d8-11e9-9536-bf2bcbf27be4.png">

3. Some minor formatting to make sure that the page limit after the introduction of these extra texts is still preserved. 

I am attaching the updated PDF file. Thanks in advance for your help with solving of this issue and updating the file. We are sorry to bother you with this but this!

[TARGER-3.pdf](https://github.com/acl-org/acl-anthology/files/3463527/TARGER-3.pdf)

**Comment by mjpost** [comment]
Hi—please use [this form](https://bit.ly/3396tyA) to submit corrections.

**Comment by mjpost** [comment]
(Sorry about this—I didn't realize that we hadn't updated the link from the Anthology page. I'll fix that now).

**Comment by alexanderpanchenko** [comment]
Thank you for the quick response. No problem, I will fill in the most recent form upon my arrival back home.

**Comment by alexanderpanchenko** [comment]
I’ve submitted the request using the MS Office form.

**Comment by mjpost** [comment]
Thanks. These are typically processed on a monthly basis. Ones submitted prior to August 10 are currently under review (https://github.com/acl-org/acl-anthology/pull/538).

**Comment by alexanderpanchenko** [comment]
OK. Thank you for letting me know about the timeline.
