### ISSUE TITLE
Stylesheet link broken on venue pages?

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#491]
https://www.aclweb.org/anthology/venues/semeval/ shows up unstyled for me

**Comment by mjpost** [comment]
This is anecdotal but it seems to me that you quickly discover every problem with the Anthology :)

It looks like my rsync from the hotel room didn't finish. I'll have to wait until tonight to rerun it, unfortunately.

**Comment by mjpost** [comment]
Fixed, thanks!
