### ISSUE TITLE
Correction: P19-1644

### ISSUE THREAD

**Issue by alsuhr-c** [acl-org/acl-anthology#494]
Use this template to request a correction to the ACL Anthology.

Please ensure that you:

- [x] ...have read and understood the [criteria for corrections](http://aclanthology.info/corrections).
- [x] ...have included (if relevant) the ACL Anthology ID (e.g., J93-2003).

If approved, we will follow up with information about how to submit the correction.

---

There are two minor corrections to this paper:

- In the main paper, Table 3, row for "Cardinality (soft)" should have 16 under NLVR column and 23.6 under NLVR2 column.
- In the supplementary, page 2, right column, "soft cardinality" should be listed as a category for which NLVR2 has significantly more examples than NLVR.

I attached the updated PDFs of the main paper and supplementary, in case it's needed now.

Thanks!

[separate_sup.pdf](https://github.com/acl-org/acl-anthology/files/3465970/separate_sup.2.pdf)
[rnlvr.pdf](https://github.com/acl-org/acl-anthology/files/3465971/rnlvr.7.pdf)

**Comment by mjpost** [comment]
Please submit [here](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u).
