### ISSUE TITLE
Correction: W19-4804 Missing Acknowledgement

### ISSUE THREAD

**Issue by verypluming** [acl-org/acl-anthology#495]
One acknowledge part is missing although I added it to our camera ready version. Could you add the acknowledge part?

Acknowledgement (P.9)

Before:
We thank our three anonymous reviewers for helpful suggestions. We are also grateful to Koki Washio, Masashi Yoshikawa, and Thomas McLachlan for helpful discussion.

After:
**This work was partially supported by JST AIPPRISM Grant Number JPMJCR18Y1, Japan, and JSPS KAKENHI Grant Number JP18H03284, Japan.**
We thank our three anonymous reviewers for helpful suggestions. We are also grateful to Koki Washio, Masashi Yoshikawa, and Thomas McLachlan for helpful discussion.
[corrected.pdf](https://github.com/acl-org/acl-anthology/files/3467464/corrected.pdf)

Thank you very much for your consideration.

**Comment by mjpost** [comment]
Hi, please submit [here](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u).
