### ISSUE TITLE
Search via ... engines need to be integrated with current anthology

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#50]
Suggested by Zeerak Waseem @zeerakw , @leondz and @evanmiltenburg @emilybender.  See Twitter thread: https://twitter.com/evanmiltenburg/status/950367985889398790

**Comment by knmnyn** [comment]
@jeisner also upped this issue.  Now upped to urgent.

Should enable the search bar to submit to Google site:aclweb.org as well as others.

**Comment by jeisner** [comment]
One option is to configure an instance of Google Custom Search at cse.google.com.

(I just tried it out by enabling it on my own papers page: https://www.cs.jhu.edu/~jason/papers/ )

**Comment by jeisner** [comment]
If I create an instance of Google Custom Search to do this, would you be willing to put that HTML onto the Anthology home page, at least for now?  It's a very quick solution with a high payoff ...

(Only downside is that the search box would probably be associated with my personal Google account.  But I'd post my settings here, and you could make your own search box whenever you wanted and swap mine out in favor of yours.)

**Comment by CTNLP** [comment]
If you were to submit a pull request with the required changes, then we should be able to get that up and running within a few days. If you just send us an HTML snipped then we could probably integrate that as well, but I cannot personally guarantee that it would be quick, since this would involve messing with the Ruby on Rails code, which I have no experience with.

**Comment by mjpost** [comment]
This has been implemented in the new version of the Anthology. Thanks, all.

**Comment by jeisner** [comment]
Awesome!  I'd like to try it out, but the search box at the top of https://aclanthology.info/ doesn't seem to do full-text search yet.  Am I looking in the wrong place?

(Sorry that I forgot to follow up on my suggestion in December with a pull request.)

**Comment by mjpost** [comment]
Yes, go to https://aclweb.org/anthology/. The other site is the old one and will be redirecting soon (#178).

**Comment by jeisner** [comment]
Ah, got it, thanks.  Seems to work great.

Has the old faceted search gone away entirely, then?
Ideally it would be possible to write a query like `author:"matt post" beam
search`, but it's a bit tricky.
If Google's indexing can't be changed, then I guess the method would be to
submit the query `beam search` to Google and then filter the results using
the author metadata.

**Comment by mbollmann** [comment]
> if Google's indexing can't be changed, then I guess the implementation would be to submit the query `beam search` to Google and then filter the results using the author metadata.

I think that's only possible if we use Google's JSON API, so we can query and filter search results via our own custom JavaScript. Unfortunately, [that costs $5/1000 queries](https://developers.google.com/custom-search/docs/overview).

There is a separate issue discussing the new search box btw: #165

**Comment by jeisner** [comment]
Thanks -- I'll move the conversation to #165.
