### ISSUE TITLE
Request for a corrected citation

### ISSUE THREAD

**Issue by chywang** [acl-org/acl-anthology#509]
My name is Chengyu Wang. I have a paper published in ACL 2019: SphereRE: Distinguishing Lexical Relations with Hyperspherical Relation Embeddings.

I was requested by Robyn Speer, the author of a paper I cited (https://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14972), to change the name of the citation from "Robert Speer" to "Robyn Speer". I am not sure how to do that in the ACL anthology. Thanks!

**Comment by akoehn** [comment]
The instructions are here: https://aclweb.org/anthology/info/corrections/

**Comment by ChristopherSweeney** [comment]
How was this corrected?  I have a similar issue, where i want to update a citation from "Robert Speer" to "Robyn Speer" in an ACL paper: A Transparent Framework for Evaluating Unintended Demographic Bias in Word Embeddings.
From the above instructions it seems a revision or erratum has to be made, which should not be necessary for changing a name in the the citation?

Thank you!

**Comment by mjpost** [comment]
The only way we can change the PDF is for you to submit an updated one that we then process as a revision. The revision will not have the original footers or page numbers on it unless you place them there. We typically process revisions once a quarter or so since it is fairly time-consuming.
