### ISSUE TITLE
ERROR:  cannot truncate a table referenced in a foreign key constraint 

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#51]
Did something change with respect to ingestion?

I didn't have this problem with re-ingesting proceedings but now it is happening.  This is for W17.xml to change one author in W17-74.

aclanthology@aclanthology:~/acl-anthology$ rake import:xml["W17"] --trace
** Invoke import:xml (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute import:xml
PG::FeatureNotSupported: ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "papers_people" references "people".
HINT:  Truncate table "papers_people" at the same time, or use TRUNCATE ... CASCADE.
: TRUNCATE TABLE people RESTART IDENTITY;
rake aborted!
ActiveRecord::StatementInvalid: PG::FeatureNotSupported: ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "papers_people" references "people".
HINT:  Truncate table "papers_people" at the same time, or use TRUNCATE ... CASCADE.

**Comment by villalbamartin** [comment]
Looking into it now. We didn't change anything recently, but it seems a side-effect of bug #42.

**Comment by villalbamartin** [comment]
Could you whether one of the following alternatives works?

- rake import:xml[true,W17]
- rake import:xml[W17]

It seems to me that the code right now is not parsing the argument correctly, because it's trying to re-ingest the entire database at once. Let me know if this works, and if so we should add some code that checks for that.

**Comment by knmnyn** [comment]
Yes, that seems to have fixed it.  I will note the correct syntax.
