### ISSUE TITLE
Missing papers "File not found" TACL vol. 7

### ISSUE THREAD

**Issue by lefterav** [acl-org/acl-anthology#510]
The following papers are missing:
https://www.aclweb.org/anthology/papers/Q/Q19/Q19-1021/
https://www.aclweb.org/anthology/papers/Q/Q19/Q19-1020/

**Comment by mjpost** [comment]
You’re right! @aryammcarthy we forgot the PDFs.

**Comment by aryamccarthy** [comment]
Ah, thanks for catching this, @lefterav. I didn't get tagged—two c's, not two m's. The files are now emailed to @mjpost for upload.

**Comment by mjpost** [comment]
Done thanks all!
