### ISSUE TITLE
rake:import_xml undesired behavior when using quotes

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#52]
As seen in bug #51, giving a command-line argument for `rake:import_xml` that it's not exactly 3 characters long deletes and re-imports the entire database from scratch. This is technically correct, but wrong for all practical purposes.

- Expected behavior: the command should give an error message, something like "that file does not exist, and therefore cannot be imported".
- Actual behavior: the database is deleted and re-imported from scratch.

**Comment by mjpost** [comment]
Closing this. Feel free to reopen if there is more information.
