### ISSUE TITLE
merge yaml venues files

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#527]
For the ID transition scheduled for January 1, 2020 (#291), we will need the following for every venue:

- A primary key, its code, e.g., `acl` or `mtsummit`
- Its long name
- Whether it's an ACL event or not
- Its short letter under the old system, e.g., `P`

I propose we merge `venues.yaml` and `venues_letters.yaml` to consolidate all of this information, and to use a structure that can grow, should other information arise.

Note that this could also be used with [acleanbib](https://github.com/Olamyy/acleanbib) for producing more concise citations in a references section.

**Comment by mbollmann** [comment]
For supporting the new ID format in #732, I've created a new YAML file that currently looks as follows:

```yaml
test4nlp:
  venue: WS
  joint:
    2020.test4nlp-1: ACL
```

This file maps *venue primary keys* (like `test4nlp`) to *top-level venues* (here: WS), which correspond to the short letters under the old system and are currently used to group venues on the front page.

The `joint` key can assign additional venues to individual volumes. I haven't done so yet, but we could easily add keys here for a venue's short name, long name, and status as an ACL event.

Note that this file currently co-exists with the old files `venues.yaml`, `venues_letters.yaml`, and `venues_joint_map.yaml`. It's not so trivial to merge all of these into this new format, as the old-style volumes only encode their *top-level* venue in their IDs (by way of the short letter), while looking up volumes in this new YAML file requires knowing the *specific venue key*. Importantly though, if we also gather short/long names and ACL event status in the new YAML file, it should not be necessary to modify the old files in any way when adding new volumes from 2020 onwards.

**Comment by mjpost** [comment]
This looks good to me.

Couldn't this file at least subsume `venues.yaml`, however, if we folded that file into it?

**Comment by mjpost** [comment]
(In fact, if so, we could just update `venues.yaml` to this new format, instead of creating a new file)
