### ISSUE TITLE
running out of IDs

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#530]
Hi folks,

We’re going to run out of workshop IDs this year when we get to EMNLP. We are cooking up the new ID format (#291) but I wanted to delay on using them till next year, since the code isn’t ready, and also that way we’d have an easy way to know (new format if year >= 2020). What do you think about using the “D” prefix for EMNLP workshops? So

- D19-1 through D19-4 will be the main volumes
- D19-5+ (or maybe we'll start at D19-10) will be EMNLP workshops

This makes some sense, I think? Anyone have any objections (even on aesthetic grounds) or see any issues?

matt

**Comment by akoehn** [comment]
I think it makes sense and it seems to be the easiest solution.  Having a D prefix even though being a workshop might be slightly weird, but I don't see an alternative other than implementing #291 -- and I agree that doing this for 2020 is much easier than rushing now.

**Comment by knmnyn** [comment]
Hi Matt, all:

I completely agree.  Having a quick stopgap measure is fine given that we
are going to switch ID systems anyways.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by mjpost** [comment]
Great, thanks, all.

**Comment by mjpost** [comment]
Asking for more input here (@akoehn @mbollmann)—I have the EMNLP request, and we indeed are out of workshop IDs. However, using D19 as a workshop prefix will require special handling in the Anthology code, since D19's volume ID will be a single digit in the case of EMNLP main conference volumes and two digits in the case of the workshops. For example, in `anthology/utils.py`, there is numerous special handling that will need expansion, see below.

I am going to go ahead with this but thought I'd mention it in case anyone sees some problem.

```python
def is_volume_id(anthology_id):
    return (
        anthology_id[-3:] == "000"
        or (anthology_id[0] == "W" and anthology_id[-2:] == "00")
        or (anthology_id[:3] == "C69" and anthology_id[-2:] == "00")
        or (anthology_id[:3] == 'D19' and int(anthology_id[4]) >= 5)
    )
```

**Comment by mbollmann** [comment]
```python
(anthology_id[:3] == 'D19' and int(anthology_id[4]) >= 5)
```
You still need to check for `anthology_id[-2:] == "00"` here!

Since we already have the special case of C69 and the logic to handle this should be concentrated in only a few places, this will probably not cause too many issues. One thing to remember is that all these workshops will need to explicitly get the `WS` tag in the venue mapping file.
