### ISSUE TITLE
Missing supplementary material

### ISSUE THREAD

**Issue by chashimo** [acl-org/acl-anthology#535]
Hi all, thanks for this awesome system!

I noticed that the supplementary material of the following EMNLP 2012 paper is missing in ACL Anthology which I remember was there and could be downloaded in some earlier version of ACL Anthology.

Anthology ID: D12-1057
https://www.aclweb.org/anthology/D12-1057/
Excitatory or Inhibitory: A New Semantic Orientation Extracts Contradiction and Causality from the Web

Did all the supplementary stuff move to elsewhere?

**Comment by mjpost** [comment]
You're right, the file is on the server. You can access it here: <https://www.aclweb.org/anthology/attachments/D12-1057.Attachment.pdf>

We should go through and look for attachments missing in the XML. If someone wants to do this, I'm attaching a full list of attachments found on the server.

[acl_attachments.txt](https://github.com/acl-org/acl-anthology/files/3663561/acl_attachments.txt)

**Comment by mbollmann** [comment]
I've kinda done this in #264 already ... this one is on the list.

**Comment by chashimo** [comment]
Thanks!!
