### ISSUE TITLE
nodalida proceedings 404?

### ISSUE THREAD

**Issue by bplank** [acl-org/acl-anthology#544]
Dear ACL anthology team,

hmm the 2019 edition is not linked on this page: 
```
https://aclweb.org/anthology/venues/nodalida/
```
and the previous link now gives a 404 (it worked yesterday):
```
https://aclweb.org/anthology/events/nodalida-2019
```
Thanks for help.

Barbara

**Comment by mjpost** [comment]
Hmm, I know what happened but can't track it down yet. The event page will be fixed in an hour, but in the meantime it's still there, you can access it here:

> <https://aclweb.org/anthology/events/ws-2019/#w19-61>
