### ISSUE TITLE
Broken links to non-paper materials (supplementary pdf, notes, data, presentations)

### ISSUE THREAD

**Issue by jkkummerfeld** [acl-org/acl-anthology#552]
For some reason links to attachments are being produced with an extra `{}/`. For example:

```
https://www.aclweb.org/anthology/attachments/%7b%7d/P19-1374.Supplementary.pdf
```
Should be:

```
https://www.aclweb.org/anthology/attachments/P19-1374.Supplementary.pdf
```

This applies to all cases I found across different conferences and years, in both the list of proceedings and in the paper-specific pages.

**Comment by mjpost** [comment]
We fixed this (#550) but it didn't get merged so the site got re-broken. I am pushing up the fix right now and this should be okay permanently by midday.

Sorry for the trouble!
