### ISSUE TITLE
What can we get from 1000 tokens? a case study of multilingual pos tagging for resource-poor languages

### ISSUE THREAD

**Issue by aaaatutu** [acl-org/acl-anthology#554]

**Comment by akoehn** [comment]
Please clarify what this issue is about.

**Comment by mjpost** [comment]
Poking around, it seems that the versioned papers were not displaying. I've fixed this and just need an approval and merge before 8 PM EST tonight.

**Comment by mjpost** [comment]
Here is the paper: https://www.aclweb.org/anthology/D14-1096/
