### ISSUE TITLE
link to easychair scripts in contrib info

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#566]
https://aclweb.org/anthology/info/contrib/ mentions easychair scripts but I don't know where to find them (only looked for ~1min).  It would be nice if they were linked from that site.

**Comment by mjpost** [comment]
It's linked from [the ACLPUB instructions](https://github.com/acl-org/ACLPUB/blob/master/anthologize/README.md): https://github.com/acl-org/easy2acl . I'll fix it soon. Private notes:

- [Step 1 here](https://aclweb.org/anthology/info/contrib/) should mention ACLPUB
- Link directly to the internal instructions
- Mention and maybe link to easy2acl, but don't send people there directly, they should be aware that it's a step in the ACLPUB process.

**Comment by akoehn** [comment]
My motivation: I saw that the syntaxfest proceedings ingested last week have no abstracts and I wanted to know why.  It seems like the organizers have to provide a .csv file as well and this is currently only documented in easy2acl.

**Comment by mjpost** [comment]
It's probably a good idea for us to make a note about abstracts in the easy2acl docs. If I remember correctly it's not easy because Easychair doesn't gather abstract information. Really, though, I want to merge easy2acl into ACLPUB (https://github.com/acl-org/ACLPUB/issues/11)
