### ISSUE TITLE
Some search results return a 404 error when clicked

### ISSUE THREAD

**Issue by adampoulston** [acl-org/acl-anthology#569]
Some results that don't return a URL with .pdf appended are 404ing.

Example search: 
https://aclweb.org/anthology/search/?q=W18-53

Example result that 404s:
https://aclweb.org/anthology/W18-53

Appending .pdf to the result does return the correct resource,eg:
https://aclweb.org/anthology/W18-53.pdf

**Comment by akoehn** [comment]
The search result is problem with the google index (which we cannot fix), this works: https://www.aclweb.org/anthology/W18-5300/

The resource never had the ID W18-53 according to the git log, it was always W18-5300.  The problem seems to be that prior to 0b4ea3798e0d75e6b02d212ff0663a369c327d37, the workshop themselves had URLs deviating from their IDs.  The IDs are padded with 00, the URLs were not.

The correspondence is a good thing IMO, maybe a redirect from `([A-Z]\d\d)` to `\100` (or whatever the syntax is) would be good to keep the old URLs intact (cc @mjpost)

**Comment by mjpost** [comment]
@mbollmann Perhaps we should update the sitemap? I'm seeing a ton of errors in the Google Search Console, where the bulk of our URLs are excluded:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/455256/66571372-1f2bb000-eb3d-11e9-8c2a-777f02674649.png">

The reasons are interesting:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/455256/66571504-66b23c00-eb3d-11e9-8efe-ca4a1f5995b1.png">

For example, Google apparently believes a large number of our URLs are "duplicates", with semanticscholar holding the canonical variant:

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/455256/66571584-8ba6af00-eb3d-11e9-9e4d-4eb9f2f40cef.png">

Many others are "Page with redirect", where the canonical variant is not in the index.

**Comment by mjpost** [comment]
I see we do still generate `/sitemap.xml`, but it has too many URLs. We should automatically split it into the smaller-pieced files as before. We are at 95k so we should probably break it up into three (or into 50k shards automatically). @mbollmann do you have time to do this so that I can resubmit them?

**Comment by mjpost** [comment]
Hmm, I see Marcel already wrote `bin/split_sitemap.py`, it's just not getting called by the Makefile. In that case, @akoehn, do you have time to add a call to `bin/split_sitemap.py build/anthology/sitemap.xml` to the Makefile, so that it automatically gets done before the `upload` target?

**Comment by akoehn** [comment]
Yes, will do when I switch trains today.

**Comment by mjpost** [comment]
Another thing we should do is add the PDF urls to the sitemap. I dug around though and can't even see where the sitemap is produced (maybe Hugo does this automatically?) I would like to claim to Google that *our* PDFs are the canonical ones. We could do that in the sitemap, but [Google's page here](https://support.google.com/webmasters/answer/139066?hl=en) says that it's best to do it on the links themselves. We have the following links:

- http://aclweb.org/anthology/URL.pdf
- https://aclweb.org/anthology/URL.pdf
- http://www.aclweb.org/anthology/URL.pdf
- **https://www.aclweb.org/anthology/URL.pdf**

It is this last one that is canonical.

**Comment by akoehn** [comment]
The PDFs are currently not part of the sitemap at all.  According to what you wrote, they should be.

If I split the `sitemap.xml`, should `sitemap.xml` be deleted and only the split ones be preserved?

**Comment by mjpost** [comment]
`sitemap.xml` can be safely deleted, yes. Do you have any idea how the sitemap is produced? I mean what code triggers it? It must be hugo.

Yes, we should add the PDFs. It should be easy to generate the appropriate urls from all relative `<url>` tags in the XML. But maybe this is a separate problem.

**Comment by akoehn** [comment]
I fear that the "canonical" information needs to be from semanticscholar, not from us. I.e., a page can only claim that *another one* is the canonical one, not that it itself is canonical.  Therefore, semanticscholar would need to add `Link: <https://www.aclweb.../XXX.pdf>; rel="canonical"` headers.

Yes, the sitemap is generated by hugo.  We could adapt the template to add the PDFs for all relative links, but I haven't looked into that.

**Comment by mjpost** [comment]
SS doesn't link back to us at all, e.g., [their page](https://www.semanticscholar.org/paper/Dependency-Tree-Based-Sentence-Compression-Filippova-Strube/6d42e405d9b7270079eb33e228141de9d57bded7) for https://www.aclweb.org/anthology/W08-1105/. They don't even get the bibtex right. So they are really just re-serving it all.
