### ISSUE TITLE
Paper pdf returning 403

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#57]
The paper [Assessing the Challenge of Fine-Grained Named Entity Recognition and Classification](https://aclanthology.coli.uni-saarland.de/papers/W10-2415/w10-2415) is returning a 403 when accessed through the Anthology interface. This happens because the paper's PDF has been moved, from `http://www.aclweb.org/anthology/W10-2415.pdf` to `http://www.aclweb.org/anthology/W10-2415.old.pdf`.

The paper can be still accessed through Google, but not through the Anthology. The person who pointed this out to me also mentioned that there's a revised version of it, available here: `http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.357.7217&rep=rep1&type=pdf` .

Should we replace the PDF link?

**Comment by knmnyn** [comment]
Working now!
