### ISSUE TITLE
Reverse-order the full bibtex?

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#572]
ACL 2020 will include the entire Anthology bibtex in the default overleaf template. Overleaf doesn't autocomplete all the keys from a file that is so large, but seems to stop after reading some number of them. For this reason, it would be nice to reorder the bib file, perhaps reverse chronologically, or putting *ACL venues first, or something like that.

**Comment by akoehn** [comment]
I had a look at the anthology bibtex today and I agree that a reverse sorting by publication date would be a good idea.  This would also automatically group by conference and should be the easiest to implement.
