### ISSUE TITLE
URL is missing from BibTeX

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#576]
E.g. https://www.aclweb.org/anthology/S12-1020.bib should have the canonical URL.

**Comment by nschneid** [comment]
This started happening around Oct. 2.

**Comment by mjpost** [comment]
Drat, I know what caused this. I'll fix it today and also add a unit test so it won't happen again.

**Comment by mjpost** [comment]
Okay, this is now fixed in production and permanently in #578. We also now have a test case to guard against this happening in the future. It's a shame that we only noticed this after I advertised the Overleaf BibTeX trick.

**Comment by nschneid** [comment]
Now it has the .pdf URL. Shouldn't we go with the canonical URL for historical consistency (and ease of accessing the metadata page)?

**Comment by akoehn** [comment]
We should also go with the canonical URL because it is the canonical URL :-)

**Comment by mjpost** [comment]
Makes sense.

**Comment by mjpost** [comment]
All right, fixed in production again and in the PR. What else did I break?

**Comment by nschneid** [comment]
LGTM, thanks!
