### ISSUE TITLE
Make "URL" the canonical URL instead of .pdf

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#587]
See #576 for a related issue.
I saw that the URL field on the paper sites point to the PDF.  I would assume that the paper pages show the same metadata as the bibtex files as they are meant as bibliographic information which someone might copy.  Therefore (and because the PDF is linked with the PDF button) I propose to use the canonical URL.

**Comment by mjpost** [comment]
You mean this?

![Untitled](https://user-images.githubusercontent.com/455256/67010892-8b1d9380-f0bc-11e9-8913-c7cd5f09be1c.png)

I see your point about this page being an HTML view of the bibtex file, but it seems weird to have a page link to itself. On the other hand, we have a lot of links to the PDF: the title, the PDF button, and this text line.

We could have this "URL" field link to the page itself, and then add a "PDF" field.

**Comment by akoehn** [comment]
Yes, I mean that.  Yes, a link to the current URL may seem weird but I see this information as "what is the relevant information if I want to cite this paper somehow?"  and in that case it should be the canonical URL for the papers hosted on the anthology itself.  This will also show people that this is indeed the canonical URL that should be used when linking to the paper; otherwise they will use the .pdf version and not the canonical one (and we don't give a guarantee that the .pdf URL will be stable!)

Example: I write an email and want to link to a paper.  It seems likely that a lot of people use the "URL" url for that link.

There are three possibilities:

 1. use the canonical URL for anthology hosted papers and the external for others
 2. use the canonical URL for every paper
 3. use pdf everywhere

3 means that even for ACL papers we distribute a URL for which we currently give no guarantee that it will work in the future and which is objectively the worse URL when comparing to the canonical one, which provides access to metadata.

The semantics for 2. would be "this is the canonical ACL anthology URL for this paper", which is pretty clear and also -- in my opinion -- a reasonable way to select which URL to present.  It also gives access to the metadata.  Possible problem: ELRA might not like that we use "our" URL as a canonical URL instead of theirs.  However, I also don't know whether ELRA gives guarantees about the stability of their URLs.

The semantics for 1. would be a bit complicated but this would be the solution "lets do it as best as we can for ACL-hosted papers and not step on ELRAs toes for external".

I prefer 2, would settle for 1 but disagree with 3.

**Comment by akoehn** [comment]
To add to that, when we will do mirrors (#295), that URL should still the the aclweb URL because it should be the canonical URL.  Imagine someone wanting to cite the data while looking at a mirror (the website kind of mirror).  Even then the canonical aclweb/anthology... URL should be used and not the URL to the PDF on some random mirror.

**Comment by mjpost** [comment]
This is compelling in favor of "URL" linking to canonical, but then it seems that there should also be a PDF link. The buttons currently have an inconsistent role: some are redundant to the columnar information (presentation, note, video), one is found only as a button (search), one is redundant with the title link (PDF), and one is listed as an export format (bibtex). It seems the buttons should be the most commonly-used shortcuts and should never be the only / primary link to an object of interest?

**Comment by akoehn** [comment]
I see everything above "bib export formats" as a listing of the bibliographic information. Then comes the bibliography export buttons. 

"notes", "video" and "presentation" is doubled, that is true, but it seems to be a different issue to me (I would probably remove the ones on the bottom to have one button for each link).  Everything relevant is then linked on the right (top for mobile) and the middle provides the bibliographic information.
