### ISSUE TITLE
Add rewrite rule towards www

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#589]
https://aclweb.org/anthology and https://www.aclweb.org/anthology  are currently both browsable. (see short discussion in #579)

IMO it would be a bit cleaner to redirect from the former to the latter, similar to what we already have in place with http:// and anthology.aclweb.org.  Should be a one-liner but I don't know which one.

**Comment by mjpost** [comment]
It'd be a simple change to [this file](https://github.com/acl-org/acl-anthology/blob/master/hugo/static/.htaccess), but would require a bit of testing.

**Comment by akoehn** [comment]
Should be one additional line after the check for https:
```
RewriteCond %{HTTPS} !=on [OR]
RewriteCond %{HTTP_HOST} !^www\. [NC]
```
