### ISSUE TITLE
PDFs missing on the server

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#598]
according to the search console, google was unable to index quite a
few paper PDFs.

Most of these are not problems of our part, but some are.  Here is the
list of 404s on our side (papers are linked from the anthology):

 - [x] https://www.aclweb.org/anthology/L18-1254.pdf
 - [x] https://www.aclweb.org/anthology/O95-1002.pdf ([volume]( https://www.aclweb.org/anthology/O95-1.pdf))
 - [x] https://www.aclweb.org/anthology/O00-1011.pdf ([volume]( https://www.aclweb.org/anthology/O00-1.pdf))
 - [x] https://www.aclweb.org/anthology/O10-2006.pdf
 - [x] https://www.aclweb.org/anthology/O91-1004.pdf ([volume](https://www.aclweb.org/anthology/O91-1.pdf)]
 - [x] https://www.aclweb.org/anthology/E06-1029.pdf
 - [x] https://www.aclweb.org/anthology/O90-1005.pdf ([volume](https://www.aclweb.org/anthology/O90-1.pdf))
 - [x] https://www.aclweb.org/anthology/O96-2004.pdf
 - [x] https://www.aclweb.org/anthology/O97-4001.pdf
 - [x] https://www.aclweb.org/anthology/W04-2303.pdf
 - [x] https://www.aclweb.org/anthology/W03-2413.pdf
 - [x] https://www.aclweb.org/anthology/W03-2410.pdf
 - [x] https://www.aclweb.org/anthology/W10-0409.pdf
 - [x] https://www.aclweb.org/anthology/I08-2128.pdf
 - [x] https://www.aclweb.org/anthology/attachments/W19-5212.OptionalSupplementaryMaterial.pdf
 - [x] https://www.aclweb.org/anthology/N16-1085v1.pdf
 - [x] https://www.aclweb.org/anthology/S19-2021v2.pdf
 - [x] https://www.aclweb.org/anthology/S19-2021v1.pdf
 - [x] https://www.aclweb.org/anthology/P12-1031v2.pdf
 - [x] https://www.aclweb.org/anthology/P12-1031v1.pdf
 - [x] https://www.aclweb.org/anthology/D15-2.pdf
 - [x] https://www.aclweb.org/anthology/W14-2104e1.pdf.pdf
 - [x] https://www.aclweb.org/anthology/attachments/S19-2207.Software.tex

Second block of missing PDFs (from search console -> "submitted URL has crawl issue"):
 - [x] https://www.aclweb.org/anthology/M92-1003.pdf
 - [x] https://www.aclweb.org/anthology/W09-2009.pdf
 - [x] https://www.aclweb.org/anthology/W09-1008.pdf
 - [x] https://www.aclweb.org/anthology/O07-1014.pdf
 - [x] https://www.aclweb.org/anthology/W03-3022.pdf
 - [x] https://www.aclweb.org/anthology/I08-7008.pdf
 - [x] https://www.aclweb.org/anthology/I08-2120.pdf
 - [x] https://www.aclweb.org/anthology/O98-1011.pdf
 - [x] https://www.aclweb.org/anthology/W10-0707.pdf
 - [x] https://www.aclweb.org/anthology/O11-1010.pdf
 - [x] https://www.aclweb.org/anthology/O00-1007.pdf

More:

- [x] https://www.aclweb.org/anthology/I08-2144.pdf
- [x] https://www.aclweb.org/anthology/W18-5901.pdf

2020 edition:
==========

Created using magic^tm

Files that could not be downloaded
----------------------------------
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.2.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.3.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.4.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.5.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.7.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.12.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.13.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.14.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.15.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.27.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.28.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.29.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.30.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.31.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.32.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.33.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.34.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.36.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.37.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.38.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.39.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2011.eamt-1.41.Presentation.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.3.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.5.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.9.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.10.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.17.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.19.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.33.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.37.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.38.Supplementary_Attachment.pdf
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.42.Supplementary_Attachment.zip
 - [x] https://www.aclweb.org/anthology//attachments/2020.inlg-1.45.Supplementary_Attachment.zip

Files with checksum mismatch
============================
 - [x] https://www.aclweb.org/anthology//2020.amta-research.11.pdf
 - [x] https://www.aclweb.org/anthology//2020.wosp-1.pdf
 - [x] https://www.aclweb.org/anthology//2020.wosp-1.12.pdf
 - [x] https://www.aclweb.org/anthology//N18-2078v1.pdf

Please mark the papers that are fixed to track progress.

For posterity sake, this is how I got that list:
 - download CSV with problematic URLs from search console
 - run this:
``` 
for i in $(sed 's/,.*//' https___www.aclweb.org_anthology_\ Index\Coverage\ Drilldown\ 2019-10-22.csv); do
  status=$(curl -I $i | head -n1)
  if [[ "$status" =~ "404" ]]; then
    echo "$i $status"
  fi
done > anthology-404.txt
```

The 2020 edition list is from the mirroring effort and should check all files
we reference.

**Comment by mbollmann** [comment]
Spotchecking some filenames, most of these seem to already have been reported in my list in https://github.com/acl-org/acl-anthology/issues/264#issuecomment-506827374.

**Comment by mjpost** [comment]
Okay, I found them all but four. Three of them have volume links, so we could extract the PDF from the volume, except that I can't read Chinese. So we need a volunteer who can do that (@davidweichiang?) I have emailed the author of O97-4001.pdf.

**Comment by davidweichiang** [comment]
I'll email the PDFs to you.

**Comment by mjpost** [comment]
Great, thank you!

**Comment by akoehn** [comment]
Added more missing PDFs to the issue from a different source.  My internet is currently not fast enough to open & check against the files reported by @mbollmann here: https://pastebin.com/d6R0AVaB

**Comment by davidweichiang** [comment]
I am sending the Chinese ones in this second batch to @mjpost.

**Comment by mjpost** [comment]
Okay, I put in place:

- O11-1010.pdf
- O00-1007.pdf
- O07-1014.pdf
- O98-1011.pdf

**Comment by davidweichiang** [comment]
Added https://www.aclweb.org/anthology/I08-2144.pdf

**Comment by GuyAglionby** [comment]
https://www.aclweb.org/anthology/W18-5901.pdf is also missing

**Comment by mbollmann** [comment]
Here are the missing PDF links [from my recently generated list](https://github.com/acl-org/acl-anthology/issues/264#issuecomment-615910423) which I don't yet see on yours:

https://www.aclweb.org/anthology/N01-1022.pdf
https://www.aclweb.org/anthology/O00-1010.pdf
https://www.aclweb.org/anthology/O02-1001.pdf
https://www.aclweb.org/anthology/O11-2009.pdf
https://www.aclweb.org/anthology/O94-1001.pdf
https://www.aclweb.org/anthology/O94-1003.pdf
https://www.aclweb.org/anthology/O94-1010.pdf
https://www.aclweb.org/anthology/P79-1024.pdf
https://www.aclweb.org/anthology/W09-0906.pdf
https://www.aclweb.org/anthology/W19-86.pdf

**Comment by akoehn** [comment]
Updated original post with 2020 file problems.

**Comment by akoehn** [comment]
... and final update based on my mirroring script. The 2020 list is based on checking all data, did someone fix the others and not mark it or what happened to them?

**Comment by akoehn** [comment]
@mjpost updated with current data.  I seems like all inlg attachments are currently missing.

**Comment by mjpost** [comment]
I just marked the following as complete, because the PDF links have been removed from the XML:

* https://www.aclweb.org/anthology/O97-4001.pdf
* https://www.aclweb.org/anthology/M92-1003.pdf
* https://www.aclweb.org/anthology/W09-2009.pdf
* https://www.aclweb.org/anthology/W03-3022.pdf
* https://www.aclweb.org/anthology/O07-1014.pdf
* https://www.aclweb.org/anthology/I08-7008.pdf
* https://www.aclweb.org/anthology/I08-2120.pdf
* https://www.aclweb.org/anthology/W10-0707.pdf
* https://www.aclweb.org/anthology/W18-5901.pdf
* https://www.aclweb.org/anthology/I08-2144.pdf

**Comment by mjpost** [comment]
Fixed all the attachments, good catch!

**Comment by mjpost** [comment]
Okay, with #1193, this should be all set!

**Comment by akoehn** [comment]
@mjpost I'll run the mirroring script again soon and then we will see :-)

**Comment by mjpost** [comment]
It's been a while, but with the merging of #1198, I think this is done.

**Comment by akoehn** [comment]
Yes. Did a full mirror (which took ~20h) and everything is there and has the correct checksum.

It is with great pleasure that I close this issue.
