### ISSUE TITLE
Search on aclanthology.info returns 404 pages

### ISSUE THREAD

**Issue by mbugert** [acl-org/acl-anthology#60]
Since a few days, the search page on https://aclanthology.info returns 404 pages when changing search queries (see attachment).
![peek 2018-06-08 16-09](https://user-images.githubusercontent.com/23331603/41162674-d50c9368-6b36-11e8-81e7-ad3a3f932280.gif)

**Comment by villalbamartin** [comment]
It looks as if the problem was not really with the sorting, but rather with a paper ID that got removed: sorting brought this paper to the first page, and then the system failed while trying to show it.

I've reindexed Solr and that seems to have solved the problem, so I'm closing the ticket now.
