### ISSUE TITLE
use build_anthology_id instead of format string

### ISSUE THREAD

**Issue by akoehn** [acl-org/acl-anthology#610]
Note for later (or someone else):
instead of `"{}-{}".format(...)` we should call `build_anthology_id`.

**Comment by mjpost** [comment]
Yes, I've been slowly converting these as I come across them, in an attempt to consolidate our assumption about what an Anthology ID looks like.

**Comment by mjpost** [comment]
(Also `deconstruct_anthology_id`, which currently returns three parts, but should be returning four: collection, year, volume, paper number)

**Comment by mbollmann** [comment]
I believe that with the switch to the new ID format, there should be no place in the main `bin/anthology/` library that still uses `.format` for constructing IDs.
