### ISSUE TITLE
smarter fixed case

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#612]
Occasionally a stellar pub chair will insert fixed-case protect themselves in titles in START. Our ingestion isn't aware of this. For example, someone may have gone to the trouble to specify:

> {SimVecs}: Similarity-Based Vectors for Utterance Representation in Conversational {AI} Systems

In which case we produce something that gets rendered to BibTeX as this:

> 	    title = "{{S}im{V}ecs}: Similarity-Based Vectors for Utterance Representation in Conversational {{AI}} Systems”

We should look for this when applying fixed case (perhaps by transforming `{` to `<fixed-case>` and `}` to `</fixed-case>`?)

**Comment by davidweichiang** [comment]
Oh, that's a big oversight. I can look at it.

**Comment by davidweichiang** [comment]
I can't reproduce this. When I make an XML file with title `{SimVecs}: ...` and run it through `normalize_anth.py -t`, I get `<fixed-case>SimVecs</fixed-case>: ...`.

**Comment by mjpost** [comment]
Sorry. I realize now this is probably because I wasn't running with `-t`.

**Comment by davidweichiang** [comment]
But without -t I also couldn’t reproduce; if you could check on your end that everything works now, that would be good I think?

**Comment by davidweichiang** [comment]
A START-based solution would also fix the problem for the conference website/handbook/app...

**Comment by mjpost** [comment]
I re-ingested CoNLL and no longer see this error. Take a look at #657.
