### ISSUE TITLE
Change title of D19-5527

### ISSUE THREAD

**Issue by afshinrahimi** [acl-org/acl-anthology#619]
Hello,

I am the publication chair of [W-NUT](http://noisy-text.github.io/2019/) workshop in EMNLP 2019. The following paper's title was changed in Softconf but unfortunately this was not reflected in bibliography.

Would it be possible to change the title to new title "What A Sunny Day ☂️: Toward Emoji-Sensitive Irony Detection" in ACL Anthology's bibliography? 

Note that the new title is already reflected in the proceeding's PDF file.

Thanks a lot!

> @inproceedings{hayati-etal-2019-dataset,
>     title = "Dataset Analysis and Augmentation for Emoji-Sensitive Irony Detection",
>     author = "Hayati, Shirley Anugrah  and
>       Chaudhary, Aditi  and
>       Otani, Naoki  and
>       Black, Alan W",
>     booktitle = "Proceedings of the 5th Workshop on Noisy User-generated Text (W-NUT 2019)",
>     month = nov,
>     year = "2019",
>     address = "Hong Kong, China",
>     publisher = "Association for Computational Linguistics",
>     url = "https://www.aclweb.org/anthology/D19-5527",
>     pages = "212--216",
>     abstract = "Irony detection is an important task with applications in identification of online abuse and harassment. With the ubiquitous use of non-verbal cues such as emojis in social media, in this work we aim to study the role of these structures in irony detection. Since the existing irony detection datasets have {\textless}10{\textbackslash}{\%} ironic tweets with emoji, classifiers trained on them are insensitive to emojis. We propose an automated pipeline for creating a more balanced dataset.",
> }

**Comment by akoehn** [comment]
We can change that, but could you clarify the exact unicode sequence for the umbrella?
It is currently #x2602 #xfe0f (UMBRELLA, VARIATION SELECTOR-16), which does not render correctly on the W-NUT website nor emacs on my device.

**Comment by sweetpeach** [comment]
Hello, I am Shirley Anugrah Hayati, one of the authors of the paper. 

The unicode for the umbrella with rain is (U+2614).

Thank you.
