### ISSUE TITLE
Make conference front matter show that it is front matter

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#62]
The legacy Anthology states that the first paper in the volume of a conference proceedings is a front matter, but the current Anthology just states the first paper is due to the chairs of the conference.  

Better retitle to state that it is front matter to the conference.

Suggested by Pierre Isabelle

**Comment by mjpost** [comment]
Frontmatter is now distinguished in the metadata. We probably won't add this note, though.
