### ISSUE TITLE
Metadata changes: D18-1500, W16-6109, D16-1062

### ISSUE THREAD

**Issue by jplalor** [acl-org/acl-anthology#624]
Hi, could you update the author name for the follow papers from "John Lalor" to "John P. Lalor"? Right now I have two ACL anthology pages and would like to merge them. Thanks!

- https://www.aclweb.org/anthology/D18-1500/ 
- https://www.aclweb.org/anthology/W16-6109/
- https://www.aclweb.org/anthology/D16-1062/

**Comment by mjpost** [comment]
Hi John,

You seem familiar with git—if you submit a PR this will get expedited. Find the files D18.xml, W16.xml, and D16.xml in data/xml and change the instances there. When merged to master the site will auto-rebuild within an hour.

matt

**Comment by jplalor** [comment]
Done & PR submitted. Thanks!
