### ISSUE TITLE
Metadata Change (EMNLP-COIN 2019)

### ISSUE THREAD

**Issue by jeff-da** [acl-org/acl-anthology#626]
D19-6010: Please change title from "Jeff Da at COIN - Shared Task" to "Jeff Da at COIN - Shared Task: BIG MOOD: Relating Transformers to Explicit Commonsense Knowledge"

D19-6001: Please change title from "Understanding Commonsense Inference Aptitude of Deep Contextual Representations" to "Cracking the Contextual Commonsense Code: Understanding
Commonsense Reasoning Aptitude of Deep Contextual Representations"

**Comment by mjpost** [comment]
Please find the lines in `data/xml/D19.xml` and submit a PR with the corrections.
