### ISSUE TITLE
Author name correction

### ISSUE THREAD

**Issue by gonzalez-agirre** [acl-org/acl-anthology#634]
Hi,

The author of the paper "PharmaCoNER: Pharmacological Substances, Compounds and proteins Named Entity Recognition track" (Anthology ID: D19-5701). It should be Aitor Gonzalez-Agirre instead of Aitor Gonzalez Agirre. It is also wrong in the bibtex, this is the correct one:

@inproceedings{agirre-etal-2019-pharmaconer,
    title = "{P}harma{C}o{NER}: Pharmacological Substances, Compounds and proteins Named Entity Recognition track",
    author = "Gonzalez-Agirre, Aitor  and
      Marimon, Montserrat  and
      Intxaurrondo, Ander  and
      Rabal, Obdulia  and
      Villegas, Marta  and
      Krallinger, Martin",
    booktitle = "Proceedings of The 5th Workshop on BioNLP Open Shared Tasks",
    month = nov,
    year = "2019",
    address = "Hong Kong, China",
    publisher = "Association for Computational Linguistics",
    url = "https://www.aclweb.org/anthology/D19-5701",
    doi = "10.18653/v1/D19-5701",
    pages = "1--10",
    abstract = "One of the biomedical entity types of relevance for medicine or biosciences are chemical compounds and drugs. The correct detection these entities is critical for other text mining applications building on them, such as adverse drug-reaction detection, medication-related fake news or drug-target extraction. Although a significant effort was made to detect mentions of drugs/chemicals in English texts, so far only very limited attempts were made to recognize them in medical documents in other languages. Taking into account the growing amount of medical publications and clinical records written in Spanish, we have organized the first shared task on detecting drug and chemical entities in Spanish medical documents. Additionally, we included a clinical concept-indexing sub-track asking teams to return SNOMED-CT identifiers related to drugs/chemicals for a collection of documents. For this task, named PharmaCoNER, we generated annotation guidelines together with a corpus of 1,000 manually annotated clinical case studies. A total of 22 teams participated in the sub-track 1, (77 system runs), and 7 teams in the sub-track 2 (19 system runs). Top scoring teams used sophisticated deep learning approaches yielding very competitive results with F-measures above 0.91. These results indicate that there is a real interest in promoting biomedical text mining efforts beyond English. We foresee that the PharmaCoNER annotation guidelines, corpus and participant systems will foster the development of new resources for clinical and biomedical text mining systems of Spanish medical data.",
}

**Comment by mjpost** [comment]
Hi—thanks. If you can correct this yourself in `data/xml/D19.xml` and issue a pull request citing this issue, it will speed up the process.

**Comment by gonzalez-agirre** [comment]
Thanks, but I don't think I can edit it, I'm not one of the editors....

**Comment by mjpost** [comment]
You can clone and submit a PR against ours, or there is a mechanism to insert an in-place PR from the web browser. If you can't figure that out, we will get to it eventually, but it may take longer.

**Comment by mjpost** [comment]
Nevermind, you're in luck, I did it myself (#631).

**Comment by gonzalez-agirre** [comment]
Hahaha, thanks!
