### ISSUE TITLE
Our favicon is goofed

### ISSUE THREAD

**Issue by aryamccarthy** [acl-org/acl-anthology#649]
See attached. On the PDF, the favicon (the ACL logo) looks normal. On the author pages and the abstract pages, it's oddly stretched, which gives this weird pixelation. Can confirm on Safari and Chrome.

<img width="756" alt="Screen Shot 2019-11-13 at 12 44 44 PM" src="https://user-images.githubusercontent.com/5395205/68789429-74168680-0613-11ea-8456-9fa4592cfa5d.png">

**Comment by aryamccarthy** [comment]
It seems that the file itself (https://raw.githubusercontent.com/acl-org/acl-anthology/master/hugo/static/aclicon.ico) is wonky. Can we borrow from the main ACL website?

**Comment by mjpost** [comment]
Now I can't unsee it. Just pushed in a fix, please approve quickly!

**Comment by nschneid** [comment]
Is there a higher-resolution version? I have an HD monitor now and it is pixelated around the edges.

**Comment by mjpost** [comment]
Are you interested in making it? The spec is easy to follow and just needs to have different res versions all in one file. We have an SVG version in the repo.

**Comment by aryamccarthy** [comment]
I've had good luck with this site, if someone wants to lead the charge. https://realfavicongenerator.net <https://realfavicongenerator.net/>

**Comment by nschneid** [comment]
Wow, I had no idea how complicated it is to set up a favicon so it works across platforms! I'll look into this.

**Comment by mjpost** [comment]
I generated them easily enough.

[favicon_package_v0.zip](https://github.com/acl-org/acl-anthology/files/3844401/favicon_package_v0.zip)

The site then gave me this code (paths would need adjusting) for header files. There would be some work I think to hunt them all down.

```html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

**Comment by mbollmann** [comment]
Briefly, the files should go into `hugo/static/`, and the code given would replace this line here, with the added caveat that the filenames should be piped through `relURL` just as the favicon is now:

https://github.com/acl-org/acl-anthology/blob/master/hugo/layouts/_default/baseof.html#L17

**Comment by aryamccarthy** [comment]
Did we fix this to @nschneid 's satisfaction? I don't have a hi-res monitor to confirm, though it certainly looks better than the image at the top of this thread.

**Comment by nschneid** [comment]
LGTM, thanks!

**Comment by aryamccarthy** [comment]
groovy

**Comment by mjpost** [comment]
I actually don't think we did anything on this.
