### ISSUE TITLE
Record the changes that we manually made to the database

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#65]
This is a low priority bug that has not happened yet, but it might in the future and so I'm documenting it.

Around two years ago, we modified the database to allow for re-importing volumes (see #42), which was fixed with commit 7909af5. What is _not_ clear anywhere is that we added a consistency check to the database.

This consistency check is not recorded in the scripts that Ruby uses to generate the database. In other words, if someone clones the project and builds the database from the .xml files from scratch, they may eventually run into the same issues we had.

I'm assigning this bug to myself, and should be solved in the same way of issue #64.

**Comment by mjpost** [comment]
In light of the static rewrite, perhaps we can close out this issue?

**Comment by villalbamartin** [comment]
Yes, it's no longer relevant. Closing the issue now.
