### ISSUE TITLE
Auto-deployment

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#656]
Currently I have a cron job that runs every hour, checks for a change on `master`, and then rsyncs the output of the build. It would be really cool if we could automatically deploy the Anthology any time something is merged to master, avoiding the need to use my local machine. The trick would be to safely setup an ssh key for this rsyncing. I don't know if this is possible, but maybe Githubs new "Actions" could help.

@villalbamartin, would you be interested in this?

**Comment by mjpost** [comment]
Another option would be just to deploy a mirror so that the build could be inspected without having to do it locally.

**Comment by akoehn** [comment]
I did some work with GitHub actions, deployment with it is relatively easy.

I don't see the point for previews as master should already have been tested.

**Comment by mjpost** [comment]
For deployment, is it easy even if you need to automate authentication somehow? 

The build checks don't catch everything. For example, if you improperly closed an HTML table or mis-bolded something.

**Comment by akoehn** [comment]
Yes, you can add encrypted secrets for deployment.

 I meant that commits in master have already gone through manual code review and first merging to then are where it works is backwards.

**Comment by mjpost** [comment]
Oh, yes, I guess that's true.

**Comment by akoehn** [comment]
I can create something next week.  BTW, deployment is also possible with Travis.

**Comment by villalbamartin** [comment]
@mjpost I could gladly take a look at this, although it would depend on what @akoehn has in mind.

**Comment by akoehn** [comment]
I have a (hopefully) working system on my branch (after some testing).  It works, but the github runners are slow and take more than 20min to build the anthology.  Maybe there is optimization potential with pyaml or the like.

**Comment by mjpost** [comment]
20 minutes to build the Anthology isn't bad at all, is it? My laptop takes 45, and I think 20 minutes is similar to what my desktop (the current build server) takes.

**Comment by akoehn** [comment]
> 20 minutes to build the Anthology isn't bad at all, is it?

It is *very* slow.  After a make clean, a complete build takes 4m30s on my machine.

The process works, I will create a PR shortly.  @mjpost : you will need to create a new ssh keypair that GitHub can use.  It will be encrypted by GitHub and not visible to anyone after you submit it.

I created this mirror using GitHub actions from my fork (remove whitespace if you actually want to see it): https ://arne.chark.eu/anthology/

**Comment by mjpost** [comment]
Just retimed this on my desktop (a late 2013 Mac Pro) and it takes 24 minutes. It takes 45 on my 2019 Macbook Air. Clearly I'm buying the wrong tools.

**Comment by mjpost** [comment]
@akoehn, maybe you want to generate the key pair, since I don't know how to deploy it? Then send me the public key, I can add it to the `authorized_hosts` file on the server.

**Comment by mbollmann** [comment]
ThinkPad T490 here, 20m35s. I'm really interested in your specs now @akoehn to find out where the bottleneck is. YAML generation alone takes ~14 minutes and I'm pretty sure that's with the C extensions installed. (Sorry for off-topic...)

**Comment by akoehn** [comment]
Very basic T480s here, I am pretty sure you guys don't have the C extensions enabled  as I just wrote to @mjpost in a mail :-)

I just did `time make -j4` and it reports 4m32s.

Will do the PR later with all necessary documentation, had too much other stuff to do.
