### ISSUE TITLE
Incorrect name in the proceedings with one of the EMNLP-IJCNLP workshops

### ISSUE THREAD

**Issue by IbraheemTuffaha** [acl-org/acl-anthology#658]
Hello!
In NLP4IF workshop. there's a minor issue with the name of one of the authors of our paper, which is titled "Pretrained Ensemble Learning for Fine-Grained Propaganda Detection". The first name of the second author is written as "Ibrahim" whereas the correct spelling is "Ibraheem". The incorrect name appears on the proceedings page: https://www.aclweb.org/anthology/volumes/D19-50/, and the paper's page: https://www.aclweb.org/anthology/D19-5020/. As for the actual paper (i.e., PDF file : https://www.aclweb.org/anthology/D19-5020.pdf), the correct name is used.
I assume changing the name in this file will fix the issue?
https://github.com/acl-org/acl-anthology/blob/master/data/xml/D19.xml
Thanks!

**Comment by akoehn** [comment]
Yes. If you could create a pull request that would be great.  Otherwise we will correct it in the future.

Btw, the name comes from the start or easychair account, whatever was used for that publication.

**Comment by akoehn** [comment]
Thanks!
