### ISSUE TITLE
Author name correction: Ana Marasović

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#662]
Via email:

> I've noticed today while filling the form for the ACL reviewing that my ACL anthology page is split due to the processing of the letter "ć":
>
> https://www.aclweb.org/anthology/people/a/ana-marasovic1/
>
> https://www.aclweb.org/anthology/people/a/ana-marasovic/
>
> Any chance you could merge these two pages?
>
> Thank you for your help!

**Comment by amarasovic** [comment]
Yes, the desired spelling is with the acute, and, you are right, I haven't spelled my last name correctly in Softconf. :)

**Comment by mbollmann** [comment]
@amarasovic In that case, you can find your paper with the misspelled variant [here](https://github.com/acl-org/acl-anthology/blob/master/data/xml/D19.xml), correct it, and submit a pull request. That would speed up the process. Otherwise one of us will get to it in the next couple of days.
