### ISSUE TITLE
metadata (?) issue: PDF rotation issue for EMNLP paper?

### ISSUE THREAD

**Issue by jmhessel** [acl-org/acl-anthology#667]
Thank you for your work on the ACL anthology!

I noticed that the pdf for one of my papers is rotated (I replicated this in several browsers) --- but only for the first page of the work. I don't know how this happened, but perhaps there are other papers that have this problem too?

Paper ID: D19-1210
https://www.aclweb.org/anthology/D19-1210.pdf

**Comment by akoehn** [comment]
Confirmed. Yes, that is strange and as the footer is rotated as well this seems to have happened in post-processing by EMNLP; the anthology ingestion does not change the PDFs.

Can you rotate the first page of the PDF somehow and link to the result? Then @mjpost can replace the PDF.

**Comment by mjpost** [comment]
Fixed.
