### ISSUE TITLE
bad display

### ISSUE THREAD

**Issue by nancyide** [acl-org/acl-anthology#670]
I was trying to get the bibtex for the article at https://www.aclweb.org/anthology/W07-1501/ (which seems to haver been moved from where it was awhile back). When I click on the "Bib Export formats: BibTeX" only part of the bibtex is displayed. Clicking on the Bibtex button on the right side gives the correct bibtex.

**Comment by mbollmann** [comment]
Both link to the exact same file, so the only explanation I can think of is some kind of network error while you were clicking on the first button.

**Comment by nancyide** [comment]
Apparently a recurrent one, as it happens every time.

**Comment by nschneid** [comment]
Both work fine for me.

**Comment by akoehn** [comment]
Works fine here too.  As @mbollmann said, both are the exact same links to the same file in the html (just double-checked this) and therefore the error has to be on the client side somewhere.

> which seems to haver been moved from where it was awhile back

The canonical URL has not changed. There may have been different working non-canonical URLs in the past, which may have stopped working (but we try to keep those working by redirecting to the canonical URLs).
