### ISSUE TITLE
W19-8600 - please kindly correct my last name

### ISSUE THREAD

**Issue by tomekd789** [acl-org/acl-anthology#686]
It should be "Dryjański", not "Dryjanski".
It applies to the all the following search results:
https://www.aclweb.org/anthology/search/?q=tomasz+dryjanski
(I have co-authored a paper with Mr. Hyungtak Choi with the correct name provided:
https://ieeexplore.ieee.org/abstract/document/8622273 )

**Comment by akoehn** [comment]
Hi Tomasz, the name in the metadata comes from your start profile.  You need to correct it there if you want the name to be correct in the future.

**Comment by tomekd789** [comment]
> Hi Tomasz, the name in the metadata comes from your start profile. You need to correct it there if you want the name to be correct in the future.

Er... Would you mind adding a short instruction, or a link?
I've tried searching for my "start profile", but unsuccessfully.

**Comment by akoehn** [comment]
You should have a softconf account to submit papers (possibly easychair if the venue uses that).  You should have received an email for your submissions with a link to your submission.

Maybe you never used anything to submit, in that case complain to your co-author who did the submission (and create a user account in softconf's start system with your correct data).

**Comment by tomekd789** [comment]
Thank you.
