### ISSUE TITLE
Paper Anthology ID: D19-1506 has incorrect first author

### ISSUE THREAD

**Issue by prabhukaliamoorthi** [acl-org/acl-anthology#694]
The first author is incorrectly mentioned as Karthik Krishnamoorthi in https://www.aclweb.org/anthology/D19-1506/ whereas the real author is Prabhu Kaliamoorthi as indicated in the paper https://www.aclweb.org/anthology/D19-1506.pdf

**Comment by davidweichiang** [comment]
Hi, this is kind of a big change -- would you mind explaining how the wrong name was entered into START?

**Comment by prabhukaliamoorthi** [comment]
I am not sure. But the PDF has the right name. The corresponding authors
must have made a mistake.

**Comment by mjpost** [comment]
@prabhukaliamoorthi, can you ask the corresponding author to comment here and confirm this change, and perhaps to comment on what happened?

It's certainly within our policy to update the metadata to reflect the PDF, but I'd like to understand what went on here. Perhaps the START IDs are similar?

**Comment by prabhukaliamoorthi** [comment]
+kozareva@google.com

Hi Zori,

My name is entered incorrectly in the PRADO paper. It could be due to START
IDs being similar. Can you please confirm?

Cheers,
Prabhu.

**Comment by prabhukaliamoorthi** [comment]
Hello everyone,

This is Zornitsa Kozareva, one of the authors of the paper

I do confirm that Prabhu is the legitimate author, it is very likely that
the softconf ID belonged to somebody else

Could you please update everything and add Prabhu? Again I confirm that he
is the author of the work and not the one showing in Acl anthology? Please
also have a look at the original pdf which has Prabhu’s name and email.

Thank you!

Best,
Zornitsa
