### ISSUE TITLE
##correction ## author name

### ISSUE THREAD

**Issue by aixiuxiuxiu** [acl-org/acl-anthology#696]
The first author's name is spelled incorrectely, Anthology ID: D19-1287. The order of first name and last name is wrong. Could you correct it, please?

**Comment by davidweichiang** [comment]
Hi, could you confirm that you want the first name to be An and the last name to be Aixiu?

**Comment by aixiuxiuxiu** [comment]
Hi, the first name should be Aixiu and last name An

Le vendredi 13 décembre 2019, David Chiang <notifications@github.com> a
écrit :

**Comment by mjpost** [comment]
Hi @aixiuxiuxiu, you can speed up this correction by finding your name in [data/xml/D19.xml], making the correction yourself, and issuing a PR.

**Comment by davidweichiang** [comment]
@aixiuxiuxiu, on the website your name currently displays as `Aixiu An` (https://www.aclweb.org/anthology/D19-1287/) which matches your name as it is printed in the PDF. Are you asking for it to be displayed with your family name first? Currently the Anthology website always displays names with the given name first and family name last. We've talked about making this more flexible, but at the moment have no plans to.

**Comment by aixiuxiuxiu** [comment]
Hi, Yes,  But it is wrong in the google scholar bibtex:

@inproceedings{aixiu2019representation,
  title={Representation of Constituents in Neural Language Models:
Coordination Phrase as a Case Study},
  author={Aixiu, AN and Qian, Peng and Wilcox, Ethan and Levy, Roger},
  booktitle={Proceedings of the 2019 Conference on Empirical Methods
in Natural Language Processing and the 9th International Joint
Conference on Natural Language Processing (EMNLP-IJCNLP)},
  pages={2881--2892},
  year={2019}
}


Le ven. 13 déc. 2019 à 17:07, David Chiang <notifications@github.com> a
écrit :

**Comment by mjpost** [comment]
Unfortunately, we don't have control over Google Scholar's bibtex. [Ours](https://www.aclweb.org/anthology/D19-1287.bib) has your name correctly. But poking around, it seems correct to me both on [Google Scholar and arXiv](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C21&q=Representation+of+Constituents+in+Neural+Language+Models%3A+Coordination+Phrase+as+a+Case+Study&btnG=) (following links).

**Comment by aixiuxiuxiu** [comment]
Yes, the one on your website is the correct one. but the name on the second
version in this link
<https://scholar.google.com/scholar?hl=en&as_sdt=0%2C21&q=Representation+of+Constituents+in+Neural+Language+Models%3A+Coordination+Phrase+as+a+Case+Study&btnG=>
on
google scholar (the EMNLP proceeding) is wrong

**Comment by akoehn** [comment]
Okay, if it correct in the acl anthology, there is nothing to be fixed here. If you want the problem to be fixed, you will have to work with google scholar.

I (and probably the others working on the anthology as well) do not know how the google scholar entry is produced by google, you would have to ask them.  google scholar and the acl anthology are two completely distinct entities.  We have no influence on google scholar at all.
