### ISSUE TITLE
I08-2 front matter links to whole PDF

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#698]
The link from here https://www.aclweb.org/anthology/events/ijcnlp-2008/ that is normally the front matter for volume 2 links instead to the full PDF for all of volume 2.

**Comment by mjpost** [comment]
That's weird. From the XML, it shouldn't be generating a link at all, since there is no `<url>` tag for the frontmatter:

```xml
  <volume id="2">
    <meta>
      <booktitle>Proceedings of the Third International Joint Conference on Natural Language Processing: Volume-<fixed-case>II</fixed-case></booktitle>
      <url>I08-2</url>
    </meta>
    <frontmatter/>
```

**Comment by mjpost** [comment]
This is a deeper problem, I suspect with `create_hugo_yaml.py`.

**Comment by mbollmann** [comment]
This is because `utils.parse_element` adds a "pdf" attribute that the `Paper` object doesn't know about:

https://github.com/acl-org/acl-anthology/blob/b8ebef6ead868e8344131156f249cd6eee604cc4/bin/anthology/utils.py#L349-L354

One-line fix incoming.
