### ISSUE TITLE
[PDF Link Error] Y98-1021 and Y98-1020

### ISSUE THREAD

**Issue by Vimos** [acl-org/acl-anthology#702]
Y98-1021 page is pointing at pdf https://www.aclweb.org/anthology/Y98-1021.pdf which is actually pdf of Y98-1020.

Y98-1020 page is pointing at pdf https://www.aclweb.org/anthology/Y98-1020.pdf which is actually pdf of Y98-1019.

I guess there are similar problems for all the related papers for `Y98`.

**Comment by mjpost** [comment]
Thank you for reporting this! I have resolved it by renaming PDFs.
