### ISSUE TITLE
Incorrect PDF for paper D19-1294

### ISSUE THREAD

**Issue by chardmeier** [acl-org/acl-anthology#703]
I wanted to download paper D19-1294 by Prathyusha Jwalapuram et al.
When I click on the PDF link on https://www.aclweb.org/anthology/D19-1294/, it serves me a different paper by Jianmon Li et al. instead. The URL for the PDF looks correct.

**Comment by davidweichiang** [comment]
Sorry about this. This is the same issue as #701 -- I can't see any rhyme or reason why this is happening to just a few papers.

**Comment by mjpost** [comment]
I got the original from the EMNLP publication chairs. This is now fixed.
