### ISSUE TITLE
Name misspelled in anthology, possible conversion bug

### ISSUE THREAD

**Issue by evanmiltenburg** [acl-org/acl-anthology#71]
It seems that my name got misspelled in the COLING proceedings bib file, so instead of "Emiel van Miltenburg", it reads "Emiel Miltenburg" (dropping the 'van'). I clicked my name to see if this happened in other places as well, and found that it also happened with the IWCS proceedings.

https://aclanthology.coli.uni-saarland.de/people/emiel-miltenburg

So far, this could be a data entry problem. But: the IWCS proceedings *do* list my name correctly: http://www.aclweb.org/anthology/W15-0110.bib

So **the system has two versions of my name for the same conference** (at least for IWCS). Maybe something went wrong with the conversion between the old anthology and the new one?

I don't know if there are guards against misspelling of author names, but if there are, then having the misspelled version of my name may lead to more wrongly spelled entries.

**Comment by evanmiltenburg** [comment]
Ah, this seems to be related to #70. Thanks to Andreas for noticing this on Twitter.

**Comment by CTNLP** [comment]
This is indeed the same problems as #70  I will try to fix it the same way as indicated there, we will also see if the <von> tag is used anywhere else in the xml files. Thanks for pointing this out.

**Comment by knmnyn** [comment]
Just FWIW, there's no guard on name forms / variants in the Anthology as of now.  We'd love to have people volunteer time to solve those problems (edit distances or some easy fix, anyone)?
