### ISSUE TITLE
How to access the ACL anthology dataset

### ISSUE THREAD

**Issue by Zafar-southeast** [acl-org/acl-anthology#717]
I want to download the ACL dataset for conducting experiments, please help me.

**Comment by akoehn** [comment]
Please be more specific.  You can download all metadata by simply cloning this repository.

**Comment by mjpost** [comment]
See also [our developer documentation](https://www.aclweb.org/anthology/info/development/) (linked in [the FAQ](https://www.aclweb.org/anthology/faq/)).
