### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by evanmiltenburg** [acl-org/acl-anthology#72]
Following #71: while searching for my name, I also found that the search box for the new anthology doesn't work. Entering part of my last name results in [this link](https://aclanthology.coli.uni-saarland.de/catalog?utf8=✓&search_field=all_fields&q=miltenburg), with a page reading:

    The page you were looking for doesn't exist.
    
    You may have mistyped the address or the page may have moved.
    If you are the application owner check the logs for more information.

**Comment by villalbamartin** [comment]
We forgot to re-index the database. This has been corrected now, and the search functionality is working again.
