### ISSUE TITLE
Some workshop series have no associated venue

### ISSUE THREAD

**Issue by GuyAglionby** [acl-org/acl-anthology#721]
It looks like some workshop series have no associated venue (e.g. Workshop on Structured Prediction for NLP). Is there a policy for when these are created?

**Comment by mjpost** [comment]
In general, deliverers of proceedings should add the venue. We don't typically fill this information in otherwise if we didn't catch it at ingestion time.

Can we close this due to #720?

**Comment by GuyAglionby** [comment]
Understood, thanks!
