### ISSUE TITLE
Wrong PDF: Q18-1033

### ISSUE THREAD

**Issue by chardmeier** [acl-org/acl-anthology#723]
The PDF for Q18-1033 contains the text of a different paper.

**Comment by chardmeier** [comment]
Actually, the PDF of Q18-1033 is the one that should be linked at Q18-1031. Q18-1031 also has an incorrect file, that of Q18-1030. Q18-1030, finally, has the file that should be at Q18-1033.

I'm getting the impression that the articles, but not the PDFs, may have got renumbered at some point. I have an old bibliography file where the Shao et al. paper, which is now Q13-1033, contains a link to the number Q18-1030, and that's exactly where I now find the right PDF, but not the right metadata.

**Comment by mjpost** [comment]
@aryamccarthy can you take a look at this? I think this predates your work but perhaps your scripts could resolve it.

**Comment by aryamccarthy** [comment]
I can fix this by correcting the XML. The issue came from that separate upstream mess we talked about.
