### ISSUE TITLE
Regarding to Metadata Correction

### ISSUE THREAD

**Issue by yudiandoris** [acl-org/acl-anthology#725]
Dear staff,

We would like to report an issue about the mismatched title of our workshop paper (Anthology ID: D19-5804) (https://www.aclweb.org/anthology/D19-5804/). It should be "Improving Question Answering with External Knowledge" instead of the current one. The title in the pdf is correct. 

Thank you very much for your attention!

**Comment by mjpost** [comment]
Thanks. If you can submit a pull request fixing this (and referencing this issue), the change will happen faster. This page should help:

https://www.aclweb.org/anthology/info/corrections/#correcting-metadata

**Comment by akoehn** [comment]
closed with #727, thanks for the PR!
