### ISSUE TITLE
Dead links for ACL 2018 proceedings

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#73]
The links to the full proceedings for P18-2, P18-3, P18-4, and P18-5 ([all linked from here](https://aclanthology.coli.uni-saarland.de/events/acl-2018)) are all dead.

**Comment by knmnyn** [comment]
Hi Matt:

These seem to work for me, from the link that you sent.  Can you check
again?

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by mjpost** [comment]
Hi Min,

Sorry, here are the actual links. You come across them if you follow the Table of Content link from the top of the page, then click on the link to the BibTeX file for the entire sub-proceedings.

- https://aclanthology.coli.uni-saarland.de/volumes/proceedings-of-the-56th-annual-meeting-of-the-association-for-computational-linguistics-volume-2-short-papers.bib
- 
https://aclanthology.coli.uni-saarland.de/volumes/proceedings-of-acl-2018-student-research-workshop.bib
- 
https://aclanthology.coli.uni-saarland.de/volumes/proceedings-of-acl-2018-system-demonstrations.bib
- 
https://aclanthology.coli.uni-saarland.de/volumes/proceedings-of-acl-2018-tutorial-abstracts.bib

**Comment by knmnyn** [comment]
Hi Matt:

Ok, you are talking about the .bib links not the proceedings links.  I see
they are broken.  I've fixed them now.  Thanks!

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by mjpost** [comment]
Perfect, thank you!
