### ISSUE TITLE
Original PDF of P19-1155 replaced with erratum

### ISSUE THREAD

**Issue by nimirea** [acl-org/acl-anthology#730]
I recently submitted an erratum to my and @kbicknell's paper (ID: P19-1155). When checking up on its status, I noticed that the original paper is missing—https://www.aclweb.org/anthology/P19-1155.pdf is now _just_ the erratum.

This seems like a bug because:

* The erratum is also linked separately as https://www.aclweb.org/anthology/P19-1155e1.pdf
* ["Requesting Corrections"](https://www.aclweb.org/anthology/info/corrections/) page says: "The original published PDF is not invalidated. The original will still stand as published and cannot be withdrawn, and both will remain available and linked on the website."

I'm not sure whether this is simply a metadata issue or not; either way, I'm including two versions of the original paper here for convenience.

* [MireaBicknell_2019.pdf](https://github.com/acl-org/acl-anthology/files/4062048/MireaBicknell_2019.pdf) = original that I submitted, without page numbering or footer info in the first page
* [MireaBicknell2019_pagenumber.pdf](https://github.com/acl-org/acl-anthology/files/4062062/MireaBicknell2019_pagenumber.pdf) = as originally published in the Anthology, with page numbering & footer info

**Comment by mjpost** [comment]
I'm not sure what happened here, since from the metadata it was processed as an erratum. Anyway I restored it from a backup and all is well. Thanks for reporting and sorry for the trouble!

**Comment by nimirea** [comment]
It seems this issue has reappeared; everything is now again as was described in my first post here.

**Comment by mjpost** [comment]
Fixed again, with an extra step taken to prevent this from re-occurring. Sorry for the trouble, Nicole!

**Comment by nimirea** [comment]
Thanks Matt!

**Comment by tanggongbo** [comment]
I meet the same problem on D19-1149.

**Comment by mjpost** [comment]
Fixed, thanks @tanggongbo.

**Comment by tanggongbo** [comment]
> Fixed, thanks @tanggongbo.

Thanks Matt!
