### ISSUE TITLE
Correction request: W19-8301

### ISSUE THREAD

**Issue by kanoyoshinobu** [acl-org/acl-anthology#733]
In all of the papers of AIWolfDial2019 workshop https://www.aclweb.org/anthology/volumes/W19-83/
which I myself submitted the data,
all of author names are reversed for their last names and first names.

For example,
(current) Kano Yoshinobu, Aranha Claus, Inaba Michimasa, Toriumi Fujio, Osawa Hirotaka, Katagami Daisuke, Otsuki Takashi, Tsunoda Issei, Nagayama Shoji, Tellols Dolça, Sugawara Yu, Nakata Yohei
but, the last name of the first author is "Kano".

Would you please correct these name orders. Thanks.

**Comment by akoehn** [comment]
Hi Yoshinobu,You can speed up the process of this by creating a pull request with the changes.  The metadata is stored in data/xml/W19.xml
null

**Comment by davidweichiang** [comment]
Additionally, there are curly braces in the booktitle. Seems like a bug in the fixed-caser.
