### ISSUE TITLE
ACL 2019 videos are available

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#735]
They can be [browsed here](vimeo.com/user/46432367/folder/1250297).

They video company provided a CSV file linking Anthology IDs to Vimeo URLs. Does anyone want to do the work of ingesting this? [02 ACL2019.xlsx](https://github.com/acl-org/acl-anthology/files/4098244/02.ACL2019.xlsx)

I also have a list of plenary talks and videos that are not currently linked from the Anthology, but should be (#298): [01 ACL 2019 - All Speeches.xlsx](https://github.com/acl-org/acl-anthology/files/4098219/01.ACL.2019.-.All.Speeches.xlsx)

**Comment by akoehn** [comment]
I can look at this next week or so, I wanted to update my linking script
anyway to link the naacl 2019 videos.

**Comment by mjpost** [comment]
The good news is that video companies from hereonout are following [the guidelines](https://github.com/acl-org/acl-anthology/wiki/Contract-Guidelines-for-Recording-Talks). This means we should get a CSV always, but also that the videos will have a backpointer into the Anthology. So the script could work on either data source (and could also double-check).
