### ISSUE TITLE
COLING 1984

### ISSUE THREAD

**Issue by dowobeha** [acl-org/acl-anthology#748]
COLING 1984 was a joint conference with ACL 1984, but the Anthology front page has a link under ACL but not under COLING. 

If someone is browsing through old COLINGs or looking for an old COLING paper, many people may not know to look under ACL 1984.

It would be nice to have a link under COLING for 1984, even if it points to https://www.aclweb.org/anthology/events/acl-1984/

**Comment by mbollmann** [comment]
It does appear on https://www.aclweb.org/anthology/venues/coling/, though.

**Comment by davidweichiang** [comment]
This happens for all joint conferences, right? Would it be better to make them show up in both places on the front page?

Also, the title page for ACL-COLING 1984 simply calls the conference "Coling" -- it seems like COLING might have been the primary event.

**Comment by mbollmann** [comment]
Turns out the only reason COLING 1984 doesn't appear on the main page is that we forgot to include 1984 in the hardcoded list of years... I'll make a PR (and can't wait to refactor & redesign the front page).
