### ISSUE TITLE
W17-1706: Author order in metadata doesn't match PDF

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#753]
https://www.aclweb.org/anthology/W17-1706/ has Nerima as first author in the metadata (matching the workshop proceedings PDF: https://www.aclweb.org/anthology/W17-1700.pdf) but as second author in the PDF.

Which should we count as the canonical order?

**Comment by aryamccarthy** [comment]
Naive option: ask them?

**Comment by davidweichiang** [comment]
I think we always treat the PDF as canonical. In a case like this, the metadata should be changed to match the PDF.

**Comment by akoehn** [comment]
It usually is canonical, but sometimes the conferences explicitly forbid author re-ordering after initial submission. Probably not in this workshop, but I would not use the PDF as a blanket canonical source for that reason.

**Comment by mjpost** [comment]
This is a tricky situation that exposes a loophole through the author list / author order restrictions imposed on many conferences these days. My thinking is that it is not our duty to enforce these restrictions; we simply do not have the resources to manage different rules from all the conferences and to discriminate legitimate and illegitimate cases. If conferences want to impose them, it is their job to ensure that PDFs do not sneak in an extra author or diverge from the original metadata. I therefore think we should continue to treat the PDF as canonical.
