### ISSUE TITLE
[P89-1018] Incorrect first author name in metadata

### ISSUE THREAD

**Issue by LoicGrobol** [acl-org/acl-anthology#756]
The name of the first author in [P-89-1018](https://www.aclweb.org/anthology/P89-1018) is *Sylvie Billot*, the current version of the metadata use *Sylvie BillotT* (possibly due to OCR error).

**Comment by mjpost** [comment]
Thanks! I have a PR (#758) in.

**Comment by davidweichiang** [comment]
These errors are VERY common, esp. with the dagger being misrecognized as t. I wish there was an easy way to fix them en masse.
