### ISSUE TITLE
NAACL 2019 videos

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#763]
NAACL 2019 videos [are uploaded](https://vimeo.com/manage/folders/820515), but unfortunately not according [to spec](https://github.com/acl-org/acl-anthology/wiki/Contract-Guidelines-for-Recording-Talks). @akoehn, you had code for matching on titles, right? Would you mind trying to do the linkup sometime if you get a free hour?

**Comment by mjpost** [comment]
Just uncovered this document from the provider: https://docs.google.com/spreadsheets/d/1Tt_WR7S3Ak3YAmfOkMdRfTErCDiAD3tvEPw5GCJanUk/edit#gid=0

**Comment by akoehn** [comment]
I can have a look. My matching script does not work with the current structure, I will have to rework that anyway so we can link the remaining old videos.

**Comment by SpencerWhitehead** [comment]
Hey guys, I have a script that can do the matching and had previously ran it for these videos, but there were some incorrect matches that I needed to fix, which I'll do asap. As of now, I don't believe I'm a member on here so I'll be creating a fork of the repo and making a pull request from there. I'll make a note in here once I do so. @akoehn This should save you some time+effort.

**Comment by akoehn** [comment]
@SpencerWhitehead go ahead and make a PR!  Did you see my video linker script in the repository (`bin/vimeo-linker.py`)?  It performs matching as well and we used it for the other videos that are linked.
