### ISSUE TITLE
Metadata correction: W18-2509

### ISSUE THREAD

**Issue by lintool** [acl-org/acl-anthology#766]
Filing an issue per instructions here: https://www.aclweb.org/anthology/info/corrections/

Paper landing page: https://www.aclweb.org/anthology/W18-2509/

The abstract begins with a parenthetical:

> (Note this is not being submitted blind. The chair of the workshop requested this submission unblinded from me on twitter, so assuming that is okay.) 

This should be removed.

**Comment by mjpost** [comment]
PR created (#772), thank you!
