### ISSUE TITLE
I11-1070 Dataset consistently disappears after a while

### ISSUE THREAD

**Issue by uschaefer** [acl-org/acl-anthology#774]
The reason seems to be an inconsistent entry for this dataset.
In `acl_attachements.txt`, the entry is `attachments/I/I11/I11-1070.Datasets.zip` with an -s-
but the download URL shown in the conference's paper list is `https://www.aclweb.org/anthology/attachments/I11-1070.Dataset.zip` without -s- (as written in `data/xml/I11.xml`)

The dataset is displayed as downloadable dataset but downloading it leads to a 404 error. After correcting/adding the file via the Google form, it first becomes downloadable, and then after a few days or weeks, again 404 occurs. I did this three times now in the past months or year and I think this is a consistent bug in the workflow or data. May I ask you to correct it in either place? Unfortunately, I can't locate `acl_attachements.txt` anymore.
thanks,

**Comment by mjpost** [comment]
Yes, it should have an "s". Thanks for reporting! I will put in a fix. In the meantime you can access it here: https://www.aclweb.org/anthology/attachments/I11-1070.Datasets.zip.
