### ISSUE TITLE
Protocol to obtain full (maybe machine-readable) article text 

### ISSUE THREAD

**Issue by scignscape** [acl-org/acl-anthology#781]
If I interpret the data correctly, links to full-text articles (in PDF form) are available via the `url` tag under `paper`: so e.g. https://www.aclweb.org/anthology/P13-1023.pdf is listed as "P13-1023" under the `paper id="23"` node in the ... /data/xml/P13.xml file.  I have two questions.  (1) Is this the general pattern for locating URLs, so I could assume that the same file and XPath pattern works for any collection/year/volume combination?  (2) Does the anthology index full text in formats other than PDF (e.g. LaTeX, XML), or can authors or chairs contribute such sources?  For example, suppose authors want to prepare papers in a format that can be primary data documents for LAF-style annotations -- and have a version of the document in (say) ScienceDirect XML -- is there any way to store a URL for that resource alongside the anthology's PDF XML?  If that cannot be done within the archive itself, perhaps via a separate resource which maps anthology dois to the machine-readable manuscripts ...

**Comment by mjpost** [comment]
1. Yes, this is the general pattern. If the `<url>` tag is an absolute link, it will be an offsite one.

2. No, we do not index full text. If a user wants to submit the raw source, it could be linked as an attachment. ACL has in the past done experiments forcing authors to submit the raw text, but have not been consistent with this, and to my knowledge this wasn't orchestrated with the Anthology to link it. We could support full-text linkage but likely would not do so without extended discussions with ACL conference organizers to make this a sustained top-level feature.

**Comment by mbollmann** [comment]
I believe this has been answered. I would add that for (1), you could also utilize the Python library under `bin/anthology` to instantiate an `Anthology` object, locate a paper via its ID in `anthology.papers` (or iterate through all of them), and fetch the PDF link through `paper.attrib["pdf"]`.

Feel free to reopen if you have more questions.
