### ISSUE TITLE
Discourse Structure and Dialogue Acts in Multi party Dialogue: the STAC Corpus

### ISSUE THREAD

**Issue by yzgdjqwh** [acl-org/acl-anthology#782]
the link failed
https://aclweb.org/anthology/attachments/D/D15/D15-1109.Attachment.zip
 Thank you,

**Comment by mjpost** [comment]
Where did you find this link? The canonical link at https://www.aclweb.org/anthology/D15-1109/ (to https://www.aclweb.org/anthology/attachments/D15-1109.Attachment.zip) works fine.
