### ISSUE TITLE
Form for requesting revisions or errata seems to be broken

### ISSUE THREAD

**Issue by texttheater** [acl-org/acl-anthology#783]
On

https://www.aclweb.org/anthology/info/corrections/

there is a link to

https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAABqTSThUN0I2VEdZMTk4Sks3S042MVkxUEZQUVdOUS4u

This form looks like an odd mix of the expected form to submit revisions or errata, and the unexpected form to request hosting proceedings.

**Comment by mjpost** [comment]
Hmm, not sure how that happened. Fixed, thank you!
