### ISSUE TITLE
NAACL-HLT 2018 doesn't have HLT as a venue

### ISSUE THREAD

**Issue by GuyAglionby** [acl-org/acl-anthology#80]
Papers from NAACL-HLT 2018 only have NAACL listed as a venue, not HLT as well (e.g. [paper](https://aclanthology.coli.uni-saarland.de/papers/N18-1000/n18-1000)). This is different to previous years of the joint conference, where both are listed (e.g. [2016](https://aclanthology.coli.uni-saarland.de/papers/N16-1000/n16-1000)). Is this an error? [This](https://github.com/acl-org/acl-anthology/blob/master/db/joint_map.txt) seems like the relevant file.

Thanks!

**Comment by knmnyn** [comment]
Hi @GuyAglionby thanks for the bug report.  That has been fixed now.
