### ISSUE TITLE
http://aclanthology.info/anthology.bib has duplicates

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#81]
There is a duplicate entry which is formally an error in the BibTeX spec:

    @InProceedings{W06-2200,
      title =       "Proceedings of the Workshop on Adaptive Text Extraction and Mining (ATEM 2006)",
      booktitle =   "Proceedings of the Workshop on Adaptive Text Extraction and Mining (ATEM 2006)",
      year =        "2006",
      url =         "http://www.aclweb.org/anthology/W06-2200"
    }

**Comment by danielgildea** [comment]
Works ok for me when I generate the file on my local machine.
Maybe the file just needs to be regenerated after rebuilding the database.

**Comment by mjpost** [comment]
When you generate it locally, do you have the duplicate W06-2200 entry?

I can use the file fine in a LaTeX project, since bibtex safely skips the duplicate entry. It's only when parsing it with third-party libraries like [pybtex](https://pybtex.org) that I get an error due to the duplicate key. I guess this might just be a problem with the library, since I'm not sure what the official bibtex spec says about duplicate keys.

But it does seem we shouldn't be generating the duplicate key.

**Comment by danielgildea** [comment]
I do not have the duplicate entry when I generate it locally.  I am guessing that somehow
there are duplicate records in the database on the

**Comment by mjpost** [comment]
@villalbamartin, can you add this to your case load for the next time you get a free minute? Are there duplicate entries in the database for this entry, and if so (easier, I hope) can we remove it and (harder) do you have any idea why it occurred?

**Comment by villalbamartin** [comment]
@mjpost I just checked the file `http://aclanthology.info/anthology.bib`, but the duplicate entry is gone. The database entry is also not duplicated, so it seems the issue fixed itself.

I'm closing the issue since I cannot replicate it, but if anyone has more information feel free to reopen it.

**Comment by knmnyn** [comment]
I think the programmatic generation helped get rid of this, as with some of the database sanitization.
FYR, the command is `rake  export:paper_bib_single`
