### ISSUE TITLE
Problems with abstract toggle

### ISSUE THREAD

**Issue by kilian-gebhardt** [acl-org/acl-anthology#813]
On https://www.aclweb.org/anthology/volumes/1995.iwpt-1/ and the other recently added IWPT workshops both the "Show all abstracts" button and the indivual papers "abs" does not work.

**Comment by mbollmann** [comment]
Looks like the Bootstrap Collapse component doesn't work correctly with periods in the identifier, which have been introduced with the new-style IDs. :unamused: 

I guess I'll modify the templates and replace the periods with something else. Thanks for noticing!
