### ISSUE TITLE
Search by title returns 404 page

### ISSUE THREAD

**Issue by bheinzerling** [acl-org/acl-anthology#82]
Searching by Title (and by All Fields) returns a 404 page for all search terms since a few days ago. Probably same as

https://github.com/acl-org/acl-anthology/issues/60
https://github.com/acl-org/acl-anthology/issues/72

**Comment by zxteloiv** [comment]
Same here. It often occurs to me over the last year.
This time the query is "[Latent Tree Learning with Differentiable Parsers](https://aclanthology.coli.uni-saarland.de/catalog?utf8=✓&utf8=✓&search_field=all_fields&q=https://aclanthology.coli.uni-saarland.de/catalog?utf8=✓&search_field=all_fields&q=Latent+Tree+Learning+with+Differentiable+Parsers)".

Other than manual re-indexing, is there any way for this?

**Comment by knmnyn** [comment]
Thanks, all.  I think someone from our group changed some of the paper metadata and forgot to reindex the database.  It should be fixed now.
