### ISSUE TITLE
make clean doesn't clean make check's venv if left over

### ISSUE THREAD

**Issue by leondz** [acl-org/acl-anthology#826]
When `make check` fails, the `venv/` dir created by `make check` sometimes isn't removed by `make clean`. It's easy enough to tidy up manually, but should a `make clean` tidy up intermediate artefacts left by the `check` target as well as intermediate artefacts from the main build target?

**Comment by akoehn** [comment]
I honestly never thought about the `venv` in the Makefile, as I always thought of it as a cache where the data in it does not harm anything.  The only exception IMO is when testing whether the requirements.txt is correct -- but there we also have the problem that globally installed packages may interfere and we miss a requirement.

Always removing the venv on a clean would lead to lots of reinstalls.

So far my thought-dump on this, comments welcome!

**Comment by leondz** [comment]
So I had a bit of trouble setting up 3.7 on 18.04LTS and had to remove this manually a bunch on times. I guess the next step is for me to reproduce the behaviour and work out what the desired behaviour would be.

**Comment by danielgildea** [comment]
I sometimes have to remove venv by hand.  I think it would be nice to get a fresh start from "make clean" without having to look into the details.  But maybe "make all" should not "make clean" in order to avoid needless reinstalls.
