### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by guyemerson** [acl-org/acl-anthology#83]
Searching sometimes gives an error, when just typing a query into the search box and hitting enter:

https://aclanthology.coli.uni-saarland.de/catalog?utf8=%E2%9C%93&search_field=all_fields&q=compositional

The page says:

```
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.
```

Searching some terms seems to be fine:

https://aclanthology.coli.uni-saarland.de/catalog?utf8=%E2%9C%93&search_field=all_fields&q=hello

It's not clear why some searches fail and some succeed.

**Comment by knmnyn** [comment]
Hi, that should be fixed now.  The indexer needed to be re-run after doing some database modifications.  Thanks!
