### ISSUE TITLE
Revision in P19-1264

### ISSUE THREAD

**Issue by eaclark07** [acl-org/acl-anthology#834]
**Description:** Footnote 7 contained the wrong URL, which has been corrected.
 
**Corrected version:** [ACL_2019_generation_evaluation_CORRECTED.pdf](https://github.com/acl-org/acl-anthology/files/4672014/ACL_2019_generation_evaluation_CORRECTED.pdf)

Thank you!

**Comment by mjpost** [comment]
Thank you for a concise description!
