### ISSUE TITLE
Spelling error in authors name in paper "2020.lrec-1.509"

### ISSUE THREAD

**Issue by rundimeco** [acl-org/acl-anthology#838]
In this paper (https://www.aclweb.org/anthology/2020.lrec-1.509/), I'm referred to as Gael (so this paper links to this page: 2020.lrec-1.509/) but the correct spelling of my first name is "Gaël" (my other papers appear here: https://www.aclweb.org/anthology/people/g/gael-lejeune/)

Best regards,
Gaël Lejeune

**Comment by akoehn** [comment]
@mjpost already pushed a fix for this, but be advised that the name comes straight from the submission. That means that your name is probably misspelled in softconf. If you have an account there, you should correct your name there to not run into this problem again. If you do not have an account there, you should tell the person who uploaded the paper to spell your name correctly the next time ;-)
