### ISSUE TITLE
Spelling error in author name in LREC 2020 paper "2020.lrec-1.462"

### ISSUE THREAD

**Issue by shashanksiripragada** [acl-org/acl-anthology#839]
In the paper (https://www.aclweb.org/anthology/2020.lrec-1.462/) my last name is spelled as "Siripragrada" , which links to https://www.aclweb.org/anthology/people/s/shashank-siripragrada/, but the correct spelling is "Siripragada" which points to my other publication here: https://www.aclweb.org/anthology/people/s/shashank-siripragada/

Regards,
Shashank Siripragada.

**Comment by akoehn** [comment]
We can (and will) fix this, but be advised that the name comes straight from the submission.  That means that your name is misspelled in softconf.  If you have an account there, you should correct your name there to not run into this problem again.  If you do not have an account there, you should tell the person who uploaded the paper to spell your name correctly the next time ;-)
