### ISSUE TITLE
Certificate no longer valid

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#84]
Hi, I get an error message when I try to access
ACL Anthology
https://aclanthology.info/
Your connection is not private
Attackers might be trying to steal your information from aclanthology.info (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

**Comment by knmnyn** [comment]
Observed by Greg Kondrak, verified by Min.  Seems a sys admin issue to obtain and get a new cert.

**Comment by villalbamartin** [comment]
Looks like the auto-renew script failed. I've manually renewed the certificate now.

**Comment by knmnyn** [comment]
Great.  Thanks so much!

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
