### ISSUE TITLE
Corrections to title -- https://www.aclweb.org/anthology/2020.multilingualbio-1.0.pdf

### ISSUE THREAD

**Issue by KhalidChoukri** [acl-org/acl-anthology#841]
In the proceedings of Multilingualbio 
https://www.softconf.com/lrec2020/MultilingualBIO/

we made a spelling error
Multili**n**gual spelled as multiligual (n missing)
This impacts the (1) pdf, (2) the bibtex files

I have re-generated the whole package under START 

Khalid Choukri , LREC 
choukri@elda.org

**Comment by mjpost** [comment]
Thanks, Khalid. This will be merged with #837.
