### ISSUE TITLE
PG database connection is faulty: no password supplied

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#85]
This just started happening a few minutes ago as I was finishing edits to J18-3.xml.  Hopefully it is temporary but may not be.  I integrated the last PR into the production system (that seemed only to pull in metadata in `import/` so I don't think that broke it.

```
aclanthology@aclanthology:~/acl-anthology/import$ rake import:xml[true,C18]
(in /home/aclanthology/acl-anthology)
rake aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
```

**Comment by villalbamartin** [comment]
I'm looking into it.

**Comment by danielgildea** [comment]
I think renaming the file is a good idea.

**Comment by knmnyn** [comment]
Hi all:

I understand that in Rails database.yml shouldn't actually contain
passwords and that usually in production environments the passwords are
retrieved from the environment.  Perhaps you can explore using something
similar?

https://stackoverflow.com/questions/40402016/how-to-use-environment-variable-to-avoid-hard-coding-postgresqls-username-and-p

**Comment by knmnyn** [comment]
@villalbamartin : your suggestion looks fine.  Please go ahead if the previous comment on passwords from the environment doesn't ring true.

**Comment by mjpost** [comment]
I think this is no longer relevant, so I'm closing this issue out.
