### ISSUE TITLE
Correction in reference section

### ISSUE THREAD

**Issue by mvzaanen** [acl-org/acl-anthology#850]
This file contains a correction in the references section of
Complex Setswana Parts of Speech Tagging
Gabofetswe Malema | Boago Okgetheng | Bopaki Tebalo | Moffat Motlhanka | Goaletsa Rammidi
It should be replaced in the Proceedings of the first workshop on Resources for African Indigenous Languages (https://www.aclweb.org/anthology/volumes/2020.rail-1/)

**Comment by mvzaanen** [comment]
[Setswana Complex POS Tagger.pdf](https://github.com/acl-org/acl-anthology/files/4744752/Setswana.Complex.POS.Tagger.pdf)

**Comment by mjpost** [comment]
Per [the instructions](https://www.aclweb.org/anthology/info/corrections/), please post the Anthology ID of the paper.

**Comment by mvzaanen** [comment]
I'm sorry for not providing this directly. This relates to article 2020.rail-1.4.
