### ISSUE TITLE
ACL 2020 software/dataset attachments

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#860]
[This paper](https://www.aclweb.org/anthology/2020.acl-main.462/) is listed as having a software attachment—I'm not sure why (I don't think we submitted one). The software link is broken, which seems to be the case for all papers.

**Comment by mbollmann** [comment]
We ([699](https://www.aclweb.org/anthology/2020.acl-main.699/)) submitted software and dataset, but only a software link shows up, and is broken.

**Comment by mjpost** [comment]
Fixed, thanks.

Nathan, it looks like your download is the latex source. I don't know why it is tagged as Software, but that came from START.

**Comment by mbollmann** [comment]
Dataset for our paper still doesn't show up, though (and doesn't seem to exist, by trying to probe the potential filename...). If that's how it came out of START, where could this issue be best reported?

It would be concerning if this is more systematic and the community provided attachments in START that we never end up using.

**Comment by mjpost** [comment]
That's all that was included in the delivery. I suggest you contact the pub chairs. It is a bit strange because there are only 32 attachments total included.

**Comment by mjpost** [comment]
(I'll raise it internally)

**Comment by nschneid** [comment]
2020.acl-main.655 software link says "null".

**Comment by bethard** [comment]
@nschneid: I can confirm that on START, you uploaded .tex files in your "Software" upload.
@mbollmann: I can see 1736_Dataset.zip in the `final` directory from the `all` download from START. @mjpost What's the relation between that `final` directory and whatever you upload on the ACL Anthology?

**Comment by nschneid** [comment]
> @nschneid: I can confirm that on START, you uploaded .tex files in your "Software" upload.

Sorry, my bad. Could this be removed then?

**Comment by mjpost** [comment]
By "this", do you mean the attachment entirely? I can `rm` the file if you do the PR.

**Comment by bethard** [comment]
@mjpost It looks like @mbollmann's dataset is still missing: https://www.aclweb.org/anthology/2020.acl-main.699/. The 1736_Dataset.zip was in https://www.softconf.com/acl2020/papers/pub/aclpub/all.zip but I gather it was not in https://www.softconf.com/acl2020/papers/pub/aclpub/proceedings.tgz? How can we fix this?
