### ISSUE TITLE
Correction to Anthology R19-1097, R19-1098, W18-6302

### ISSUE THREAD

**Issue by ninikolov** [acl-org/acl-anthology#865]
Hello, 

I just realized that I've ended up having two separate author pages on the ACL anthology: 

Nikola Nikolov: https://www.aclweb.org/anthology/people/n/nikola-nikolov/
Nikola I. Nikolov: https://www.aclweb.org/anthology/people/n/nikola-i-nikolov/

Would it be possible to convert all papers from Nikola Nikolov to Nikola I. Nikolov for consistency? The papers that need to be changed are: 
https://www.aclweb.org/anthology/R19-1097/
https://www.aclweb.org/anthology/R19-1098/
https://www.aclweb.org/anthology/W18-6302/

The PDFs of the papers are already correctly named. 

Thank you & Best, 
Nikola

**Comment by davidweichiang** [comment]
I'll start by merging the two author pages into one.

**Comment by mjpost** [comment]
@ninikolov, this isn't too difficult. Can you check that you have your name set correctly in your [Global START profile](https://www.softconf.com/acl2020/super/scmd.cgi?ucmd=updateProfile)? This is where START gets it from, and will prevent this from happening in the future.

**Comment by mjpost** [comment]
@davidweichiang, shall I edit the metadata, or are you doing that as well?

**Comment by davidweichiang** [comment]
@mjpost could you do that? I haven't done actual paper corrections before.

**Comment by davidweichiang** [comment]
Oh I see, the PDFs are already correct and it's just the metadata that needs to be changed? Sure, I can do that.

**Comment by mjpost** [comment]
Yes, just the XML.
