### ISSUE TITLE
Correction to Anthology ID P19-1020

### ISSUE THREAD

**Issue by aonotas** [acl-org/acl-anthology#874]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Revision or erratum: please add the following information**

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**

These people is not same people. 
- Motoki Sato
- Motoki Sano
https://www.aclweb.org/anthology/people/m/motoki-sano/

I am Motoki Sato. My publications are following:
- https://www.aclweb.org/anthology/P19-1020/
- https://www.aclweb.org/anthology/C18-1308/
- https://www.aclweb.org/anthology/E17-1093/
- https://www.aclweb.org/anthology/I17-2017/
- https://www.aclweb.org/anthology/K17-3007/
- https://www.aclweb.org/anthology/P19-1020/
Could you fix this page? : https://www.aclweb.org/anthology/people/m/motoki-sano/

<img width="854" alt="スクリーンショット 2020-06-26 12 09 33" src="https://user-images.githubusercontent.com/5954536/85816311-ee140e00-b7a5-11ea-9d3c-49a31b959c7a.png">

Recently some researcher use wrong name like. 
<img width="596" alt="スクリーンショット 2020-06-26 12 12 44" src="https://user-images.githubusercontent.com/5954536/85816469-5d89fd80-b7a6-11ea-97f5-b2ee105e5fda.png">
https://www.aclweb.org/anthology/2020.acl-main.529/

My correct name is "Motoki Sato" != "Motoki Sano". 
My bib is correct. 
https://www.aclweb.org/anthology/P19-1020/

I'm not sure why there is people identification problem. But if you can fix it, could you fix it?

**Comment by mjpost** [comment]
Thanks. I have a PR in to fix this (#875). This probably happened some time ago by accident when we applied an automatic routine to match similar names.

**Comment by aonotas** [comment]
I see, the dictionary was automatic generated. 
Thank you for your quick work!
