### ISSUE TITLE
Correction to Anthology ID 2020.nlp4convai-1.13

### ISSUE THREAD

**Issue by jianguoz** [acl-org/acl-anthology#880]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**
https://www.aclweb.org/anthology/2020.nlp4convai-1.13/
The author names are incomplete under the BibTex and the website descriptions. We want to update them to the author names list inside the paper. Xiaoxue Zang, Abhinav Rastogi, Srinivas Sunkara, Raghav Gupta, Jianguo Zhang, Jindong Chen

## Revision or erratum: please add the following information**

- [ *] I have attached the revised PDF or erratum to this issue
- [ *] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**
Author names changes in the Bibtex and the webite desciptions from `Xiaoxue Zang, Abhinav Rastogi, Jindong Chen` to ` Xiaoxue Zang, Abhinav Rastogi, Srinivas Sunkara, Raghav Gupta, Jianguo Zhang, Jindong Chen`

**Comment by jianguoz** [comment]
Hi, any updates for this?

**Comment by mjpost** [comment]
Why did you close this? Corrections often take some time to process. Also, can you please explain why the author list changed so dramatically?

**Comment by jianguoz** [comment]
> Why did you close this? Corrections often take some time to process. Also, can you please explain why the author list changed so dramatically?

Thanks very much for the comments, we answer in the pull request [#928 ]

**Comment by mjpost** [comment]
Hi, apologies for the delay in responding, but it took some time for us to determine our policy. Many conferences do not permit changes to the author list, so we require permission from the relevant program chairs or workshop organizer. Please arrange for this permission to be sent to me at anthology@aclweb.org, or to be added here, along with some evidence that the person posting is authorized (i.e., link to website with list of conference organizers).
