### ISSUE TITLE
Revision to paper Anthology ID: 2020.acl-main.477

### ISSUE THREAD

**Issue by bigaidream** [acl-org/acl-anthology#885]
Our new PDF: [new-2020.acl-main.477.pdf](https://github.com/acl-org/acl-anthology/files/4846839/new-2020.acl-main.477.pdf)

I would like to request to update the content of the paper [2020.acl-main.477](https://www.aclweb.org/anthology/2020.acl-main.477/). 

We provide an additional section "Broader Impact" in this new version.

**Comment by bigaidream** [comment]
We'd also like to change the Abstract in the meta-data into:

Understanding human preferences, along with cultural and social nuances, lives at the heart of natural language understanding. Concretely, we present a new task and corpus for learning alignments between machine and human preferences. Our newly introduced problem is concerned with predicting the preferable options from two sentences describing scenarios that may involve social and cultural situations. Our problem is framed as a natural language inference task with crowd-sourced preference votes by human players, obtained from a gamified voting platform. We benchmark several state-of-the-art neural models, along with BERT and friends on this task. Our experimental results show that current state-of-the-art NLP models still leave much room for improvement.

**Comment by mjpost** [comment]
You can expedite things by submitting a PR with the updated abstract (see `data/xml/2020.acl.xml`).

**Comment by bigaidream** [comment]
I've created a PR: https://github.com/acl-org/acl-anthology/pull/889
