### ISSUE TITLE
Source code for https://www.aclweb.org/anthology/2020.acl-main.69/ is provided in the link in the paper

### ISSUE THREAD

**Issue by kaustubhdhole** [acl-org/acl-anthology#890]
The "software" section of https://www.aclweb.org/anthology/2020.acl-main.69/
mistakenly contains the latex contents and not software. So, this link to software (green download button) should not be shown since the code would be provided at the link mentioned in the paper.

**Comment by mjpost** [comment]
Do you want me to remove the attachment entirely, or change the download label to "LaTeX"?

**Comment by kaustubhdhole** [comment]
Okay, I guess making the download label to "Latex" can be helpful! Thanks!
