### ISSUE TITLE
Wrong metadata on Google Scholar for D19-1506

### ISSUE THREAD

**Issue by prabhukaliamoorthi** [acl-org/acl-anthology#891]
The first author for the paper is Prabhu Kaliamoorthi. This is rightly mentioned here https://www.aclweb.org/anthology/info/corrections/

but on Google search the aclweb.org link incorrectly says the first author is K Krishnamoorthi
https://www.google.com/search?q=PRADO+nueral+network&rlz=1CAVNXA_enUS782US783&oq=prado+nueral+&aqs=chrome.0.69i59l2j69i57j46j69i59j69i60l3.2606j1j7&sourceid=chrome&ie=UTF-8

**Comment by mbollmann** [comment]
Huh, that's a weird issue! However, I've double-checked the metadata is correct on our side and there is no mention of "K Krishnamoorthi" anywhere on the page or our metadata of the [D19-1506](https://www.aclweb.org/anthology/D19-1506/) paper (which I assume you've meant). This must be a problem with Google Scholar.

**Comment by prabhukaliamoorthi** [comment]
Thanks for the confirmation.

**Comment by mjpost** [comment]
See #694. I assume that Google crawled it prior to that fix and has not since recrawled.
