### ISSUE TITLE
Correction to 2020.acl-main.176

### ISSUE THREAD

**Issue by spakhomov** [acl-org/acl-anthology#898]
Description of the correction: The column labels "DEMENTIA" and "CONTROL" in Table 1 were accidentally swapped in the original submission. Table 1 has been corrected to change the order of labels to "CONTROL" for the first column and "DEMENTIA" for the second column.  

[ACL_2020_TaleOfPerplexities_final_final.pdf](https://github.com/acl-org/acl-anthology/files/4880268/ACL_2020_TaleOfPerplexities_final_final.pdf)

**Comment by mjpost** [comment]
Hello, [per the instructions](https://www.aclweb.org/anthology/info/corrections/), please provide the Anthology ID.

**Comment by spakhomov** [comment]
Sorry! - 2020.acl-main.176
