### ISSUE TITLE
 Error 404 while opening paper 

### ISSUE THREAD

**Issue by ykkhan** [acl-org/acl-anthology#899]
When I try to open the paper 2020.winlp-1.23 "Developing a Monolingual Sentence Simplification Corpus for Urdu", It is giving error 404 as shown in the image. Kindly check this issue. 
![ACL 2020 result](https://user-images.githubusercontent.com/42977303/86626048-8fd5ff00-bfdf-11ea-9ffb-145fc2acd6dd.png)

**Comment by mjpost** [comment]
Hello, yes, it's been made unavailable. We will remove the landing page soon.
