### ISSUE TITLE
Handle Errata

### ISSUE THREAD

**Issue by cfedermann** [acl-org/acl-anthology#9]
**S/N:** 9
**Title:** Handle Errata

**Comment by knmnyn** [comment]
Please keep open.  Errata can be submitted to the Anthology, but the current Anthology doesn't handle errata, but only handles fully (drop-in) revisions.  This issue is for this.

**Comment by mjpost** [comment]
With the static rewrite, errata now work (e.g., 
http://aclweb.org/anthology/papers/W/W16/W16-5807/), so I'm closing this.
