### ISSUE TITLE
Ensure casing for bibtex generated in the anthology.

### ISSUE THREAD

**Issue by CTNLP** [acl-org/acl-anthology#90]
Currently casing is not preserved when generating the bibtex files that are published in the anthology, we need to look into a simple solution for preserving this information.

**Comment by logological** [comment]
Note that as a general rule, casing should _not_ be forced except for proper nouns and acronyms.  BibTeX styles automatically handle casing (or at least downcasing). That is, BibTeX generally expects titles and book titles to be entered in the source file in title case (first word capitalized, and all other words capitalized except for short prepositions and function words); depending on the BibTeX style file used, it will then downcase them to sentence case (only first word capitalized).

If authors did not indicate at the time of submission which words in article titles should remain capitalized, then there is no easy way of correcting this.  You could force capitalization of the entire title field by wrapping it in braces.  But if the title was written in sentence case, then this will annoy everyone using a bibliography style that mandates title case, and if the title was written in title case, then this will annoy everyone using a bibliography style that mandates sentence case.

**Comment by logological** [comment]
> @logological, your information here makes a lot of sense, though I had never heard it before. Do you have any kind of citation or source for this notion of correctness?

My, does no one read product manuals any more? ;)  This is covered in both the official BibTeX and LaTeX manuals:

1. Oren Patashnik.  BibTeXing. February 1988.
2. Leslie Lamport. _LaTeX: A Document Preparation System: User's Guide and Reference Manual._ 2nd edition. Addison Wesley, 1994.

Section 3.2 of the former says that the `booktitle` and `title` fields should be "typed as explained in the LaTeX book", which refers to Appendix B.1.2 of Lamport's manual:

> The bibliography style determines whether or not a title is capitalized; the titles of books usually are, the titles of articles usually are not. You type a title the way it should appear if it is capitalized… BibTeX will change uppercase letters to lowercase if appropriate.  Uppercase letters that should not be changed are enclosed in braces.

For secondary sources, you might consult the [TeX FAQ](https://texfaq.org/FAQ-capbibtex) on [Capitalisation in BibTeX](https://texfaq.org/FAQ-capbibtex) (originally published by the UK TeX Users Group), or the question [BibTeX loses capitals when creating .bbl file](https://tex.stackexchange.com/questions/10772/bibtex-loses-capitals-when-creating-bbl-file) at the [TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/). They recapitulate and expand upon what's already in the BibTeX and LaTeX manuals.

**Comment by danielgildea** [comment]
> @danielgildea, by "the anthology database", do you mean the XML file that serves as the authoritative representation, or the SQL database that is generated from this representation?

I mean the SQL database.

> I didn't realize that there is a second step, whereby XML files are generated from the database after being imported. Why not generate the final bib from the first round of XML files (or from the original bibs, for that matter)?

I think either of those options would work!

> It seems problematic that our current pipeline is lossy, and I think we should fix it. In the current setting, this would mean maintaining braces through all steps, removing them only at terminal steps as needed. But I think this is part of a larger discussion, too, that we can move to another thread.

Yes, we could retain braces in the SQL database, and generate the bibtex from SQL in ruby.

We could also just retain the original bibtex files.  That would mean less fussing around to 
make sure nothing gets lost.  But it would also mean not having one master database to 
change when, eg, someone wants to change their author order.

**Comment by mjpost** [comment]
I think it's important to have a master database, and the question is whether it should be the original bibtex or the XML that is generated from it. I would think we can keep the XML for now, and modify it to preserve case and other features.

**Comment by knmnyn** [comment]
Hi all:

I agree that the master information should be available somewhere.  I'd
prefer having the XML be authoritative as this is easier for people to read
and issue PRs against in github (this model is similar to that of
csrankings.org)

The database should be the productionized version of the canonical files.
We need to work towards having all of the necessary information in the XML,
inclusive of SIG/venue affiliation (which is currently in separate files)

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by mjpost** [comment]
Let's stick with XML then. I think that for longevity it good to have a format that can be validated against a schema and that's designed for arbitrary data, and it is easy to generate out of XML into any format we might like.

**Comment by danielgildea** [comment]
> This suggests not only that we keep the (original, pre-database) XML file as authoritative, but perhaps also convert it into MODS format. Are there any arguments for or against this? How different is MODS from what we currently use?

For one thing, there is no way to indicate protected casing in MODS.

**Comment by mjpost** [comment]
Oh, right, sorry to have forgotten this point you made.

We could continue to use the braces format, e.g.,

    <titleInfo>
      <title>Building a large annotated corpus of {E}nglish: The {P}enn Treebank</title>
    </titleInfo>

`xm2bib` produces:

    title="Building a large annotated corpus of {\{}E{\}}nglish: The {\{}P{\}}enn Treebank",

which is ugly, but also easily removed (`perl -pe 's/\\//g; s/\{(.*?)\}/\1/g'`). However, this suggests we might encounter more problems if we start with MODS. It doesn't seem to difficult to use our own scripts.

**Comment by danielgildea** [comment]
I wrote some code to generate bibtex from the sql database on a new branch:
[443b39b]

**Comment by mjpost** [comment]
Thanks, Dan. I think the current plans are, in light of the [static rewrite](https://github.com/acl-org/acl-anthology/projects/3), is to generate both [BibTeX](https://github.com/acl-org/acl-anthology/issues/122) and [MODS-formatted XML](https://github.com/acl-org/acl-anthology/issues/121) directly from the authoritative XML. This would remove the complexity of the conversions into and out of the database, would allow us to generate arbitrary and correct BibTeX, and would allow us to continue to generate non-BibTeX citation formats with bibutils.

Looking through your commit, I think a lot of the LaTeX equivalents and conversions from UTF-8 will be useful in this.

**Comment by mjpost** [comment]
This has been addressed with the `fixed-case` tag and existing errors are covered by other issues (#160 #123 #200 #231), so I’m closing it. It remains one of my favorite issues, though, due to the wealth of bibtex information!
