### ISSUE TITLE
Error in opening paper 2020.winlp-1.23

### ISSUE THREAD

**Issue by ykkhan** [acl-org/acl-anthology#900]
My paper is giving error 404  while opening
The paper title is "Developing a Monolingual Sentence Simplification Corpus for Urdu". 
please check this issue. why it is occurring. 
https://www.aclweb.org/anthology/2020.winlp-1.23/

Best Regards

**Comment by mjpost** [comment]
This was removed at the request of the WiNLP workshop chairs: https://github.com/acl-org/acl-anthology/commit/dc5c871d8713f6d86412ca50b317f6844cdbf791

**Comment by mjpost** [comment]
Perhaps @rossanacunha can comment?

**Comment by rossanacunha** [comment]
Tks @mjpost for redirecting the issue. @ykkhan we removed your paper since you asked to be anonymized during the submission.

**Comment by ykkhan** [comment]
Hi Rossana Cunha, 
Thanks for replying, apologies for the inconvenience.
This paper is not more anonymized in the WiNLP website. It would be great to add the abstract in ACL also which is uploaded on the WiNLP website.  

I shall be very Thank full.
