### ISSUE TITLE
Request to change the paper status (2020.winlp-1.23) 

### ISSUE THREAD

**Issue by ykkhan** [acl-org/acl-anthology#902]
Hi,
Apologies for the inconvenience.
This paper is not anonymized in the WiNLP website. It would be great to add the abstract in ACL also which is uploaded on the WiNLP website.

https://www.aclweb.org/anthology/2020.winlp-1.23/ 

I shall very thank full.

**Comment by ykkhan** [comment]
Hi, mjpost
Thank you for replying. 

Sir, Is It restored? If yes, 
I am still facing the same error 404 (not found). 

Best Regards.

**Comment by mjpost** [comment]
No. There is a PR (#903) which has to be approved and merged.
