### ISSUE TITLE
Correction to Anthology ID: 2020.readi-1.9

### ISSUE THREAD

**Issue by mattshardlow** [acl-org/acl-anthology#905]
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

Correct spelling of title to "CompLex: A New Corpus for Lexical Complexity Prediction from Likert Scale Data"

## Revision or erratum: please add the following information**

- [ x ] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**

This  revision updates a typo in the paper title. 'Prediction was misspelt as 'Predicition'

[2003.07008.pdf](https://github.com/acl-org/acl-anthology/files/4891097/2003.07008.pdf)

**Comment by mjpost** [comment]
What paper?

**Comment by mattshardlow** [comment]
Sorry.  It's: https://www.aclweb.org/anthology/2020.readi-1.9/

Updated file here (without the arxiv banner):

[READI_2020_CWI(1).pdf](https://github.com/acl-org/acl-anthology/files/4891115/READI_2020_CWI.1.pdf)

**Comment by mattshardlow** [comment]
thanks for being so speedy on this!
