### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#92]
There are some missing bits of documentation that should be integrated in several parts of the code:
  * The current configuration of the NGINX server is not in the repo because an NGINX server is not strictly required. There should still be a template stored somewhere to simplify the work of future system administrators.
  * There is missing documentation on the new caching functionality. Off the top of my head: how to clear the cache (for the record: delete the corresponding html file inside the `public` directory), and how to make our old code work nicely with NGINX (which I thought I had written in an issue, but apparently I didn't).

These are specific items that I'm aware are missing (and will fix as soon as I can), but if there's any missing piece of documentation feel free to add them to this issue.

**Comment by mjpost** [comment]
This seems no longer relevant, so I'm closing this out for now.
