### ISSUE TITLE
Correction to Anthology ID 2020.acl-main.109

### ISSUE THREAD

**Issue by macleginn** [acl-org/acl-anthology#924]
## Metadata correction

Is it possible to add a link to the supplementary materials?

https://www.cse.huji.ac.il/~oabend/data/translation_divergences_supp.zip

**Comment by mjpost** [comment]
Were these submitted to Softconf? There was a bug in the Softconf → Anthology transition, causing attachments to be ignored. That will be fixed this weekend, in which case, this could be closed.

**Comment by mjpost** [comment]
This was completed with #969.
