### ISSUE TITLE
Correction to Anthology ID 2020.iwslt-1.1

### ISSUE THREAD

**Issue by marcellofederico** [acl-org/acl-anthology#925]
[IWSLT_2020_Evaluation_Overview_Paper (1).pdf](https://github.com/acl-org/acl-anthology/files/4913582/IWSLT_2020_Evaluation_Overview_Paper.1.pdf)

## Revision or erratum: please add the following information**

- [ X] I have attached the revised PDF or erratum to this issue
-  [X ] I have written a brief description of the changes below

I already uploaded the new version in Softconf and regenerated 
the proceedings files. 

**Description of changes**
This revision corrects a typo in the title of section 1: 
1. Introduction [Marcello] -> 1. Introduction

**Comment by marcellofederico** [comment]
Hi Matt, any updates on this?

**Comment by mjpost** [comment]
#942
