### ISSUE TITLE
Correction to Anthology ID D19-5201

### ISSUE THREAD

**Issue by Tzawa** [acl-org/acl-anthology#944]
[D19-5201.pdf](https://github.com/acl-org/acl-anthology/files/5048804/D19-5201.pdf)
**Please be sure to add the Anthology ID in the title**

[See here](https://www.aclweb.org/anthology/info/corrections/) to read about the three types of corrections.

## Metadata correction: please describe the issue here**

The author list needs to be updated as follows:
Toshiaki Nakazawa, Nobushige Doi, Shohei Higashiyama, Chenchen Ding, Raj Dabre, Hideya Mino, Isao Goto, Win Pa Pa, Anoop Kunchukuttan, Yusuke Oda, Shantipriya Parida, Ondřej Bojar, Sadao Kurohashi

## Revision or erratum: please add the following information**

- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

**Description of changes**

This revision adds an additional author.

**Comment by mjpost** [comment]
Hi,

Please see our (just-enacted) policy on revisions to the author list.

### Note on author changes

> Some conferences and workshops have a policy of disallowing authorship changes after the initial submission. Because it is beyond our ability to track this, changes to the list of authors, whether in the PDF or in the metadata, require permission from the associated conference program chair or workshop/tutorial chair. You are responsible for arranging for this permission to be conveyed to us, either via email or on your Github issue. We will make exceptions for the correction of obvious spelling errors or other typos, and for author name changes (i.e., the list of authors is unchanged, but one of the authors changes their name).

**Comment by mjpost** [comment]
I'm closing this for now, since there has been no action nor reply. Please feel free to reopen it if want to move forward.

**Comment by Tzawa** [comment]
Dear Matt Post,

I've just received the response from EMNLP2019 workshop chairs (Vera Demberg and Naoaki Okazaki) and adding an author is approved by them. Could you please proceed to modify the meta-data and PDF?

**Comment by mjpost** [comment]
Can you have them either comment here or email me?

**Comment by mjpost** [comment]
Please also find your paper in data/xml/D19.xml, add the author in the appropriate position, and create a PR that references this issue.
