### ISSUE TITLE
paper https://www.aclweb.org/anthology/2020.figlang-1.3.pdf

### ISSUE THREAD

**Issue by bbeigmanklebanov** [acl-org/acl-anthology#946]
Hi Matt,

I see that the paper still shows the version before revision and this URL https://www.aclweb.org/anthology/2020.figlang-1.3v2.pdf returns an error.

Could you please advise when the revision will be visible in the anthology?

Thank you,
Beata

**Comment by mjpost** [comment]
I had forgotten to sync them. They're live now.

**Comment by bbeigmanklebanov** [comment]
Thanks, Matt.

Beata
