### ISSUE TITLE
Missing 2012 workshops and 1977 

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#95]
(via email from Anurag of Google Scholar) 

Looking at https://aclanthology.coli.uni-saarland.de/events/ws-2012, workshops numbered ws12-47 to ws12-61 aren't included. The paper the author had contacted us about was in W12-58 (Proceedings of the Workshop on Speech and Language Processing Tools in Education).

Looking around a bit, looks like W77-01 isn't yet included on aclanthology.coli.uni-saarland.de as well.

**Comment by villalbamartin** [comment]
I think these issues are now solved.

W77-01 is available [here](https://aclanthology.coli.uni-saarland.de/events/ws-1977), and WS12-47 to WS12-61 now show up [here](https://aclanthology.coli.uni-saarland.de/events/ws-2012). Could I get confirmation to close this issue?

**Comment by knmnyn** [comment]
LGTM.  Closing
