### ISSUE TITLE
Adding more languages to the capitalisation truelist

### ISSUE THREAD

**Issue by marcschulder** [acl-org/acl-anthology#953]
Looking at the fixed-case tags in [2020.signlang.xml](https://github.com/acl-org/acl-anthology/blob/master/data/xml/2020.signlang.xml) I noticed that many sign languages have faulty forced capitalisation. For example, in "Filipino Sign Language" the F is tagged to ensure capitalisation, but the S and L are not. (Note that here "Sign Language" is part of the name of a specific language and therefore capitalised, as opposed to a reference to the general concept of sign languages, which is written in lowercase.)

I assume the best way to ensure correct capitalisation would be to extend [bin/fixedcase/truelist](https://github.com/acl-org/acl-anthology/blob/master/bin/fixedcase/truelist) and then re-run it on the existing XML files (at the very least on 2020.signlang). If so, I could add around 140 sign languages to the list. They are mainly taken from [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3), although I manually added a few more that have been used in paper titles of the LREC Sign Language Workshop in the past.

Theoretically one could take this even further and add the entire list of 7720 languages that I extracted. I also have compiled similar lists for countries, their subdivisions and major geographic regions.

I have attached the lists in question:
[Languages - ISO 639-3.txt](https://github.com/acl-org/acl-anthology/files/5068258/Languages.-.ISO.639-3.txt)
[Languages - other.txt](https://github.com/acl-org/acl-anthology/files/5068259/Languages.-.other.txt)
[Countries - ISO 3166.txt](https://github.com/acl-org/acl-anthology/files/5068256/Countries.-.ISO.3166.txt)
[Country subdivisions - ISO 3166-2.txt](https://github.com/acl-org/acl-anthology/files/5068257/Country.subdivisions.-.ISO.3166-2.txt)
[Regions.txt](https://github.com/acl-org/acl-anthology/files/5068261/Regions.txt)

As a bonus, there are some more capitalised terms from the LREC Sign Language Workshop series:
[LREC SignLang - other.txt](https://github.com/acl-org/acl-anthology/files/5068260/LREC.SignLang.-.other.txt)

Which of these lists should I integrate?

**Comment by nschneid** [comment]
Thanks for pointing this out! I added the current list of language names based on https://en.wikipedia.org/wiki/List_of_language_names (with a bit of manual curation). But there are clearly a lot of missing proper names. If you submit a pull request with additional entries I'll be happy to review it.

The main thing to watch out for are words that may be more likely to occur as a non-proper name in NLP titles. We probably don't want to include the language "E", for example.

Also be careful about hyphenation. I think the script that matches against the truelist treats hyphens as optional separate tokens, so they should not be in the truelist. If there is a token with a non-initial capital, it will automatically be handled, so there's no need to list it. There is no lemmatization of names, so ideally both singular and plural forms should be listed where applicable.

[Fixed-case algorithm description](https://github.com/acl-org/acl-anthology/blob/master/bin/fixedcase/README.md)

**Comment by marcschulder** [comment]
Will do. Should I make separate pull requests for languages, countries and the miscellaneous SignLang terms? Or just lump it all into one request?

**Comment by akoehn** [comment]
I would say do as you see fit & is less work for you.

**Comment by nschneid** [comment]
Maybe separate commits all in one PR? Before merging I'll want to run it on the full anthology and do a spot check.

**Comment by marcschulder** [comment]
The updated truelist is now submitted in pull request #983.
I've checked the output on all proceedings XMLs, so there should hopefully not be any glaring false positives. There are a few matches in non-English titles that may or may not be incorrect. Also some hits are parts of person names, found mainly in book reviews. These hits were correct, but result in very spotty fixed caps for those titles. Some manual TLC might be required for those items.

@nschneid, please beware that the protect.py script appears to not have been run on most XMLs in a while, so you'll have to run it both before and after pulling my commit and compare those two states, rather than comparing to the current XMLs.

**Comment by nschneid** [comment]
> @nschneid, please beware that the protect.py script appears to not have been run on most XMLs in a while, so you'll have to run it both before and after pulling my commit and compare those two states, rather than comparing to the current XMLs.

Yes this is #892

**Comment by nschneid** [comment]
#983 is merged!

**Comment by mjpost** [comment]
Thanks to you both for your awesome work on this!
