### ISSUE TITLE
Correction to anthology ID W05-1506

### ISSUE THREAD

**Issue by andreasvc** [acl-org/acl-anthology#973]
- [x] I have attached the revised PDF or erratum to this issue
- [x] I have written a brief description of the changes below

The revised version is made available by one of the authors: https://web.engr.oregonstate.edu/~huanlian/papers/huang-iwpt-correct.pdf
and attached here: [huang-iwpt-correct.pdf](https://github.com/acl-org/acl-anthology/files/5124455/huang-iwpt-correct.pdf)

The PDF of the revision contains the following explanation:

> Appeared in the Proceedings of the 9th International Workshop on Parsing Technologies, Vancouver, B.C, October 2005. This version fixes a bug in the pseudo-code of Algorithm 3 (See Figure 7). Thanks to David A. Smith and Jonathan May for pointing it out. In the actual implementions, an earlier version is used which has the correct behavior.

I submit this issue because I want to ensure this revised version is preserved for posterity, and to make the revised version more discoverable. At the time I implemented the algorithm in this paper I was not aware of the revised version and I spent weeks trying to debug the code before I discovered it...

**Comment by mjpost** [comment]
Thanks for posting. @davidweichiang, is this okay with you?

**Comment by davidweichiang** [comment]
Yes, fine with me! Does Liang need to approve as well?

**Comment by mjpost** [comment]
I don’t think so. I didn’t imagine any objections but just wanted to make sure one of you was okay with it.

**Comment by mjpost** [comment]
This was closed with #977.
