### ISSUE TITLE
Erroneous link in online documentation

### ISSUE THREAD

**Issue by AdrianAvenarius** [acl-org/acl-anthology#978]
From the last paragraph in hugo/content/info/development.md (https://www.aclweb.org/anthology/info/development/):

`Our scripts use the [lxml.de](https://www.fridaysforfuture.org) library to parse the XML.`

Seriously?

**Comment by akoehn** [comment]
Thanks for opening this issue. Maybe next time write it in a less confrontational way?

**Comment by mjpost** [comment]
Clearly an innocuous cut-and-paste error, easily fixed.
