### ISSUE TITLE
Search returns "The page you were looking for doesn't exist."

### ISSUE THREAD

**Issue by heatherleaf** [acl-org/acl-anthology#98]
It's happened again (#93, #83, etc): Now I can't search for e.g. "Software" (and other terms)

**Comment by knmnyn** [comment]
Hi all:

The host with the solr search engine seems to be down.  Can anyone help on this?

**Comment by villalbamartin** [comment]
Our IT department had to restart the server, and Solr didn't come back up. It is up now.
