### ISSUE TITLE
Please re-open #978 (Erroneous link in online documentation)

### ISSUE THREAD

**Issue by AdrianAvenarius** [acl-org/acl-anthology#982]
Reason:

The sentence in question now reads `Our scripts use the [lxml.de](lxml.de) library to parse the XML.`, which results in the invalid local link https://www.aclweb.org/anthology/info/development/lxml.de instead of https://lxml.de.

Some explanations:

@akoehn Your perception of my original message made me think (surprisingly) long and hard. I get that stating one's own intentions does not retroactively heal a rude or confrontational impression evoked on the side of a reader or listener.
I had thought of a terse style as wasting the least amount of attention for everyone involved, as a form of politeness, actually - well, you live and learn.

@mjpost Of course this is innocuous and hardly worth mentioning. Most probably, the page was drafted in 'airplane mode' and the placeholder-URI simply stayed in there.

Disclaimer:

No, I do not intend to wisecrack on every typo I might find in the future. What led me here was reading a string of articles ([Quanta Magazine](https://www.quantamagazine.org/)) on AI and NLP seeking inspiration (i.e., shoplifting ideas) for algorithmic composition (yes, the musical kind). This should explain why the probability of me contributing anything substantial to this repository is arbitrarily close to zero and cloning the whole shebang to submit a proper pull request would be slightly over the top.

**Comment by mjpost** [comment]
Thanks for reporting this again! We do appreciate having errors in the site brought to our attention.

This will be closed with #977.

**Comment by akoehn** [comment]
Hi @AdrianAvenarius, there is absolutely nothing wrong with opening a short issue, it was only the "Seriously?" part rubbed me the wrong way. Maybe I misinterpreted it -- at the time it sounded to me like an allegation that the link was put there on purpose.  So as @mjpost wrote: please continue opening issues on projects, it is appreciated.

**Comment by AdrianAvenarius** [comment]
Dear @mjpost, dear @akoehn,

thank you both for revisiting this issue! The usual short designation "broken link" seemed inappropriate to me, since that term typically indicates deprecation or textual mangling (e.g., by a content management system trying to function "intelligently"), but not a nonsensical, working reference.

By the way, I have seen benign cases of intentional oddities in the wild. If you were to insert a debugging-only variable into working code, for instance, it might make sense to have it stick out textually. A moniker like "magnolia" beats a bland "counter" in this respect; but I digress ...

Regards, A.
