### ISSUE TITLE
Ingesting ACL 2020 videos

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#986]
I am posting this in hopes that I can find someone interested to help merge links to ACL 2020 videos into the Anthology.

The task steps are as follows. We especially could use help with #1 and #3, since we have a tool in place for #2.

1. Produce a single consolidated TSV file of (Anthology ID, Slideslive ID) tuples from all the CSV files [here](https://github.com/acl-org/acl-2020-virtual-conference/tree/master/sitedata_acl2020).
   * Each CSV file contains an Anthology ID and other metadata, the most important of which are the `UID`, `title`, and `pdf_url` columns
   * For ACL main conference events, there is a `*.slideslive_ids.csv` file that maps from `UID → Slideslive ID`, so this has to be joined to the above CSV files
   * For workshops, there is no link to the Anthology ID, so it must be matched by paper title. The Slideslive ID is found in the `presentation_id` column

2. Once we have this consolidate file, we can generate `<video>` tag links for all papers, since the Slideslive URL is formed from the Slideslive ID

3. (Optional) embed video playing into the Anthology paper page (for both Vimeo and Slideslive papers). This is a fairly simple change to the template [hugo/layouts/papers/single.html](https://github.com/acl-org/acl-anthology/blob/master/hugo/layouts/papers/single.html).

For example, here is the first two data lines line of the TSV file:

    anthology_id	slideslive_id
    2020.acl-main.8	38929437
    2020.winlp-1.1	38929537
    ...

* The first (non-header) line is produced by joining the first row of [main_papers.csv](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/sitedata_acl2020/main_paper_zoom_links.csv) with [main_paper_slideslive_ids.csv](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/sitedata_acl2020/main_paper_slideslive_ids.csv).

* The second line (for a workshop paper) is produced by getting the `presentation_id` field from [w1_papers.csv](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/sitedata_acl2020/w1_papers.csv), along with the title, and then searching the Anthology for the title.

We could easily process this in two batches: (1) ACL main papers (where the job is easier) and (2) workshop papers (where the job is a bit harder, since papers have to be matched on titles).

(Note that, longer term, we are going to move all hosting to the Anthology, but that is not part of this task.)

**Comment by dipteshkanojia** [comment]
Please allow me to start with #1.

**Comment by akoehn** [comment]
Go ahead, the CSV files are linked above in @mjpost's post.

**Comment by dipteshkanojia** [comment]
I am getting a 404. This repo is probably not public, Could any of you please add me to the repo?

**Comment by dipteshkanojia** [comment]
This is what I have done for #1 *_papers.csv
https://github.com/dipteshkanojia/acl-2020-sitedata-edited

For workshop papers though, I am still unclear what I have to join them with. The presentation ids are present in the wX_papers.csv, but is there an Anthology CSV file I am missing? 

I am unable to find it in the repo.

**Comment by mjpost** [comment]
Hi Diptesh—when I created this, I didn't realize that the repo was private. Sorry about that. I have updated the links.

I woke up this morning, though, and someone had emailed me with the results. Thanks for your willingness to help here, though.

**Comment by dipteshkanojia** [comment]
No worries. :+1:

**Comment by mjpost** [comment]
Closed with #999.
