### ISSUE TITLE
LREC 2018 in the Anthology

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#99]
This is a summary of the current situation regarding LREC 2018 in the ACL Anthology.

There are some minor errors in the XML file
  * There is no general Proceedings information - the paper with ID 1000 is missing.
  * The ids of the papers should (I believe) start from 1001 rather than from 1.

I can fix both of these things quickly, and I'm writing them down just as a general reminder.

As for the issues I cannot fix myself, there are two of them:
  * we still need to upload the PDFs to the ACL server
  * some of the files there do not have the proper name - for instance, the PDF for `Text Normalization Infrastructure that Scales to Hundreds of Language Varieties` has ID 216 in the XML file, but the corresponding PDF file is called `L18-8883.pdf`. I'm getting in touch with the authors regarding this.

**Comment by villalbamartin** [comment]
Here's an update:
  * The paper with ID 1000 has now been added
  * The IDs of the papers have been updated
  * The PDFs have been uploaded to the ACL server
  * The PDF files have their correct names. I'm assuming that this was the work of Min.

All that's missing is uploading the final file with all of the proceedings to the ACL server, and to put this in production.

**Comment by knmnyn** [comment]
Hi all: I think we need to close this issue and mount the LREC proceedings on the main production server.  We are still missing the final file "with all of the proceedings" <- I think this refers to the full volume PDF?  @villalbamartin can you clarify?

**Comment by villalbamartin** [comment]
Indeed, the file that's missing is `http://aclweb.org/anthology/L18-1000`, which contains the full volume PDF. Note that, for some reason, clicking on the PDF export for the volume (as opposed to the first paper) asks for the file `http://aclweb.org/anthology/L18-1`, no idea why.

Other than that, I've now imported the proceedings in the production server, and I'm re-indexing SOLR and exporting BIB files as I'm typing. It should be all done in about 30 minutes.

**Comment by knmnyn** [comment]
`L18-1000` refers to the front matter, and `L18-1` refers to the full volume PDF.  We need to get these from ELDA/ELRA.

**Comment by villalbamartin** [comment]
I just downloaded (I think) the file for `L18-1000`. I put it in the home directory of our test server, under the name `L18-1000.pdf`. I'm assuming either @knmnyn or @mjpost have the keys for uploading it to the aclweb servers. It's a 380M pdf file, should we attempt to compress it?

As for `L18-1`, I don't think it is in the ftp server.

**Comment by mjpost** [comment]
That's monstrous! It seems silly to me to generate these but likely there is some use-case I'm not considering. I think we can just post it. I will figure out how to.

As for L18-1, I think we should file this away with #31—we shouldn't generate links to PDFs that don't exist.

**Comment by mjpost** [comment]
[L18-1](http://aclweb.org/anthology/L18-1) is now in place. I'm going to close this issue.
